### ISSUE TITLE
Swiftmailer is end-of-life. Need to upgrade to Symfony Mailer

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#10097]
## Overview
Symfony recently announced that maintenance of Swiftmailer will officially **end in November 2021** in favour of Symfony Mailer. [See EOL announcement](https://symfony.com/blog/the-end-of-swiftmailer).

We'll need to investigate the migration path and set a plan for doing this work.

## Acceptance criteria
- [ ] CMS5 branch is using Symfony Mailer v6

#### Side note
- Yes... Work _just_ happened to upgrade to v6 of Swiftmailer for the CMS 4.9 release 🤦 
- The goal of the card is just to update to Symfony mailer however feel free to take extra time to refactor things along the way and pay down some technical debt.

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10517
- https://github.com/silverstripe/silverstripe-framework/pull/10527
- https://github.com/silverstripe/silverstripe-framework/pull/10494
- https://github.com/silverstripe/silverstripe-behat-extension/pull/225
- https://github.com/silverstripe/silverstripe-behat-extension/pull/229
- https://github.com/silverstripe/silverstripe-behat-extension/pull/230
- https://github.com/silverstripe/silverstripe-testsession/pull/81
- https://github.com/silverstripe/silverstripe-installer/pull/336
- https://github.com/silverstripe/developer-docs/pull/92

**Comment by ScopeyNZ** [comment]
Maybe we should take this opportunity to switch to an adapter pattern, and then it would theoretically be less of a problem with this situation in the future.

**Comment by maxime-rainville** [comment]
> Maybe we should take this opportunity to switch to an adapter pattern, and then it would theoretically be less of a problem with this situation in the future.

`silverstripe/mailer` FTW

@frankmullenger @danaenz How will this impact S/MIME?

**Comment by emteknetnz** [comment]
Realistically we're only going to give proper to support to one mailer, almost certainly SymfonyMailer.

An adapter pattern sounds like it could be over-abstraction? I think the FullTextSearch module started off with similar thinking and just ended up as an over-abstraction for solr

To be fair, email is a lot simpler than search so extra-abstraction would be less painful.

**Comment by ScopeyNZ** [comment]
I don't think you can really ever classify an email adapter as over abstraction to be honest. It's abstraction for a completely valid reason. 

I think the FullTextSearch module just failed to implement the adapter pattern, so ended up not actually being an abstraction at all, just a bunch of cruft around Solr.

You could get the side effect of being able to keep existing deprecated SwiftMailer code and also adding support for SymfonyMailer. You'd also get the benefits of simpler guidance around development environments (using something like MailTrap).

Other benefits include improved testability of Mail APIs. Abstraction of complicated per-mailer logic into their own adapters, potentially simplifying the interfaces.

Downside is that it might be hard to do without breaking changes, but I guess that's why Max is saying "`silverstripe/mailer` FTW".

**Comment by emteknetnz** [comment]
Right now we've got [Email.php](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php) which extends ... ViewableData :-)

We'll need to keep Email.php as is since that's how you [send Emails](https://docs.silverstripe.org/en/4/developer_guides/email/#usage) in SIlverstripe 

Looks like it was there was some intention at some point to have the mailer swappable:
- https://github.com/silverstripe/silverstripe-framework/blob/4/_config/email.yml#L9
- https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Mailer.php

But right now Email.php is pretty [hardcoded to swiftmailer ](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php#L371)

A)
If we go for mutli-mailer support (including swiftmailer v6) we'd probably have to do abstraction in Email.php and refactor the thing.  

B)
If we go for "you must use SymfonyMailer" we'd need to refactor Email.php to use SymfonyMailer.  Might break some sites on upgrade which is bad eh?

**Comment by xini** [comment]
I think refactoring to use SymfonyMailer makes a lot of sense. SymfonyMailer supports the standard built-in transports like smtp and sendmail (https://symfony.com/doc/current/mailer.html#using-built-in-transports) but also has a lot of third-party transports available already (https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport).

**Comment by GuySartorelli** [comment]
We have a module we use on almost all of our sites ([signify-nz/silverstripe-mailblock](https://github.com/signify-nz/silverstripe-mailblock)) which includes a plugin for Swiftmailer - dropping support for Swiftmailer altogether in favour of SymfonyMailer would break that module.

IMO while it would be good to provide support for SymfonyMailer, Swiftmailer also needs to be supported until SS5.0 for backwards compatability, since dropping it would be a breaking change.

**Comment by emteknetnz** [comment]
Yes technically? Mailer is very lightweight interface - it's set here [here](https://github.com/silverstripe/silverstripe-framework/blob/4/_config/email.yml#L10). I'd be surprised if you could just swap this out and things just work.

The work for actually sending mails is done by [Email](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php) (and the Email class is a docblock param for the [Mailer](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Mailer.php) interface anyway).  Email is very much hardcoded to SwiftMailer e.g. https://github.com/silverstripe/silverstripe-framework/blob/4/src/Control/Email/Email.php#L263

Seems messy to turn this into an adapter at this stage in CMS4.  We have CMS5 on the horizon so that gives us the opportunity to do this cleaners

**Comment by GuySartorelli** [comment]
All PRs merged.
