### ISSUE TITLE
Document PHPUnit 9 transition

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10160]
Following the work to enable PHPUnit 9 support, we need to provide clear guidance on how to transition away sminnee/phpunit 5.7 to phpunit/phpunit.

# Acceptance criteria
- [x] A PHPUnit 9.5 transition guide has been written for doc.sulverstripe.org
- [x] A link to the guide has been added to the 4.10 changelog
- [x] Guide provides clear explanation about updating why the changes is needed and what your options are.
- [x] Guide explains how to update your set up to install PHPUnit 9.5.
- [x] Guide give a timeline for moving away from PHPUnit 5.7.
- [x] Guide provides guidance specific to module maintainers.
- [x] Common example of things that need to be changed are provided either in the guide or in a more informal channel like the forum
- [x] Bespoke developers have a chance to provide input

# Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10169

**Comment by emteknetnz** [comment]
I'd want to steer away from `Guide explains how to upgrade your project unit test to be compatible with PHPUnit 9.5.` since we're not technically responsible for that.  i.e. I don't want to write a comprehensive guide for all the API differences in PHPUnit 9 vs 5.  There's already things on the internet about the various things that were deprecated by the phpunit team.

If we do want to write something quick, speaking from experience, the 98% of the things are:
- `setUp()` and `tearDown()` require the `:void` return type
- `assertContains()` and `assertNotContains` no longer accept scalars (only strings in practice), so for strings needs to be updated to `assertStringContainsString()` and `assertStringNotContainsString()`
- `assertInternalType('<Type>') needs to be changed to `assertIs<Type>()` e.g. `assertIsInt()

**Comment by maxime-rainville** [comment]
All done
