### ISSUE TITLE
Is the return type in DataObject canX method PHPDocs incorrect?

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10184]
This question comes about from discussion in silverstripe/silverstripe-elemental#951 - some of which will be quoted here for convenience.

I was under the impression that `DataObject` canX methods (canView, canEdit, etc) methods should _always_ return a boolean value - either the user _can_ perform the action, or they _cannot_. The elemental module's `BaseElement` class, which is a subclass of `DataObject`, returns `null` under some circumstances.

@ScopeyNZ pointed out that `null` should be a valid return type here, and that the PHPDoc is wrong:
> The PHPDoc is wrong. null is a valid return type which basically means "defer". This is a tri-state. I'd raise an issue on SearchableService if it's incorrectly expecting a boolean, or not casting the value from DataObject::canX
> 
> I also don't know the reason for the tri-state, but returning null instead of false if you're not trying to explicitly deny should be the preferred approach.

Personally I think this doesn't make sense in the context of a `DataObject` - it makes sense from a `DataExtension` subclass which alters the permissions of the `DataObject`, but from a `DataObject` itself in my view the response should be a definite "yes you can" or "no you cannot" - it's not clear to me what value a `null` would provide here, since there's nothing to defer _to_. You'd be effectively saying "I don't know whether the user is allowed to perform that action" which imo could easily result in inconsistent behaviour if that is a canonically valid response from those methods.

If the tri-state is valid, and the PHPDoc for `DataObject` is incorrect, we will need to update not only the PHPDoc for `DataObject` itself, but also for any subclass of it which have implemented their own canX methods and include the PHPDoc. It would also be great if someone could document exactly what that null value means in this context.

Can we please get some clarification on this point?
Thanks.

**Comment by emteknetnz** [comment]
Personally it's the first time I've heard of canX being a tri-state rather than a boolean, though I haven't been around as long as others

Looking at the original code on the linked PR though

```
function canView() {
...
  return (Permission::check('CMS_ACCESS', 'any', $member)) ? true : null;
```

Where `null` is supposed to defer - I'm not sure why what "deferring" is actually supposed to do here?  I don't believe there's another object that would then see the `null` and then run another `canView()` check that returns a boolean, so I'd expect `null` to basically just get treated as `false` in practice.

**Comment by emteknetnz** [comment]
@GuySartorelli 
To fix your specific problem though, I'd be inclined to raise a PR to update FullTextSearch SearchableService::isSearchable to cast the canView checks as a `(bool)` so that the functions return type is always correct

PHPDoc type hinting is non-enforceable unlike proper return types, meaning that those canView checks could theoretically return a string or something even less helpful.  Casting to a bool should resolve this.

**Comment by kinglozzer** [comment]
@GuySartorelli I think you’re correct - `null` is only a valid return value in extensions’ can* methods, it should always be a boolean in `DataObject` classes themselves.

**Comment by GuySartorelli** [comment]
The specific issue that spawned this has been merged, and it seems likely that silverstripe/silverstripe-elemental#951 isn't going to be reopened for (founded) fears of BC issues.
I'll close this now.
