### ISSUE TITLE
[Enhancement] Warning in dev/build?flush for tablenames including blanks

### ISSUE THREAD

**Issue by Marimchen** [silverstripe/silverstripe-framework#10259]
Can you please add some kind of warning message or an red error-message in dev/build for classes which have a blank at the beginning of their name e.g " MyTable" or "My Table". It's hard to see in the database itself and it causes real bad behaviour for popular modules like silverstripe-fluent from tractorcow.

Thank you very much, kind regards

**Comment by dhensby** [comment]
Under what kind of circumstances to table names have spaces at the front or in the names? Is it developer error, or is YML/config being parsed incorrectly and adding whitespace erroneously?

**Comment by dhensby** [comment]
If everything is working as expected with spaces in *except* fluent, it seems the bug is in fluent rather than in the framework? If identifiers with spaces are valid, why should we issue warnings about it? It's pretty tricky to know what developer intent is and to know that a space should or shouldn't be in a name or not.

I can definitely see that it *could* have compatibility issues (though it seems, in general, it doesn't) but that's also true for our table names with capital letters in them, but we allow those.

**Comment by GuySartorelli** [comment]
Spaces are valid in SQL table names - I agree that this sounds like a bug in the fluent module.

**Comment by GuySartorelli** [comment]
I've opened tractorcow-farm/silverstripe-fluent#764 and am closing this issue in favour of the new on in fluent.
