### ISSUE TITLE
4.11.0-beta1 login doesn't work with PHP 8.1

### ISSUE THREAD

**Issue by xini** [silverstripe/silverstripe-framework#10304]
## Affected Version

4.11.0-beta1, PHP 8.1

## Description

When you visit /admin/pages you get redirected to /Security/login correctly. When you then submit the form, you get redirected back to the login form instead of the CMS. 

With PHP 8.0 it works. 

There is no difference whether silverstripe/login-forms is installed or not.

**Comment by GuySartorelli** [comment]
Hi @xini 
I cannot reproduce this - can you please provide your `composer.json`?

**Comment by xini** [comment]
Thanks @GuySartorelli, that's weird. Here my `composer.json`:

```
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": "^7.4 || ^8",
        "silverstripe/recipe-cms": "^4.11.0-beta",
        "silverstripe/login-forms": "^4.7.0-beta1",
        "silverstripe/html5": "^2.3.0",
        "silverstripe-themes/simple": "~3.2.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"
    },
    "autoload": {
        "psr-4": {
            "Innoweb\\SS4Dev\\": "app/src/"
        },
        "classmap": [
            "app/src/Core/Pages/Page.php",
            "app/src/Core/Pages/PageController.php"
        ]
    },
    "extra": {
        "resources-dir": "_resources",
        "project-files-installed": [
            "app/.htaccess",
            "app/_config.php",
            "app/_config/mimevalidator.yml",
            "app/_config/mysite.yml",
            "app/src/Page.php",
            "app/src/PageController.php"
        ],
        "public-files-installed": [
            ".htaccess",
            "index.php",
            "web.config"
        ]
    },
    "config": {
        "process-timeout": 600,
        "allow-plugins": {
            "composer/installers": true,
            "silverstripe/vendor-plugin": true,
            "silverstripe/recipe-plugin": true
        },
        "preferred-install": {
            "silverstripe/html5": "source"
        }
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```

**Comment by GuySartorelli** [comment]
Even with that exact composer.json file in an entirely new environment, I'm unable to reproduce this issue.
It is likely to either be caused by:
- incorrect credentials when you're trying to log in
- some custom code you have introduced (try it with a fresh install and fresh database)
- something to do with your server configuration
- ?? Something else?

I suppose it could also be the _specific_ version of php 8.1 you have? I'm using php 8.1.5

**Comment by xini** [comment]
Thanks, @GuySartorelli.
I can exclude 1 and 2 as the site works when I run PHP 8.0.
I have cleared everything out, installed from scratch and upgraded PHP from 8.1.0 to 8.1.5. 
Still the same. Any other ideas?

**Comment by GuySartorelli** [comment]
I don't think you can exclude 2 just because it works on other PHP versions. There could be something either in your code, or in an interaction between your code and core, that php 8.1 doesn't like.
But also you said "I have cleared everything out, installed from scratch" so I guess that rules that one out.

I can't think of what would be causing that, sorry. It's working locally for myself and other colleagues I've asked to try it, and we also don't experience this problem with our behat tests. I'll leave this open for the day in case someone else has some ideas, but then I'm going to close it as this doesn't seem to be an issue with core itself. Might be worth asking on slack to see if anyone else has had a similar issue, or might have ideas for how to help you resolve it.

**Comment by xini** [comment]
@GuySartorelli thank you very much. 
I have upgraded another project of mine to 4.11 and PHP 8.1, unfortunately with the same result. So there is definitely something that I'm not seeing...
I'll keep digging.

**Comment by michalkleiner** [comment]
Could be a difference in PHP modules/config? `php -i` might help.
Another thing I'd check is whether Composer actually runs PHP 8.1 as you allow 7.4 in the constraints. I'd remove that from composer.json and try again.

**Comment by xini** [comment]
oh god... composer was using 8.1, yes. now I have removed php8.1from the server and re-installed it, and installed a new version of ss4.11-beta with a new database. now it works. no idea what it was though. thanks everyone for their help. and sorry for the trouble...
