### ISSUE TITLE
Upgrade CMS5 to use TinyMCE6

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10369]
## Acceptance criteria
- [x] Silverstripe CMS 5 uses TinyMCE6
- [x] All existing WYSIWYG functionality is retained.
- ~~Skin is replicated~~ See https://github.com/silverstripe/silverstripe-admin/issues/1366
- [x] Our current plugins are upgraded to work
- [x] Upgrade docs are updated to reflect any changes developers will need in their own projects (within reason - we can just link to tinymce's notes where appropriate)
- [x] Documentation that mentions tinymce generally is updated

## Note
- TinyMCE has a react integration. There might be some value in converting our HTMLEditor field to be a pure react component. But that's a secondary concern.
- "Paste from word" and "spell check" plugins are now premium plugins. We might need to validate how much of a pain loosing those will be.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10508
- https://github.com/silverstripe/silverstripe-admin/pull/1367
- https://github.com/silverstripe/silverstripe-cms/pull/2781
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1293
- https://github.com/silverstripe/developer-docs/pull/91

## Fix PRs
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1295
- https://github.com/silverstripe/silverstripe-admin/pull/1372
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1296

**Comment by maxime-rainville** [comment]
@GuySartorelli will have an initial look at to what has changed between TinyMCE 4 and 6.

**Comment by GuySartorelli** [comment]
Had a bit of a look around and a play.

## Download options
1. Download .zip file from https://www.tiny.cloud/get-tiny/ and include in `thirdparty` dir
    - This is how we do it atm but it's not ideal. Makes it harder to update.
2. Install via yarn: https://www.tiny.cloud/docs/tinymce/6/npm-projects/#install-tinymce-using-npm-or-yarn
    - Just the regular JS without the official react component.
3. Official react component: https://github.com/tinymce/tinymce-react
    - I haven't look much into this - we already have our own react component and this one doesn't seem to add much. If anything it would probably be more work to rip out our one and re-do our code to use this one.

## Upgrade path
There is docs for upgrading from 4 to 5, and from 5 to 6. We can use those to figure out what has been deprecated or removed from 4 to 6.
[Docs for upgrading from 4 to 5](https://www.tiny.cloud/docs/migration-from-4x/)
[Docs for upgrading from 5 to 6](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/)

The following are things I know we'll have to make changes for:
- The `paste`, `spellchecker` and `contextmenu` plugins have been removed.
  - Spellchecker functionality is now premium, though the `browser_spellcheck` option still works.
  - Context menus are [now part of core](https://www.tiny.cloud/docs/tinymce/6/contextmenu/) instead of a separate plugin
  - Paste is now [part of core](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#plugins-paste) instead of a separate plugin
    - Word paste functionality is explicitly not supported - there is a [call for maintainers](https://github.com/tinymce/tinymce/discussions/7487) if we think this is worth supporting (which IMO it is)
    - There is a premium [powerpaste](https://www.tiny.cloud/tinymce/features/powerpaste/) plugin that includes pasting from word
- The `mode` option has been deprecated and is no longer used
- The 'modern' theme has been replaced with the 'silver' theme.
- Third-party skins (i.e. our skin) should be applied using the `skin_url` option: https://www.tiny.cloud/docs/tinymce/6/editor-skin/#skin_url
- Various plugin API have changed: https://www.tiny.cloud/docs/migration-from-4x/#plugins
  - This will mean we need to change our sslink, ssemail, and other custom plugins
- There are a few changes to events firing that we may need to look into
- Our changetracker js needs a slight modification.
  ```diff
  - var serializer = new tinymce.html.Serializer(config);
  - var parser = new tinymce.html.DomParser(config);
  + var serializer = tinymce.html.Serializer(config);
  + var parser = tinymce.html.DomParser(config);
  ```
  - Note: Not sure if that will actually work - but the console _was_ complaining before I made that change, 'cause those aren't constructors anymore. May be related to [new keyword no longer used to instantiate plugins](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#new-keyword-no-longer-used-to-instantiate-plugins)

**Comment by GuySartorelli** [comment]
@silverstripe/core-team
While upgrading I've run into a scenario where it will be easier to make a change than to retain the existing behaviour, and I'd like some feedback to decide whether to make the change or not.

## Existing behaviour
- When _saving_ content from the visual editor into the underlying `textarea` element, a conversion takes place where content added through the embed or media plugins (i.e. embed a youtube video or insert an image) is converted from its HTML markup to shortcode markup.
- When loading content _from_ the `textarea` _to_ the visual editor, those shortcodes are converted back to their HTML markup
- This conversion is _different_ from the conversion in PHP - i.e. the HTML markup in the visual editor is _not identical_ to the markup that will be displayed on the front end.
- This HTML markup is not only used in the visual editor but also displayed in the code editor.

![code editor showing the temporary html markup](https://user-images.githubusercontent.com/36352093/191142930-36d29d04-5e8e-4afa-b559-81f1c4b4ae9d.png)

## Proposed new behaviour
- This conversion happens when _getting_ content from and _setting_ content into the visual editor. The difference here is that the HTML markup will only be used inside the visual editor as a visual placeholder - but the code editor will show the shortcode markup as it will be stored in the database

![code editor showing the shortcode markup](https://user-images.githubusercontent.com/36352093/191143178-6bf7245f-6d02-40ad-a710-896fa89ff032.png)

## Reasoning
- The `SaveContent` event has changed in tinymce6. I can't see any documentation about this change, but although the event fires the new content (with the shortcode markup) doesn't actually end up in the `textarea` which means it gets stored in the database with the HTML markup which was only intended as a placeholder for the WYSIWYG visual editor
  - The event is listed as supported [in this list](https://www.tiny.cloud/docs/tinymce/6/webcomponent-ref/#supported-tinymce-events) but is completely absent [from this list](https://www.tiny.cloud/docs/tinymce/6/events/) which leads me to believe the documentation in that first list is simply outdated and it's not actually supported anymore.
- The temporary HTML markup displayed in the visual editor is misleading anyway - if you modify that markup for the embed, it may result in the embedded shortcode not actually working as expected. If we instead display the actual shortcode inside the code editor it is clearer what will _actually_ be affected
- Link shortcode and custom shortcodes already display in the code editor _as shortcodes_ - doing this with embeds and images will be more consistent

**Comment by emteknetnz** [comment]
This seems like a good change to me.

As I understand it, this would only have an effect on end users when clicking the "view source" button, which is itself is probably a fairly narrow use case for a content editor.  The fact they're seeing shortcodes instead of html tag does seem like it's that big of a deal.  They can still see what's going on.

As a developer this is improvement as what's I see when I click "view source" is closer to what's in the database.

I also like that fact we'd be removing some "duplicate yet different" conversion logic

**Comment by GuySartorelli** [comment]
To be clear, the conversion logic is still going to be there - it's necessary for the visual WYSIWYG editor to display the image or embed placeholder. It's just that the dummy HTML markup will _only_ be used inside the visual editor where before it was used anywhere tinymce used the markup.

**Comment by lozcalver** [comment]
I’m fine with this change. In TinyMCE 4, if you view source and edit the “HTML” for a shortcode (that is, the placeholder HTML) then presumably you’ll lose any edits anyway?

As an aside, how flexible/“pluggable” is the placeholder conversion logic? We sometimes override shortcodes to change how they’re rendered on the frontend, it’d be great to be able to update the placeholder conversion logic so the visual representation is closer to the rendered content.

**Comment by GuySartorelli** [comment]
> In TinyMCE 4, if you view source and edit the “HTML” for a shortcode (that is, the placeholder HTML) then presumably you’ll lose any edits anyway?

Depends what the edits are. The image shortcode will accept any attributes you add to it - that will be the case in its shortcode syntax form as well. The embed shortcode won't, though, so edits on the temp-markup for that would be mostly lost.

> how flexible/“pluggable” is the placeholder conversion logic?

I don't think it would be possible to extend or replace it with your own conversion logic with the way it's written at the moment. Check out the `SaveContent` and `BeforeSetContent` event handlers in [TinyMCE_ssembed.js](https://github.com/creative-commoners/silverstripe-asset-admin/blob/1/client/src/entwine/TinyMCE_ssembed.js) for an example.
