### ISSUE TITLE
SPIKE Strongly type every thing

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10414]
There could be some value in strongly typing all our code base.

How we go about dong that is unclear.

## Objectives
- Explore various approaches to achieve this, automated or otherwise.
- Evaluate how much effort would be needed to do this. 
- Identify how much work this change would impose on people upgrading.

# Timebox
4 days

# POC PR
- https://github.com/silverstripe/silverstripe-framework/pull/10453 **(draft, don't merge)**

**Comment by emteknetnz** [comment]
### Summary

Code writing strong typing based on trace results is viable, though there are concerns with accuracy

With further work we could get this to pass with our CI-suite of tests, though we won't know how it performs in the real world until after we tag 5.0.0 stable.  So there's plenty of risk associated with doing this.

### Approach

I wrote a code tracer, trace analyser and code writer - https://github.com/emteknetnz/type-transitioner which is a 3-step process:

1. Code-writing to add trace statements _a() and _r() to all methods which are used for log trace results to a text file
2. Running ALL unit-test and behat tests in recipe-kitchen-sink to generate the trace text file
3. Using the results of the trace text file, code write in strongly type params and return types

I created a draft [PR](https://github.com/silverstripe/silverstripe-framework/pull/10453) that shows the scope of change on silverstripe/framework.  If we decide to continue it can be tidied up e.g. using imports instead of inlining fqcn's, etc

The big limitation to this approach is that it relys on unit-test and behat test coverage.  The type detection in tracing is only as good as the test coverage.

I analysed the existing docblocks in silverstripe/framework and determined they're basically useless for code-writing strongly typed methods due to their high innacuracy rate compared to what is actually passed in the trace results.  I got a paltry ~41%, which is partly limited by the difficulty in translating non-fqcn classnames in docblocks to the fqcn counterparts, though I wouldn't expect this to go up by much with more sophistication.

```
[method_traced] => 4155 (80.3%)
[method_not_traced] => 1022 (19.7%)
[-] => 
[traced_param_has_docblock] => 3402 (79.8%)
[traced_param_missing_docblock] => 861 (20.2%)
[--] => 
[traced_arg_in_docblock] => 2646 (39.4%)
[traced_arg_null_not_in_docblock] => 625 (9.3%)
[traced_arg_in_docblock_as_mixed] => 91 (1.4%)
[traced_arg_not_in_docblock] => 3353 (49.9%)
[---] => 
[traced_return_has_docblock] => 2677 (65.1%)
[traced_return_missing_docblock] => 1433 (34.9%)
[----] => 
[traced_return_in_docblock] => 10294 (54.6%)
[traced_return_in_docblock_as_mixed] => 6171 (32.7%)
[traced_return_not_in_docblock] => 2393 (12.7%)
[-----] => 
[not_traced_param_has_docblock] => 605 (66.3%)
[not_traced_param_missing_docblock] => 308 (33.7%)
[------] => 
[not_traced_return_has_docblock] => 565 (55.3%)
[not_traced_return_missing_docblock] => 457 (44.7%)
```

**Comment by GuySartorelli** [comment]
## Low risk automation opportunities

The scope for low-risk automation is quite small, I think. The only thing I could think of isn't something *I* thought of, it was an example Steve gave:

- Add `void` return types for any methods that simply do not return any value (either no `return` statements at all, or the return statements are explicitly `return;`)

Beyond this case, which we can have confidence in explicitly because there _is_ no typing, I think any type we add for any purpose has an equal level of risk across the board of being incorrect.

## Where to go from here

This approach does have promise. With more data (I still think running this through some of the larger bespoke test suites would be worthwhile since they will test logic for use cases that our tests probably effectively ignore), it could produce some solid results. It is likely that this, or something _like_ this, would be worth doing for CMS 6 when we have more time to set this up, review it thoroughly, and have ample time for regression testing.
That said I don't think we do have enough time to do that thoroughly for a CMS 5 release, so the risk is quite high.

I think that for CMS 5 we should park this idea - the low risk options don't provide much value, and the high risk options are just too risky with the timeframe we have.

For CMS 6 we should revisit this, and either run this early and use bespoke projects as test cases to validate it and ask for community feedback _very_ early on, _OR_ look for specific high-usage classes, methods, and properties to start with (derisking by narrowing the scope of the changes), and slowly branch out from there in subsequent major releases.

We can also make this easier on ourselves by defining a phpstan or similar config which runs against PRs about how we use certain classes/methods in core code. This would be helpful for example to ensure core code keeps to a set of types we _think_ are appropriate before we add the actual type restrictions into the codebase itself.

## What _can_ we do for CMS 5?
A separate but related exercise which would be beneficial is look for any method which accepts a variable number of arguments (search for `func_get_args()`) and set explicit parameters instead (e.g. `RequiredFields`'s constructor should have a parameter `array $fields = []`).
We shouldn't automate this for the same reason risk-factor reasons we should hold back on the general automation of parameters/return types in CMS 5 - but there are only 69 instances across 42 files of this in `silverstripe/` code (excluding tests) which is far from insurmountable to do manually.

**Comment by emteknetnz** [comment]
Note: there was an issue with the type-transitioner module where `$lineageJ = $this->getClassLineage($argTypeI);` should have been `$lineageJ = $this->getClassLineage($argTypeJ);` - this caused some odd return types such as `CMSMain` instead of `Controller`.  However rerunning the task to generate the pull-request resulted in getting stuff in a recursive loop, and by this point it's obvious that we're not going to proceed with this course of action, so I didn't bother to fix properly.

If this hadn't been broken in the first place, I still don't believe it would have changed our decision to not proceed.  The fundamental issue is that we're not confident that a fully automated approach has enough test coverage to lower the risk of doing this enough.

**Comment by GuySartorelli** [comment]
Actions:

- Create a card to replace `func_get_args()` with concrete parameters
- Create a card to add strong typing for high-traffic methods (e.g. methods in `DataObject` or `DataList`)

**Comment by emteknetnz** [comment]
Have raised a couple of follow up issues
- https://github.com/silverstripe/silverstripe-framework/issues/10455
- https://github.com/silverstripeltd/product-issues/issues/583

**Comment by LiamKearn** [comment]
@emteknetnz Not sure how much work would be required to use: https://tomasvotruba.com/blog/2019/11/11/from-0-doc-types-to-full-type-declaration-with-dynamic-analysis/. I remember reading this blog post at some point and saw this issue on the sprint forum. I know some are overzealous about rector but it's worth taking a look at if it's not a huge hassle to setup IMO.

I'm not saying to replace your analyser with it (I have a feeling rector might not work straight away as it advertises) I'm just saying if possible running the test with two different tools could yield more stats to make decisions on :)

EDIT: Ah never-mind I've seen your closed PR comment now, Best of luck with this for CMS 6 🤞🏻
