### ISSUE TITLE
ArrayList::canFilterBy() does't work with ArrayData fields

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-framework#10428]
# ArrayList::canFilterBy() does't work with ArrayData fields

Impacted version: CMS 4.10.

Looks like the current implementation doesn't work with magically defined properties. Tested this with a GridField with the default config and a very plain data source (ArrayList populated with ArrayData items).

![Screen Shot 2022-07-28 at 9 45 20 AM](https://user-images.githubusercontent.com/26395487/181378628-7ec6264d-bafa-4d52-997a-c70b038ef62f.png)

This behaviour is expected as per [PHP documentation](https://www.php.net/manual/en/function.property-exists.php).

![Screen Shot 2022-07-28 at 9 50 00 AM](https://user-images.githubusercontent.com/26395487/181378755-dd859fc4-6a0e-4d9d-bf16-4534c10aad91.png)

## Impact

Using plain ArrayList with ArrayData items in a GridField results in the inability to use filter header component as the canFilterBy() returns false even if the GridField is correctly configured.

### Example code snippet

```php
*
 * Format raw array data into a GridField table
 * Data is expected to follow this format
 * - list of items representing rows
 * - each item has named keys representing columns
 *
 * @param array $data
 * @param Form $form
 * @param string $fieldName
 * @return GridField|null
 */
public function formatArrayIntoGridField(array $data, Form $form, string $fieldName): ?GridField
{
    if (count($data) === 0) {
        return null;
    }

    // Determine header table columns
    $firstItem = $data;
    $firstItem = array_shift($firstItem);
    $header = array_keys($firstItem);
    $header = array_unique($header);
    $header = array_combine($header, $header);

    // Compose GridField data
    $source = ArrayList::create();

    foreach ($data as $item) {
        $itemData = ArrayData::create($item);
        $source->push($itemData);
    }

    $gridField = GridField::create($fieldName, null, $source);
    $gridField->setForm($form);

    /** @var GridFieldDataColumns $dataColumns */
    $dataColumns = $gridField
        ->getConfig()
        ->getComponentByType(GridFieldDataColumns::class);
    $dataColumns->setDisplayFields($header);

    return $gridField;
}
```

You are expected to feed the function data in a table format. Something like this:

```php
$data = [
    [
        'Column1' => 'Value11',
        'Column2' => 'Value12',
    ],
    [
        'Column1' => 'Value21',
        'Column2' => 'Value22',
    ],
];
```

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10915

**Comment by emteknetnz** [comment]
I'm honestly inclined to just deprecate the method. I don't see anyway to get this to work in all scenarios since `property_exists()` doesn't work with the `__get()` magic method and there's just a whole lot of magic going on

I did try to see if calling [ViewableData::__isset()](https://github.com/silverstripe/silverstripe-framework/blob/5.0/src/View/ViewableData.php#L113) directly which has the similar logic as ViewableData::__get() and like you'd expected ViewableData::__has(). It doesn't work, even in CMS 5 which is slightly less magic in that it uses [hasDynmicData()](https://github.com/silverstripe/silverstripe-framework/blob/5.0/src/View/ViewableData.php#L253) and friends instead of pre php 8.2 dynamic properties

As an example of probably why PHP doesn't allow `property_exists()` to work with `__get()`, let's say there's the following class - there's no easy way for PHP to know that `property_exists(new MyClass(), 'mySomething')` should return `true`:

```php
class MyClass extends ViewableData
{
    private $myPrivate = 123;

    public function __get($prop)
    {
        if (prop == 'mySomething') {
            return $this->myPrivate;
        }
    }
}
```

Only way I can see this working is horrible and still doesn't really work.  It would be to iterate the entire ArrayList and see if any the values in there has a property that has a non-null value.  Of course because of the magic the 'property' could easily end up being a database call so it could get incredibly expensive quickly if everything returns null.  Also null may be a valid return value.

Note that while this issue mentions `ArrayData` seems like we should just look at `ArrayData::hasField()` inside `ArrayList::canFilterBy()` - `ArrayList->items[]` can contain anything, not just `ArrayData`

If anyone can spot something I've missed then I'm open to suggestions, otherwise I'll look to just deprecate this.

**Comment by GuySartorelli** [comment]
@emteknetnz I've added a PR to this issue which I think fixes it.

**Comment by emteknetnz** [comment]
Nice, merged it.  Discussed offline - Guy pointed out that it's up to subclasses of ViewableData to implement hasField() themselves so that ViewableData::__get() still works correctly.
