### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10574]
https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/3420591854/jobs/5695618864

In the recipe-kitchen-sink specifically, apparently in only one area of framework, user errors are being emitted instead of converted to exceptions which means they can't be detected. This results in the following failed tests:

> `1)` SilverStripe\i18n\Tests\i18nTextCollectorTest::testCollectFromNewTemplateSyntaxUsingParserSubclass
Failed asserting that exception of type "PHPUnit\Framework\Error\Notice" is thrown.
>
> phpvfscomposer:///home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/phpunit/phpunit/phpunit:97
/home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/bin/phpunit:118

> `2)` SilverStripe\i18n\Tests\i18nTextCollectorTest::testCollectFromTemplateAdvanced
Failed asserting that exception of type "PHPUnit\Framework\Error\Notice" is thrown.
>
> phpvfscomposer:///home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/phpunit/phpunit/phpunit:97
/home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/bin/phpunit:118

> `3)` SilverStripe\i18n\Tests\i18nTextCollectorTest::testCollectFromCodeNewSignature
Failed asserting that exception of type "PHPUnit\Framework\Error\Notice" is thrown.
>
> phpvfscomposer:///home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/phpunit/phpunit/phpunit:97
/home/runner/work/recipe-kitchen-sink/recipe-kitchen-sink/vendor/bin/phpunit:118

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10576

**Comment by emteknetnz** [comment]
For whatever reason framework was checked out in that failing job with and older framework commit `00f0b01` which is one commit before the "Use restore_error_handler()" commit

I can replicate this issue locally with framework commit `00f0b01` using a testsuite of 
```
<directory>vendor/silverstripe/framework/tests/php/Dev</directory>
<directory>vendor/silverstripe/framework/tests/php/i18n</directory>
```

When I use newer framework commit `ed63bee` using the same testsuite it passes

This shows the regression was caused by the custom error handler in the `Deprecation` class.  All we need to do is re-run the recipe-kitchen-sink build, ensure it picks up a newer framework commit and it should pass

I've manually triggered a new build [here](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/3425144335)

**Comment by GuySartorelli** [comment]
PR merged.
