### ISSUE TITLE
Improve deprecation warnings in CMS4 UI

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#10608]
With the upcoming release of Silverstripe CMS 5, we will be encouraging a lot more devs to enable deprecation warnings. So this feature will get a lot of attention very soon.

The current look for deprecation warning is pretty bad. It just dumps the error in plain text. This is not developer friendly. Some developers might like the option to output those warnings to their error logs instead of displaying them directly in the browser.

![image](https://user-images.githubusercontent.com/1168676/206404959-8ea06ead-788a-434a-9df5-f5ebd8bbc56d.png)

## Acceptance criteria
- [ ] Developers can choose to display deprecation warnings in the browser or in their error logs.
- [ ] When deprecations are displayed in the browser, they are generally well formatted and readable.
- [x] Doc is updated to explain how to control where the deprecation warnings are showed.

## Note
- Former colleague @adrhumphreys had a POC to include a better error formatter. We might want to look at that.
- Arguably, this as a UX component although only devs should see it.
- Maybe we could use the Debug bar for this purpose.
- The actual error was creating by adding a fake deprecation to a random

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10697
- https://github.com/lekoala/silverstripe-debugbar/pull/148
- https://github.com/silverstripe/developer-docs/pull/165

**Comment by maxime-rainville** [comment]
If you create a deprecation warning using `user_error('bah', E_USER_WARNING);` you get something like this. Not perfect, but it's way better than what we show natively. I would be happy with that.

![image.png](https://images.zenhubusercontent.com/5ac42fb74b5806bc2bcd8e13/bf5ff3db-9657-443f-8d01-9ba378bb605b)

**Comment by GuySartorelli** [comment]
Note:
https://github.com/Seldaek/monolog/blob/1.x/doc/01-usage.md#log-levels
> NOTICE (250): Normal but significant events.
> WARNING (300): Exceptional occurrences that are not errors. Examples: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.

But currently monolog logs `E_USER_DEPRECATED` and `E_DEPRECATED` as notices
https://github.com/Seldaek/monolog/blob/904713c5929655dc9b97288b69cfeedad610c9a1/src/Monolog/ErrorHandler.php#L109-L128

@maxime-rainville This means _we_ are currently logging these as `NOTICE` when really it seems both logically and according to documentation that they should be logged as `WARNING`. I'm inclined to make this change - but I'd like your thoughts first on whether this is "allowed" as a minor version change.

**Comment by GuySartorelli** [comment]
> If you create a deprecation warning using user_error('bah', E_USER_WARNING); you get something like this.

If you use `E_USER_WARNING` instead of `E_USER_DEPRECATED` in `Deprecation::outputNotices()` the output does not change. You get the output you showed there if `E_USER_DEPRECATED` is used in `Page::getCMSFields()` as well. The problem is not the _type_ of error, but when it's being output.

**Comment by maxime-rainville** [comment]
> This means we are currently logging these as NOTICE when really it seems both logically and according to documentation that they should be logged as WARNING. I'm inclined to make this change.

Go for it ... the worst thing that could happen in my mind is that someone had set up their production environment to suppress notices but not warnings ... Which sounds like an insane set up.

> If you use E_USER_WARNING instead of E_USER_DEPRECATED in Deprecation::outputNotices() the output does not change. You get the output you showed there if E_USER_DEPRECATED is used in Page::getCMSFields() as well. 

I was just trying to find a way to systematically get the "nice" error styling. I take it that the `user_error()` calls are being handled by [DebugView](https://github.com/silverstripe/silverstripe-framework/blob/ab566b0a156376020dc25e6754c9d07ca12c2d56/src/Dev/DebugView.php#L241).

Don't necessarily have views on the best way to get the deprecation warning rendered nicely.

**Comment by GuySartorelli** [comment]
Logging deprecations in debugbar is pretty easy it turns out - with exception of XHR requests in the CMS.

The main issue this card is built for is XHR requests inside the CMS - which we just can't do anything about without a _lot_ of faffing about either detecting deprecation notices in _all_ of our XHR requests and putting them in a separate place in the DOM _or_ having some session-based pool of deprecation warnings, which we then have a _special_ XHR request to fetch all warnings in the pool, and then put them... somewhere in the DOM.

Basically, having deprecation notices that come from XHR requests look nice in the browser is a _lot_ more effort than it's worth. 

There's two ways we can go about this:

**Option 1**
- The recommended way to look at deprecation notices is to log them into a file.
- Debugbar can be used to limited effect for people who want that option.
- By default, if you enable deprecations but _do not_ have debugbar installed and aren't logging errors to a file, you will simply see nothing (or perhaps we throw a standard warning in that case).

**Option 2**
- The recommended way to look at deprecation notices is to log them into a file.
- Debugbar can be used to limited effect for people who want that option.
- By default deprecation warnings will be output to the DOM in the way they currently are.

There's a secret third option to spend a bunch of time implementing one of the other solutions I mentioned above but frankly those will take forever to implement with very little benefit and these could be prone to introducing regressions. Developers should be comfortable looking through logs, seriously, logging is good.

@maxime-rainville Do you have a preference of the above options? I'd prefer just _never_ output them directly to the DOM, and say the only official way to see deprecation warnings is to log them to a file or use debug bar (i.e. option 1). @emteknetnz has also said he's onboard with that idea.

**Comment by maxime-rainville** [comment]
Doesn't seem like there's an lot of daylight between option 1 and 2. Is the only difference that Option 1 would suppress deprecation warning on XHR requests? I still think there would be some value in outputting the the deprecations as regular warning in that scenario.

Whatever we do, I think we need to be very clear about needing the debug bar and give very clear explications on that front.

**Comment by GuySartorelli** [comment]
The only difference is that Option 1 would _never_ output directly to your browser (and CLI) (you'd have to set up an appropriate logging handler, or install debugbar which is in itself just a fancy logging handler) - whereas option 2 would _by default_ output to the browser (and CLI) like it currently does, but that can be disabled (basically the framework PR in this card right now is option 2).

You can see the docs PR re being very clear etc.
In either case, it sounds like you prefer option 2, is that correct?

**Comment by GuySartorelli** [comment]
Discussed in person - either option is fine. I've gone with option 1.

**Comment by GuySartorelli** [comment]
@max there's a question for you in the docs PR
