### ISSUE TITLE
Incorrect Email Rendering with Swift_MailTransport in SilverStripe

### ISSUE THREAD

**Issue by niklas-cic** [silverstripe/silverstripe-framework#10668]
## Affected Version

mikey179/vfsstream          v1.6.11 Virtual file system to mock the real file system in unit tests.
silverstripe-themes/simple  3.2.1   The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/frameworktest  0.4.12  Aids core and module developers in testing their code against a set of sample data and behaviour.
silverstripe/login-forms    4.8.0   A collection of templates for the CMS login screens
silverstripe/recipe-cms     4.12.0  SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin  1.7.0   Helper plugin to install SilverStripe recipes
silverstripe/recipe-testing 2.0.0

## Description

Incorrect email rendering occurs in SilverStripe when using Swift_MailTransport to send emails, as it uses newline character (\n) in headers instead of the required carriage return and newline (\r\n) by PHP's mail function (https://www.php.net/manual/de/function.mail.php). This causes the email to be sent with text/plain content type instead of multipart/alternative.

## Steps to Reproduce

1. Create a new SilverStripe project.
2. Set up SwiftMailer with Swift_MailTransport.
3. Send an email using the Email class.

**Comment by emteknetnz** [comment]
The php mail() function, used by the MailTransport was [deprecated and removed by swiftmailer](https://github.com/swiftmailer/swiftmailer/issues/866) due to security concerns about the PHP mail() function.  The recommended replacement is sendmail or SMTP.

The Swift_MailTransport was copied to the [silverstripe/framework thirdparty directory](https://github.com/silverstripe/silverstripe-framework/blob/4/thirdparty/swiftmailer/Swift/MailTransport.php#L4) simply to keep backwards compatibility in CMS 4 for the mail() function.

In CMS 5, SwiftMailer has been replaced with symfony/mailer and there is no support for the PHP mail() function

Given that the mail() function won't be supported going forward, this will not be fixed
