### ISSUE TITLE
CMS 5 beta: Possible ViewableData regression (maybe related to DBComposite fields)

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-framework#10684]
## Affected Version

CMS 5 beta

## Description

I'm working on Silverstripe 5 support for the [FocusPoint](https://github.com/jonom/silverstripe-focuspoint) module, and I'm struggling a bit to understand some behaviour change that seems to have occurred.

I don't think this is FocusPoint specific, but might be related to composite fields?.. The FocusPoint module uses a `DBComposite` field to store some basic information.

```php
$newFocusPoint = DBFocusPoint::create();
$newFocusPoint->setValue([
    'X'      => $cropData['x']['FocusPoint'],
    'Y'      => $cropData['y']['FocusPoint'],
    'Width'  => $cropData['x']['TargetLength'],
    'Height' => $cropData['y']['TargetLength'],
], $newImage);

print_r($newFocusPoint);

// important bit here
$newImage->FocusPoint = $newFocusPoint;

print_r($newImage->FocusPoint);
```

Before:

`$newImage->FocusPoint` was equal to `$newFocusPoint`.

Now:
`$newImage->FocusPoint` is equal to whatever the `FocusPoint` was before the new assignment.

## Acceptance critera
- We validated that this is a problem related to DBComposite field (an not something specific to FocusPoint)
- If this is an actual bug in CMS 5, fix the issue.
- If this is expected behviour, document a proper fix and call it out in the CMS5 upgrade doc.

## Notes
- There's a DBMoney field that has similar each functionality. This could be a good example to test if the problem is with FocusPoint or with DBComposite.

### PRs
- https://github.com/silverstripe/silverstripe-framework/pull/10698
- https://github.com/silverstripe/developer-docs/pull/166

**Comment by GuySartorelli** [comment]
@maxime-rainville FYI this one is blocking upgrades bespoke are doing

**Comment by emteknetnz** [comment]
@chrispenny I've debugged this, issue is that [this dynamic property](https://github.com/jonom/silverstripe-focuspoint/blob/master/src/Extensions/FocusPointDBFileExtension.php#L56) is not getting set

**FocusPointDBFileExtension.php**
```php
    public function setFocusPoint(?DBFocusPoint $point): self
    {
        $this->owner->focuspoint_object = $point;
        // var_dump($this->owner->focuspoint_object); // CMS 5 = null, CMS 4 = DBFocusPoint <<<<<<<<<<<
        return $this;
    }
```

This no longer works because of the changes we made to ViewableData to give PHP 8.2 support to the old dynamic properties behaviour - https://github.com/silverstripe/silverstripe-framework/blob/5.0/src/View/ViewableData.php#L233

There's no easy way to make this work, long story short you get tripped on the overloaded `DBComposite::hasField()` which will ALWAYS return `false`, so while `$this->owner->__set('focuspoint_object')` will set a dynamic property, you cannot actually get it via `$this->owner->__get('focuspoint_object')` because it will call the always false `DBComposite::hasField()`

This is such a narrow use case we're solving for here (it's frankly bad looking code) that I'm fairly inclined to not touch framework at all. If we did we'd be adding dynamic property support on to DBComposite which IMO we just shouldn't be doing, because dynamic properties are just weird quasi API.

This following is a functional solution that is not 100% non-breakable, due to the use of `spl_object_id` because of "The object id is unique for the lifetime of the object. Once the object is destroyed, its id may be reused for other objects" - https://www.php.net/manual/en/function.spl-object-id.php.  Because we're caching a result we could end up with a cache hit when we shouldn't.  However in practice we don't destroy objects within the same request. I've added a `serialize($this->owner)` to be safe.

**FocusPointDBFileExtension**
```php
<?php

namespace JonoM\FocusPoint\Extensions;

use JonoM\FocusPoint\FieldType\DBFocusPoint;
use SilverStripe\Assets\Storage\DBFile;
use SilverStripe\View\ViewableData;

/**
 * @property DBFile|FocusPointDBFileExtension $owner
 */
class FocusPointDBFileExtension extends FocusPointExtension
{
    /**
     * Marking as internal means this is not treated as config by PrivateStaticTransformer
     * @internal
     */
    private static $focusPoints = [];

    /**
     * 
     */
    private function getObjectIden(): string
    {
        return md5(spl_object_id($this->owner) . serialize($this->owner));
    }

    /**
     * Get focus point for this image; Prevent failover to backend Image
     *
     * @return DBFocusPoint
     */
    public function getFocusPoint(): ?DBFocusPoint
    {
        $iden = $this->getObjectIden();
        if (isset(self::$focusPoints[$iden])) {
            return self::$focusPoints[$iden];
        }

        // If this DB file was generated from a source image,
        // let's copy the focus point across. This can happen if
        // using a non-focuspoint resize mechanism.
        /** @var ViewableData|FocusPointExtension $failover */
        $failover = $this->owner->getFailover();
        if ($failover && $failover->hasExtension(FocusPointExtension::class)) {
            $sourceFocus = $failover->FocusPoint;

            // Note: Let Width / Height be lazy loaded, so don't generate here
            $newFocusPoint = DBFocusPoint::create();
            $newFocusPoint->setValue([
                'X'      => $sourceFocus->getX(),
                'Y'      => $sourceFocus->getY(),
            ], $this->owner);

            // Save this focus point and return
            $this->setFocusPoint($newFocusPoint);
            return $newFocusPoint;
        }

        return null;
    }

    /**
     * Set a new focus point
     *
     * @param DBFocusPoint|null $point
     * @return $this
     */
    public function setFocusPoint(?DBFocusPoint $point): self
    {
        $iden = $this->getObjectIden();
        self::$focusPoints[$iden] = $point;
        return $this;
    }
}
```

@GuySartorelli I need your opinion if this is a bad idea or not.  If the above solution is too weird the other option is to change DBComposite::hasField() to also check parent::hasField() which will end up looking in ViewableData::hasField()

**Comment by emteknetnz** [comment]
Update - if we use this [PR](https://github.com/silverstripe/silverstripe-framework/pull/10698), we can do this much cleaner:

```php
<?php

namespace JonoM\FocusPoint\Extensions;

use JonoM\FocusPoint\FieldType\DBFocusPoint;
use SilverStripe\Assets\Storage\DBFile;
use SilverStripe\View\ViewableData;

/**
 * @property DBFile|FocusPointDBFileExtension $owner
 */
class FocusPointDBFileExtension extends FocusPointExtension
{

    /**
     * Get focus point for this image; Prevent failover to backend Image
     *
     * @return DBFocusPoint
     */
    public function getFocusPoint(): ?DBFocusPoint
    {
        if ($this->owner->hasDynamicData('focuspoint_object')) {
            return $this->owner->getDynamicData('focuspoint_object');
        }

        // If this DB file was generated from a source image,
        // let's copy the focus point across. This can happen if
        // using a non-focuspoint resize mechanism.
        /** @var ViewableData|FocusPointExtension $failover */
        $failover = $this->owner->getFailover();
        if ($failover && $failover->hasExtension(FocusPointExtension::class)) {
            $sourceFocus = $failover->FocusPoint;

            // Note: Let Width / Height be lazy loaded, so don't generate here
            $newFocusPoint = DBFocusPoint::create();
            $newFocusPoint->setValue([
                'X'      => $sourceFocus->getX(),
                'Y'      => $sourceFocus->getY(),
            ], $this->owner);

            // Save this focus point and return
            $this->setFocusPoint($newFocusPoint);
            return $newFocusPoint;
        }

        return null;
    }

    /**
     * Set a new focus point
     *
     * @param DBFocusPoint|null $point
     * @return $this
     */
    public function setFocusPoint(?DBFocusPoint $point): self
    {
        $this->owner->setDynamicData('focuspoint_object', $point);
        return $this;
    }
}

```

**Comment by chrispenny** [comment]
Thanks, @emteknetnz 😄 

That makes sense to me. I think it would be perfectly reasonable to say that I need to update the usage in the module to no longer rely on dynamic properties (like your first example). This might even be a bit more self-documenting than using a new API (`setDynamicData()`).

I'd say I'm easy either way. If you think you'd like `setDynamicData()` for other reasons, then we'll go with that.

**Comment by GuySartorelli** [comment]
I think we need the new `set/get/hasDynamicData()` methods anyway, since we _do_ technically support dynamic data in `ViewableData` subclasses, we need to give them a way to access that data (e.g. if they overload `hasField()`) - otherwise our changelog would have to say something like "Dynamic data can still be set but only if you don't overload anything, and then the behaviour starts getting wonky" and it gets really hairy. Much clearer to say "But if you overload things you'll need to use this new API to get at the data".

**Comment by GuySartorelli** [comment]
A new API is provided in [5.0.0-beta3](https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.0-beta3) for accessing dynamic data, and that API has been documented (see PR, that docs change won't be live yet).
