### ISSUE TITLE
ENH JSON Field & related DBField

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/silverstripe-framework#10854]
## Affected Version

CMS All

## Description

There is no generic support (that I can see) for holding JSON data in the CMS. It's probably rare to want to allow users to edit JSON objects but on occasion, you might want that  

## Proposal

* Add in a DBField that encodes/decode the supplied text
* Add a Form field (example below) that validates the data
  * Optional allow JSON to be displayed as formatted
  * Optional force font to be monospace  

## Example

I roughly built the actual field, albeit a simplified version of it. I am currently looking into how to hook this more into the DB to make the DB Field associated with the data store it as JSON over "Text"

```php
class JSONField extends TextareaField
{
    public function validate($validator)
    {
        if (empty($this->value)) {
            return true;
        }

        $response = json_decode($this->value, true);
        if (is_null($response)) {
            $validator->validationError(
                $this->name,
                _t(
                    __CLASS__ . '.ValidationError',
                    'Please ensure the input data is a valid JSON object ' . json_last_error_msg()
                ),
                'validation'
            );
            return false;
        }

        return true;
    }
}
```

**Comment by michalkleiner** [comment]
There's https://github.com/phptek/silverstripe-jsontext but a bit out of date though should be a fairly good way to get a start on a project-level field or enhancement to the framework to fold that into the core.

**Comment by GuySartorelli** [comment]
I'm not convinced that a JSON db field is ever a good idea, and I'd push back against having it included in core. As soon as you have JSON in your database you lose the ability to easily filter/sort/etc in the database, and _have_ to pull all of the data for all of the records with that field into memory in order to do any of those operations.
It's fine as a project-level field or as its own module, but I don't think this type of field belongs in core.

@michalkleiner do you have any thoughts on that? I'm inclined to close this issue but given you responded first I'd like your take on it.

**Comment by michalkleiner** [comment]
Yeah nah, that's all good, I just floated it as an idea without too much thought on the implications, so thanks for adding that context.

Unless we have two tiers of fields where one would be simply read/write (like this JSON) and didn't support all the other ORM stuff, it could be part of core, otherwise it probably shouldn't for the reasons you mentioned. Happy for this to be closed.

**Comment by GuySartorelli** [comment]
Sweet.
Thank you for the suggestion @catharsisjelly. Hopefully the module @michalkleiner pointed you to helps. I think [`silverstripe/linkfield`](https://github.com/silverstripe/silverstripe-linkfield/) has (or had - may need to look at an earlier version) a json field you could look at, as well.
I'll close this now as discussed above.

**Comment by michalkleiner** [comment]
It sure does have an [abstract JSON field](https://github.com/silverstripe/silverstripe-linkfield/blob/master/src/Form/JsonField.php) to built on, so that's another potential direction.

**Comment by catharsisjelly** [comment]
> I'm not convinced that a JSON db field is ever a good idea, and I'd push back against having it included in core. As soon as you have JSON in your database you lose the ability to easily filter/sort/etc in the database, and _have_ to pull all of the data for all of the records with that field into memory in order to do any of those operations.

I know at least MariaDb has [native JSON support](https://mariadb.com/kb/en/differences-between-json_query-and-json_value/), MySQL introduced it in [5.7.8](https://www.digitalocean.com/community/tutorials/working-with-json-in-mysql), [Postgres](https://www.postgresql.org/docs/current/functions-json.html) too has it but appreciate why this is an issue.

I'll look into the above mentioned modules 🙂

**Comment by GuySartorelli** [comment]
The ORM doesn't have support for JSON regardless of the underlying db functionality, which is the main problem. Sure that could be added, but that's a _much_ larger slice of pie than this issue probably wants to tackle.
Feel free to open a separate issue for that if you think it would be useful and if you're willing to do the leg work of implementing it.
