### ISSUE TITLE
CMS 6 - changes to validators

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10908]
Follow up from #10907

## Acceptance criteria

- [ ] ~Rename `FieldsValidator` to `FormFieldsValidator`~
- [x] `RequiredFields` should be renamed `RequiredFieldsValidator` to match the naming convention of other validators
- [ ] ~Anywhere that just adds `RequiredFields` to a form should instead add `CompositeValidator` with both a `FormFieldsValidator` and (if necessary) `RequiredFieldsValidator` validator~
  - ~`Form::__construct()` and `SilverStripe\AssetAdmin\Forms\RemoteFileFormFactory::getForm()` should explicitly exclude the `RequiredFieldsValidator` validator~
- [x] FieldsValidator is removed
- [x] Form loops its form fields and calls validate on each of them
- [x] `RequiredFieldsValidator` should _not_ call the `validate()` method on form fields, as that is the responsibility of the `FormFieldsValidator`.
- [x] Anywhere that previously added RequiredFields to a form just to get FormField validation to work no longer adds a validator
- [x] `RequiredFieldsValidator` can be configured to not consider whitespace only a value
  - `RequiredFieldsValidator` should be configurable to consider whitespace only values to not constitute the presence of a value
  - This should be configurable globally via YAML, and configurable for individual `RequiredFieldsValidator` instances via a new setter method.
  - It should be `false` by default e.g. mimic existing behaviour

## Note about PRs

I've basically treated this like 3 separate issues and split the PRs
- Allow whitespace changes
- Rename classes
- Call form field validate with form

## CMS 5 PRs - allow whitespace only
- https://github.com/silverstripe/silverstripe-framework/pull/11491
- https://github.com/silverstripe/developer-docs/pull/647

## CMS 5 PRs - rename classes
- https://github.com/silverstripe/developer-docs/pull/646
- https://github.com/silverstripe/silverstripe-framework/pull/11490
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/565
- https://github.com/silverstripe/silverstripe-userforms/pull/1354

After merging all the above reassign to Steve to merge-up and rebase

## Kitchen sink CI CM6 - rename classes
- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12245293053

^ Unit test failure is [existing](https://github.com/silverstripe/silverstripe-framework/actions/runs/12228337036/job/34106455689)

## CMS 6 PRs - rename classes
- https://github.com/silverstripe/silverstripe-framework/pull/11486
- https://github.com/silverstripe/silverstripe-userforms/pull/1353
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/564
- https://github.com/silverstripe/silverstripe-admin/pull/1864
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1519
- https://github.com/silverstripe/silverstripe-cms/pull/3033
- https://github.com/silverstripe/silverstripe-elemental/pull/1286
- https://github.com/silverstripe/silverstripe-linkfield/pull/355
- https://github.com/silverstripe/silverstripe-mfa/pull/578
- https://github.com/silverstripe/silverstripe-spamprotection/pull/129
- https://github.com/silverstripe/silverstripe-frameworktest/pull/214
- https://github.com/silverstripe/developer-docs/pull/645

## Kitchen sink CI - call form field validate within form

- https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/12268735349

^ Unit test failure is [existing](https://github.com/silverstripe/silverstripe-framework/actions/runs/12228337036/job/34106455689)

## CMS 6 PRs - call form field validate within form
- https://github.com/silverstripe/silverstripe-framework/pull/11506
- https://github.com/silverstripe/silverstripe-userforms/pull/1358
- https://github.com/silverstripe/developer-docs/pull/652
- https://github.com/silverstripe/silverstripe-frameworktest/pull/217
- https://github.com/silverstripe/silverstripe-spamprotection/pull/130
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1522

**Comment by emteknetnz** [comment]
@GuySartorelli Having a second look at these ACs it seems like they may cause a fair bit of upgrade pain as RequiredFields is a very commonly used class, and it's very likely that projects will forgot to "upgrade" them to be CompositeValidators that includes both a FieldsValidator and a RequiredFields, and now field validation will silently stop working

Even when they do remember to add it, it honestly sounds like really annoying boilerplate.  People will wonder why they need to add a FieldsValidator since that should really just be there by default

I'm keen not to go with the original solution, I can think of a few alternative solutions instead:

## Option A
- Do nothing, or something minimal such as make RequiredFields extend FieldsValidator

## Option B
- Update the logic in Form so that no matter whatever Form::setValidator() is called with, when calling Form::getValidator() you always end up with a CompositeValidator with a FieldsValidator along with what the argument passed to setValidator() was if it wasn't a CompositeValidator or a FieldsValidator

## Option C
- Set the Form validator to a CompositeValidator with a FieldsValidator in Form::__construct()
- Remove setValidator() and getValidator()
- Add addValidator() which adds to the Forms CompositeValidator()
- Add setCompositeValidator() and getCompositeValidator()

## Option D
- Get rid of FieldsValidator
- Move it logic to Form::validate() to happen before calling the equivalent of $this->getValidator()->validate()

My recommendation is Option D as it seems like it should have always been doing this - can you think of any reason to not do this?

**Comment by GuySartorelli** [comment]
D sounds fine.

**Comment by GuySartorelli** [comment]
CMS 5 PRs merged, reassigning to Steve to prepare CMS 6 PRs.

**Comment by GuySartorelli** [comment]
@emteknetnz It's not clear why this is assigned to me - there's no PRs that aren't in draft.

**Comment by emteknetnz** [comment]
Sorry forgot to mark PRs as ready for review

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to Steve for the next round

**Comment by emteknetnz** [comment]
No more rounds, we're done :-)
