### ISSUE TITLE
HTMLEditorField::setRows() works differently in CMS 5

### ISSUE THREAD

**Issue by scott1702** [silverstripe/silverstripe-framework#10938]
## Affected Version

5.0

## Description

Trying to decrease the size of an HTMLEditorField via setRows does not change the height of the field 

Additional context is in the comments, but pertinently the height configuration for TinyMCE used to be for only the editable text section of the editor, but is now for the _entire_ editor UI, which means `setRows()` is currently _not_ setting the number of rows in the editable section.

## Steps to Reproduce

- Create an HTMLEditorField
- Call ->setRows(2) on the field
- Note the height of the field isn't changed
 
## Acceptance criteria
- `setRows()` with a value of less than 20 is honored in the HTMLEditor. 
- `setRows()` sets the number of rows of editable text by default

## Draft PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1588
- https://github.com/silverstripe/silverstripe-framework/pull/10965

**Comment by GuySartorelli** [comment]
Thanks for reporting that. Would you like to take a go at raising a pull request to fix this?

**Comment by emteknetnz** [comment]
I've done some investigation, it seems that this is just a limitation with TinyMCE 6 (the version that CMS 5 updated to, up from TinyMCE 4 I believe) doesn't want to have a height of less than 400px.  I've provided a "solution" down the bottom of this but I don't recommend it.

### PHP (both versions)

From what I can tell, the ->setRows() will set the rows attributes on a `<textarea rows="n">` element which TinyMCE is reads for 'config'.  Default row is 20, which can be set globally via config.  It will also add a style="height:$height px" attribute at HTMLEditorFIeld::getAttributes():122 where $height = $rows * (rowheight) - where rowheight is a configurable value that defaults to 20.  So the default $height is 400px.

### TinyMCE 6 (CMS 5)

You can ->setRows(50) and the editor will become much larger.  However setting it less than 20 will have no affect.

TinyMCE 6 sets the editor height based on the `<textarea rows="n">` attribute and ignores the `style="height:$height px" `attribute

The way to vertically scale the editor is the `style="height <n>px"` css at the top level `.tox-tinymce` container, which starts at 400px.  The resize handle on the bottom right of the editor will directly alter this attribute, and you can manually make this go lower

The [docs](https://www.tiny.cloud/docs/tinymce/6/editor-size-options/#height) on the 'height' attribute say "Default value: 400 or the size of the target element if larger than 400 pixels" - implying that 400 is a bit of a magic number

### TinyMCE 4 (CMS 4)

In TinyMCE 4 it's the opposite where it ignore the `<textarea rows="n">` attribute and instead copies the `style="height:$height px"` and applies it to the iframe inside the editor, with a lower bound of 100px.  

### Way forward (not really)

Only way forward here I think is pretty hackish.  It would be to write some javascript that manually adjusts the style.height attribute on the appropriate `.tox-tinymce'` element so that the inner `.tox-sidebar-wrap` matches what the TinyMCE `<iframe>` element used to be, after taking into account the vertical size of all the buttons, status bar and other UI.

I really don't like this, it's very hackish.  I'm much more inclined to say that TinyMCE just wants to start out at 400px and if you want it smaller then the user has to manually adjust it smaller via the resize handle at the bottom right.

**Comment by sig-peggy** [comment]
A workaround solution: The [TinyMCE height](https://www.tiny.cloud/docs/tinymce/6/customize-ui/#changing-editor-height-and-width) attribute is a configurable option, so this can be changed on individual fields with e.g.
`$htmlField->getEditorConfig()->setOption('height', 150);` to set the height to 150px.

I haven't looked into whether you could use that to convert the row count into pixels to fix the `setRows()` function, but it might help.

**Comment by sabina-talipova** [comment]
I tested this problem in both versions of CMS 5 and CMS 4.
I believe that this is not an error. This is most likely a limitation imposed by the TinyMCE editor itself. In both versions of the editor, TinyMCE does not take into account the `rows="n"` value, but it only reads the height value from the textarea inline style. Moreover, if this value is less than a certain default value (TinyMCE 4: 100px(textarea), TinyMCE 6: 400px(editor)), used somewhere inside the TinyMCE editor itself, then the default value will be applied. If the new height value is greater than the default value, the new value will be applied. I think this is due to the fact that TinyMCE does not use the textarea as such and cannot apply the `rows` attribute directly to the textarea. Also in TinyMCE 6, the height value is applied to the entire editor, with buttons, input area and footer ([See](https://www.tiny.cloud/docs/tinymce/6/basic-example/)). In version 4, height is applied only to the internal part([See](https://www.tiny.cloud/docs/tinymce/6/basic-example/)). You can see how it works in different versions of TinyMCE [here](https://codepen.io/tinymce/pen/YydQrY) and [here](https://www.tiny.cloud/docs/tinymce/6/basic-example/) (comment out the height value in the JS Editor and set the height and level values in the HTML editor). As you can see, the rows attribute does not work. We use `setRows` to calculate the approximate height value, which is then read by TinyMCE.
The height value that is specified in the configuration file (`_config.php`) and then transferred to TinyMCE during initialisation has the highest priority and is used strictly in TinyMCE 6/5, but in TinyMCE 4 only if it is not lower than the default value.
Therefore, if you are using CMS 5, you should most likely use the configuration file and set the required value. It is worth considering that this value applies to the entire editor, and not just to the editing area.
We should probably raise this issue directly to TinyMCE Editor.

**Comment by sabina-talipova** [comment]
It is not an issue in Silverstripe CMS. I have to close this ticket.

**Comment by GuySartorelli** [comment]
In `HTMLEditorField::getAttributes()` we're already doing some wonky stuff to the attributes based on a calculated height. Let's just tell TinyMCE to directly use that height instead.

```diff
 public function getAttributes()
 {
+    $config = $this->getEditorConfig();
+
     // Fix CSS height based on rows
     $rowHeight = $this->config()->get('fixed_row_height');
-    $attributes = [];
-    if ($rowHeight) {
+    if ($rowHeight && ($config instanceof TinyMCEConfig)) {
         $height = $this->getRows() * $rowHeight;
-        $attributes['style'] = sprintf('height: %dpx;', $height);
+        $config = clone $config;
+        $config->setOption('height', $height);
     }
 
     // Merge attributes
     return array_merge(
-        $attributes,
         parent::getAttributes(),
-        $this->getEditorConfig()->getAttributes()
+        $config->getAttributes()
     );
 }
```

Edit: Sabina has pointed out the following flaws in this approach:
- on different screens the editor has different view.
- the value that user passes to setRows is not quite obvious, it's more guessing. You pass setRows(7), but get 2 rows in editor.
- user won't be able to override this value with _config file.

**Comment by sabina-talipova** [comment]
I'll raise this question [on Stack Overflow](https://www.tiny.cloud/docs/tinymce/6/support/#community-support).

**Comment by GuySartorelli** [comment]
@sabina-talipova I'm reassigning this to you - issues shouldn't be in "awaiting" without someone assigned unless they're there awaiting a release.
By being assigned to an awaiting issue, it makes it clear _who_ is awaiting something, so we know who to ask if we want to know the status of it.

**Comment by sabina-talipova** [comment]
I prepared some changes based on the solutions suggested by [Steve](https://github.com/silverstripe/silverstripe-framework/issues/10938#issuecomment-1716656325) and [Guy](https://github.com/silverstripe/silverstripe-framework/issues/10938#issuecomment-1738266664) and added them as a draft PR to this ticket. The changes seem to work, but I don't think it's the best solution. Therefore, I also added [my question to Stack Overflow](https://stackoverflow.com/questions/77198860/how-to-properly-set-textarea-height-only-without-menu-bar-toolbars-and-status-b) and hope that there is a simpler solution to this problem. Or if TinyMCE developers read questions with 'tinymce' tag, they will take this problem into account when developing the next version.

**Comment by GuySartorelli** [comment]
There's been no response in stackoverflow - might be worth creating an issue in the TinyMCE github issue tracker.

**Comment by sabina-talipova** [comment]
There is one really similar issue and it is still without any solutions. I'm afraid of that they can close our new ticket as a duplicate. Probably, I might keep going to discuss in searching for possible solution in existing issue?!.
https://github.com/tinymce/tinymce/issues/6591

**Comment by GuySartorelli** [comment]
Yup, that sounds like a solid plan. I'd suggest explaining our use case (the issue as it stands is pretty abstract and doesn't explain what the real-world problem is that needs solving) and then try to get the convo going from there.

**Comment by sabina-talipova** [comment]
I left a comment to inquire about any updates on this issue: https://github.com/tinymce/tinymce/issues/6591#issuecomment-1771809624

**Comment by phptek** [comment]
> A workaround solution: The [TinyMCE height](https://www.tiny.cloud/docs/tinymce/6/customize-ui/#changing-editor-height-and-width) attribute is a configurable option, so this can be changed on individual fields with e.g. `$htmlField->getEditorConfig()->setOption('height', 150);` to set the height to 150px.
> 
> I haven't looked into whether you could use that to convert the row count into pixels to fix the `setRows()` function, but it might help.

Can confirm that this works. In my scenario (Silverstripe 5.0.x, framework-only with custom `HTMLEditorConfig`) setting ala the following in `app/_config.php` works like a charm.

```
TinyMCEConfig::get('myCustomConfig')
    ->setOptions([
        'height' => '150',
    ]);
```

Also works on a field-basis too:

```
$fields->dataFieldByName('myEditorField')->getEditorConfig('myCustomConfig')->setOption('height', '150');
```

**Comment by sunnysideup** [comment]
It would be great if setRows just worked.

**Comment by michalkleiner** [comment]
@sunnysideup how do you think it should work? TinyMCE doesn't have a mechanism to set rows directly on it as the content is HTML and can be any height, any style.. so it needs to be actually done using height in pixels.
The best solution I see would be to add setHeight to the config in SS and accept int value for number of pixels, and not magically calculate height from rows when there's no clear/linear relation.

**Comment by sunnysideup** [comment]
@michalkleiner  - I think this is a classic engineer vs pragmatist situation. 

You are correct of course, but right now, it simply ignores lower values. As a pragmatist, i would be super happy with an approximation of a row.  E.g. I set it to three rows (translated to, letrs say 60px), review it and then change to 2 rows, if I am not quite happy with the result. 

Even in SS3 and SS4 it never quite got the exact rows correct - and keep in mind that the text can vary in size even within a single editor as you may use an H1 or a P tag or whatever - key is that it is intuitive for the developer: setRows(1) - little height, setRows(10) - larger height.

**Comment by emteknetnz** [comment]
Linked PRs have been merged, patch releases will be automatically created shortly
