### ISSUE TITLE
IDEA: add _manifest_exclude to the TMP folder

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#10972]
## Affected Version

SS4 / SS5

## Description

In case you set your own tmp folder, it often has to be in the root folder. SilverStripe searches the root folder, for any files, so it maybe useful to add, by default a `_manifest_exclude` to the `tmp` folder and maybe even an .htaccess `piss off` statement?

**Comment by GuySartorelli** [comment]
What is the `tmp` folder you're talking about? There's no folder called "tmp/" in Silverstripe core code.

**Comment by sunnysideup** [comment]
The temp / tmp folder used by ss for storing manifest snd other caches.

**Comment by michalkleiner** [comment]
You already started with "in case you set your own tmp folder", so wouldn't you in that case also be responsible for configuring whatever exclusion and htaccess additions? Similar to Guy I'm not sure I follow what you're suggesting.

**Comment by GuySartorelli** [comment]
Yeah that was my next thought, that if this is for `silverstripe-cache/`, that isn't in your project root unless you explicitly and intentionally put it there yourself.
The `.htaccess` would be entirely redundant in any case since in CMS 5 (where any enhancement would be made) you have to use `public/` as your web root anyway.

I could maybe see adding a manifest exclusion to the top-level subfolders of the `silverstripe-cache/` dir as a courtesy, but frankly I don't think anyone in the CMS Squad is going to spend time on that. I'd consider merging a PR if it's implemented in a very simple and unobtrusive way though.

**Comment by GuySartorelli** [comment]
Based on the conversation we've had above and the fact that there has been no response, I'm going to close this issue. If you feel there's more conversation necessary, feel free to leave a comment and we can look at reopening it based on the conversation that continues.
