### ISSUE TITLE
Toast message has problems with umlauts

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-framework#11089]
## Affected Version
5.1.0

## Description

Toast-Message cannot display umlauts like "äöüÄÖÜß" correctly. See screenshot.
![umlauts](https://github.com/silverstripe/silverstripe-framework/assets/4725743/0a69f1f6-99e8-41a2-bec8-92b48c8c3758)

## Affected location
GridFieldDetailForm_ItemRequest.php Line 543.
my temporary solution: `'type' => mb_convert_encoding($this->record->i18n_singular_name(), 'ISO-8859-1'),`

## Steps to Reproduce

Add title to data object and save.

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11105
- https://github.com/silverstripe/silverstripe-admin/pull/1640

**Comment by lerni** [comment]
Umlauts show fine in SiteTree-"Toasts" but are scrambled with DOs per GF.
![bloeg-aertikoel](https://github.com/silverstripe/silverstripe-framework/assets/472115/2fe5ee60-350b-4d26-840d-dc1cb9142b26)

**Comment by lekoala** [comment]
In the same line, ' character is not working well either.

<img width="144" alt="image" src="https://github.com/silverstripe/silverstripe-framework/assets/250762/72a09be6-3af1-497a-bcfd-daa88951f21a">

it seems that utf8 encoded characters are not being displayed properly

**Comment by lekoala** [comment]
I'm also a bit confused why the link creation is a direct call to htmlspecialchars instead of using the Convert class. It seems to be that either we use the Convert class or we don't, but mixing the two approaches is really odd.

https://github.com/silverstripe/silverstripe-framework/blob/c003dfd4b16a80b9b9429b070452cf853433287d/src/Forms/GridField/GridFieldDetailForm_ItemRequest.php#L552-L576

**Comment by GuySartorelli** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-admin/issues/1639 which has more information in it (and is against the correct repo)
