### ISSUE TITLE
type mismatch

### ISSUE THREAD

**Issue by cdogcatch** [silverstripe/silverstripe-framework#11164]
https://github.com/silverstripe/silverstripe-framework/blob/4f3282bf2a107178689be43db72a4ef19349d38c/src/ORM/DataList.php#L1948

Hello

OffsetGet() and offsetExists() accept a mixed type. and directly call limit() which only takes a int for the offset.

Just wondering if there is a reason for this? 
Thanks

**Comment by GuySartorelli** [comment]
Please don't raise support questions in the issue tracker. We use GitHub issues only to discuss bugs and new features. For support questions, please use one of the support options available in our community channels.

This accepts `mixed` because the [`ArrayAccess` interface](https://www.php.net/manual/en/class.arrayaccess.php) dictates `mixed` in its method signatures.
