### ISSUE TITLE
Replace `Path` class with Symfony `Path` class

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11340]
[Path](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Core/Path.php) could be possibly be replaced with the [Path](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Filesystem/Path.php) class in symfony/filesystem

## Notes
- If we can simply swap it out and no unit tests break, then do the work directly in CMS 5 instead. Otherwise if we need to update the code that calls these methods, then target CMS 6

## Acceptance criteria
- [x] Determine if replacing the Silverstripe `Path` class is worthwhile and viable
- [x] Deprecate and replace `Path`

## CMS 5 PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11381

## CMS 6 PRs

Do not merge yet - after CMS 5 PR is merged, reassign to Guy to rebase.

- https://github.com/silverstripe/silverstripe-framework/pull/11380
- https://github.com/silverstripe/silverstripe-assets/pull/643
- https://github.com/silverstripe/silverstripe-graphql/pull/605
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/61
- https://github.com/silverstripe/developer-docs/pull/586

**Comment by emteknetnz** [comment]
I don't think this is worthwhile as the Silverstripe `Path` methods having additional logic which symfony path does not

Silverstripe [Path::join()](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Core/Path.php#L37) includes protection against directly traversal i.e. not allowed `..` and will throw an exception, whereas Symfony [Path](https://github.com/symfony/filesystem/blob/6.4/Path.php) will not stop you from having a path with '..' and will simply return a path with the the `..` resolved for you - `"all "." and ".." segments are removed as far as possible"`

The Silverstripe normalize() method also has an additional param $relative which means that the directory seperators will be rtrim()'ed off

If you agree with this assessment then just close this issue

**Comment by GuySartorelli** [comment]
> Silverstripe [Path::join()](https://github.com/silverstripe/silverstripe-framework/blob/5/src/Core/Path.php#L37) includes protection against directly traversal i.e. not allowed .. and will throw an exception, whereas Symfony [Path](https://github.com/symfony/filesystem/blob/6.4/Path.php) will not stop you from having a path with '..' and will simply return a path with the the .. resolved for you - "all "." and ".." segments are removed as far as possible"

I honestly think the way symfony does that is better. Directory traversal protection doesn't belong in a "join these two paths together" method, it belongs in whatever is _using_ that path - at which point you'd know where you are or aren't allowed to traverse to.
If I go `Path::join('_resources/theme/simple/images/', '../css/');` I should be able to get `'_resources/theme/simple/css/'` as a result without an error thrown in my face for trying to get a perfectly valid path.

> The Silverstripe normalize() method also has an additional param $relative which means that the directory seperators will be rtrim()'ed off

I think it's worth losing that little bit of functionality and having a few `ltrim(Path::normalize($myPath), '/');` around the place for the sake of

1. not having any confusion at all about which `Path` class to use, because there's only one
2. IMO better join functionality
3. All of the additional methods symfony has on their `Path` class

And yes technically we can use the other Path class along side our one, but that just makes point 1 worse imo.

**Comment by michalkleiner** [comment]
I'd go with Symphony's Path class, too, so that we don't have the same conversation in a year why we didn't replace this component when we replaced others.

**Comment by GuySartorelli** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/11380#pullrequestreview-2311488637
We're not doing it I guess
