### ISSUE TITLE
Refactor sake around Symfony console

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#11341]
[sake](https://github.com/silverstripe/silverstripe-framework/blob/5/sake) is basic though functional way to run cli commands

It's very non-standard, and it's likely that we could make the interface significantly better by changing it to use symfony/console instead.  There may also be some downstream benefits of making it easier to project to extend/customise if they have a need to

## Related
- https://github.com/silverstripe/silverstripe-framework/issues/5542
- https://github.com/silverstripe/silverstripe-framework/issues/8998
- https://github.com/silverstripe/silverstripe-framework/issues/7509

## Acceptance criteria
- [x] First determine if this is something that's viable without breaking much in terms of backward compatibility i.e. user should still call `sake`, though possibly some of the commands are different, though preferably not
- [x] Target CMS 6
- [x] Replace as much of sake with symfony/console as possible

## CMS 5 PRs

- https://github.com/silverstripe/silverstripe-framework/pull/11365
- https://github.com/silverstripe/silverstripe-graphql/pull/603
- https://github.com/silverstripe/silverstripe-ldap/pull/91
- https://github.com/silverstripe/silverstripe-subsites/pull/599
- https://github.com/silverstripe/silverstripe-externallinks/pull/147
- https://github.com/silverstripe/silverstripe-realme/pull/162
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/203
- https://github.com/silverstripe/silverstripe-contentreview/pull/257
- https://github.com/silverstripe/silverstripe-crontask/pull/94
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/60
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/887
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/240
- https://github.com/symbiote/silverstripe-queuedjobs/pull/447
- https://github.com/silverstripe/developer-docs/pull/580
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/890

## CMS 6 PRs

[kitchen sink run](https://github.com/creative-commoners/recipe-kitchen-sink/actions/runs/11024053756)
CI failures are pre-existing

- https://github.com/silverstripe/silverstripe-framework/pull/11353
- https://github.com/silverstripe/silverstripe-testsession/pull/93
- https://github.com/silverstripe/silverstripe-graphql/pull/600
- https://github.com/silverstripe/silverstripe-session-manager/pull/213
- https://github.com/silverstripe/silverstripe-frameworktest/pull/203
- https://github.com/silverstripe/silverstripe-assets/pull/635
- https://github.com/silverstripe/silverstripe-ldap/pull/89
- https://github.com/silverstripe/silverstripe-linkfield/pull/329
- https://github.com/silverstripe/silverstripe-subsites/pull/597
- https://github.com/silverstripe/silverstripe-externallinks/pull/145
- https://github.com/silverstripe/silverstripe-realme/pull/160
- https://github.com/silverstripe/silverstripe-staticpublishqueue/pull/201
- https://github.com/silverstripe/silverstripe-userforms/pull/1325
- https://github.com/silverstripe/silverstripe-contentreview/pull/255
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/259
- https://github.com/silverstripe/silverstripe-graphql-devtools/pull/58
- https://github.com/silverstripe/silverstripe-elemental/pull/1252
- https://github.com/silverstripe/silverstripe-crontask/pull/93
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/552
- https://github.com/symbiote/silverstripe-queuedjobs/pull/445
- https://github.com/tractorcow-farm/silverstripe-fluent/pull/884
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/239
- https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/97
- https://github.com/silverstripe/silverstripe-environmentcheck/pull/112
- https://github.com/silverstripe/silverstripe-cms/pull/2999
- https://github.com/silverstripe/silverstripe-tagfield/pull/307
- https://github.com/silverstripe/silverstripe-behat-extension/pull/282
- https://github.com/silverstripe/silverstripe-taxonomy/pull/123
- https://github.com/silverstripe/silverstripe-registry/pull/107
- https://github.com/silverstripe/silverstripe-auditor/pull/92
- https://github.com/silverstripe/silverstripe-siteconfig/pull/176
- https://github.com/silverstripe/silverstripe-spamprotection/pull/127
- https://github.com/silverstripe/silverstripe-hybridsessions/pull/113
- https://github.com/silverstripe/recipe-kitchen-sink/pull/72
- https://github.com/silverstripe/developer-docs/pull/571

**Comment by GuySartorelli** [comment]
I've gotten pretty far with this for everything included in installer. I'm nearly at the point where I can clean up and start writing tests (and then move onto the rest of kitchen sink).

One thing I'd like some opinions on is how the `dev/` commands should be arranged.

Right now the PRs have these just swapping `dev/` to `dev:`, i.e. you can run the commands like so:
|HTTP route|CLI command|CLI alias (for backwards compat)|
|---|---|---|
|`dev/tasks/my-task`|`dev:tasks:my-task`|`dev/tasks/my-task`|
|`dev/config`|`dev:config`|`dev/config`|
|`dev/build`|`dev:build`|`dev/build`|

![Example of the existing command setup](https://github.com/user-attachments/assets/13914ac1-0e08-4f3d-b671-0426e5be3e89)

This however keeps all of the commands clumped together in an unhelpful way, and means you have to type `dev:` before every command, which is completely unnecessary in the CLI. The only reason they had that historically is because sake was just a CLI wrapper for the HTTP controllers, so the routes *had* to be identical. Now they don't.

I would like to change the commands to be more meaningful in CLI, while keeping their HTTP routes as they currently are. That would look more like this:

|HTTP route|CLI command|CLI alias (for backwards compat)|
|---|---|---|
|`dev/tasks/my-task`|`tasks:my-task`|`dev/tasks/my-task`|
|`dev/config`|`config:dump`|`dev/config`|
|`dev/build`|`db:build`|`dev/build`|

![Example of the proposed command setup](https://github.com/user-attachments/assets/49d6b024-d9d9-4707-971e-2fd7e3a866b6)

This gives us a more sensible grouping for the CLI commands, allows for new commands to be more easily added to those groupings in a meaningful way, reduces unnecessary key-strokes, and I think just looks way tidier.

(I'm planning on hiding the tasks from this initial list (at least if there are more than some configurable number of them) and only showing them when you run `sake tasks` (or `sake dev:tasks` if this proposal isn't accepted) so don't get too caught up on how those are filling the output)

@silverstripe/core-team Does anyone have any thoughts on this?

**Comment by wilr** [comment]
@GuySartorelli 100% agree. Coming from a laravel view that makes a lot more sense than prefixing everything `dev`. 👍

**Comment by emteknetnz** [comment]
Looks good, happy to get rid of the `dev` prefix

**Comment by lozcalver** [comment]
+1 for getting rid of the dev prefix

**Comment by michalkleiner** [comment]
All good to drop the `dev:` prefix.

**Comment by emteknetnz** [comment]
@GuySartorelli Will need to rebase the PRs that have phpunit/phpunit in `require` rather than `require-dev`. behat-extension is one of them, there may be others.

I'm unable to install of the PR's at the same time locally due to conflicts between phpunit 11 which was just merged and phpunit 9

**Comment by GuySartorelli** [comment]
Yup there's rebasing to be done, just needed that CMS 5 pr merged first 👍

**Comment by emteknetnz** [comment]
@GuySartorelli A few things I've noticed from doing some quick testing locally, which I'll not here rather than on individual PRs where they'll need to be fixed:
- Running sake tasks lists a bunch of tasks in a mixture of casing, e.g. tasks:WorkflowReminderTask and tasks:content-review-emails. We should only have a single style, which to me seems like it could be the WorkflowReminderTask style as that matches the class name which people are familiar with. The command names and docs will need to be updated.
- sake dev/tasks and dev/graphql and simply sake dev don't work like they used to, though dev/build and dev/config do work which is inconsistent
- There's some text which doesn't make sense in a CLI context, e.g. sake tasks:delete-queued-jobs will prompt `Really delete 3 jobs? Please add ?confirm=1 to the URL to confirm.` - should be prompting use to add `--confirm` when in CLI instead

I'm also finding the new `permissions_for_browser_execution` private static confusing for a few reasons:
- It (probably correctly) uses an `any` check vs the LeftAndMain subclasses `required_permission_codes`'s `all`
- In 02_Hybrid_commands.php (rename to 02_Poly_commands.php) it says "An array of permissions a user must have to run the command in an HTTP request" which implies it's an 'all', however the fact that `ADMIN` is in all of these arrays implies they're all ADMIN only, which isn't the case.
- Also the `anyone_with_dev_admin_permissions` and `anyone_with_task_permissions` keys really confused me, I thought they were actually some sort of new functionality for a while until I realised they're just labels to try and be helpful. They're actually unhelpful so the keys should just be be removed

**Comment by michalkleiner** [comment]
With the inconsistency it's likely either a class name or a custom defined URL segment, so unless we want to support both interchangeably in CLI, I'm not sure we can solve it easily, since multiple tasks can have the same class name in a different namespace, and possibly also multiple tasks can define the same url segment (haven't tried that).

**Comment by emteknetnz** [comment]
I think they're just inconsistently name in the new private static $commandName e.g. 
- [content-review-emails](https://github.com/silverstripe/silverstripe-contentreview/pull/255/files#diff-4eede9dbc7dfdce77c8e39a1c7c2f60a863c6f647c75f6c46b8fd5e5349f5e21)
- [WorkflowReminderTask](https://github.com/symbiote/silverstripe-advancedworkflow/pull/552/files#diff-26f8fc631a10ce06e553721418a440e1960b39343b59a597f03c0334609739b2)

With both methods of naming things there's still a risk of collision due to lack of namespace. I think short classname is the better choice here simply because it matches the existing filename/classname, which means one less thing way to label/remember something

Only exceptions would be for the two tasks in fluent which already has $segment's in CMS 5 which didn't match the ClassName, they should say as is

**Comment by GuySartorelli** [comment]
> Running sake tasks lists a bunch of tasks in a mixture of casing, e.g. `tasks:WorkflowReminderTask` and `tasks:content-review-emails`. We should only have a single style, which to me seems like it could be the `WorkflowReminderTask` style as that matches the class name which people are familiar with

I think we should aim for lowercase task names for newly named tasks, because that's easier to type and is more consistent with basically everything else you'll ever do in CLI (at least for *nix).
Note that these names are _also_ used for the URL segment, where lowercase with hyphens is also more standard than using capital letters.

I would prefer not to rename existing tasks that already have short names so that we can preserve backwards compatibility for them (I gave an explicit name to some tasks that were falling back to FQCN because the FQCN is really long and looks awful in the new `sake tasks` output).

> Only exceptions would be for the two tasks in fluent which already has $segments in CMS 5 which didn't match the ClassName, they should say as is

Based on this comment it seems you agree that we should avoid renaming the tasks which already have short names defined. So this is only about tasks we're giving a command name where the legacy `segment` wasn't already defined

**Comment by GuySartorelli** [comment]
> sake dev/tasks and dev/graphql and simply sake dev don't work like they used to, though dev/build and dev/config do work which is inconsistent

They *can't* work like they used to, because sake doesn't use the routed controllers to get or list info anymore. Lists of commands are handled by `symfony/console` internals.

`sake tasks` is a slightly special case because I've implemented logic to *hide* tasks from the main list if you have too many, so I made an explicit command for listing them - but that still just fires off the equivalent of `sake list tasks`. It doesn't use the old logic to list the tasks, nor should it.

Given the intention behind adding backwards compatibility is to allow _scripts_ to continue working, I don't see any value in adding backwards compatibility for the commands that only listed what commands are available, given that doing so would be adding tech debt (immediately deprecated code).

**Comment by GuySartorelli** [comment]
> There's some text which doesn't make sense in a CLI context

I'll resolve the one you've listed, but the way you said that implies there are more cases? Please point them all out, since you saw them and I didn't it would be hard for me to fix them without them being pointed out.

**Comment by GuySartorelli** [comment]
> I'm also finding the new permissions_for_browser_execution private static confusing for a few reasons:
> 
> - It (probably correctly) uses an any check vs the LeftAndMain subclasses required_permission_codes's all

It's essentially doing the job of the now-deprecated `init_permissions` configuration property on the old controllers, e.g https://github.com/silverstripe/silverstripe-framework/blob/6287b6ebeba1989cfc7bbcef860166b290664740/src/Dev/DevConfigController.php#L40-L44

> - In 02_Hybrid_commands.php (rename to 02_Poly_commands.php) it says "An array of permissions a user must have to run the command in an HTTP request" which implies it's an 'all', however the fact that ADMIN is in all of these arrays implies they're all ADMIN only, which isn't the case.

Please point out things like this in the relevant PR - it's a lot easier for me to keep track of changes I need to make to a specific PR if the comment is *in* that PR.
I'll try to update the wording in a way that doesn't imply "all".

> - Also the anyone_with_dev_admin_permissions and anyone_with_task_permissions keys really confused me, I thought they were actually some sort of new functionality for a while until I realised they're just labels to try and be helpful. They're actually unhelpful so the keys should just be be removed

Those permissions already existed. I'm keeping the same permissions in order to preserve backwards compatibility.
Although if I've misunderstood what you're meaning it may pay to comment in context of the PR so I can see what you're talking about.

**Comment by emteknetnz** [comment]
>> Running sake tasks lists a bunch of tasks in a mixture of casing ... Note that these names are also used for the URL segment

Yeah I'll assume that most most tasks are being run via the browser rather than CLI, simply because it's generally easier to login as an admin rather than SSH on to a production server, so the lower-case-with-dashes which $segment currently uses is probably the better standard.

>> There's some text which doesn't make sense in a CLI context ... Please point them all out

I had look through all the tasks, I could find any others like this one I already pointed out

>> sake dev/tasks and dev/graphql ... They can't work like they used to

All good

**Comment by GuySartorelli** [comment]
All PRs merged. CI will be cleaned up in https://github.com/silverstripe/.github/issues/313

**Comment by madmatt** [comment]
Thank you to everyone who has worked on this, very glad to see this happening <3
