### ISSUE TITLE
[2010-05-04] Consistently use ShortcodeParser in Text/HTMLText value getters (breaking [sitetreelink_id] in SiteTree.Content)

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1381]
created by: @chillu (ischommer)
created at: 2010-05-04
original ticket: http://open.silverstripe.org/ticket/5535

---

At the moment the ShortcodeParser just applies in HTMLText/HTMLVarchar->forTemplate(). This getter is not used when further processing the output or using an alternative, e.g. through FirstParagraph().

SHortcodes should be respected in all those getters, specifically:
 * StringField->forTemplate() ?
 * Varchar->LimitCharacters()
 * Text->FirstParagraph(), LimitWordCount(), LimitWordCountXML(), LimitSentences(), FirstSentence(), Summary(), BigSummary(), ContextSummary()
 * HTMLText->LimitCharacters(), Summary, FirstSentence()

Also, its unclear why its limited to HTML fields only - text fields should be able to have shortcodes as well, right? Best example being the bbcode style enforced on BlogEntry.Content.

**Comment by tractorcow** [comment]
This issue hasn't been touched for about 2 years but I'd like to elevate this as a bug impacting 3.1. At the very least, HTMLText should override any method that doesn't respect shortcodes with an appropriate replacement.

With the recent work on updating the blog module we should look at improving framework's support for these methods.

**Comment by tractorcow** [comment]
Will try to address in #5653

**Comment by dhensby** [comment]
Context: At the moment the shortcodes are parsed only on `HTMLText` objects so a plain text object cannot have shortcodes parsed. `HTMLText` parses the shortcodes in the `forTemplate` method so it happens at the last possible moment (just before being output in the template) rather than when the value is `set` or `get`. Each have their advantages and pitfalls.

What is certain is that the shortcodes need to be parsed before any content-type encoding or other manipulation of the value is done.

I think adding the parser to the`setValue` method makes instantiation of a `HTMLText` object too expensive, putting it on the `getValue` is inefficient (multiple runs) or too fragile to cache.

For now, it looks like @tractorcow's suggestion of overriding each of the functions (`XML`, `Summary`, etc) and having them parse the codes FIRST and then escape is best.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/5653 :D
