### ISSUE TITLE
[2011-04-24] Thai Filename Breaks Image Upload

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1401]
created by: gordonbanderson
created at: 2011-04-24
original ticket: http://open.silverstripe.org/ticket/6608

---

I initially thought this problem was due to memory limitations (90M) on Dreamhost, but I managed to recreate the problem locally.

To recreate the problem:

1) Edit any page
2) Click on the image icon
3) Select'Choose File'
4) Try to upload the attached image.

Nothing appears to happen visually.

When I change the name of the file to say 'fred.jpg' then the upload works

The workaround for the moment is to rename the files as English

**Comment by chillu** [comment]
Since 2011, we've improved unicode char handling in file uploads (filtering out non-ASCII characters in a configurable way through `FileNameFilter`, and defaulting to an auto-generated filename when all characters are non-ASCII). I can't view the originally attached file, but I've tested this locally with `ราชาศัพท์.jpg`
