### ISSUE TITLE
[2011-05-30] is_cli returns false when cron jobs run with cgi-fcgi

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1403]
created by: burnbright
created at: 2011-05-30
original ticket: http://open.silverstripe.org/ticket/6649

---

The is_cli function on Director.php only functions correctly when php_sapi_name() returns 'cli', however some setups run cron jobs with 'cgi-fcgi', causing the function to return false.

The execution will therefore act as a web-based rather than command-line, resulting in html output of the secuirty login page being returned to the cron output.

**Comment by sminnee** [comment]
Don't think we should change this.

**Comment by lakinmohapatra** [comment]
Hi All . Please go through my blog post related the same issue and i hope , you guys will get the fix.
http://lakinmohapatra.blogspot.in/2016/08/solve-if-php-file-being-executed-by.html

**Comment by tractorcow** [comment]
Could we declare a constant in cli-script.php that would ensure any subsequent checks for "is_cli" to true? Maybe just after the PHP_SAPI check?

**Comment by tractorcow** [comment]
in cli-script.php


```php
if(PHP_SAPI != "cli" && PHP_SAPI  != "cgi" && PHP_SAPI != "cgi-fcgi") {
	echo "cli-script.php can't be run from a web request, you have to run it on the command-line.";
	die();
}
define('SS_ENVIRONMENT_CLI', true);
```

In Director.php

```php
public static function is_cli() {
	return defined('SS_ENVIRONMENT_CLI') || php_sapi_name() == "cli";
}
```

**Comment by dhensby** [comment]
:S If our CLI script has this check, why isn't the same one used by `Director`? We could add the constant, but those are pseudo "environment vars" and being on the CLI is not a property of the environment... so it feels nasty.

**Comment by lakinmohapatra** [comment]
@tractorcow  , For resolving this issue , we dont need to  change core files because basically cron jobs should be run by cli .
To fix this, we need to find the exact path to the correct php binary by typing this:
"which php"
This should give you a path like /usr/bin/php. You can go one  step further and check if this is actually a "symbolic link" pointing to a different filename or not:
ls -l $(which php)

Output will be like /usr/bin/php -> /usr/bin/php5-cli / may be some other binary
Then add this full path to the PHP executable and use that in your crontab entry, so it looks something like this:
* * * * */usr/bin/php5-cli   /home/path/to/artisan schedule:run 1>> /dev/null 2>&1

I hope , it will solve your issue without hacking core files.

**Comment by dhensby** [comment]
changing core files is not "hacking" if we're fixing a bug... we are maintaining the core files here.

I don't have a problem with cron module identifying itself as running not on the CLI - what OS / PHP versions do you have installed?

**Comment by lakinmohapatra** [comment]
@dhensby , it will be good if you will write common function for identifying cli jobs.
But i was telling from user prospective. 

Possible solutions : 
if (array_key_exists('REQUEST_METHOD', $_SERVER)) die();
if (php_sapi_name() === 'cli' OR defined('STDIN')) return true;

But make sure , your cli defending system is covering all scenarios.

**Comment by dhensby** [comment]
@lakinmohapatra ah, ok. @tractorcow was suggesting a fix that could be used in core, rather than suggesting you amend core files in your project (which of course would be bad).

**Comment by lakinmohapatra** [comment]
@dhensby , Thanks for understanding my points.

Please review again his codes and see if it's working for all sapi names  being mentioned in php.net

**Comment by lakinmohapatra** [comment]
One more point  - 
There are lots of advantages of using php-cli instead of other sapi names.
It has unlimited execution time .
It does not write headers to output.
The CLI SAPI  does not change the current directory to the directory of the executed script!
When using the CGI  version, the output is:
$ pwd
/tmp
=
$ php -q another_directory/test.php
/tmp/another_directory
============================================
This clearly shows that PHP changes its current directory to the one of the executed script. 
Using the CLI SAPI  yields:
$ pwd
/tmp
==
$ php -f another_directory/test.php
/tmp
This allows greater flexibility when writing shell tools in PHP. 

So i think , it has lots of advantages over other sapi names. 
So better to stick with cli check only.
@dhensby  please let me know your feedback on it.
http://www.softpanorama.org/Scripting/Phprama/command_line_php.shtml

**Comment by tractorcow** [comment]
> :S If our CLI script has this check, why isn't the same one used by Director? We could add the constant, but those are pseudo "environment vars" and being on the CLI is not a property of the environment... so it feels nasty.

Because it doesn't check if the environment IS cli, it checks if the environment is definitely NOT cli.

`cgi-fcgi` is still ambiguous.

**Comment by sminnee** [comment]
Yeah this is a wonfix, I think.

**Comment by sminnee** [comment]
We could potentially introduce the `if(defined('SS_ENVIRONMENT_CLI'))` check but leave it up to project developers to create a script where that is defined. They can ensure that the script that defines it is outside of the webroot or similar.

`cli-script.php` will end up getting exposed to some webservers by a hapless installer and I don't want to see a highway-like security bypass created in those situations.

**Comment by dhensby** [comment]
It sounds like we can do better at detecting cli, but @sminnee raises a good point about just assuming cli script is run by cli

**Comment by tractorcow** [comment]
Agreed, #wontfix :)

**Comment by dhensby** [comment]
I've run into this problem myself and the resolution is to run the cron using `php-cli` instead of `php` binary...

Seems like a fairly simple fix and perhaps something `sake` should be looking for?
