### ISSUE TITLE
[2012-03-07] Confirm that GridFieldPopupForms and GridFieldAction use SecurityToken and $allowed_actions properly

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1443]
created by: @chillu (ischommer)
created at: 2012-03-07
original ticket: http://open.silverstripe.org/ticket/6899

---

A bit of a research task...

- Make sure we don't have any XSRF holes in both row-level actions and GridFieldPopupForms saving (try by leaving out SecurityID from submission, should fail)
- Only actions which are explicitly allowed should be handled by GridField (new logic in Controller.php for GridField and the action_ prefix, hence the check)

**Comment by tractorcow** [comment]
As far as I can tell all actions must be whitelisted in `allowed_actions` by now. I'm not sure about SecurityToken.

**Comment by chillu** [comment]
I've just tried to replay a "remove member" button click ("copy as Curl" in dev tools). Left out the SecurityID, which didn't cause a HTTP error but also didn't remove the member. Even if SecurityID wasn't enforced there, since the GridField states are encoded on every button by a six character hash, its unlikely that a CSRF attack would be successful (unless you can get a browser to run through hundreds of thousands of combinations). And any GridField based form submissions like "Add Member" are CSRF protected through standard means. Closing off.
