### ISSUE TITLE
[2012-05-20] Fix i18nTextCollector_Parser quote escaping before writing to YAML

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1479]
created by: @chillu (ischommer)
created at: 2012-05-20
original ticket: http://open.silverstripe.org/ticket/7369

---

See https://github.com/silverstripe/silverstripe-cms/pull/130

Check if the template parser class returns those correctly, or if we need to manually unescape.

Example in install_deleteinstallfiles.ss

```
<%t ContentController.StartEditing 'You can start editing your site\'s content by opening <a href="{link}">the CMS</a>.' link="admin/" %>. 
```

**Comment by kinglozzer** [comment]
Just tested, the above output is still what’s written to YAML so this bug is still valid as it results in `site\'s` being output to the template. The YAML dumper will handle escaping, so the original ticket is correct in that we just need to “unescape” before writing to YAML.

I ran a quick test by adding `stripcslashes($spec[0])` to [this line](https://github.com/silverstripe/silverstripe-framework/blob/c303c6354bdffbe6c219323f3bac8742a96da417/i18n/i18nTextCollector.php#L791) and it seemed to solve the issue. Would probably benefit from a unit test too.

**Comment by dhensby** [comment]
Ping @tractorcow had been sorting out the collector

**Comment by tractorcow** [comment]
I haven't fixed this... take care that the i18n code also respects the correct escaping syntax though, not just the text collector.

**Comment by tractorcow** [comment]
Fixed in 4.x; Text collector isn't done in 3.x anymore. We now use symfony/yaml for writing these strings.
