### ISSUE TITLE
[2012-11-05] Show in Search no longer relevant for core?

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1633]
created by: camfindlay
created at: 2012-11-05
original ticket: http://open.silverstripe.org/ticket/7995

---

Working in ss3 these days all the available search optons are in external modules... raises the issue of is the show in search checkbox still relevant to existing on site tree pages in a base level install since is doesn't actually do anything unless tied together with a search module.

suggest dropping that out of the core and add as extension with the fulltext search module?

**Comment by jakxnz** [comment]
I'm not sure the rationale here tracks (possibly due to the age of the issue).

`MySQLDatabase::searchEngine()` is entirely dependent on `SiteTree` and `File` (from their respective packages). So, as long as `MySQLDatabase::searchEngine()` is still primarily using concerns introduced by those classes, then `ShowInSearch` seems endemic as well, and thus is relevant?

**Comment by lerni** [comment]
It's also respected with https://github.com/wilr/silverstripe-googlesitemaps - if it's gone no problem but if keeped, it really should output `<meta name="robots" content="noindex">`.

**Comment by chillu** [comment]
Yeah I'm going to close this, we would only remove it by also removing `searchEngine()` from the ORM (which might well happen in 5.x)
