### ISSUE TITLE
[2013-02-05] Tighten up usage of dependency injection in core

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1678]
created by: @chillu (ischommer)
created at: 2013-02-05
original ticket: http://open.silverstripe.org/ticket/8249

---

We have dependency injection in core for over a year now, and practically nobody uses it.
The technique has great potential, but is hard to explain, and will just find adoption
if we provide consistent practices in our own core usage.

Code:
- Define commonly used classes as services: Upload, Email, Mailer, Cookie, Session, Cache, Debug, Log, Permission
- Convert static methods to use instance methods on a singleton created through injector
- Declare dependencies through injector. Ensure accessors exist, and they fall back to creating their own instance (in case the originating class hasn't been created through injector)
- Duplicate any configuration-like statics on classes as instance properties, and add them (incl. default values and documentation) to the injector config. 

Docs:
- Add note to intro tutorials about further reading on DI
- Rewrite docs to use `<Object>::create()` in instead of `new <Object>()`, since it uses the injector (without the verbosity of Injector::inst()->create()). Rewrite to fluent syntax where possible.
- Rewrite /topics/configuration with better examples on how to _use_ injected configs. Most devs shouldn't need to understand the concept of DI or "services" in order to use the config system to tweak things.
- Create how-to for gracefully refactoring a "static class" into one driven by instance methods and injected config rather than static properties.

Using DI is further complicated by the lack of introspection into the config layer, so we should also fix  silverstripe/sapphire#1577 .

**Comment by tractorcow** [comment]
Cookie_Backend is configurable via DI
Object::useCustomClass needs to be deprecated (see https://github.com/silverstripe/silverstripe-framework/issues/2965)
SS_Log::$logger_class probably can't be DI because it's necessary during bootstrapping.
Image::$backend is configurable via DI

This leaves Authenticator::$default_authenticator and Diff:$html_cleaner_class

**Comment by dhensby** [comment]
come on then, @tractorcow !

**Comment by tractorcow** [comment]
Ugh, I'm never going to find time to refactor member authentication, am I?

**Comment by sminnee** [comment]
Mailer is not injectable thanks to https://github.com/silverstripe/silverstripe-framework/pull/6466

@chillu do you think there's much value in keeping such a broad ticket open? It feels a bit like a "use more unit tests" ticket – always a good idea, never finished, but substantially progressed since the ticket was raised.

**Comment by chillu** [comment]
A bit unhappy that we've chosen not to make this a concerted effort up until this point ("make DI a first class citizen in core"), but it's going to come up again in other contexts (like the [app object](https://github.com/silverstripe/silverstripe-framework/issues/6681) discussion) - so closing
