### ISSUE TITLE
dev build error when Page Table is removed "Table 'Page_versions' doesn't exist"

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-framework#1883]
silverstripe only creates a table for an object if it is required.

so once you add DB fields to class Page silverstripe creates the Page table.
if you then remove those DB fields from class Page, the table is no longer required and silverstripe removes it.
this behaviour is expected and also works:

```
Table Page: renamed to _obsolete_Page
Table Page_versions: renamed to _obsolete_Page_versions
Table Page_Live: renamed to _obsolete_Page_Live
```

but after that, an error occurs:

```
[User Error] Couldn't run query: SELECT COUNT(*) FROM "ErrorPage_versions" LEFT JOIN "Page_versions" ON "Page_versions"."RecordID" = "ErrorPage_versions"."RecordID" AND "Page_versions"."Version" = "ErrorPage_versions"."Version" WHERE "Page_versions"."ID" IS NULL Table 'Page_versions' doesn't exist
```

![table_page_versions_doesnt_exist](https://f.cloud.github.com/assets/186158/493008/1b1abefc-bb10-11e2-8648-ceba7010b96b.png)

this error appears 3 times in this dev build, 1 for each subclass of page:
- Error Page
- Redirect Page
- Virtual Page

but, it only occurs at the first dev build that is run after removing the Page table.
if you run it again afterwards, it runs fine.

**Comment by nickspiel** [comment]
I know this issue is quite old but I am having a similar problem: http://stackoverflow.com/questions/34212050/silverstripe-is-creating-obsolete-tables-on-build 

The last couple of times I have pushed code to production, silverstripe will set a table or two as obsolete, even if the changes made are unrelated to that class. When I run a build for a second time the table is back but with no rows.

On staging and production we are running sake dev/build in a post deployment hook through beanstalk which is when the obsolete tables are being created.

Has anyone gotten to bottom of this?

**Comment by tractorcow** [comment]
Sorry, I can't say I've seen that before. It's an interesting issue!

Can you think about any changes to page classes or extensions that you might have added? Sometimes seemingly unrelated changes can have effects we didn't anticipate.

Are you adding extensions programatically? (e.g. in _config.php). Possibly you could run into a case where, at some point in the pipeline, the framework recognises the need for tables, but not in others.

**Comment by tractorcow** [comment]
I think the issue was possible due to incorrect config caching of the old DB; It seems fixed in the current 3.x branch in any case.
