### ISSUE TITLE
[2010-01-16] Add a way to check current Sapphire/CMS/etc code version

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1911]
created by: dalesaurus
created at: 2010-01-16
original ticket: http://open.silverstripe.org/ticket/4924

---

Perhaps I've missed it but I see no way to figure out what version of SS (cms, sapphire) you are running.  I see this is done in LeftAndMain.php and the SapphireInfo.php controllers via some file_exists and regexes, which are not ideal to duplicate.

It would be helpful for modules to be able to check what the current version is.  In my case it would be knowing where to locate the Third Party directory to include stuff per 2.3 vs 2.4.

I would suggest either defining some global constants like so:
define(SS_CORE_VERSION,'2.4.0');
define(SS_CORE_MAJOR,'2');
define(SS_CORE_MINOR,'4');
define(SS_CORE_REVISION,'0');

Or put the code from SapphireInfo->Version into a static function somewhere handy, like Requirements to be used to check requirements in addition to setting them.

Again I apologize if this exists, but it is pretty common among other frameworks I've used.  Of course this could open a larger discussions as the modules would need a systematic way to report their versions as well as check versions of other modules they rely on (like cms).

**Comment by kinglozzer** [comment]
Can this be closed? @tractorcow does `cow` handle @chillu’s above suggestion?

**Comment by dhensby** [comment]
It's be good to do that as part of the tag, I guess. But couldn't we now use composer to find this out?

**Comment by tractorcow** [comment]
It's done on the archive, but NOT on the tag, currently.

https://github.com/silverstripe/cow/blob/master/src/Steps/Release/BuildArchive.php#L191

I prefer the suggestion of moving the composer.lock logic out of LeftAndMain and into another core class. Adding more "meta" commits to each tag makes release more complicated, and introduces the risk of development branches having incorrect versions included.

Don't hard code what you can infer!

**Comment by chillu** [comment]
Pointer to the composer.lock logic commit: https://github.com/silverstripe/silverstripe-framework/commit/2b6d735182c323e5943365cea70eba61753c7492

I agree with @tractorcow in that we should try to infer this information rather than clutter the commit stream on each tag. In which case, the functionality is already in place. Yes, there's probably a more generic place for it than `LeftAndMain`, anybody's welcome to improve that :) @wilr's update reminder is a great idea, and implementing that could be the trigger to move the logic.

As far as this ticket goes, I would recommend using `LeftAndMain->CMSVersion()`. It's a public API, so functionality can rely on it, and we'll deprecate it if moving it around. Since there's not been any traction on this ticket for three years, and a solution (sort of) exists, I'm going to close it.
