### ISSUE TITLE
[2010-03-11] Replace user_error() calls with exceptions

### ISSUE THREAD

**Issue by silverstripe-issues** [silverstripe/silverstripe-framework#1915]
created by: mstephens
created at: 2010-03-11
original ticket: http://open.silverstripe.org/ticket/5184

---

Replace calls to user_error() with exceptions thrown instead.

Any body of code that is using try...catch to clean up after an error currently either misses any fault reported via user_error, or has to manipulate the global error handler manually, which is messy.

A specific example is code using transactions for ensuring multiple database operations are done atomically:

$db->startTransaction();
try {
  (some database operations)
  $db->endTransaction();
}
catch (Exception $e) {
  $db->Rollback();
  // maybe other cleanups too
  throw $e;
}

currently misses most errors, and could be an issue with persistant database connections, for example.

try... catch seems a more elegant mechanism than user_error in this way.

Non-fatal calls to user_error (warnings and notices) should be left as user_error().

Not sure of the scope of this change. Definitely at the ORM/database level, possibly wider.

**Comment by chillu** [comment]
Related uservoice issue: https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6805690-errorexception-instead-of-user-error

**Comment by Acen** [comment]
> Related uservoice issue: https://silverstripe.uservoice.com/forums/251266-new-features/suggestions/6805690-errorexception-instead-of-user-error

For posterity, considering the user voice service is no longer running for SS.
>ErrorException instead of user_error
In the framework user_error() is still used quite regularly and while at certain points this functionality might be wanted.
I would like it to be changed to use ErrorException (http://php.net/ErrorException) this would allow any developer to actually catch some of these Errors (especially the ones related to database errors like duplicated key etc.) and use them as they wish.
In my case i would like to catch these for a Restful API and return them as Error arrays in my json response.
Which in the current implementation is not really possible since all errors go through the Debug::loadErrorHandlers() with no chance to catch these outside of defining your own set_error_handler() implementation (as far as i know off at least).

>N. Schipper shared this idea  ·  December 05, 2014

**Comment by sminnee** [comment]
FYI this is still relevant. Warnings should be left as-is but there are a fair few E_USER_ERRORs in the system.

**Comment by robbieaverill** [comment]
I'm happy to do this if we want to do it. Do we consider it a breaking change? If not I'll PR into the 4 branch

**Comment by sminnee** [comment]
As long as you leave warnings and notices as-is it's not a breaking change. 👍🏻

**Comment by robbieaverill** [comment]
I've replaced all E_USER_ERRORs in the default Silverstripe install. There's 4-5 left in the PEG parser, which I didn't really want to change.

**Comment by ScopeyNZ** [comment]
All merged. Are there any other repos that should be covered?

**Comment by robbieaverill** [comment]
Nah, I think it was mostly in the framework/cms code, no need to keep the issue open any longer than 10 years!

**Comment by sminnee** [comment]
Yay for slaying zombies ;-)
