### ISSUE TITLE
can't add comments to yml files

### ISSUE THREAD

**Issue by joernroeder** [silverstripe/silverstripe-framework#1963]
It seems like you can't add `# comments` on yaml files at the moment. I got the following error:

_Notice: Configuration file '…/mysite/_config/config.yml' does not have an equal number of headers and config blocks in /framework/core/manifest/ConfigManifest.php on line 228_

**Comment by MrJamesEllis** [comment]
Side note: you can get this error "does not have an equal number of headers and config blocks" if a newline is added at the end of the yml file.
Some code editors do this automatically.

**Comment by dhensby** [comment]
Gosh, is this really a problem, still?

**Comment by kinglozzer** [comment]
I’m guessing SF2’s YAML component [doesn’t support multiple blocks](https://github.com/symfony/Yaml/blob/master/Parser.php#L233), so we’ll have to fix this internally.

**Comment by dhensby** [comment]
anyone?

**Comment by MrJamesEllis** [comment]
Hit this again out of the blue and I did some digging to work out what was happening:

My yml file:

```
---
Name: foobar
After: framework/routes#coreroutes
---
Director:
  rules:
    'foo/bar' : 'foo_bar_controller'
---
```

I had a trailing --- at the end of this specific YML file which was being ignored until I edited the file - I found my editor added a trailing newline at the end of the file upon save which wasn't apparent until I reloaded the file.
I've since turned off that setting and SS_ConfigManifest parses the file just fine with the trailing "---" thanks to the "PREG_SPLIT_NO_EMPTY" which ignores empty parts, meaning the modulus of $parts is going to be zero - addYAMLConfigFile() will barf if you have a trailing "---\n" at the end of a yml file but not a trailing "---"

I'm unsure if the Yaml spec allows for a trailing --- in the file, with or without a newline after it, but running both options through the Yaml PECL extension's yaml_parse_file returns a valid response with the last element being empty in both cases.

Aside from me dropping the trailing  "---" from the yml file, my suggestion would be to trim whitespace from the initial contents of the file:
https://github.com/silverstripe/silverstripe-framework/blob/3.3/core/manifest/ConfigManifest.php#L264

```
-               $fileContents = str_replace(array("\r\n", "\r"), "\n", file_get_contents($pathname));
+               $fileContents = str_replace(array("\r\n", "\r"), "\n", trim(file_get_contents($pathname)));
```

or use yaml_parse_file() if the PECL YAML (http://pecl.php.net/package/yaml) package is installed as it's a more robust parser. For instance having a trailing "..." in the yml file, which is allowed in the Yaml spec, causes sfYamlParser to fail in the current setup

yaml_parse_file also ignores comments in the YML file.

**Comment by dhensby** [comment]
@MrJamesEllis I'd be happy with your suggested fix (the `trim`) care to PR?

**Comment by tractorcow** [comment]
Comments seem to be well supported in any part of yml files in ss 4.0.

**Comment by sabeena1217** [comment]
Comments can be added in yaml,
the only thing is you have to add # at the very beginning of the line, NOT the beginning of the code segment.

eg:
#            this is a comment

                                  #but this is NOT a comment
