### ISSUE TITLE
Entwine onclick triggers when right clicking in Firefox 

### ISSUE THREAD

**Issue by MarcusDalgren** [silverstripe/silverstripe-framework#2103]
Not sure where to report this.

Anyways, right clicking anything that has entwine with an onclick hanlder bound on it triggers the link as if it was a left click. Chrome does not exhibit this behaviour and neither does IE10 so it seems to be an FF thing.

I took a peek at the Entwine code but couldn't wrap my head around exactly how this stuff is proxied.

**Comment by chillu** [comment]
A few reasons for closing this:

 * Relatively small Firefox user base
 * Little core expertise in Entwine internals since Hamish left
 * You can always limit event handling to left click in specific entwine handlers
 * Already a bug on https://github.com/hafriedlander/jquery.entwine/issues/21
 * We're moving away from Entwine towards React in newer interfaces
