### ISSUE TITLE
Unable to have an Abstract Data Object

### ISSUE THREAD

**Issue by oilee80** [silverstripe/silverstripe-framework#2856]
Due to how the DataObject inheritance works it is not possible to have an abstract DataObject. The use case for this would be:

``` php
abstract class MediaLinkRelationship extends DataObject {
    private static $db = array('Title' => 'Varchar','AltName' => 'Varchar',.....);
    private static $has_one = array('MediaItem' => 'MediaItem');
}
class PageMediaLinkRelationship extends MediaLinkRelationship {
    private static $has_one = array('Parent' => 'Page');
}
class AnotherDataObjectMediaLinkRelationship extends MediaLinkRelationship {
    private static $has_one = array('Parent' => 'AnotherDataObject');
}
```

The error occurs during build as it is trying to instantiate the abstract class (MediaItemRelationship) during DatabaseAdmin::doBuild().

**Comment by patricknelson** [comment]
But can't you still use reflection to ensure that a particular class isn't abstract prior to attempting to instantiate it? Why *must* it be instantiated? After all, it's the abstract class' child class which should be the target here, upon which the `->augmentDatabase()` method could be called, for example. An important point to an abstract class is to ensure it's not instantiated (along with defining a good baseline API).

Due to the complexity of my code base (and the need to reuse code throughout the site), I'm finding more and more that I need to have the ability to setup an abstract class which itself isn't intended for instantiation, but can define a contract/API and consolidate some functionality at the same time.

**Comment by dhensby** [comment]
I think the main issue is that the people who want abstract DataObjects haven't volunteered the effort to make it a reality. In the scheme of things, this isn't a priority for the core team.

**Comment by patricknelson** [comment]
I concur @dhensby, especially given the potential effort involved. What branch would a PR for this sort of change go into?

**Comment by tractorcow** [comment]
It would need to be master, since any existing code could rely on `singleton($class)` not to crash.
