### ISSUE TITLE
Deal with CSRF errors in a user friendly way

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#2876]
When you submit a form and then copy the URL and send it to someone ... they get this horrible message: 

> > There seems to have been a technical problem. Please click the back button, refresh your browser, and try again.

Which is wrong and useless.

I wonder if we can add something like this to the controller (PSEUDO CODE)

``` php

        if($this->request->param("Action") == $nameOfForm && !isset($_POST["SecurityID"])) {
            return $this->redirect($this->Link());
        }
```

**Comment by tractorcow** [comment]
I've re-named this ticket and changed its focus to the core issue.

I still think that moving CSRF to form validation is the best way to address this, but it would be acceptable to address this some other way that improves UX.

**Comment by Zauberfisch** [comment]
+1 for doing it in Form->validate(), makes a lot of sense and would be most easy to integrate there

**Comment by shaunjc** [comment]
In most of my projects I still show the error, but I at least load it using an Error Page if one is available. The same principles could be used to redirect the user elsewhere on the site , change the error message, or adjust how the CSRF logic works.

Using SS4 I use the Injector API to replace \SilverStripe\Forms\FormRequestHandler::httpError(), in order to pass the error message through to the onBeforeHTTPError extended methods. I also have an Extension added to \SilverStripe\Forms\FormRequestHandler, which will search for an error page using the same version, load the theme, replace the content with the error message text, add the controller to the stack, then render and output it to the browser.

Note: In my actual production code, I use different class names and namespaces.

*# mysite/_config/config.yml*
<pre>
SilverStripe\Forms\FormRequestHandler:
  extensions:
    - EnhancedRequestErrorHandlerExtension
SilverStripe\Core\Injector\Injector:
  SilverStripe\Forms\FormRequestHandler:
    class: EnhancedFormRequestHandler
</pre>

*# mysite/forms/FormRequestHandler.php*
<pre>
class EnhancedFormRequestHandler extends \SilverStripe\Forms\FormRequestHandler
{
    /**
     * Replaces the existing \SilverStripe\Forms\FormRequestHandler::httpError()
     * method to pass $errorMessage to 'onBeforeHTTPError' extension methods.
     * 
     * @see \SilverStripe\Forms\FormRequestHandler for method arguments, return,
     * and other documentation.
     */
    public function httpError($errorCode, $errorMessage = null)
    {
        $request = $this->getRequest();
        
        // Adjust extend method calls to include $errorMessage.
        $this->extend("onBeforeHTTPError{$errorCode}", $request, $errorMessage);
        $this->extend('onBeforeHTTPError', $errorCode, $request, $errorMessage);
        
        throw new HTTPResponse_Exception($errorMessage, $errorCode);
    }
}
</pre>

*# mysite/extensions/FormRequestHandler.php*
<pre>
use SilverStripe\View\SSViewer;
use SilverStripe\Core\Extension;
use SilverStripe\Core\Config\Config;
use SilverStripe\Versioned\Versioned;
use SilverStripe\ErrorPage\ErrorPage;
use SilverStripe\SiteConfig\SiteConfig;
use SilverStripe\ORM\FieldType\DBField;
use SilverStripe\CMS\Controllers\ModelAsController;

class EnhancedRequestErrorHandlerExtension extends Extension
{
    /**
     * Core function: Fires before the HTTPError() code executes
     * 
     * Locates an error page, updates some of the visible information
     * on the page, dumps the rendered html to the browser and stops
     * further processing.
     * 
     * @param int $errorCode Default: 404
     * @param \SilverStripe\Control\HTTPRequest $request
     * @param string $errorMessage Error message string.
     */
    public function onBeforeHTTPError($errorCode = 404, $request = null, $errorMessage = '')
    {
        // Get one error page - they all should work as fine as each other
        $page = Versioned::get_one_by_stage(ErrorPage::class, Versioned::get_stage());
        if ($page && $page->exists()) {
            // Ensure theme is loaded
            Config::modify();
            Config::inst()->set(SSViewer::class, 'theme_enabled', true);
            Config::inst()->set(SSViewer::class, 'theme', SiteConfig::current_site_config()->Theme);
            
            // Set response code and prevent Breadcrumbs
            $page->Breadcrumbs = '';
            if (is_string($errorMessage) || is_a($errorMessage, DBField::class)) {
                $page->Content = $errorMessage;
            }
            
            // Add Error Page Controller to stack
            $controller = ModelAsController::controller_for($page);
            $controller->setRequest($request);
            $controller->pushCurrent();
            // Manually render the template and output the HTTPResponse.
            $controller->getResponse()
                ->setStatusCode($errorCode)
                ->setBody($controller->render()->value)
                ->output();
            exit;
        }
    }
}
</pre>

**Comment by GuySartorelli** [comment]
Great idea but it's a super old issue that we're not going to do anything with any time soon. Closing. If someone is keen for this and wants to put in the work to implement it, `@` me and we can revisit.
