### ISSUE TITLE
BUG Insert file via HTMLEditorField media icon redirects to blank page

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#2976]
When you try to upload a file (non-image) via the HTMLEditorField using the media button, you are redirected to a blank screen.

To re-create:
- Go to edit a page.
- Click the media icon of the content field (tree icon)
- Choose a file (ie PDF) to upload.
- Click 'Update'

Versions Affected: 3.0.9 (3.1 seems fine on the demo site).

Verified by @kinglozzer

**Comment by kinglozzer** [comment]
Just tested in SS4, you can’t insert non-image files like this, you get an error: “Embed is only compatible with remote files”.

In 3.5.3 it doesn’t redirect to a blank screen, but it still inserts the file path for the link rather than the shortcode. It could still be fixed in SS3 by adding `setAllowedFileCategories('image')` to the `UploadField`

**Comment by lukereative** [comment]
I'm closing this as it is a SS 3.x only bug and SS3 is now in security only support.
