### ISSUE TITLE
Upgrade php 5.3 -> 5.4 memory issue (cache related)

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-framework#2986]
After upgrading from PHP 5.3 to PHP 5.4 vice versa, SilverStripe generates an out-of-memory error, that can be fixed by doing a /dev/build?flush=1 or by emptying the cache by hand. Versions 3.1.2 and 3.1.3. Happened on a nix hosting platform and can be reproduced on MAMP.

Not so much of an issue if only you know in advance. Unfortunately I'm not fluent enough to come up with an answer nor where it comes from, SilverStripe or Zend.

**Comment by JorisDebonnet** [comment]
I got the same problem today after upgrading from php 5.5 to php 5.6, while using SilverStripe 3.1.8. All 7 sites on my server displayed the out-of-memory error (in Core.php I believe), which I could solve for 4 by flushing, and for the other 3 I had to manually delete the cache folder (because flushing didn't work). 

Could we please invalidate all cache when a major php upgrade is detected? 

(or perhaps dig into which single piece needs to be invalidated, but I'm sure it wouldn't hurt to just remove the whole cache folder's contents to be sure)

**Comment by dhensby** [comment]
I'm leaning towards agreeing with @stevie-mayhew. Detecting major upgrades (or any upgrade) of PHP seems like a lot of work to protect against an edge case.

Production environments should be stable and rarely the subject of upgrades.

I acknowledge that with shared hosting you rarely get any warning or, if you do, you definitely have no specific time for when it'll happen but that's the compromise you make when you get shared hosting over a stand-alone server (be it Virtual or not).

**Comment by hafriedlander** [comment]
It wouldn't be that hard to include the PHP version in the name of the default cache directory, like the UID already is. I sometimes run into this when testing in 5.3 & 5.4 on my dev machine, and currently solve it by just constantly `rm -rf silverstripe-cache` which can get pretty annoying.

**Comment by JorisDebonnet** [comment]
I like @hafriedlander 's idea! So I went ahead and implemented it.

**Comment by tractorcow** [comment]
Fixed with #3882 https://github.com/silverstripe/silverstripe-framework/commit/047fe3a410624f34d617e4577669c4c7db52613b
