### ISSUE TITLE
Problem finding template for renderWith() w/custom class

### ISSUE THREAD

**Issue by moniuch** [silverstripe/silverstripe-framework#3051]
The following code is my class I am trying to develop, yet experience problems coupling it with a template. The code is basically a copy of the original DropdownField, yet skimmed down to the Field method alone, with the last line changed. The problem is **None of these templates can be found in theme 'simple': DropdownFieldData.ss**
- I flushed the cache repeatedly.
- I deleted the cache folder on my localhost (XAMPP)
- I moved the template around to various locations of my 'simple' theme: `/simple/templates`, `/simple/templates/forms`, `/simple/templates/Includes`
- As you can see, the template name does not have an underscore character which has once been reported to cause problems.

I suspect a bug. Version 3.1.3

``` php
class DropdownFieldData extends DropdownField {

    public function Field($properties = array()) {
        $source = $this->getSource();
        $options = array();
        if($source) {
            // SQLMap needs this to add an empty value to the options
            if(is_object($source) && $this->emptyString) {
                $options[] = new ArrayData(array(
                    'Value' => '',
                    'Title' => $this->emptyString,
                ));
            }

            foreach($source as $value => $title) {
                $selected = false;
                if($value === '' && ($this->value === '' || $this->value === null)) {
                    $selected = true;
                } else {
                    // check against value, fallback to a type check comparison when !value
                    if($value) {
                        $selected = ($value == $this->value);
                    } else {
                        $selected = ($value === $this->value) || (((string) $value) === ((string) $this->value));
                    }

                    $this->isSelected = $selected;
                }

                $disabled = false;
                if(in_array($value, $this->disabledItems) && $title != $this->emptyString ){
                    $disabled = 'disabled';
                }

                $options[] = new ArrayData(array(
                    'Title' => $title,
                    'Value' => $value,
                    'Selected' => $selected,
                    'Disabled' => $disabled,
                ));
            }
        }

        $properties = array_merge($properties, array('Options' => new ArrayList($options)));
        return $this->customise($properties)->renderWith('DropdownFieldData');

//      return parent::Field($properties);

    }
}
```

**Comment by axyr** [comment]
This happens also when having theme specific form templates. The form templates are only picked up when they are stored in themes/mytheme/templates/.

```php
CheckboxSetField::create('Specialisations', '', $myList)->setTemplate('ThemeSpecificCheckboxSetField');
```

My first idea would be to put this template in themes/mytheme/templates/forms, that won't work.
Second guess would be Includes, that won't work either..

Only themes/mytheme/templates/ThemeSpecificCheckboxSetField.ss will overload the core CheckboxSetField.ss, which lives in framework/templates/forms ....

I think its very legit to have theme specific form templates, and I also think that those should/could be stored in a separate forms folder, like we can do in modules and the framework does by default...

The theme/templates folder should only have a master Page.ss, if you ask me and not also MyFormTemplate.ss :).

Yes, mysite is a place to put custom frontend templates, since that is a project specific folder, but that wont work when you have 2 themes with a different markup structure and when you need one form field to have a one time different markup for a theme specific use case..

**Comment by dhensby** [comment]
I think I looked into this some time ago and it turns out case is important. To override a core template it must replicate the folder structure exactly. It doesn't help that the casing is inconsistent. 

Have you made sure your casing is the same? Also, I presume this is not in the cms as per above answer?

**Comment by axyr** [comment]
Yes, I'm very picky when it comes to Casing and it is happing in frontend.
But I spoke some people on the IRC, I will investigate this further, since i'm setting the theme in Page_Controller::init() with : 

```php
Config::inst()->update('SSViewer', 'theme', $theme);
```

**Comment by dhensby** [comment]
setting the theme in init shouldn't be a problem...

**Comment by dhensby** [comment]
I must say that I have just deployed a site in 3.1.x and have templates in the themes folder: `themes/default/templates/forms/ChecboxSetField.ss` and these work for me.

Granted, I'm just overriding the default template and not reassigning a new one...

If you move the template to Includes and it still didn't work, that is quite peculiar. What version of SS are you using?
