### ISSUE TITLE
BUG get_declared_permissions_list() always returns NULL

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#3080]
`Permission::get_declared_permissions_list()` always returns null becuase it relies on `Permission::$declared_permissions` which by default is `null`. What's more no code in `framework` or `cms` seems to refer to either this method or to the property.

Has this method ever worked? I see the only place this would likely be used in the CMS is in the Security admin, but in fact the logic used to show permission descriptions is on `Member::getCMSFields()` and uses a `PermissionCheckboxSetField_Readonly` field to do the job.

# Related Pull Request
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8558

**Comment by kinglozzer** [comment]
Marked as docs because if it is used anywhere, it’s certainly not documented well enough 😉

**Comment by dhensby** [comment]
Is this actually going to be addressed?

**Comment by robbieaverill** [comment]
I've only had a quick skim of this code but I think there's some minor refactoring that could be done (at least) here. E.g. using `$this->config()->get('...')` over `self::$config_prop_name` (SS 4.2.x)

**Comment by phptek** [comment]
Wow. I was still firmly in my 30s when I wrote this...

**Comment by maxime-rainville** [comment]
I added the `affects/4` tag because it's still relevant to SS4. It's not quite clear to me what this thing is meant to do.

There's the following methods and properties that only reference themselves:
* `private static $declared_permissions = null;`
* `private static $declared_permissions_list = null;`
* `public static function get_declared_permissions_list()`
* `public static function get_label_for_permission($perm)`
* `protected static function traverse_declared_permissions($declared, &$list)`

No other files anywhere else references those methods.

My vote would be to deprecate the whole lot.

**Comment by maxime-rainville** [comment]
I did https://github.com/silverstripe/silverstripe-framework/pull/8558 to add deprecation notices.

**Comment by GuySartorelli** [comment]
The deprecation PR was merged, and the deprecated code will be removed in the next major version.
This issue doesn't need to be open any more.
