### ISSUE TITLE
undeclared private statics

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3236]
The following yml config declarations do not seem to match any private static variables:

``` yml

Oembed
      Oembed.providers does not exist
      Oembed.autodiscover does not exist
      Oembed.enabled does not exist

HTTP
      HTTP.MimeTypes does not exist

UploadField
      UploadField.defaultConfig does not exist

Injector
      Injector.HTMLValue does not exist

i18n
      i18n.module_priority does not exist

Injector
      Injector.RequestProcessor does not exist

GoogleSitemap
      GoogleSitemap.enabled does not exist
      GoogleSitemap.objects_per_sitemap does not exist
      GoogleSitemap.google_notification_enabled does not exist
      GoogleSitemap.use_show_in_search does not exist    


```

You don't need to declare private static variables, but the consensus seems that we do so it would be good to keep with that. 

In some cases, the naming convention (lowercase with underscores) is also missing.  This is not a biggie, but it might be a good idea to align this.

**Comment by jakxnz** [comment]
A quick summary:

Here is a PR that considers @sminnee 's thoughts about debugging the config manifest https://github.com/silverstripe/silverstripe-framework/pull/9542/files

It includes an "audit" that shows which config entries have missing property definitions.

I've raised a PR with the few missing definitions https://github.com/silverstripe/silverstripe-framework/pull/9543/files

Can we assume that packages only need to define properties within a class, if that class is within the package that references the property? E.g I have not defined properties referenced by`silverstripe/graphql`

While I'm aware that the scope of this issue is ever-changing, can it be closed based on the above changes?

**Comment by sunnysideup** [comment]
I have since developed this tool:

https://github.com/sunnysideup/silverstripe-config_manager

That is related I guess....

**Comment by sunnysideup** [comment]
![image](https://user-images.githubusercontent.com/167154/84340204-466add80-abf4-11ea-8722-4be66e9bc5d3.png)

**Comment by GuySartorelli** [comment]
Seems like any actions that were needed have been taken. Closing this issue now, but if I missed something which hasn't been actioned feel free to reopen with an explanation of what still needs to be done.
