### ISSUE TITLE
UploadField width

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-framework#3382]
I don't like the new stacked layout introduced with https://github.com/silverstripe/silverstripe-framework/commit/46a5ee7d1de7fecd574b091377abad5a56326126. The UploadField doesn't vertically align with other Fields on the right hand side.

for more context:
https://github.com/silverstripe/silverstripe-framework/pull/3329

My first thought was to make UploadField max-width:696px or $grid-x * 87;
https://github.com/silverstripe/silverstripe-framework/blob/3.1/scss/UploadField.scss#L17

I've suggested this to adrexia but she thinks it looks a bit silly. She suggested to shorten all other fields white max-width: $grid-x * 52; (results in 416px instead of 512px):
https://github.com/silverstripe/silverstripe-framework/blob/3.1/admin/scss/_forms.scss#L109

.chzn-container is also 416px (think ListBox & dropdown)
https://github.com/silverstripe/silverstripe-framework/blob/3.1/admin/scss/_forms.scss#L224

I would like to see an adjustment for this but not sure which way to go since I think it's to drastic to change all fields length. What do you / @clarkepaul think?

How it looks now:
![now](https://cloud.githubusercontent.com/assets/472115/3905904/87da77c6-22ed-11e4-83ff-8959d83276f2.png)

enlarged UploadField:
![enlarged](https://cloud.githubusercontent.com/assets/472115/3905913/947cef9a-22ed-11e4-94df-0701c710cad5.png)

shortened all other Fields:
![shortened](https://cloud.githubusercontent.com/assets/472115/3905925/b3648e9a-22ed-11e4-80f6-60b5c843d5c0.png)

**Comment by bilekt3** [comment]
Hello, is this scheduled told some release? Or it is suspended? Thanks for reply.

**Comment by jonom** [comment]
I also have never liked that the UploadField takes up more width than all other fields - it looks really strange. When there are lots of buttons (i.e. when an image is selected) it would be nice if we could group them in to an options dropdown something like this:

![upload-dropdown](https://cloud.githubusercontent.com/assets/1079425/8705055/ea375104-2adb-11e5-9252-0bef715f2081.png)

Or an alternative could be to keep the buttons but have a `show options` / `hide options` toggle button and use the styling provided by @MattyBalaam above when they are visible.

**Comment by Jeroenem** [comment]
I really like the example by Jono Menz to keep the upload interface
uncluttered!


2015-07-15 19:30 GMT+02:00 Jono Menz <notifications@github.com>:

**Comment by kinglozzer** [comment]
I’d lean more towards the original layout if in edit view, and the new layout (from #3329) if in split view mode - just toggle the layouts depending on how much width is available. The dropdown design looks nice, but I’m not sure I like putting an extra click in between the user and all of the actions.

**Comment by jonom** [comment]
I know what you mean about the click - but I think UploadField might be one of those instances of an interface in the CMS that draws far too much attention relative to its importance, so would be good to simplify this somehow. I think @clarkepaul is actively trying to reduce this kind of imbalance at the moment?

A good comparison might be the URLSegment field - you have to click an edit button before you can actually do anything there, so the extra click isn't without precedent. I would quite like to copy that pattern actually, would simplify the interface a lot, and only show all the controls when you actually need them:

![upload-toggle](https://cloud.githubusercontent.com/assets/1079425/8727400/560ba688-2b94-11e5-97d6-21000478e594.png)

**Comment by kinglozzer** [comment]
IMO the current layout works reasonably well, I don’t think we want to shrink it too much as you’d struggle to identify images (photographs anyway) at a smaller size than we’ve got currently. One for you and the rest of our frontend gods to mull over ;).

For the short term, I hope we can fix (or at least improve) this with a few minor CSS tweaks. Any bigger refactors would probably have to go against 4

**Comment by kinglozzer** [comment]
How about this: https://github.com/kinglozzer/sapphire/commit/0c013161bf8a9c3f384b25123c4e4cff10eebe54? "edit mode" is the old layout that matches other fields’ widths, split view is the new layout.

Edit mode:
![screen shot 2015-07-16 at 16 53 48](https://cloud.githubusercontent.com/assets/1655548/8728179/a4dfb1e0-2bdb-11e5-8669-b5ea8f5a25a0.png)

Split view mode:
![screen shot 2015-07-16 at 16 53 58](https://cloud.githubusercontent.com/assets/1655548/8728182/a7608138-2bdb-11e5-9a41-55da346a1bc0.png)

**Comment by jonom** [comment]
SemVer for UI design is an interesting topic... how would you define a breaking change without an API? :) I don't disagree necessarily but bigger changes than this are headed to 3.2 and 3.3 already.

For your layouts above, ironically when more screen width is available (Edit mode) the field is taking up more vertical space because the last button wraps to a second line... so I would probably say there's no advantage in switching the layouts, may as well stick to one layout for both modes.

**Comment by jonom** [comment]
Hey you called me a god! :smile: lol

**Comment by kinglozzer** [comment]
>SemVer for UI design is an interesting topic... how would you define a breaking change without an API? :) I don't disagree necessarily but bigger changes than this are headed to 3.2 and 3.3 already.

That’s true, it’s a tricky balance because even minor CSS changes could screw someone over!

Yeah I did think it’s a bit strange to have “less room” in the full edit mode... but then this ticket (and other complaints I’ve seen in IRC) are about the fields not lining up like they used to.

I think if we don’t want the buttons to wrap in most languages, our only option (for now) is the wide version show in the 2nd screenshot on the original issue. I tried doing that without adding JS classes for the specific layout modes but failed! :disappointed: https://github.com/silverstripe/silverstripe-framework/compare/3...kinglozzer:pulls/uploadfield-width

**Comment by jonom** [comment]
2nd screenshot is a really easy fix fortunately, in fact @lerni described how to do it in the description: https://github.com/jonom/silverstripe-framework/commit/8137a5ac9de822bcb184b60c75822dc91fc7fe8b agree this would be good as a first step.

**Comment by jonom** [comment]
p.s. note that for English (and I assume some other languages) this tweak provides enough space to prevent the last button wrapping to a second line. Maybe not the case for German going by the screenshot in description.

![screen shot 2015-07-16 at 10 17 13 am](https://cloud.githubusercontent.com/assets/1079425/8730112/e255ca92-2ba3-11e5-9fca-61458af2df3d.png)

**Comment by chillu** [comment]
I'm not a fan of the "options" dropdown, goes too far off the other direction (from very explicit to very hidden). Maybe we can trim this back visually by replacing the button styling with some more lightweight link actions? Or we could have the major actions (edit and remove) as buttons on the right, with a down arrow revealing the other two options?

**Comment by adrexia** [comment]
I think ditching the really large buttons and relying a bit more on icons could help. Could move the remove/clear button up to be in the corner of the field itself. Edit could be an expand selector style. 

Why do we even have the option to delete from files?

**Comment by jonom** [comment]
@chillu that could work, only reduces the number of buttons by 1 but it would reduce the total width of the buttons by quite a bit as the two buttons with the longest labels would be removed.

@adrexia I'm not sure icons alone would be a good option here - even with text these actions are a bit confusing and we've had debates about changing the labels. I think 'Clear Selection' would be better than 'Remove', and like you I don't love that there is a 'Delete from files' button (no, pretty sure there isn't any logic to stop you deleting a file that's used elsewhere - and if there was it would probably be inaccurate and not include many_many or HtmlEditorField uses).

We could maybe get rid of the 'Choose another file' button and force people to click 'Remove' (or Clear Selection :wink:) first before they can choose a different button. You already have to do this if you want to upload a new file after all. If we also removed the 'Delete from files' button that would mean there are only ever two buttons visible in this interface and we probably wouldn't have a width problem anymore.

**Comment by adrexia** [comment]
Agree. I think iconography would only make sense for the clear. And I agree, it should be called 'Clear' if there's a text label. The naming and iconography is currently very dev centric. I don't think a normal user needs to know that it will unlink the file record from the table. If it weren't for the separate delete button, then using a minus or a times symbol would work for clear.

**Comment by clarkepaul** [comment]
Without going and playing with designs, I think we could strip it back to one button "Edit" which opens the description directly in-place for editing. Presenting just two options which would be "Save" and "Remove/Clear", as someone mentioned earlier you probably don't need the actions "choose another file" as onced cleared they can add another file. The "delete from files" should just be a link to file in the files area where ideally there should be more information about what pages the file lives on and just allowing delete from there.

If that is possible to present on the same screen without navigating away you would just need an additional close/hide link.

@jonom yeah this is a good example of the things I would like to reduce the weight of, four big buttons in a row attract way too much attention from the user.

**Comment by jonom** [comment]
@clarkepaul if I understand you right then if you want to Remove/Clear you would first need to click Edit and maybe then scroll to the bottom of the inline File Edit form to find the button. I think that is hiding the most important action too far away, but what about something like this for the 'File Selected' state:

![upload-toggle-2](https://cloud.githubusercontent.com/assets/1079425/8781360/5ad011c2-2ec3-11e5-9520-6b72fb7d0c1a.png)

Not with that exact design, but I think just having those two clearly labelled actions would be sufficient. Clicking 'Clear Selection' resets the interface and allows you to upload a file or choose one from the CMS, while clicking 'Edit File' could either open a file editing form in place, or take you to the Files section (my preference) - either way it would lead to an option to permanently delete the file if you choose (side note - how about a 'Trash' module for SilverStripe?).

IMO the specificity of the labels is very important. Remove, Clear, Edit are all fairly ambiguous terms and don't clearly communicate whether you'll be affecting the link to the file or the file itself and what the result will be. This is the No. 1 thing that needs to be improved on this field I think. To me the expense of a slightly longer button is easily worth it for the benefit of users being able to accurately predict what the button does.

I think the inline editing of file information here may be an added source of confusion for some people because it kind of implies that the File description is closely tied to the Page or other object it's linked to... or well it doesn't imply it exactly but it doesn't *help* people understand that the File is merely linked, and any edits you make are to the File, not the Page, and may have repercussions elsewhere.

**Comment by adrexia** [comment]
I like where that is heading a lot more, but I think I would accidentally hit clear a lot more often. I think the buttons need to look different or be in different places.

**Comment by jonom** [comment]
Hey @adrexia yeah the mockup was just to illustrate functionality and labels really - the design can certainly be improved.

This is still only indicative but we could de-emphasise the edit action and link it more clearly to the related file object like this perhaps:

![upload-toggle-3](https://cloud.githubusercontent.com/assets/1079425/8788005/56f074f6-2eec-11e5-9952-4b828a4335d4.png)

**Comment by clarkepaul** [comment]
Hey, this is what I was meaning - sorry for the delayed response, excuse the rawness.
![pasted_image_23_07_15_11_42_am](https://cloud.githubusercontent.com/assets/555033/8840137/54ef0bf8-3131-11e5-9e35-9e78c4f99767.png)

@jonom I not sure if the "clear" action is as important as the edit (I guess it could go either way)
 if it was only shown after the "edit" was clicked then it could act like a two step process making sure people are sure they want to clear the selection. 

Anyway all of your mockups are better than what is existing. I would probably go with either one of these:
![pasted_image_23_07_15_11_55_am](https://cloud.githubusercontent.com/assets/555033/8840192/fb139c1a-3131-11e5-95c5-611f5fcc4a3b.png)
![pasted_image_23_07_15_11_55_am](https://cloud.githubusercontent.com/assets/555033/8840194/ff898606-3131-11e5-810f-e5053a9f5803.png)

**Comment by jonom** [comment]
@clarkepaul thanks - sorry for my delay now too, had a couple of days off. I like that mockup but I think if I clicked 'Delete from files' and it took me to the Files section instead of actually deleting the file that might be annoying. Also feels like if we do intend to keep showing the entire Edit File form interface inline here, it's maybe a bit inefficient to send people to the Files section just so they can properly access the Delete button, as that would be the only thing missing.

I like the 'Remove from page' label, assuming that could be smart and insert the appropriate class name as necessary e.g. 'Remove from Testimonial'. I don't like 'Remove File' as a label as it's ambiguous - could mean delete or un-attach/de-select.

@clarkepaul would you mind having a look at my comment here about file selection https://github.com/silverstripe/silverstripe-framework/issues/4409#issuecomment-125268452 I think there's a duplication of effort happening in the CMS and we could maybe streamline things by tweaking and then re-using the Files section fields and forms within a modal interface for UploadField and HTMLEditorField. Key benefits would be reduced maintenance effort, and shallower learning curve for CMS users as they would see the same familiar interface in multiple scenarios.

**Comment by clarkepaul** [comment]
@jonom My reason for only being able to delete from the files area is to acknowledge that it may be used elsewhere, if we could bring some of that info (eg: used on at least 3 other places) into this screen or a warning dialog saying that this image could be also in other locations then I'm all for the delete staying on in this area.

**Comment by jonom** [comment]
The inline Edit form already includes the same 'Used on' field as in the Files section but I agree that a warning dialogue would be good and the 'at least' part is critical - this notice has always been misleading because it doesn't account for nearly all the ways a File may have been used. It would be awesome if we could upgrade this notice to accurately count all has_one, has_many and many_many relations a File is part of. Probably would still need to say 'at least' though even then. That would pave the way for a 'delete unused assets' task for developers that should be relatively safe. I took a crack at developing this once but came up a bit short trying to access all of the possible relations.
