### ISSUE TITLE
search button for groups is meaningless... 

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#3420]
when you click on search in the group model admin in the CMS there is no field to search...  This should allow you to search for the group name:

![image](https://cloud.githubusercontent.com/assets/167154/3994480/cc52a404-291a-11e4-9ec7-37f6acb21558.png)

**Comment by tractorcow** [comment]
You can set the summary_fields to Title, but then override the gridfield cell generation for that field to display the breadcrumbs.

**Comment by SpiritLevel** [comment]
@kinglozzer @tractorcow @sunnysideup

Loz's solution (changing L97 and L100) works perfectly well. 

However, if we just delete lines 95-103 altogether then we get a filter input field for Group name and one for Description, and partial matching works for both as expected. Having a searchable description seems potentially useful. What do you think ? 

And, unless I am missing something, the lines 95-103 are completely superfluous anyways; breadcrumbs still display properly on the top left corner of Main and the grid field columns display with the correct heading. It seems that `$columns` is not used anywhere else in `SecurityAdmin`.

I propose we just delete lines 95-103 as the solution to this issue.

I quickly experimented with @tractorcow's idea of using `$summary_fields` but couldn't get anything to work. Maybe I am missing something here ? Or was this an idea for searching on subgroups ? 

I did notice one other minor quirk: if the `GridFieldFilterHeaders` are closed in all tabs (Users, Groups, Roles), then opening `GridFieldFilterHeaders` in one tab opens it in all tabs. However, when the `GridFieldFilterHeaders` are open in all tabs, closing it in one tab only closes it in that tab; it remains open in all other tabs. Should I submit an issue for this ?

@sunnysideup: There will always be at least one in the Administrators group, will there not (the Default Admin)? So I suppose there is always something to search on :-). 

Anyhow, let me know what you think. I'll submit a PR after consensus reached :)

**Comment by sunnysideup** [comment]
@SpiritLevel , what I mean is that the search icons displays, but is not actually operational.  I guess I am wondering how the search icons display when there is no searchable field (as opposed to searchable rows). 

Of course, it is great to be able to search the groups, but in its current setup without a searchable field, it should look like this:

![image](https://cloud.githubusercontent.com/assets/167154/20652736/c1de455a-b563-11e6-9ea6-a48251ac1d02.png). There will always be gridfields that are "unsearchable" and so maybe the GridFieldFilterHeader should allow for this.

Does that make sense?

**Comment by SpiritLevel** [comment]
Hi there @sunnysideup 

Not sure about a couple of points you raised. :( Likely due to my not understanding something.

However, I take it that you would be happy with either my or Loz's solution so that we can use `GridFieldFilterHeader` in `SecurityAdmin` to filter on `Group` and that there is always at least one member in the `Administrators` group to filter on making it sensible to always offer filtering on `Group`.

I am a bit confused by the way you distinguish between "searchable" fields and "searchable" rows. If you can filter on a field then this can be used to filter out rows of data you aren't interested in. Or, did you mean something else ? 

And, just off the top of my head, I can't think of what wouldn't be filterable. Can you give me an example ? I think that all list data structures in SS implement `SS_Filterable`. 

I believe the code for constructing the HTML that displays the "search" icon (which is actually filtering) can be found in `GridFieldFilterHeader::getHTMLFragments()`. So, you could copy and rename `GridFieldFilterHeader` and make your own modifications to this method. Or, perhaps you could copy and rename `SecurityAdmin` and remove the grid field config component `GridFieldFilterHeader` when there is nothing to be filtered ?

**Comment by sunnysideup** [comment]
_And, just off the top of my head, I can't think of what wouldn't be filterable:_  

an example is Group, 

but there are others instances like this or at least we should not make the assumption that there is always a database field.   That is, if the column assigned value in a gridfield is not a direct database field then it is not filterable: https://github.com/silverstripe/silverstripe-framework/blob/master/src/Forms/GridField/GridFieldFilterHeader.php#L145 (canFilterBy basically checks if a field is a database field). 

So what I would propose is in three steps:

(a) hide filter altogether if there is nothing that can be filtered (keep in mind that the filter is part of the base config for gridfields: https://github.com/silverstripe/silverstripe-framework/blob/master/src/Forms/GridField/GridFieldConfig_Base.php#L20)

(b) allow database fields to be assigned to columns for filtering while display is more detailed .... e.g. in Group BreadCrumbs are displayed but the Group Title is filtered on. 

(c1) allow filters to work on non-database fields (that is a big job)

AND / OR

(c2) tap into the searchable_fields variable and related concepts for more information on fields that can be filtered in a gridfield, rather than solely providing a partial match for database fields.

**Comment by SpiritLevel** [comment]
Hmmm...

I looked at `canFilterBy` and it only checks (i) if a **list** has at least one record by trying to get its first record and (ii) if that first record has the field that you want to filter on. It does not appear to require the field you want to filter by to be in any database table. In other words, as long as you somehow get the field of interest into the list, you will then have `canFilterBy` returning true for that field. 

Does this change your thinking ?

**Comment by sunnysideup** [comment]
for Array Lists:
https://github.com/silverstripe/silverstripe-https://github.com/silverstripe/silverstripe-framework/blob/master/src/ORM/ArrayList.php#L480-L4888 

and for DataList:
https://github.com/silverstripe/silverstripe-framework/blob/master/src/ORM/DataList.php#L253-L269

Does a Gridfield use a Datalist or an Array List? I'd say a datalist, but even if it were an Array List then the only fields would be the database fields anyway?

**Comment by SpiritLevel** [comment]
Ah, yes, I only looked at the `ArrayList` version of `canFilterBy` which is why I thought that with an `ArrayList`, one could just add any fields one wants and use these for filtering. 

The `DataList` implementation of `canFilterBy` is different, requiring the fields to be from a database. And, if you do a `var_dump` on `$groupList` in `SecurityAdmin` you will see it includes a `DataList`. So, `DataList` it is! :)

According to the api docs, `GirdField` gives an `SS_List`. Perhaps `GridField` just uses the list it is given. In our case, it is `Group::get()` which is a `DataList`. I am thinking you can instead provide `GridField` with an `ArrayList` and in this case the `ArrayList::canFilterBy()` method is used. 

Anyhow, I'll have to think about this and do some experiments now that I understand your point :)

**Comment by tractorcow** [comment]
ok, so my solution was a bit off. Looking at the code in SecurityAdmin.php:

```php
$columns->setDisplayFields(array(
	'Breadcrumbs' => singleton('Group')->fieldLabel('Title')
));
$columns->setFieldFormatting(array(
	'Breadcrumbs' => function($val, $item) {
		return Convert::raw2xml($item->getBreadcrumbs(' > '));
	}
));
```

Changing it to the below makes it searchable / sortable

```php
$columns->setDisplayFields(array(
	'Title' => singleton('Group')->fieldLabel('Title')
));
$columns->setFieldFormatting(array(
	'Title' => function($val, $item) {
		return Convert::raw2xml($item->getBreadcrumbs(' > '));
	}
));
```

Is that what you wanted? It won't search on all the breadcrumbs, but it will at least work on the end breadcrumb (i.e. the title).

**Comment by tractorcow** [comment]
ok, that's exactly what @kinglozzer had suggested... I'm just rushing through my unreads. XD

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6797
