### ISSUE TITLE
Adding foo.js to end of a url causes the controller to be exposed

### ISSUE THREAD

**Issue by ColmMcBarron** [silverstripe/silverstripe-framework#3422]
Noticed this issue on a number of sites that are running silverstripe 3+

If you go to any subpage from the top level and add /foo.js (or anything else with 'css', 'js', 'jpg', 'jpeg', 'gif', 'png', 'bmp', 'ico' extension) on it, it doesn't return a 404, it returns the controller and an error message.

The source of this problem is in the class 'HTTPRequest' class:

``` php
public function isMedia() {
   return in_array($this->getExtension(), array('css', 'js', 'jpg', 'jpeg', 'gif', 'png', 'bmp', 'ico'));
}
```

Not sure what the best fix is here since yes it's good for images, but we shouldn't been exposing the controller names.

I can give some example urls if needed.

**Comment by sminnee** [comment]
This was a deliberate design decision, although I can appreciate that maybe this wasn't the behaviour that you expected / desired.

The reason that we introduced this functionality was for performance. Typically, URLs with the extensions defined aren't opened directly by the user, but are referenced as dependencies of a page. You'll sometimes get a situation where a broken reference to a CSS file will cause a 404 on every page view.

We wanted to ensure that responding to these 404s was both low-bandwidth and low-processing-time. So, rather than send a full friendly 404 page, we've opted to send a much more abridged view.

A few thoughts:

 * Not everyone wants this behaviour, and so maybe it should be configurable. I still think th
 * Right now the 404 message will often be some gobbledegook rather than an abridged, friendly message explaining that the page isn't available. Something like this might be better (the text could be amended with a config option):
     ```
     Content-type: text/plain

     Sorry, this page cannot be found.
      ```

I would suggest resolving this by adding a couple of config options:

 * `ContentController.friendly_error_for_media_requests`: Default to false, if set to true then the rendered error page should be shown even for media requests.
 * `ContentController.error_message_for_media_requests`: If `friendly_error_for_media_requests` is false then this map of messages will used to send plain text responses. A map of HTTP status code => message.

**Comment by tractorcow** [comment]
See my comment on https://github.com/silverstripe/silverstripe-cms/pull/1091

**Comment by ColmMcBarron** [comment]
@sminnee I don't think there is a problem with the friendly/lower bandwidth messages, I would agree with the design here.

The problem is exposing the controller name, any identifying information and not sending a HTTP 404 status header.

Potentially there should be another asset .html file like what's currently used for standard 404 pages.

**Comment by tractorcow** [comment]
I think that in this case, even when the information is being exposed, the response code is till 404 correct?

**Comment by ColmMcBarron** [comment]
It returns a 200 status code currently, e.g.

http://www.silverstripe.org/software/test.png

**Comment by tractorcow** [comment]
@ColmMcBarron I'm getting 404

![image](https://cloud.githubusercontent.com/assets/936064/7308010/cc838798-ea64-11e4-89f7-4057c60fcc6f.png)

**Comment by ColmMcBarron** [comment]
@tractorcow ok, weird not sure where I was seeing the 200, retrying and you are correct getting a 404 status code.

**Comment by dhensby** [comment]
Current message I get is `Action 'foo' isn't available on this handler.` which, whilst unfriendly, doesn't expose information about the actual controller...

**Comment by tractorcow** [comment]
From memory, we no longer expose controller name outside of dev mode. The initial issue raised is resolved, even though the behaviour may still be less than desirable.
