### ISSUE TITLE
Make DataQuery->selectField() public

### ISSUE THREAD

**Issue by schippie** [silverstripe/silverstripe-framework#3574]
Make selectField() : http://api.silverstripe.org/3.1/source-class-DataQuery.html#745-753  on the dataQuery a public function since their is no way currently to add additional table fields to a query as an alias. The function has been made protected but i can't find a reason why this is since you can still call DataQuery->selectFromTable() which does more or less the same thing except it forces you to set all the fields at once. 

It only acts as an annoyance right now preventing you from easily adding one additional field after the other.

**Comment by axyr** [comment]
+2. 

I managed to have a DataList with eager loading of hasone fields, with a JoinedDataList extends DataList, but still had to subclass DataQuery to access the selectField.
See this working (not fully tested) example I work with on a project (yes some code could be removed....) :

http://sspaste.com/paste/show/559f99a28efac

**Allow more complex sorting**
I needed to do an alternative sort with a CASE WHEN select. For this I needed to overload the DataQuery as well to access the selectField, so I can sort on the CASE WHEN result, like this: 

http://sspaste.com/paste/show/559f9a6fea3b1

Maybe both use cases can be accomplished easier, but I couldn't find it, and this is what I came up with..

**Comment by kinglozzer** [comment]
This method will be public in 4.0, see #4038. For now, there are workarounds (the examples above, using `Injector` to specify a custom class, or even using `ReflectionMethod`), so closing this :)

**Comment by patricknelson** [comment]
@kinglozzer I thought about using `Injector` here, except it's kind of a huge PITA from what I can tell. 

Basically you have to:

1. Override `DataList` in Injector with your own `CustomDataList` class since that uses the `new` keyword to instantiate `DataQuery` ([reference](https://github.com/silverstripe/silverstripe-framework/blob/3.7/model/DataList.php#L55))
1. Create another `CustomDataQuery` class to override `DataQuery` so that you can setup your method, 
1. Name that method something different, e.g. `->selectField2(...)` so that you can make it public, since overriding a method and changing it's visibility wouldn't be allowed.

However, that doesn't work, because there are classes that then extend from `DataList` which end up being injected as well (e.g. `RelationList`) whenever they are attempted. Because, of course, in `3.x` this bug exists: https://github.com/silverstripe/silverstripe-framework/issues/4774 

😭

**Comment by kinglozzer** [comment]
Whenever I needed this in 3.x I just used ReflectionMethod to make it
accessible and then invoke it :)

**Comment by patricknelson** [comment]
Darn you and your logical workarounds.

This is an example of those situations where I show the difference between less and more experienced developers. Less experienced developers may still solve the problem, but may be less efficient and have tons more code when there's a much simpler and quicker solution.

That said: Reflection is it's own form of ugly hack, but overall, much less so IMHO.
