### ISSUE TITLE
BUG Edge case in SS_DatetimeTest::testFormatFromSettings()

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#3749]
There is an edge case in the timezone calculation used by this method which seems to surface during new years day. About 13 hours every new year (while NZ is one year ahead of GMT time) this test case will fail.

```
$ ./framework/sake dev/tests/SS_DatetimeTest flush=all
SS_DATETIMETEST

---------------


............F
SS_DatetimeTest::testFormatFromSettings
Failed asserting that two strings are equal.
PHPUnit_Framework_Assert::assertEquals(31/12/2014 10:11:01,31/12/2015 10:11:01)
DatetimeTest.php:170
```

It seems that at 1pm on new years day (since nz is +13GMT during daylight saving) the issue magically resolves itself. Perhaps some issue with zend_date?

**Comment by sb-relaxt-at** [comment]
I guess this issue is the same @jonom discovered with my pull request (https://github.com/silverstripe/silverstripe-framework/pull/4882#issuecomment-168538805). I have investigated this further and I am afraid there is a pattern mistake in using Zend_Date. In Zend_Date 'Y' (http://framework.zend.com/manual/1.12/en/zend.date.constants.html#zend.date.constants.selfdefinedformats) refers to the year as specified in ISO 8601, which in turn is not always equal to the calendar year (namely around the beginning of a year: https://en.wikipedia.org/wiki/ISO_week_date#Disadvantages). See also this related discussion: http://stackoverflow.com/questions/1978051/zend-datetostring-outputs-the-wrong-year-bug-in-my-code-or-zend-date

From my understanding we have to change all 'Y' (uppercase) occurencies when using Zend_Date to 'y' (lowercase). Fortunately the options in Member seems to use the lowercase 'y'. Nevertheless the format description on the profile page advertise the use of uppercase 'Y'. I am not sure whether or not there are other parts to change. I will start with updating the testcase accordingly.

**Comment by sb-relaxt-at** [comment]
The update for the testcase: https://github.com/sb-relaxt-at/silverstripe-framework/commit/642751f7e410069d9c2d56a72f3bad6ae5913e70

**Comment by jonom** [comment]
Thanks for your work on this @sb-relaxt-at!

**Comment by tractorcow** [comment]
We can probably fix this for 2.2.2 :)

**Comment by chillu** [comment]
We're no longer using Zend_Date in 4.x, nor are we using `Member.DateFormat` (and hence not advertising `Y` vs. `y` to users). We're setting `i18n::$date_format = 'yyyy-MM-dd', so from what I read above that should be fine by default. We're referencing `YYYY` in the docs: https://github.com/silverstripe/silverstripe-framework/pull/6887

Closign this off, unless somebody wants to write a migration script for `Member.DateFormat` data, a new test case for 3.x, and an accompanied fix for 3.x

**Comment by tractorcow** [comment]
Yay it fixed itself. Or you'll be getting a phone call from me at 1am jan 1st :P
