### ISSUE TITLE
SS <=3.1.8 - ModelAdmin - Inverse component Error

### ISSUE THREAD

**Issue by andrelohmann** [silverstripe/silverstripe-framework#3779]
I came across the following Error:
When having multiple many_many relations to the same DataObject class, editing of one of the items relates in an "Inverse component" Error within ModelAdmin.

Here is some code:

```php
class Category extends DataObject {
    
    private static $db = array(
        "Title" => "Varchar(255)"
    );
    
    private static $many_many = array(
        'BigProducts' => 'Product',
        'SmallProducts' => 'Product'
    );
}

class Product extends DataObject {
    
    private static $db = array(
        "Title" => "Varchar(255)"
    );
    
    private static $belongs_many_many = array(
        'BigCategories' => 'Category.BigProducts',
        'SmallCategories' => 'Category.SmallProducts'
    );
}

class CategoryAdmin extends ModelAdmin {

    private static $managed_models = array('Category','Product');
    private static $url_segment = 'categories';
    private static $menu_title = 'Categories';

}
```

I was able to track it down to following files and lines:

framework/model/DataObject.php :1857

framework/core/Config.php :582

framework/core/Config.php :525

framework/core/manifest/ConfigStaticManifest.php :39

The static manifest files are not including the "." notation of the relation names and there seems to be an algorithm missing, to extract these. But here my knowledge and my ability to follow up the bug stopped.

Anyway, I hope these informations will help.

**Comment by kinglozzer** [comment]
Looks like this relates back to #1377. Some work was started in #3415

**Comment by micmania1** [comment]
@andrelohmann A workaround is to swap a many_many with belongs_many_many.

    class Category extends DataObject {

        private static $db = array(
            "Title" => "Varchar(255)"
        );

        private static $many_many = array(
            'BigProducts' => 'Product',
        );

        private static $belongs_many_many = array(
            'SmallProducts' => 'Product'
        );
    }

    class Product extends DataObject {

        private static $db = array(
            "Title" => "Varchar(255)"
        );

        private static $many_many = array(
            'SmallCategories' => 'Category'
        );

        private static $belongs_many_many = array(
            'BigCategories' => 'Category',
        );
    }

**Comment by andrelohmann** [comment]
That Workaround is a niceone, but sometimes you need even more than two many_many relationships.

Anyway, if you look up in this thread, you see a solution, that solves the problem, by editing the DataObject.php. But I didn't checked that for side effects.

**Comment by tractorcow** [comment]
The current issue with multiple many_many is that it doesn't allow for duplicate parent/child classnames. See http://doc.silverstripe.org/en/developer_guides/model/relations/

To look at the issue simply, the mapping table is always named "ParentClass_ChildClass". You can, as suggested, get around the issue by having another "ChildClass_ParentClass" as a secondary relationship.

Another possible workaround is to have one relation, and then categorise it with:

```php
private static $many_many = array('Products' => 'Product');
private static $many_many_extraFields = array('Products' => array(
  'Size' => 'Enum("Large,Small")';
));
```

Or if the products themselves have a fixed size (which is likely the case) I would just add the Size field to the product directly, and then you can filter `$category->Products()->filter('Size', 'Large')`;

Another another work-around is to have separate subclasses for each product type, thus ensuring distinct mapping table classes (`Category_BigProduct`, `Category_SmallProduct`, etc).

In the future we should implement this, for sure, so just treat these as work-arounds for the time being. :D

**Comment by tractorcow** [comment]
The current issue with multiple many_many is that it doesn't allow for duplicate parent/child classnames. See http://doc.silverstripe.org/en/developer_guides/model/relations/

A possible workaround is to have one relation, and then categorise it with:

```php
private static $many_many = array('Products' => 'Product');
private static $many_many_extraFields = array('Products' => array(
  'Size' => 'Enum("Large,Small")';
));
```

Or if the products themselves have a fixed size (which is likely the case) I would just add the Size field to the product directly, and then you can filter `$category->Products()->filter('Size', 'Large')`;

Another another work-around is to have separate subclasses for each product type, since each subclass will have its own belongs_many_many back to category.

Until https://github.com/silverstripe/silverstripe-framework/pull/3415 is fixed and merged you'll need to work around this restriction, I'm afraid.

**Comment by kinglozzer** [comment]
Another workaround (as this will need to be 3.2 at the earliest as it’s a new feature) is just to paste [`DataObject::many_many()`](https://github.com/kinglozzer/sapphire/blob/1377-multiple-many-many/model/DataObject.php#L1974-L2063) and [`DataObject::belongs_many_many()`](https://github.com/kinglozzer/sapphire/blob/1377-multiple-many-many/model/DataObject.php#L1878-L1972) from [this PR](https://github.com/silverstripe/silverstripe-framework/pull/3799) into your DataObject subclass, rather than hacking core files. I’ve been using this on an internal project with any issues :)

**Comment by andrelohmann** [comment]
Hi, the Problem is not, that the dot notation isn't working on my relations. It is working very well. The only Problem ist the ModelAdmin, which can be fixed by my small core hack.

Also just subclassing ist not an option. My example with the big and small products is just an example, to point the kind of relations.

In my real world application, I have extended the Member object with serveral Relations (also to itself) to model Friendships, subscriptions and other member to member relations. Having subclasses here is not a viable way.

**Comment by kinglozzer** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/3799
