### ISSUE TITLE
CGI mode detection breaks install

### ISSUE THREAD

**Issue by colymba** [silverstripe/silverstripe-framework#3794]
Using the 3.1.9 release, I just tried to do a fresh install twice on our live server, but the install stops and fails when trying to detect URL rewriting "Friendly URLs are not working. This is most.....". The server runs PHP Version 5.4.35 with CGI/FastCGI enabled.

All seems installed but there is no way to access `/dev`, `/admin` or anything, getting a 404.

The errors comes down to the new basic auth rewrite rule added for CGI/FastCGI system. Added here https://github.com/silverstripe/silverstripe-framework/blob/b2ace2b76cf65f97d22e9591e2d393388ee86044/dev/install/install.php5#L1497
by this commit fbebf96d66d71f32766f84ef73a75d8e69910d8c

When removing this new RewriteRule, all goes back to normal. Maybe that rule should not be added automatically for all systems? Especially since this seems to be useful for test systems mainly?

**Comment by tractorcow** [comment]
I had to revert a similar change in the installer project because it broke mod_php https://github.com/silverstripe/silverstripe-installer/commit/4d8ab05f90e5d1d15e03334d0a6ffa2b29f6dd6c

I hadn't realised the custom code would break even on cgi installations. It's a shame since testing it locally didn't reveal this issue prior to release (since I'm using mod_php locally).

This PR will have to be reverted as well.

**Comment by tractorcow** [comment]
This issue has been fixed and will be included in the 3.1.10 release, which will possibly be in Feb.
