### ISSUE TITLE
GridField and DataObject canView()

### ISSUE THREAD

**Issue by NGlasl** [silverstripe/silverstripe-framework#3831]
If you have a GridField containing any DataObject with a canView() resulting in true, everything is perfectly fine as you would expect. However, when the canView() results in false, you end up having items that are **suppressed** from the view. They aren't actually removed, but more so hidden, and therefore introduce a number of issues..

Firstly, you basically end up having the GridField show "no items found" which is correct, however you'll see something like "view 1–15 of 100" displayed at the top. Secondly, if you're using the export to CSV button, you'll actually have the complete 100 items exported.. completely bypassing the permissions in place.

I understand that there's some performance issues to take into consideration with regards to permission checking, however something like this seems completely fundamental to me. I think this needs some attention in the near future, as I have also encountered similar issues when using full-text search pagination out of the box (as noted in #2791).

**Comment by wilr** [comment]
I agree and it's misleading. Pagination would require more thinking but the CSV export missing canView() is much more vital (#3845).

**Comment by NGlasl** [comment]
Nice work covering off the export canView() issue. Since the main problem has been corrected, I'll close this off for now. However, it seems like the pagination will require some work in the future.

**Comment by talbet** [comment]
Is it possible to reopen this and look at what it would take to fix the pagination issue?

On initial inspection it appears that the all `GridField_DataManipulator` inheritor classes, such as `GridFieldPaginator` receive a list that hasn't been filtered by `canView()`. 

This is expected and reasonable, but when using extensions like 'Lumberjack' and 'Restricted Objects' together, you start to get gridfields where the expectation is to see a paginated list of pages that can be viewed, but instead get a paginated list that says "no items found" because the viewable pages are not condescend to the first paginated page.

Changing this behaviour would almost definitely have performance implications, but might be necessary for sites with complex `canView()` behaviours and enterprise-ish admin permissions.

**Comment by dhensby** [comment]
@talbet it's definitely worth looking into this issue but I'd rather (you) open a new issue than us re-open this old one? This old one is part solved and doesn't offer any helpful context
