### ISSUE TITLE
Add Sqlite3 cache backend

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#3863]
Since most servers prefer to use Sqlite3 over the "old" Sqlite, why not add Sqlite3 cache backend?
https://github.com/gencer/zend-cache-sqlite3

As far as I've tested, it passes all tests.

**Comment by chillu** [comment]
You mean for `SS_Cache`? There's `Zend_Cache_Backend_Sqlite` already, basically only because it comes packaged with `Zend_Cache`. The library you're linking to is written by a single dev, untested, three years old and already showing signs of decay (the blog entry it links to is deleted). Given that you should be able to drop in this library to existing SilverStripe projects via composer autoloading or a `require()` call, I don't see the need to add this to core.
