### ISSUE TITLE
Escaping quotes in the CSV export for Excel

### ISSUE THREAD

**Issue by Ben-Speakman** [silverstripe/silverstripe-framework#3895]
I am having some issues with the CSV export and Excel. 
On line [152 of GridFieldExportButton](https://github.com/silverstripe/silverstripe-framework/blob/3.1/forms/gridfield/GridFieldExportButton.php#L152) quotes are escaped with `\"` but it is [recommended](http://stackoverflow.com/a/216623/908257) to use a double quote `""`. Is there any reason that the slash quote is used here?

Happy to submit a PR but just wanted to check there was no specific reason as it seems to work fine in Openoffice etc just as well.

**Comment by dhensby** [comment]
You're indeed correct and that should be fixed.

To be honest, I think the core needs a central library for doing CSV <-> Data as this is a fairly useful function to have in the core and should be implemented consistently.

This is a little CSV formatter I've been using (though it's a bit flawed) https://gist.github.com/dhensby/69456d2f7f0f57ab288f

I've seen https://github.com/goodby/csv which could be a dependency we introduce to do CSV properly.

In the mean time, I'd welcome a patch to that file.

**Comment by Ben-Speakman** [comment]
Agreed about the CSV function. Its a very handy feature.

**Comment by JorisDebonnet** [comment]
I only just noticed that this issue is now fixed. I had originally reported this issue about a year ago in #3408 (and fixed with #3411). But I notice that this patch did not update GridFieldExportButtonTest.php to test for correct " escaping, which my PR did :)

Anyhow, please note that there is no real need to write or use custom csv libraries, as php already has `fputcsv`. I remember I even ended up using `fputcsv` in my #3411 fix. So actually,.. wouldn't that PR still be a more robust fix? :)
