### ISSUE TITLE
ClassInfo::implementorsOf() doesn't return all classes that implement an interface

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#3915]
Classes that descend from other classes that implement an interface don't get returned as "implementors of".

eg:

``` php
class MyClass implements HiddenClass {
}

class MyChildClass extends MyClass {
}

ClassInfo::implementorsOf('HiddenClass'); //just returns MyClass
```

**Comment by sminnee** [comment]
In the places that it is used, the current behaviour is probably more appropriate.

For example, if we define`LeftAndMain::providePermissions()` we don't want it calling the identical method on every subclass.

I would suggest that we add a flag to allow for Dan's suggested behaviour rather than just changing it.

As such, marking as enhancement.

**Comment by sminnee** [comment]
#wontfix

**Comment by michalkleiner** [comment]
There's a way how to check if the class has any subclasses and only call the method on the youngest child.
I had to do just that as I don't want to trigger the method on all implementors.

However, I just found that the method doesn't return any classes that implement an interface IntB when looking for implementors of IntA (and IntB extends IntA).
