### ISSUE TITLE
ViewableData::defineMethods() wasting memory?

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4063]
https://github.com/silverstripe/silverstripe-framework/blob/1db08bac88f9330dc4e6dda1ae08628f245a5212/view/ViewableData.php#L177-L183

This is run for every subclass of `ViewableData` that’s called during a request, fetching and then iterating over every single method of every class! I can’t find this caching behaviour documented anywhere, looks like it’s probably a pre-open-source relic? Either way, given that it’s using around 1mb of memory, I think it should probably be removed...

[Before](http://i.imgur.com/FrPEpoY.png) and [after](http://i.imgur.com/F9B8bp7.png) XHProf

**Comment by tractorcow** [comment]
That's a nice performance increase. :)

This is one reason I'd love to have dynamically assigned traits instead of extension methods. _call no longer has to do all the hard work. But, 4.0 land. :)

Does viewable data even have the chance to call defineMethods from the failover? During construction of the object that variable isn't even assigned is it?

How many methods match the second part of the function, which are prefixed with a single underscore? Is this a template pattern that SSViewer relies on?

**Comment by kinglozzer** [comment]
> Does viewable data even have the chance to call defineMethods from the failover? During construction of the object that variable isn't even assigned is it?

`defineMethods()` is called right at the end of `Object::__construct()`, and subclasses [seem to](https://github.com/silverstripe/silverstripe-cms/blob/7f1f6156347d6e5c6135d12b35090368bad94188/code/controllers/ContentController.php#L46) set the failover before calling `parent::__construct()`, so I think the failover object is available at this point. Using `?debugfailover=1` seems to indicate that too

> How many methods match the second part of the function, which are prefixed with a single underscore? Is this a template pattern that SSViewer relies on?

I can’t find any in core that it’s even possible to use from a template. `_t()` matches the convention, but that’s a special case that wouldn’t hit this method.

If there’s a BC risk, we could always change the method to something other than `cachedCall` that triggers a deprecation notice before calling `cachedCall` and remove this in 4.0?

**Comment by kinglozzer** [comment]
Closed in https://github.com/silverstripe/silverstripe-framework/pull/5232
