### ISSUE TITLE
Versioned::get_latest_version of published page

### ISSUE THREAD

**Issue by blpraveen** [silverstripe/silverstripe-framework#4075]
Get Latest Version returns latest version unpublished.

          Versioned::get_latest_version('SiteTree',$ID);

How do I get the latest Version Published/live?

**Comment by kinglozzer** [comment]
Hey @blpraveen,

Github is used for tracking bugs, not for getting code support.

It’s probably fetching a draft version because that’s the stage you’re currently viewing. I’ve not tested this, but I believe this should work:

```php
$oldMode = Versioned::get_reading_mode();
Versioned::set_reading_mode('Stage.Live');
$latestVersion = Versioned::get_latest_version('SiteTree', $ID);
Versioned::set_reading_mode($oldMode);
```

I’ll close this for now. If you think there’s definitely a bug, please re-open this issue :)
