### ISSUE TITLE
Tree view sometimes fails to load nodes, or sorts them incorrectly

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4137]
I’m having a really difficult time tracking down the exact cause of this issue...

The site in question has ~100 pages, no modules that interfere with any of the tree view or hierarchy logic. The issues I’m experiencing are:

- If I hard-refresh while editing a page that’s 2 levels deep, it appears at the bottom of the list (i.e. last in the sort order, even though it definitely isn’t last).
- If I hard-refresh while editing a page that’s 3 levels deep, the tree view appears briefly, but is completely collapsed, and then it hides itself entirely - collapsing the very top-level “node” that is the site title.

Uncommenting [this line](https://github.com/silverstripe/silverstripe-framework/blob/d6e1c5131c299df549c3c407d9063c5faa7beb54/admin/code/LeftAndMain.php#L824) fixes both issues, I don’t know the `Hierarchy` class well enough to understand why this was commented out originally. According to @stojg in #3309:

> when it tries to find a deleted page, it flushes the DataObject cache and the that chains to hierarchy flush as well. This throws away all work done previously in markPartialTree

Difficult to reproduce. I managed to reproduce it on a blank install by adding around 50 pages (no particular structure, dotted around at different levels), then editing a page that’s 4-levels deep.

**Comment by stojg** [comment]
His is a really tricky issue. I've spent a lot of time trying to understand the core issue, but never got there.

Part of the problem is that the code execution bounces between sitetree, versioned, hierarchy (if I remember it correctly) and it's really hard to debug because of a combination of caching, lot of objects and Ajax. 

So depending on the view mode (published, show deleted etc), the amount of eager loaded nodes- its neigh impossible to figure out all the edge cases with the current solution.

I'm afraid that fixing this specific issue will break something else, unless there is some serious rethink about how this implemented.

**Comment by jonom** [comment]
@kinglozzer I think this is the same issue: https://github.com/silverstripe/silverstripe-cms/issues/1135

I provided a DB dump and instructions to replicate the issue if it helps: http://cl.ly/2T0f2g1K0E22

**Comment by kinglozzer** [comment]
Yeah looks like the same issue, for now I’m just using a (pretty awful) workaround: https://gist.github.com/kinglozzer/b46fabc5adc5d95095b1
