### ISSUE TITLE
Int can't be a class name in php 7

### ISSUE THREAD

**Issue by g4b0** [silverstripe/silverstripe-framework#4271]
Trying to run SS 3.1.13 on a php7 box I get this error:

Fatal error: "int" cannot be used as a class name in /vagrant/tribedistribution.zk/framework/model/fieldtypes/Int.php on line 8

**Comment by tractorcow** [comment]
Possibly we'll need to resolve this in 4.x when we move to namespaces.

Can SilverStripe/Framework/Int be a namespaced class?

**Comment by simonwelsh** [comment]
No. Classes can't be named after keywords.

**Comment by kinglozzer** [comment]
Same issue applies to `float` keyword. How about `SilverStripe/Framework/Integer` and `SilverStripe/Framework/FloatingPoint`?

It’s either that or `SilverStripe/Framework/Floater` :hankey:

**Comment by jonom** [comment]
> It’s either that or SilverStripe/Framework/Floater :hankey:

First time I've ever LOL'd at a github notification

**Comment by dhensby** [comment]
`SilverStripe/DBField/Int` is more likely to be the convention. Amirite @sminee @assertchris? 

If we can't even use int in a namespaced class, then we are going to have a bad time.

**Comment by kinglozzer** [comment]
@dhensby Yeah my examples were just rough, unfortunately we can't use int or float (or string or bool, but we don't use those anyway), even when namespaced. :(

**Comment by tractorcow** [comment]
`SS_Int`? Simon already pointed out you cant have a classname that's a keyword, even if it's in a namespace.

**Comment by kinglozzer** [comment]
It’ll probably come down to personal preference, my preference being to ditch the `SS_` prefix and name them something else - IIRC that prefix was only really added to work around namespacing. We’d end up with even less consistency:

- `SS_Int`
- `SS_Float`
- `Varchar`
- `Boolean`

`Int` -> `Integer` could work, but I don’t know what we’d do with `Float`. Unless we map `FieldType` to `SS_FieldType` internally?

**Comment by stevie-mayhew** [comment]
I think that re-classing them all as `SS_*` makes sense - we already have `SS_Datetime` which follows this convention? As you say though, personal preference :wink:

**Comment by jonom** [comment]
If they're all subclasses of DBField, I would prefer a prefix of DB than SS and use it for all of them for consistency.
DBInt
DBDate
DBVarchar etc.
Looks like there is already a `DBLocale` so there is a precedent :grinning:

**Comment by simonwelsh** [comment]
I'd suggest against using `Integer` as, while it's not in PHP7, it may become reserved later on. Same with `Double` and `Boolean`.

**Comment by dhensby** [comment]
Yes, we must be careful not to choose words that are obvious candidates to become reserved later (though not if it stifles progress), I'm against the `SS_` prefix as it's only been used as a pseudo namespace for clashing class names in the global namespace. 

Prefixing `DB` does seem most sensible to me at the moment. And it makes it much clearer what is a DB type rather than some other core class (like `SS_Cache`

**Comment by kinglozzer** [comment]
Yeah that’s a good point @simonwelsh, it probably is too risky to continue using those class names (I was pretty surprised that `bool` is reserved but not `boolean`!).

As long as we pick one convention and stick to it, I’m happy.

We’ll probably have many other discussions like this when work on namespacing kicks off again :stuck_out_tongue_closed_eyes:.

**Comment by dhensby** [comment]
cc @assertchris

**Comment by assertchris** [comment]
@dhensby at this point my opinion will only entertain. You probably know my feelings on naming classes after words-that-we-should-have-assumed-were-going-to-be-reserved-words...

**Comment by sminnee** [comment]
My inclination here would be to rename all the classes to have DB as the prefix (as well as a namespace) to match `DBField`, and then probably to provide some mapping that defines the values that go in the `$db` array, so that people don't need to specify (fully qualified) classnames there.

Something like:

    DBField:
      type_mapping:
        Int: SilverStripe\Model\FieldType\DBInt
        Varchar: SilverStripe\Model\FieldType\DBVarchar
        ...

I think that having an explicit map table would probably be less frustrating than any kind of magic like auto-dropping namespaces or auto-dropping the `DB` prefix.

We may run into issue if we have two module each of which map a different class to the same string. One solution for that would be to allow module-specific mappings, but it could get kind of complicated. We couldn't really leave it up to the app developer to re-map if they use conflicting modules, as it would require patching those modules. Alternatively, we could discourage the use of short values for custom field types used in modules.

If we were to go for module-specific mappings, my inclination would be to do this within the config system, allowing specific configurations that are applied to a sub-set of classes, maybe through injection.  A config system that sets up DI patterns for injecting config objects into classes is a bit circular, but not necessarily unworkable.

**Comment by assertchris** [comment]
@sminnee <3

**Comment by tractorcow** [comment]
I was thinking about something similar to this, but how about a generic `uses` config that's applied at the dataobject level, and can be used for classes outside of just DBField?

```
class DataObject {
    private static $uses = array(
        'Int' => 'SilverStripe\Model\FieldType\DBInt',
        'Member' => 'SilverStripe\Model\Security\Member'
    );
}
```

Our expectation is that we would be able to reference any namespaced class or DB field without having to specify the full namespace in every use case. User code should also be able to alias their own namespaced classes (or even override existing aliases).

**Comment by sminnee** [comment]
Yeah, that's pretty close to what I had in mind. The biggest differences that I see:

 * The config is applied to DataObject, not DBField. That makes sense because it affects the behaviour of DataObject, not DBField
 * It could apply not only to DBField references, but also to DataObjects referenced in has_one, has_many, many_many, and belongs_many_many. :+1: from me!
 * Rather than allowing custom config for a module or for an arbitrary set of classes, it follows the class hierarchy. I'm not convinced that this would necessarily be ideal, but it has the advantage of existing now without requiring Config refactoring.

I'd support Damian's approach, and then shunting out module-specific, injected configuration to a separate issue to pick up some stage in the future. The nice thing is that, as long as long as we heavily recommend that people access config with `$this->config()` over `Config::inst()`, it shouldn't have too heavy an impact on site/module developers' code.

The only thing I dislike is the name `$uses`. It's a little *too* generic for my liking.

**Comment by tractorcow** [comment]
I think this discussion should go over in the "namespaces" issue at https://github.com/silverstripe/silverstripe-framework/issues/3548, since this is a pretty significant decision in how namespaced objects are to be supported.

**Comment by sminnee** [comment]
Fair call, we probably want to pull together an RFC to get our thinking in order.

**Comment by dhensby** [comment]
The manifest has (or will have, can't remember state of PR) a function to determine the fully qualified namespace of a class depending on the namespace and other imported namespaced classes (`use` keyword). We could use this to allow a more "native" feel like so:

```php

<?php
namespace MyProject\Model;

use SilverStripe\Model\DataObject;
use SilverStripe\Model\FieldType\DBInt as Int;
use SilverStripe\Model\FieldType\DBVarchar as Varchar;
use SilverStripe\Model\FieldType\DBDatetime as Whatever;

class MyObject extends DataObject {

    private static $db = array(
        'Title' => 'Varchar(255)',
        'ViewCount' => 'Int',
        'PublishedOn' => 'Whatever',
        'OtherType' => 'SilverStripe\Model\FieldType\DBEnum("one,two,three","three")',
    );
}

```

**Comment by sminnee** [comment]
OK I've done a PR for this here: https://github.com/silverstripe/silverstripe-framework/pull/4551

I've gone with a simple solution for class mapping: use Injector. Less code wins, at least for the first PR.

**Comment by sminnee** [comment]
Also related, I've put together an RFC at #4562.

**Comment by sminnee** [comment]
This was resolved in #4551

**Comment by mhenden** [comment]
Hey guys -- just struck this for the first time with a new sites running SS 3.4.0. How do I fix it??! Please??!

**Comment by sminnee** [comment]
Hi @mhenden, you could downgrade to PHP 5.6, or use the SilverStripe `master` branch. SilverStripe 3 can't work with PHP 7, sorry!

**Comment by mhenden** [comment]
Managed to downgrade. Whew!
