### ISSUE TITLE
DBConnector::previewWrite() a sub-optimal API

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4289]
I'm not entirely comfortable with the implementation and use of the `DBConnector::previewWrite()` function.

 * Every query function implemented on DBConnector sub-classes that performs a query must call `$this->previewWrite()`, break on a failure, or risk introducing data corruption—specifically, the database will be modified even if `?previewwrite=1` is enabled.
 * The `previewWrite()` function has a mixed purpose:
   * Determine if previewwrite mode is active
   * Determine if the current query should be blocked in previewwrite mode (i.e. is a write query)
   * Display a log message
   * Return a boolean requesting that the query is blocked

Because of the first point, this is a public API, and because the risk of getting things wrong is data-corruption, it's an important one.

I wonder if it would be better to push the previewwrite functionality into `Database` rather than `DBConnector`, and instead declare `abstract DBConnector::isWriteQuery($sql)` that just returns write if the current query is a write/schema-mod query?

Frankly, the previewwrite functionality as currently provided is a little ill-conceived, but that only strengthens my point: if it's baked into DBConnector rather than Database it will be harder to refactor/remove in the future, as every database back-end would need to be changed.

**Comment by tractorcow** [comment]
My vote is to remove it entirely in 4.0. Mimicking writes in an application may have unintended effects that could damage data or content (not all state is stored in the database). 

I wouldn't keep it unless we could demonstrate it added benefit.

**Comment by tractorcow** [comment]
In fact, a much better solution to having core hooks in DB code is to simply provide extension points and let users add their own.

I would propose, (once we move to an event system):
- Dropping params like previewwrite, showqueries, etc
- Add event hooks
- Document how users can control db classes using events

As it stands, my normal debugging regime is to add custom code to core classes anyway for testing. A lot of the time the core functionality isn't enough and it needs to be overridden anyway. Let's support developers ability to customise the behaviour instead of trying to solve it for them. :D

**Comment by sminnee** [comment]
I think that DBConnector::isWriteQuery() could be preserved in 4.0 (it's just an information query) but the ?previewwrite=1 functionality can be pulled out if we decide that's best.

This strengthens the importance of removing the existing previewWrite() function from the 3.2 code.

**Comment by tractorcow** [comment]
Moved to SS_Database in https://github.com/silverstripe/silverstripe-framework/pull/4288

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4288
