### ISSUE TITLE
Resampled prefixes (e.g. SetWidth400) in folder instead of filename

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#4295]
When people download a picture from a SilverStripe website, they've got a high chance of it having a prefix such as SetWidth400- or SetRatioSize800800- etc, before the actual filename. Those prefixes don't mean anything to them, it all looks very code-ish, people don't like it. 

There's actually a pretty simple solution for it: instead of the resampled files going into `_resampled/SetWidth400-[filename]` they could go into `_resampled/SetWidth400/[filename]`. The URL is still just as unique, but when people download it, they get the original sense-making filename. 

Is this already possible? If not, can we make it possible, perhaps even the default? It's prettier and no one gets hurt! :)

**Comment by jonom** [comment]
I really like this idea, especially since image filenames are going to look even worse in 3.2 onwards due to the arguments being encoded.

An example filename from 3 branch is `ResizedImageWzEyMDAsODAwXQ==-Sample-IMG-Apples` so would just have to make sure that those encoded arguments will always be safe for directory names. On my machine it looks like the arguments are always alphanumeric except for the `=` signs. I tested the `/Uploads/_resampled/ResizedImage/WzEyMDAsODAwXQ==/Sample-IMG-Apples.jpg` structure and it worked fine so I'm definitely keen to see this idea explored more!

**Comment by JorisDebonnet** [comment]
Wow, I didn't even know about that 3.2 change yet! Let's hope we can make this change land before a release candidate is released then. I'll see if I can do what it takes...

**Comment by jonom** [comment]
I think @tractorcow is aiming to get 3.2 beta 1 out within the next week... Good luck! :+1:

**Comment by jonom** [comment]
I think @tractorcow was aiming to get 3.2 beta 1 out within the week - good luck! :+1: (no sarcasm)

By the way there was [some debate](https://github.com/silverstripe/silverstripe-framework/pull/4229#issuecomment-105918366) about whether changing filename output constitutes a breaking change, don't think we reached a consensus. I take the side that this should be okay, because the API doesn't make any promises about the file path for the images that will be generated. Plus in this particular case going from 3.1 to 3.2 the argument encoding is already changing the filenames of all resampled images, and I renamed a bunch of image methods, so it's already pretty jumbled up :)

**Comment by JorisDebonnet** [comment]
Right, this has an effect in quite a few places, and I see those encoded arguments have already been in the codebase for two years: since 2013-04-24, 5fbb3da by Nico Haase, if I'm seeing this right. I guess everything from that commit would have to be checked. The most simple change would be if the - was replaced with /, and then ensure any filename pattern matches still validate, and the folders are created when necessary. 

Too much work for me to do right now ... anyone more used to that code willing to change it? If not, I'll try and dive into it another time.

**Comment by JorisDebonnet** [comment]
There's also the chaining of methods that could probably be more easily handled if we just use 1 level of folders, such as `SetWidth123456SetHeigh123456/filename.jpg` rather than `SetWidth/123456/SetHeigh/123456/filename.jpg`. I personally think 1 folder level for the methods-and-arguments-part would be fine.

**Comment by jonom** [comment]
I couldn't look at it until next week and not too familiar with the caching/chaining code so not confident I could get a solid solution together quickly. So probably will need to target 4.0 with this change unless someone else is keen to look at it.

**Comment by jonom** [comment]
Or 3.3... I always forget there will be a 3.3 :)

**Comment by JorisDebonnet** [comment]
I'll just go for it anyway. I'll sleep another day! :)

**Comment by tractorcow** [comment]
If it can be made semver compliant we could put it in a 3.x version, but otherwise it's safe to assume we can put this into 4.0 ;P

My gut feeling says a new folder structure for resampled images probably won't make it into 3.x since it could break user code that relies on the current structure.

You might have noted that we now have 3.2 branch; So anything you want to go into 3.3 can go into the current 3 branch.

Get some sleep; It's so important! :D

**Comment by JorisDebonnet** [comment]
... but I really really want to avoid getting those new scrambled filenames! :) It's fine for thumbnails or images that are part of a design, but larger images that may be downloaded by visitors... shouldn't have terrible looking filenames, in my opinion. 

I'm getting a pretty good grasp at it actually, I'm confident I can finish this. I guess the only remaining question then is whether any application would break due to *this* change, and would *not* have broken because of the other changes that are already planned to be released (base64 arguments and some new generator names).

**Comment by tractorcow** [comment]
You could make the behaviour configurable, and simply ensure the default behaviour is as per the current one.

**Comment by JorisDebonnet** [comment]
I guess that would be the safest option, then people just keep using the `SetWidth400-` format by default. 

I've also figured that `Image::regenerateFormattedImages` does not regenerate images that were transformed with the "old" filenames. It would probably be nice for upgrading if it *did*, otherwise people may get images-not-found on their pages. 

Does anyone actually remember why the arguments are to be base64-encoded? What's wrong with leaving them as numbers (and the occasional background color)?

**Comment by JayDevlin** [comment]
Hello. I have a module for this and its working seamlessly with vanilla image regeneration. I thought about configurable filenames too. It's easily doable, but decided against it at the time because of possible misuse. 

Have a look:
https://github.com/JayDevlin/silverstripe-module-rsimage

**Comment by JayDevlin** [comment]
@JorisDebonnet 

I don't like the json/base64 encoding in filenames either. Apparantly, in 5fbb3da661248d277af78073c12adae1ddf93808 someone fixed a bug for cached images who were generated in multiple steps. E.g. $image->setWidth(444)->setHeight(333). But I don't really see what his issue was exactly. But I fixed a issue in 3.1 with paddedImage in 552b54201a617690e75f2792391ba054ea77dd16 which is probably related since he had a test for paddedImage too.

**Comment by jonom** [comment]
I think it's important to encode the arguments - maybe the bundled Image methods use simple numeric arguments but SilverStripe is a framework and you should be able to create image methods that accept arguments like `20%`, `-1` etc. and know that a safe filename will be produced. Plus encoding them takes care of this problem: https://github.com/silverstripe/silverstripe-framework/issues/3710 It's a pity it's at the expense of readability for developers but think that is trumped by the need for foolproof filenames. 

I don't think users will be particularly put off by the filenames if they've ever downloaded a photo from Facebook, Pinterest etc. - just downloaded one of my photos from Facebook and it was called *11393395_10152953531797817_1144883728408018240_o.jpg*. :neutral_face: 

All that aside I still think it would be great to follow this through and use the encoded arguments for a directory name rather than in the filename. @JorisDebonnet I agree there's probably no benefit in nesting directories e.g. `/method/args/method/args/image.jpg`. `/method-args-method-args/image.jpg` should be fine.

**Comment by jonom** [comment]
@JayDevlin that module looks like a great start for this! Personally I would like to see all the images continue to reside in the `_resampled` folder though, within sub-directories names for the method/args.

**Comment by JayDevlin** [comment]
I'm totally ok with using a encoded string as the folder name for the cached image as long as the filename itself is clean. 
Something like ParentFolder/_resampled/awkwardbase64string/filename.jpg

The main purpose of my module was to provide a appropriate filename for Google Image search and I'd be happy if we had nice filenames in the framework too.

@jonom 
I agree with the _resampled folder. In retrospect, my little filesystem folder exception looks a little out of place.

**Comment by JorisDebonnet** [comment]
I will finish my suggested edits either tomorrow or on Sunday. `getGeneratedImages` is the main thing I still need to finish (since it now needs to search through directories recursively), but it doesn't even look like that much work. It will be `/method2-args/method1-args/image.jpg` if methods are chained by the way... not that I necessarily wanted to do the nesting, but it looked like the most straightforward way :)

**Comment by JorisDebonnet** [comment]
Happy to say I finished this! I clearly underestimated the amount of work (ended up taking about 10 hours of it), but the end is result is pretty clean code that supports, well, everything (chaining methods, regeneration, ...). This gave me more experience with unit testing!

I also fixed an issue in that original base64 implementation: base64 is not URL-safe since it may contain + and /. So it's using `base64url_` functions now, which I added at the bottom of `Image.php`... I wasn't sure where else to put helper functions like that.

**Comment by JorisDebonnet** [comment]
A short SemVer analysis then: 

* The URLs for transformed images change, but they already did that with that base64 implementation, so no change in that area. It doesn't cause any issues that weren't there before: any cached transformed images with the old filenames simply stay where they were, so it doesn't cause broken images. Unless people clear out their `_resampled` directory, but that causes issues before 3.2 too (namely: resized images in the CMS get hardcoded src attributes). 
* The new thing is: transformed images no longer reside in the same folder as their original image. This should be transparent to all users. The only thing I can think of is that there might be issues for those that heavily depend on how resampled images are saved, but again, the base64 change already moved them too. It shouldn't really matter whether they are in a different folder, unless someone specifically looks only in the same folder as the original image. But I honestly can't figure out a good reason to do that, you'd almost have to be hacking the framework. 
* Another thing perhaps is that all the transformed images have the same filename as the original file (they're only in a different folder). I guess this could be an issue if someone uses a manual search function to find a file and end up finding too many of them, but that would be silly since it's much easier to use SilverStripe's 'native' functions.

So all in all I think that creating the directory structure does not break SemVer any more than the original base64 implementation, so in my opinion it would be best to bundle this change together with that one (whether that's for 3.2. or later). People will only have an issue if they are heavily hacking into the Image caching system, and those kind of people will probably be careful when they upgrade to 3.2. anyway.

**Comment by dhensby** [comment]
Where's the PR ;)

**Comment by JorisDebonnet** [comment]
Oh, I thought it would automatically appear here because I referenced this issue from there. Anyway, it's #4328!

**Comment by JorisDebonnet** [comment]
So any thoughts about whether this should be included in 3.2? 

I can't actually find any reference to the changing of the addresses for transformed images in [the Changelog](http://docs.silverstripe.org/en/3.2/changelogs/beta/3.2.0-beta1), so perhaps something needs to be added there about that in any case. Even if it shouldn't have an impact on coding, it does change what is generated (and thus what visitors may see).

**Comment by jonom** [comment]
@JorisDebonnet's PR uses `base64url_encode()` instead of `base64_encode()`, so I think that by itself justifies putting this in to 3.2, if there's still time. We know that introducing encoded arguments in to the image paths is a potential SemVer issue but we seem to have agreed not to revert those changes, so if those are staying in I don't think there's any harm merging this for 3.2 - may as well combine these changes to image paths in one release, so if anyone is using image paths in a 'hacky' way they only have to update their code once.

**Comment by dhensby** [comment]
Does anyone have any insight into why base64 encoding a filename is a good idea? I don't really understand the point of it and (as is raised here) it's meaningless (to people) and makes the files unrecognisable for manual debugging purposes...

**Comment by JorisDebonnet** [comment]
@jonom explained [above](#issuecomment-113191597) that the benefit of encoding the image formatting is to allow method arguments with characters that may mess up a URL (such as 20%, #fff, etc). I do agree it looks meaningless to people though, and that's precisely why I made it so that the filenames themselves are at least free of it, and the 'meaninglessness' only appears in the folder structure anymore (the filenames are simply identical to those of the original images).

**Comment by JorisDebonnet** [comment]
Might we get any milestone tag on this? :)
(see my comment on the [pull request](https://github.com/silverstripe/silverstripe-framework/pull/4328#issuecomment-124552432))

**Comment by tractorcow** [comment]
I've been told off for too-liberally applying milestones, actually. :) In future we'll wait until we are 100% sure before applying them. It might be better to apply this to the PR itself in fact.

**Comment by JorisDebonnet** [comment]
I redid this against the 3 branch in #4507.
