### ISSUE TITLE
Back button doesn't trigger, "are you sure you wish to leave this page?" confirm

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4419]
* Load admin/pages
 * Select a page
 * Make some changes, but don't press save
 * Press back button

You would expect the message "Are you sure you wish to navigate away?" to appear, but it doesn't. The reason is that this feature is called from `loadPanel()` in `LeftAndMain.js`, and that's not used by the back button.

Marking as critical as this can cause users to lose their work quite easily. The most frequent time this happens is when pressing backspace without a form field highlighted.

**Comment by sminnee** [comment]
It looks like the issue is that `loadPanel()` has the change-tracking functionality when it should be refactored into `handleStateChange()`. This will probably have quite a few side-effects and so is less likely to be low-risk; bumping to `change/minor`.

**Comment by tractorcow** [comment]
This is a pretty high priority bug; It has the potential to cause huge user discontent.

**Comment by tractorcow** [comment]
I'm looking for a solution to this now.

**Comment by tractorcow** [comment]
OK, here's what I have found.

When the back button is clicked, you CANNOT stop the browser from changing the url. It will automatically navigate to the url in the location field. However, it's entirely possible to interrupt the actual changing of content.

This gave me the idea of not aborting the navigation, but rather if a change is detected and aborted, restore (push) the last known state to the top of the history stack.

However, this doesn't work if this is the first navigation, since the "last" known state doesn't exist on the stack. It also means that the location bar temporarily displays the wrong url.

I wonder what an acceptable level of "strange behaviour" is? Is it worth allowing some strange url / history manipulation, if it means we can prevent unnecessary unsaved data loss?

**Comment by tractorcow** [comment]
@sminnee can you please check this and let me know what you think  is reasonable. :)

**Comment by sminnee** [comment]
It's critical to prevent data loss. Keeping URLs consistent is a nice-to-have against that. So I'd probably start by fixing the data loss issue and the URLs can be what they will be.

On the first page, the back button is already working. Deep link to a page edit and give it a go—it triggers the same behaviour as trying to close the browser.

So, ideally we could still update the URL in-place on second and subsequent pages. In my view I would try for an implementation and see what it's like? A flickery URL would be better than a wrong one.

**Comment by tractorcow** [comment]
Yep that's fine with me. :D I wouldn't expect we could get it correct in 100% of cases, but I can at least aim to make it behave predictably in 70% of cases and prevent data loss in 100% (which is the real aim here).

**Comment by dhensby** [comment]
So it sounds like this is a limitation in the history API?

If we see a popstate event and there are unsaved changes, we can fire off a `confirm` - if the user says not to navigate we don't run any of our AJAX and we just push the state back in?

**Comment by tractorcow** [comment]
Yeah that's what I will attempt to do;

**Comment by tractorcow** [comment]
Fix proof of concept at https://github.com/silverstripe/silverstripe-framework/commit/6376d86fc48dcb72fd1d6e2c649d85855b17dfe5

It needs browser testing before it's ready for a PR though.

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4458

**Comment by nzjoel** [comment]
Thanks guys! I look forward to utilizing this improvement!
