### ISSUE TITLE
Attempting to call Fields() on instance of SS_HTTPResponse

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#4592]
On a subclass of `AssetAdmin` in its `getEditForm()` method, I can call `parent::getEditForm($id, $fields);` and find it's possible for the framework to return an instance of `SS_HTTPResponse` rather than the expected `Form` if a `canView()` check up the chain in `LeftAndMain` fails.

Looking in `LeftAndMain::getEditForm()` checks are failing on line 1174 and I'm being returned an instance of `SS_HTTPResponse` rather than `Form`. This means I get the error:

`Fatal error: Call to undefined method SS_HTTPResponse::Fields() in /var/www/htdocs/my-project/cms/code/controllers/AssetAdmin.php on line 158`

**Comment by phptek** [comment]
Besides the fact that `LeftAndMain::getEditForm()` is documented as returning 'Form` which is not really true as it stands; a potential fix might be to return a Form but with an error message being displayed replacing any form fields.

**Comment by chillu** [comment]
So that's https://github.com/silverstripe/silverstripe-framework/blob/3/admin/code/LeftAndMain.php#L1209, right?

We should probably throw an `SS_HTTPResponse_Exception` at this point in the logic, and handle it more gracefully through `Security:: permissionFailure()` on the caller side of `getEditForm()`. The `permissionFailure()` call has the advantage of redirecting users to a login form, rather than showing a fairly generic/unhelpful error screen as `SS_HTTPResponse_Exception` would. `show()` would be a good starting point for this. We want to avoid duplicating the `$record->canView()` call though - is that cached? Sorry, no ready-made solution here, just providing some pointers :)

**Comment by phptek** [comment]
@chillu thanks for the response.

L1209 correct, yes :-)

Totally get what you're saying re: login screen, I'll refactor a new PR and let you know

**Comment by phptek** [comment]
@chillu OK, different, less jarring solution, which - technically speaking is correct as far as current phpDoc is concerned :-P

````php
    if($record && !$record->canView()) $this->redirect('/admin/pages', 403);
````
> The permissionFailure() call has the advantage of redirecting users to a login form, rather than
> showing a fairly generic/unhelpful error screen as SS_HTTPResponse_Exception would

Hmm but then your logic is moot if the user is already logged-into the CMS. What help would re-logging actually achieve, given that the route will have the BackURL parameter in there, potentially causing an infinite loop?

Thoughts?

**Comment by maxime-rainville** [comment]
LeftAndMain and AssetAdmin have changed too much since the issue was raised. This issue is probably not a factor anymore.
