### ISSUE TITLE
DataList::canFilterBy() does not consider joins

### ISSUE THREAD

**Issue by jakxnz** [silverstripe/silverstripe-framework#4633]
ArrayList::canFilterBy() doesn't check for properties of joined tables, and can return false incorrectly.

**Comment by kinglozzer** [comment]
I assume this refers to `DataList::canFilterBy()`?

**Comment by jakxnz** [comment]
Hey there,

I'm away between the 20th - 28th of March. I'm really sorry if this causes any inconvenience, though - please feel free to leave a detailed email for me to read on my return.

Happy Holidays!

If you're a spam message, I hope this auto-responder spams you back and I hate you. Otherwise, I look forward to getting in touch when I'm back!

Cheers,
Jackson Darlow
M +6421 0236 9109
www.jdinnovation.com

**Comment by jakxnz** [comment]
Hi @kinglozzer, yeah, sorry. Thanks for spotting. I did mean DataList::canFilterBy()

**Comment by tractorcow** [comment]
I would modify the premise of this issue to "DataList::canFilterBy doesn't respect relations on the base model", which is the qualification that SearchFilter subclasses actually respect.

When you filter by a relation, the join is added automatically via DataQuery::applyRelation(). I think it would be a bit much to make the filter API support arbitrary table joins that aren't relations, do you agree?

**Comment by jakxnz** [comment]
A DataList can successfully filter by contexts that encompasses arbitrary joins, so I would think it's canFilterBy() method should reflect that, wouldn't you?

**Comment by tractorcow** [comment]
Yeah, but that's a side effect of the fallback doing a non-table specific where condition, since it is unable to properly verify the model that backs that column.

See the comment in SearchFilter::getDBName()

It's not really preferred behaviour for the filter API to rely on this fallback any more than it needs to, since it runs the risk of hitting "ambiguous table" errors.

We can solve this problem a lot easier for "real" relationships, rather than arbitrary joins, which quite frankly, you should be joining on anyway. :P

**Comment by kinglozzer** [comment]
@tractorcow Are you happy to close this?

**Comment by tractorcow** [comment]
I suppose it hasn't had any action in a few years. If it's still an issue we can re-open.
