### ISSUE TITLE
Allow SVGs as an `Image` in `UploadField`

### ISSUE THREAD

**Issue by nickspiel** [silverstripe/silverstripe-framework#4670]
I opened a PR to allow SVGs as a File type: https://github.com/silverstripe/silverstripe-framework/pull/4669

As part of this I was going to allow SVGs for Image types as well but ran into a real deal breaker of an issue.

The image uploads fine but then throws an error:

"SyntaxError: Unexpected token <"

So it looks like the UploadField is doing some sort of parsing / validation of the file (probably to generate the thumbnail?).

It would ROCK MY WORLD if we could get SVGs to work as images in SilverStripe (most of my projects are now at least IE9+) it is just a little beyond my knowledge.

**Comment by tractorcow** [comment]
I think you should be able to upload SVG as a `File` dataobject, although sadly until GD supports SVG manipulations these will likely not be supported as `Image` dataobjects.

http://stackoverflow.com/questions/28361836/convert-svg-to-png-with-gd

**Comment by tractorcow** [comment]
Do you have a stacktrace to go with this error? :D

**Comment by nickspiel** [comment]
The CMS didn't provide a stack trace, just a red line of text near the image name. Will see if I can extract stack trace.

**Comment by tractorcow** [comment]
Ah, try installing xdebug? That normally spits out the trace. :)

**Comment by jonom** [comment]
I think ImageMagick supports SVG manipulations so that could provide a path forward for now - but to truly support SVG we'd have to change the concept of what an Image is in SilverStripe. Right now it means a raster graphic only, and converting an SVG to a raster (e.g. PNG) probably defeats the purpose of having an SVG in the first place.

@nickspiel you might like to take a look at [this discussion](https://groups.google.com/forum/#!topic/silverstripe-dev/cMRZ8HVe4Os) which relates to this issue. I'm suggesting that maybe we shouldn't have an Image DO type at all since a file may be able to be interpreted as a raster graphic in one environment but not another. It's not a file extension that determines this alone but also the contents of the file and the tools you have to read and convert the contents. I don't think it makes sense to make a distinction about whether or not a file is an image in the database layer, because these other variables aren't known at that level and are subject to change.

As a sidenote I don't love that we limit the types of files that people can upload or that can be downloaded from the assets folder. There are a lot of file types out there and we can't really know which particular types of files a particular website/app will want to manage. Could we blacklist some file extensions instead and have a similar level of security?

**Comment by nickspiel** [comment]
I totally agree with your line of thinking in that feed. 

"Who knows what formats will be invented and supported in the future too... I imagine it won't be long before Live Photos from the new batch of iPhones are being uploaded to SilverStripe websites."

Good to know this is being thought about :)

I was thinking SVGs at this stage, but while we are at it, might as well have a good think about other (possible) formats too. 

I will keep my fingers crossed for some progress on this as it is a little beyond my skills to be able to provide any insight on how to actually make this happen.

**Comment by dhensby** [comment]
fixed by #4669
