### ISSUE TITLE
HTML Editor Shortcodes don't work for images

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#4678]
Because if we embed `<img src="[file_link id=4]" />` the preview area doesn't know how to display the image to the content editor.

**Comment by jonom** [comment]
I think shortcodes have long been a powerful but under-utilised feature because they're not user-friendly - too much like 'coding' for most CMS users. Maybe this is a good opportunity to establish a reusable pattern for rendering shortcode content in the editor and making it editable through a form? I've outlined a possible approach for this here, would love if you could take a look: https://github.com/silverstripe/silverstripe-framework/issues/4337#issuecomment-126009280

**Comment by sminnee** [comment]
That's a fair point, @jonom, however, this issue was more narrowly focused. In particular, I that a form for editing the shortcode would be a bad idea for media insertion—the change requested by this issue should be invisible to the user; it's just a leftover issue from some of the about-to-be-merged filesystem work.

**Comment by jonom** [comment]
Yeah fair enough - wasn't sure how much work would be required to fix this narrow issue, so if substantial work is required just thought it would be worth keeping this idea in mind. I didn't mean to imply that it would have to return a simplistic/generic form either - I was imagining in the case of media that it would behave the same way it does currently, but if we could define this behaviour in a reusable way it might lead to people embracing shortcodes more. Something to consider for the future maybe.

**Comment by sminnee** [comment]
A piece that relates to this ticket: Having a facility for shortcodes to be transformed to and from placeholder content would be nice. We already have some kind of API for this (the oembeds use it), but I'm not sure how easy to use / well documented the APIs for this are.

**Comment by tractorcow** [comment]
Yikes, this is a duplicate issue then. I'll close this in favour of #4337 . Sorry @jonom :D I'll add this as a continuation of that discussion rather than a separate one.
