### ISSUE TITLE
Resampled images not moved when main image moved to new folder

### ISSUE THREAD

**Issue by SpiritLevel** [silverstripe/silverstripe-framework#4685]
I'm not sure if this is a bug or desired behaviour!

To reproduce: Edit an uploaded image, use the folder dropdown, select a different folder, then click save.

The main images moves to the new folder but the resampled versions stay in the original folder. From my point of view, ideal behaviour to me would be that the resampled images move as well as the main one. At the very least, it seems to me that the resampled images should be deleted from the original folder ?

**Comment by jonom** [comment]
Hey @SpiritLevel, what version of the CMS are you using? This has been refactored from 3.3 onwards I think as a by-product of some great work from @JorisDebonnet. In any case I don't think what you're describing should have any negative effects. New resampled images will be generated as they're required so there's probably no great need to move them, and in <= SS3.2 (or possibly < 4.0) removing the resampled images from the original location would actually be harmful as any references to these images from HTMLText instances would be broken. Image paths will be stored as shortcodes from 4.0 onwards so that will fix that problem.

I'm going to close this but feel free to re-open it if you've still got concerns.

**Comment by SpiritLevel** [comment]
Thanks @jonom. I am using 3.2.0 for client work at the moment. The only negative effect I suppose is the potential accumulation of orphaned, resampled images. In any case, 4.0 will be here soon enough...I just thought I would let someone know; I'll watch out for this issue while experimenting in 4.0.

**Comment by tractorcow** [comment]
I'm not sure if resampled images in HTML content areas are going to automatically re-generate if they are linking to moved files.

All the better reason to move to shortcodes for images (4.0 work in progress) but thought I'd raise that query. ;D

**Comment by SpiritLevel** [comment]
Thanks for the heads up @tractorcow....I'll keep an eye on that too ;)
