### ISSUE TITLE
FormAction useButtonTag should be globally configurable.

### ISSUE THREAD

**Issue by bummzack** [silverstripe/silverstripe-framework#4723]
If a website-design requires `<button>` instead of `<input>`, it can be a huge problem to change all forms accordingly.

I'd propose a config flag on `FormAction` that allows setting `useButtonTag` globally (eg. via a static config variable).

Overriding individually using `setUseButtonTag` should still be possible though.

**Comment by wernerkrauss** [comment]
Isn't this configurable via template now in SS3.2 ?

**Comment by bummzack** [comment]
You're right. One could just as well create a custom template. In that case `useButtonTag` should be deprecated?

**Comment by jonom** [comment]
Converting FormAction::$useButtonTag to a config static is probably not a good idea because it could reach beyond your own code and affect the CMS and other modules whose styles and scripts might be relying on an input field rather than a button.

I don't think there's any need to deprecate `->setUseButtonTag(true)` it's more convenient than e.g. `->setTemplate('FormActionButton')` and has the advantage of being documented in the API - plus you would have to supply your own button template in that second example as both `input` and `button` rendering is handled in FormAction.ss currently.

**Comment by bummzack** [comment]
Fair enough. Overriding the `FormAction` template basically does the same (override globally).

**Comment by dhensby** [comment]
Hmm. So this basically would be opt out of button rather than opt in? I think it could still be worth fixing as it does sound useful. 

How would it break the CMS, though?

**Comment by bummzack** [comment]
I don't know how/if it would break the CMS ;) When I "globally" replaced `input` with `button` using a new template, the CMS didn't break. But I know at least one module that didn't work with `button` instead of the `input` tags, because of jQuery selectors… there might be others out there, so @jonom is right in this regard.

My initial thought was to have a global "preference" which tag to use, while still leaving the option to change it on single instances.
The default could still be `input` for backwards compatibility.

But as others have pointed out, you can just as well create a custom template… it just seems slightly inconsistent

**Comment by dhensby** [comment]
I agree. I think it should be configurable globally. Want to PR?

**Comment by tractorcow** [comment]
It could also break lots of js code and behaviour; E.g. "default action" behaviour when pressing "enter" when a field is selected.

I disagree with it being globally configurable. :)

**Comment by dhensby** [comment]
> E.g. "default action" behaviour when pressing "enter" when a field is selected.

How would changing from input to button break that?

> It could also break lots of js code

maybe - devs really shouldn't rely on tag names for selectors/JS :/

> I disagree with it being globally configurable. :)

justify?

**Comment by tractorcow** [comment]
> I disagree with it being globally configurable. :)

Because every permutation of a site configuration introduces another level of complexity that may break / affect the behaviour of other components in a site. If the "html tag" of a button is now configurable, then any other code (e.g. javascript) which once relied on a certain html element being present now needs to be updated to work properly with both. Will tabbing work the same? Will default form actions still work?

A second point is that buttons and inputs are not substitutable; There are accessibility considerations when choosing between which to use. E.g. you can put HTML into the body of a `<button></button>` tag, but not an `<input type="button" />` tag.

**Comment by dhensby** [comment]
Right, in light of recent core committee meeting :

This is a feature request. @bummzack are you prepared to take on this work and fix all the code regressions that rely on buttons being inputs? 

If not, we need to close this as a feature request.

**Comment by bummzack** [comment]
Thanks for the update @dhensby 

Since this feature is already available by some other means (overriding a template), I'd rather spend my time fixing/improving more important things.

I'll close this for now, then.

**Comment by dhensby** [comment]
Thanks
