### ISSUE TITLE
Injector service definitions should not inherit to subclasses

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#4774]
*sminnee says:*

Class Inheritance and Depedency Injection are two different extensibility paradigms. The labels in Injector should be thought of as service names, and should be decoupled from the class inheritance tree entirely.

------

Original:

I don’t really know what to make of this:

```yml
Injector:
  CoreService:
    class: MyCustomCoreService
```
```php
class CoreService extends Object {
}

class MyCustomCoreService extends CoreService {
}

class ServiceSubclass extends CoreService {
	public function foo() {
	}
}

// Object->__call(): the method 'foo' does not exist on 'MyCustomCoreService'
ServiceSubclass::create()->foo();
```

I understand what’s happening - Injector can’t find any configuration for `ServiceSubclass`, so looks to the parent class and uses that config - but I don’t really understand why. Injector was clearly built this way intentionally, am I misunderstanding/misusing it here?

Feel free to close if I’m being a doofus :)

**Comment by dhensby** [comment]
This is really interesting.

Imagine you want to override `DropdownField` to use `CustomDropdownField` and you add some behaviour.

What if you then have another class extend `DropdownField` (`AnotherDropdownField`)? We can't make that inherit from our new custom class, though `Injector` has been told `DropdownField` shouldn't be used...

It's actually a really tricky issue to determine correct behaviour for... As we can't even force `AnotherDropdownField` to inherit the behaviour of `CustomDropdownField` maybe we shouldn't even try, rather than just return a `CustomDropdownField`.

**Comment by sminnee** [comment]
The Injector is used to retrieve the objects corresponding to named services, and by default, the services are named the same as the class. In better/more-bloated architectures, the service is named according to an interface, rather than a class, and you load it with some implementor of that interface.

If you have a service named by a parent-class and you have requested a sub-class, it doesn't seem likely that you're wanting to grab a copy of the parent-class' service. So I'd call this a bug.

Even though it's a bug, since it seems possible that people might rely on the current behaviour, I'd put the fix into `master`.

----

The whole "inject CustomDropdownField into DropdownField" pattern doesn't mean "don't use DropdownField". What is means is "the DropdownField service is now provided by CustomDropdownField". It's easier for me to conceptualise if I imagine that I am injecting into a DropdownFieldInterface instead.

The pattern of class replacement use to be don with `Object::useCustomClass()` is a bit of a sloppy pattern and not great for extensibility precisely because it makes subclassing impossible. In any case, in Dan's example, AnotherDropdownField is unrelated to CustomDropdownField and we should avoid any suggestion that they they are at all related.

This whole issue is made more confusing by conflating services and classes. Injector deals in services, not classes. Admittedly the `<classname>::create()` syntax encourages us to think in this unhelpful way. We might want to clear up the docs on this.

**Comment by kinglozzer** [comment]
Thanks Sam, that all makes sense. I appreciate what you’re saying about blurring the lines between services and classes - correct me if I’m wrong but it seems to me that Injector probably wasn’t designed to swap classes out like this anyway, it’s just a by-product of having named services that has been (ab?)used ever since.

The `::create()` syntax does encourage us to think in terms of classes - as it’s inherently tied to classes that extend `Object` - and it’s impossible to use it with services that _aren’t_ named by classes anyway as you can’t do `MyServiceInterface::create()`.

Anyway, if it’s agreed that this is a bug I’ll look to fix it. Master does sound like the safest route (you can work around it by specifying `Injector.MySubclass.class: MySubclass` anyway). My initial and mostly untested idea was this: https://github.com/kinglozzer/sapphire/commit/dfa92fafc61df379e07139b0d39c65f0f841b075. When things are a little less busy I’ll look over it properly!

**Comment by dhensby** [comment]
I think this is a pretty crazy bug that should be fixed in current releases.

I don't see that devs rely on a descendant class being hijacked more than they rely on it not being.

Continuing the `DropdownField` example. If we override it, we don't expect all `CountryDropdownFields` to become my new `CustomDropdownField`. I don't see an instance where this is relied upon.

I, personally, think it should go into 3.2.x but if it's too "risky" I'd put it into 3.x at the latest. We should be that cautious, but not that cautious.

**Comment by sminnee** [comment]
I could live with 3.x, but I'm opposed to 3.2.x. Patch release upgrades should be able to be done in people's sleep; we need to tone down our enthusiasm for stirring stuff up in them—remember all the pain that the ClassInfo changes caused, @dhensby ;-)

**Comment by dhensby** [comment]
sure :(

**Comment by tractorcow** [comment]
I think it's a pretty risky change, so I agree with 3.x.

Just to confirm, we agree the fix is "service definitions don't automatically get inherited by subclasses?" 

Class A provides a service, as do classes B and C that both extend A.
We declare that Class A is provided by B using injector.

```yaml
Injector:
  A: B
```

Current behaviour:
- `C:create() instanceof B` // incorrect
- `A:create() instanceof B`
- `B:create() instanceof B`

Expectation: 
- `C:create() instanceof C` // correct
- `A:create() instanceof B`
- `B:create() instanceof B`

**Comment by tractorcow** [comment]
Anyone feel like implementing this fix, if I promise to review / merge? :P

**Comment by nyeholt** [comment]
Only just saw this thread of conversation... The 'inheritance' of configuration lookups was implemented to mirror some of the general Config paradigms that were already in place. I can't recall if there was a specific usecase that it was required for though.

**Comment by tractorcow** [comment]
I commented on https://github.com/silverstripe/silverstripe-framework/issues/5334; My main feeling is that it doesn't make sense to only inherit part of the config; It should probably be inherited fully or not at all.

**Comment by sminnee** [comment]
I wonder if it's better to say that DI and inheritance are mutually incompatible extensibility paradigms, and either:
 * throw a warning when people use Injector to instantiate a subclass of a base class that has been replaced with a new service
 * ignore all the configuration data of parent definitions, not just subclasses

**Comment by sminnee** [comment]
The latter option—"ignore all the configuration data of parent class Injector definitions, not just the class name"—is less likely to piss people off, but I'd say it's a major release change, since it's fairly fundamentally changing the behaviour of Injector.

**Comment by tractorcow** [comment]
@sminnee @kinglozzer please see https://github.com/silverstripe/silverstripe-framework/pull/5440 as an alternative.

I've stripped out all automatic inheritance, but have added an optional explicit inheritance feature for people who want to use it.

This should also solve the issue of having to duplicate all your injector configurations in https://github.com/silverstripe/silverstripe-framework/pull/5433
