### ISSUE TITLE
Should Convert extend Object?

### ISSUE THREAD

**Issue by jonom** [silverstripe/silverstripe-framework#4844]
Wanted to add a method to the Convert class with an extension (for convenience) but realised I couldn't as it doesn't extend Object. Any reason for that? I can submit a PR to change that if there's no reason not to?

**Comment by sminnee** [comment]
I don't think we should be relying on everything extending from Object, it's against SS4's goal of increased modularity and better interoperability with other frameworks.

I'm also unclear as to the benefit of adding an extension to a Convert, which is a bag of static methods. Can you just define the method on another class and call that? Extensions should be used to modify the behaviour of existing objects/classes, which I can't see happening with Convert.

If it's a case of "I want the method call to start with `Convert::` instead of `somethingelse::` I don't think this is a good reason: it reduces the clarity about which code is being executed.

**Comment by jonom** [comment]
> If it's a case of "I want the method call to start with Convert:: instead of somethingelse::

That's exactly the reason :) just wanted to keep the conversion methods together but what you're saying makes sense.

FYI case in point:
```php
// This doesn't currently work as Convert doesn't extend from Object.

/**
 * ConvertRaw2P class.
 * Apply this extension to the Convert class to access Convert::raw2p function.
 *
 */
class ConvertRaw2P extends Extension {

	/**
	 * Convert raw text to paragraphs.
	 * Preserve white space by replacing single line breaks with <br> and double 
	 * line breaks with paragraphs.
	 *
	 * Before:
	 * -------
	 * Hey this is a paragraph.
	 *
	 * And this is another one.
	 * With a manual line break.
	 * -------
	 *
	 * After:
	 * -------
	 * <p>Hey this is a paragraph.</p>
	 * <p>And this is another one.<br>
	 * With a manual line break.</p>
	 * -------
	 *
	 * @param string $text Text to convert
	 * @return string
	 */
	public static function raw2p(string $text) {
		$xml = htmlspecialchars(trim($text), ENT_QUOTES, 'UTF-8');
		$xml = nl2br($xml);
		return '<p>' . preg_replace('#(<br />[\r\n]+){2}#', "</p>\r\n<p>", $xml) . '</p>';
	}
}

/**
 * TextRaw2P class.
 * Apply this extension to the Text class to access $YourText.Raw2P in templates.
 *
 */
class TextRaw2P extends Extension {

	private static $casting = array(
		'Raw2P' => 'HTMLText'
	);

	/**
	 * Convert raw text to html and replace single line breaks with <br> and double 
	 * line breaks with paragraphs.
	 *
	 * @return string
	 */
	public function Raw2P() {
		return Convert::raw2p($this->owner->value);
	}
}
```

**Comment by robbieaverill** [comment]
I think this is a valid question/point. In my case, I want to modify the `raw2json()` method to add configurable JSON options (e.g. pretty printing for the sake of local API development visibility). I don't want to change the `Convert` name wherever its used of course!

**Comment by tractorcow** [comment]
Maybe we should make convert a singleton (thus can be substituted via DI).
