### ISSUE TITLE
[BUG/Enhancement] Renaming a file should keep it's extension

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-framework#4883]
When the user is given the option to rename a file, the user needs to add the extension as well.
I think it's better to give the user the option to rename a file, but append the extension (.jpg) manually. If a user doesn't add it, the file becomes unusable, because the extension is lost.

**Comment by jonom** [comment]
Hi @Firesphere are you talking about this dialogue or something else?

![screen shot 2016-01-03 at 11 39 58 am](https://cloud.githubusercontent.com/assets/1079425/12080438/cd919950-b20e-11e5-9dcf-ff4edebc428d.png)

I definitely appreciate your concern, I imagine some power users might like to keep the option to edit the file extension though so I think we'd either need to make sure this is still possible, or introduce a config setting to determine whether or not users can edit the file extension.

One option might be to split the filename field in to a composite field with one field for the name and one for the extension, which should be a backwards compatible upgrade safe for a minor version. Another option would be to lock the extension and have it displayed on the right of the filename field instead of within it, but this could disrupt some users' workflows so would need to be opt-in or go in to master as a breaking change.

I'd call this a feature request rather than a bug so per [contribution guidelines](https://docs.silverstripe.org/en/contributing/issues_and_bugs/) it should probably be closed unless you plan on turning this in to a pull request shortly?

**Comment by Firesphere** [comment]
Yes, it's that dialog. I'm not entirely sure, I'm ok with the renaming option, but the image shouldn't loose it's extension if the Filename was set without one, if you ask me.
I'd file it under bug, because if you're not entering the extension, it literally renames the file to "myfile", instead of "myfile.jpg". Which breaks the site if it's used in the frontend, like $Link, it works, but a lightbox for example, won't work because the filename is incorrect.

**Comment by jonom** [comment]
> I'd file it under bug, because if you're not entering the extension, it literally renames the file to "myfile", instead of "myfile.jpg"

I'd argue that's user error though. You're editing the full filename including the extension, so I think it's expected behaviour for the extension to be removed if you delete it. A bug would be if it behaved unexpectedly. I think the idea of reserving github issues for bugs is that we can stay focused on things that really need to be fixed, as opposed to improvements. This would be a nice feature, but since it's not critical and you're not able to turn it in to a pull request yourself at the moment I think it probably should be on UserVoice instead. This is just semantics about how to classify the issue though - either way it's definitely a good idea to protect against this :) 

> My preference would be, to lock the extension. It's not like the user would want to change it anyway.

An example where a user might want to rename an extensions is where they have `.jpeg` or `.JPG` and want to make it `.jpg`. Generally we can rely on files having lowercase extensions but sometimes they get through. Or if you have a `something.pdf.jpg` and it's actually supposed to be `something.pdf`. Or maybe somehow you ended up with a `something.jpig` in the system. It's probably not common that people will want to change file extensions but I don't think we can remove this capability and call it backwards-compatible.

> I'd go with a fallback method. If no file-extension is set, set the old file-extension, via a preg-match or something.

A fallback method should be okay but I don't really like to correct users input in the background without their confirmation - it can be really frustrating when this type of thing happens automatically if their is an edge case we haven't considered. Linux and Mac OS for instance don't really require files to have extensions so perhaps there are situations when users really do want to remove them? It's probably fine to introduce a fallback method but I think it would be safest to consider it a breaking change and introduce it in to master, just in case.

Another potential fix here might be to just add a bit of validation on that field that prompts people to confirm they want to change the file extension if they've tried to do so, and let them easily restore it to what it was before if they didn't mean to remove or change it?

**Comment by Firesphere** [comment]
Convincing arguments. All in all, I'd go for the last option. With the fallback option if the user isn't administrator.
Sorry to say, but you can't always rely on user intelligence. My experience tells me, a lot of the users that actually change/edit these files, are not really tech-savvy, they're just SEO-people and such and are unsure of what's going on in the backend. So they don't know that not adding the extension, might break something.

I think, the best solution would be, to make it the most complicated one? But that's a long-run update.
1. Anyone but the admin can edit the full name.
2. Anyone below admin can edit the name, but has to click a button to change the extension
3. If no extension given, and the user is not admin, give an alert
4. As fallback for anyone "lower" than a given edit-right, always add the extension and tell them to contact the administrator.

I know this is a very uncompromising solution, but my experience tells me, it's the best of both ways.

But, after reading your opinion and reasoning, I agree, it's not really a "bug", more a "feature that gives too many people the option to break things"

**Comment by tractorcow** [comment]
Could we use a bit of front-end validation, and have a popup confirmation if the extension is changed? It would be a good safeguard against error but not block explicit actions, even for admins.

**Comment by sminnee** [comment]
I like OS X's behaviour on this:

 * When clicking into the filename field, highlight the entire name except for the "." and the extension, so if you just start typing text, the extension will be preserved.
 * If you change the extension, show a warning dialog with as the two buttons "Change extension" or "Keep .PDF"

**Comment by jonom** [comment]
I think some kind of front-end validation might be the best bet, as that's un-intrusive and not likely to cause problems for anyone.

I like Mac OS X's behaviour too but I don't think javascript lets us select a segment of text in an text input, so we'd probably have to implement some kind of fake input that looks like a regular one - kind of like how editors like TinyMCE work. The idea of having two text inputs side by side is the low-fi version of this concept.

**Comment by Firesphere** [comment]
Well, javascript should let us select anything before the dot (an onfocus event?), but it's unreliable, since "myfile.awesome.jpg" would only select myfile. That would mean implementing some sort of object or array, having the allowed extensions and checking on those.
I'm not a fan of that. I've seen the CMS slow down to a halt on corporate machines. Adding more javascript and arrays to iterate would only make it even worse.

**Comment by jonom** [comment]
Oh you're right, I guess you can select a portion of text in an input. Example: https://jsfiddle.net/3wb6ot6e/

I don't think we'd need to limit the allowed extensions and it shouldn't be hard to get everything leading up to the last dot with a little regex or something, so I don't think it should cause a performance concern.

If we made it so that when you focus on the filename field, all the text leading up to the last dot is selected maybe this is enough protection against accidentally removing file extensions? It's better than what we currently have and not as aggressive as a validation message.

**Comment by Firesphere** [comment]
Sounds better than the current situation :) . The validation message with comparing the "extension" part, as per Sam's suggestion, might be a fallback for the future?

I'm still a slight bit unsure about the detection of that though, that should be tested, but that's also for future reference :)

**Comment by jonom** [comment]
Either or both solutions would be fine, the real question is 'Who is going to build this?' :) I guess we can leave this open for now and see if anyone volunteers

**Comment by Firesphere** [comment]
Hah, not me, I have enough stuff to fix at the moment. Maybe when I've settled in Wellington, I could have a look :) But that's at best 4 weeks from now.

**Comment by maxime-rainville** [comment]
This does not affect SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
