### ISSUE TITLE
Micro-RFC: Better whitespace handling in rendered templates

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#4896]
After the recent whitespace clean-up, I think that SS4 could do with a more considered cleanup.

My recommendation is that we change things such that whenever an HTMLText object is rendered into a template, the whitespace is removed.

Since HTMLText objects are returned as the result of template render calls, this will cover many use-cases, including:
- Form fields
- Layout templates
- The result of custom logic that involves template rendering
- HTMLEditorFiedl contents, such as `$Content`
- `<% include %>` tags

Since the trimming would happen when templates are assembled rather than when the HTMLText object is generated, the rendering of top-level templates that get sent to back to the HTTP client will include a trailing newline, which makes sense.

For completeness, I'd apply it to HTMLVarchar as well, although use of this class is much less common.

Does this make sense to everyone?

**Comment by jonom** [comment]
I think this makes sense. Can't really think of any scenarios where it would cause a problem.

**Comment by tractorcow** [comment]
>  the whitespace is removed.

Which whitespace? Leading and/or trailing? On a per-line or per-string basis? How about indentation? Do you want nested templates to inherit indentation?

Determining what is "top level" is hard, since what happens if a FormField::Field() result is sent as a "top level" string, e.g. via ajax?. You might have to enforce a trailing newline on every output, and then trim it manually when injecting it as a component of a parent template, maybe?

I think I need to get a clearer picture of the benefits we expect from this. Resulting templates will probably still be ugly, even after this fix, unless we just apply HTMLTidy across all output. :D

**Comment by sminnee** [comment]
> Which whitespace? Leading and/or trailing? On a per-line or per-string basis?

Trim leading & trailing on a per-string basis.

> Determining what is "top level" is hard, since what happens if a FormField::Field() result is sent as a "top level" string, e.g. via ajax?

Whenever an HTMLText is inserted into a template, the text will be trimmed. Whenever getValue() is used directly, the text is not trimmed. Thus, "top level" really means "accessed with getValue() rather than forTemplate()".

> I think I need to get a clearer picture of the benefits we expect from this.

The relationship between template variables and resoling HTML will be clearer, despite the use of trailing newlines in template files.

If you have a template that looks like this:

    Something
    $AVariableThatReturnsOneLine or <% include ATemplateThatReturnsOneLine %>
    SomethingElse

The resulting output will be 3 lines, with text one each line, regardless of the trailing whitespace included in each file.

**Comment by tractorcow** [comment]
Ok, that makes sense. :)

Hm, I wonder if another (perhaps simpler) place this could be done is in DBField::forTemplate()? Since we use HTMLText for templates, don't we? It's probably the place closest to output (which is typically where we prefer text manipulations) where we could safely trim whitespace.

**Comment by sminnee** [comment]
Yes, that would be a good potential implementation, or even just StringField::forTemplate(), although I would probably still structure a test suite to be more along the lines i've described the RFC. That is, I would test the result on rendered templates, not just on the output of forTemplate().

**Comment by sminnee** [comment]
It would be good to get input from a couple of other core committers before pushing the PR.

**Comment by kinglozzer** [comment]
Why do we need to do this? I understand the example in the [comment above](https://github.com/silverstripe/silverstripe-framework/issues/4896#issuecomment-169514564), I’m just not really sure why it matters - is it just to make unit testing easier, or is it an aesthetic choice (or both)? I can’t see any strong reason why we *shouldn’t* do this, though. Unless it’s possible that someone out there would want that extra whitespace that we’re proposing removing (though I can’t imagine why).

If we’re going to do this, however, then I don’t think we should put it in `StringField::forTemplate()` - what if a CMS user intentionally adds a trailing newline to a textarea? I think this should be kept at a template-level if at all possible (i.e. `SSViewer` or something) rather than affecting DB fields.

_Aside: should we really be using DB fields like `HTMLText` to render templates anyway?_

**Comment by tractorcow** [comment]
> Aside: should we really be using DB fields like HTMLText to render templates anyway?

the DBField subclasses currently have two purposes; One as DB field definitions, the other as cast helpers for php values. I admit to feeling a bit uneasy about lumping both purposes into the same class, but that's the status quo. ;)

I don't really feel strongly about trying to address whitespace in templates, to be honest. I guess it can't hurt though.

**Comment by sminnee** [comment]
> Should we really be using DB fields to render templates?

I have the same views as Damian.

> Why do we need to do this?

My concern was that I didn't want trailing whitespace in template files to be something has has a material impact on how SilverStripe behaves. It seemed like having people say "I don't want to put trailing newlines on files because I want my HTML to be tighter" to be an anti-pattern. It was prompted by my work in whitespace.

I get the impression that no-one has a particular problem with this, but I'm also the only one who cares. I'll make a PR if I get the urge. ;-)

**Comment by kinglozzer** [comment]
> the DBField subclasses currently have two purposes; One as DB field definitions, the other as cast helpers for php values. I admit to feeling a bit uneasy about lumping both purposes into the same class, but that's the status quo. ;)

Ah, I’d forgotten about the casting side of things. I agree it does make sense for us to be able to say “treat this value is if it were an `XXField`” at a variable level, but looking at `SSViewer::process()` I’m still not sure why we need to do this at a template level. Not that it’s a bug, or that impacts this issue at all anyway, just an observation :)

> My concern was that I didn't want trailing whitespace in template files to be something has has a material impact on how SilverStripe behaves.

Okay, that makes sense. If it does alleviate having to add extra `trim()`s to unit test then that’s a bonus ;)

If we’re talking about tackling whitespace in template rendering, could it not be fixed in `SSViewer::process()`? Top-level templates, includes and forms/fields all seem to pass through that, and we wouldn’t have to touch how DB fields are rendered

**Comment by tractorcow** [comment]
> I’m still not sure why we need to do this at a template level.

This is so that evaluated templates (HTML) don't get accidentally re-encoded as though they were unescaped text.

**Comment by sminnee** [comment]
Exactly. It's a very common pattern to have a helper method that renders something in a template and then the result is inserted into another template as a merge variable. E.g. `FormField::Field()`.

Rather than force everyone to apply casting meta-data for each of these methods, which would be a bit hassle as well as a backwards-combat nightmare, I just return `HTMLText` objects, and it all "Just Works".

It was introduced in 3.1 I think, when the first pass of assuming that strings should be escaped by default was added.

**Comment by tractorcow** [comment]
@dhensby has an "escape by default" pr for 4.0 we need to get merged.

https://github.com/silverstripe/silverstripe-framework/pull/3924

We've always had default_cast, but it isn't consistently respected. E.g. `$Var` by itself will ignore it.

`$Var.Summary` will first cast to default_cast, then invoke summary method.

**Comment by GuySartorelli** [comment]
> I get the impression that no-one has a particular problem with this, but I'm also the only one who cares. I'll make a PR if I get the urge. ;-)

Given that hasn't happened and this is super old, I'm going to close it.
