### ISSUE TITLE
Show number of children for Folder::getSize()

### ISSUE THREAD

**Issue by sekjal** [silverstripe/silverstripe-framework#5021]
While folders don't have a meaningful size in KB/MB/GB, they do have a count of the number of items they contain.  Since File::getSize() returns a string, why not return something like "# files/items" instead of null?

**Comment by tractorcow** [comment]
If it did this, it would need to be another field, because getSize() is strictly a file size field. Folders of course have no meaningful size (unless you are doing a sum of all children) so it's probably correct that it's omitted.

In 4.x the UX for files and folders will be revamped in any case, so let's wait and see how that turns out. ;D

**Comment by dhensby** [comment]
I'm not sure this is valuable, plus it's a feature request. 

Please either open a PR or discuss it in the dev mailing lish

**Comment by sekjal** [comment]
Thanks for following up!  I'll submit a PR with a more thorough justification for why this would be a beneficial change for CMS users.

**Comment by dhensby** [comment]
:) thanks
