### ISSUE TITLE
Session not saved

### ISSUE THREAD

**Issue by icecaster** [silverstripe/silverstripe-framework#5045]
Hey Ingo ( @chillu )
(assigning to you as you were on the blame here: https://github.com/silverstripe/silverstripe-framework/blame/3/control/Director.php#L192)

Some session variables are not persistent in my SS 3.1.2 set up.
I've traced this back to the commented inst_save() call in Director.php:
https://github.com/silverstripe/silverstripe-framework/blob/3/control/Director.php#L192

Are you able to shed some light into this?

Thanks

**Comment by chillu** [comment]
Whew, 8 years ago ;) `inst_save()` is called after `handleRequest()` here, which seems to be the desired behaviour. If a custom `RequestProcessor` is further modifying the session via `postRequest()`, it needs to take care to save session data itself. I'm not sure which context your issue is coming from, sorry.

**Comment by icecaster** [comment]
Meh just close it I'll file a proper report when I get the chance. 
8yrs... We are getting old!

**Comment by icecaster** [comment]
How's things with you? Any more trips planned south?

**Comment by chillu** [comment]
Hey Tim, same old over here in Wellington. No trips planned, sorry - going to EU three summers in a row, damn weddings! :D
