### ISSUE TITLE
BUG Errors are displayed when thrown too early

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-framework#5250]
I'm investigating an issue where errors are being displayed in live mode when they're thrown too early (ie. db connection issues). It also returns a 200 HTTP response instead of 500 so health check tools don't detect a failure.

A fix i've come up with is to change the following to suppress errors (true): https://github.com/silverstripe/silverstripe-framework/blob/3.2/main.php#L125

Is there a reason why this isn't the case already? What's the thought behind wanting to display errors by default?

**Comment by tractorcow** [comment]
How about we just make this method respect original value of display_errors? That is, make the logic of setSuppression to ONLY allow errors to be suppressed if they were originally visible, but NOT to set errors to visible if they were already suppressed via the default php config?

Dev mode: (php ini says display_errors true)

Original display_errors: true
setSuppression(true)
Result: display_errors false

Original display_errors: true
setSuppression(false)
Result: display_errors true

Live mode: (php ini says display_errors false)

Original display_errors: false
setSuppression(true)
Result: display_errors false


Original display_errors: false
setSuppression(false)
Result: display_errors false // because suppression is off, but original errors are off to it doesn't become un-suppressed.

**Comment by tractorcow** [comment]
There's also ErrorControlChain::execute which is setting display_errors.

**Comment by tractorcow** [comment]
Oh, it looks like there's already an originalDisplayErrors.

**Comment by halkyon** [comment]
This has been merged, so can be closed?

**Comment by dhensby** [comment]
I believe errors still respond with 200 responses

**Comment by tractorcow** [comment]
@dhensby fix for 200 errors is at https://github.com/silverstripe/silverstripe-framework/pull/5556

Patch to fix this specific issue (of not correctly handling display_errors) is at https://github.com/silverstripe/silverstripe-framework/pull/5555
