### ISSUE TITLE
Bit confused about branching in contributing guidelines

### ISSUE THREAD

**Issue by IgorNadj** [silverstripe/silverstripe-framework#5345]
Have been reading through this trying to figure out which branch to raise a PR against.

There are two places guidance is given:

- [CONTRIBUTING.md](https://github.com/silverstripe/silverstripe-framework/blob/master/CONTRIBUTING.md)
- [docs/en/05_Contributing/01_Code.md](https://github.com/silverstripe/silverstripe-framework/blob/master/docs/en/05_Contributing/01_Code.md) – bullet point _Choose the correct branch_

Questions:

1) Do we need the same information in both? I suggest we replace one text block with a link to the other.

2) In CONTRIBUTING.md - how do we define the "public API"? Is this just any public method? I have a basic understanding but would be good to get something down on paper.

3) In CONTRIBUTING.md - "raise it against the correct $MINOR branch." – what is the correct $MINOR branch? The same one your project uses? The latest MINOR branch? 

E.g. if my project is on 3.2 should I PR against 3.2? or 3.3? 

Will old MINOR branches be kept updated? If I PR against 3.3 will 3.2 get the change as well?

Or should the advice be to always PR against the latest MINOR branch, because you should always be updating your MINOR version? (Updating should be safe since with SemVer MINOR upgrades shouldn't break anything). 

In docs/en/05_Contributing/01_Code.md - it says:
> "Branches are periodically merged "upwards" (3.0 into 3.1, 3.1 into master)."

Does this mean the advice should be to go as far back as possible and PR against that? So in my e.g. I would PR against 3.0? Or is this upwards merging only for bugfixes?

4) Just curious, when would you PR against a MAJOR branch rather than master? E.g. against 3? 

5) Where can you find the current stable version for a module? 

I plan to update docs once it's all clear in my head. Thanks!

**Comment by sminnee** [comment]
Agree that we could improve the docs here.

 1. Agreed
 2. We need to lock down what "Public API" means. Loosely, it means any aspect of the system that we have designed to be used by SilverStripe module & site developers. In SilverStripe 3, because we haven't been clear, we have to treat every public method as potentially part of the public API, but sometimes it comes to a judgement call about how likely it is that a given method will have been used
 3a. Generally you should raise things against the latest minor branch. Frankly, "if in doubt, raise it against `3`" is probably the best advice.
 3b. We do merge forwards. So if something goes into 3.1, it will generally get merged forward into future versions.... eventually.
 4. You can raise new features that don't break APIs against `3`.
 5. Not sure what you mean by this?
