### ISSUE TITLE
New flysystem abstraction doesn't handle large files locally

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-framework#5462]
Using the built-in `Local` flysystem adapter, it looks like all assets are passed through a SilverStripe controller, regardless of whether they are protected or not. This is a potential performance problem.

Beyond that though, the `FlysystemAssetStore` is calling `read()` which reads the entire file into memory before creating an `SS_HTTPResponse` to send the response to the user. This is bad for large files, as you need a `memory_limit` bigger than the largest asset that you have on your site.

Code is here: https://github.com/silverstripe/silverstripe-framework/blob/master/filesystem/flysystem/FlysystemAssetStore.php#L816

We could maybe just use PHP's native `readfile()` function directly, or look at using `FileSystemInterface->readStream()` (https://github.com/thephpleague/flysystem/blob/master/src/FilesystemInterface.php#L36)

**Comment by chillu** [comment]
@micmania1 You raised this before as well, right? Was there any issues raised for it on Github?

**Comment by micmania1** [comment]
It was discussed on the main filesystem ticket. Something like stream_copy_to_stream() would work here as the data can be passed straight to `STDOUT` instead of being stored in memory. @tractorcow was talking about implementing something like this in `SS_HTTPResponse` I believe.

This still leaves a problem where large files will take a long time to download so max time limit could also be an issue here.

From what I remember, unprotected files weren't being passed through SilverStripe but I could be wrong. That would seem like a separate problem if true.

**Comment by tractorcow** [comment]
I've a stash of some WIP for a streamed file response object. See https://github.com/tractorcow/silverstripe-framework/commit/afb65bd003205edadd7fb349e9ecf40caed042b2

Our internal jira ticket for this feature is at https://silverstripe.atlassian.net/browse/OSS-1365

**Comment by chillu** [comment]
There's discussion on how to generally improve file access performance through dynamic requests: https://github.com/silverstripe/silverstripe-framework/issues/6457

**Comment by tractorcow** [comment]
Fix PRs:

 - [ ] https://github.com/silverstripe/silverstripe-framework/pull/6909
 - [ ] https://github.com/silverstripe/silverstripe-assets/pull/18
