### ISSUE TITLE
can't find a way to publish protected files

### ISSUE THREAD

**Issue by guyvanbael** [silverstripe/silverstripe-framework#5529]
I have added an image relation to every page 
```
private static $has_one = array(
		'paginabeeld'=>'Image'
	);
```
It works. I can upload it and view the result in the template, but as soon as i log out as administrator, the file isn't visible anymore. 

I can't find where or how to make it public to all users. I can imagine this will be very confusing for future content authors.

guy

**Comment by tractorcow** [comment]
Can you please list your modules? are you using secure files module? Which framework version?

If you are using 4.0, you need to publish the Image first. If you want your images automatically published with your page, you can add an ownership relation.

```php
class MyPage {
   private static $owns = array(
        'paginabeeld'
    );
    private static $has_one = array(
        'paginabeeld'=>'Image'
    );
}
```

However, I guess you'd be using a version of 3.x (since 4.0 is only in alpha) in which case, I can't guess why your image isn't public. :)

**Comment by guyvanbael** [comment]
i was testing the SS4... this is my composer.json. I read about publishing the image, in the image edit window there's only a save button.

This is my composer.json
`{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "4.0.x-dev",
		"silverstripe/framework": "4.0.x-dev",
		"silverstripe/reports": "4.0.x-dev",
		"silverstripe/siteconfig": "4.0.x-dev",
		"silverstripe-themes/simple": "3.1.*",
		"silverstripe/asset-admin": "^1"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~4.8"
	},
	"extra": {
		"branch-alias": {
			"dev-master": "4.0.x-dev"
		}
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}
`

**Comment by guyvanbael** [comment]
adding the ownership relation solves the problem. Still can't find the way to publish manually thoug
![schermafbeelding 2016-05-13 om 09 22 56](https://cloud.githubusercontent.com/assets/3098809/15240822/7ad74418-18ec-11e6-9707-92273f31a9cb.png)
![schermafbeelding 2016-05-13 om 09 23 04](https://cloud.githubusercontent.com/assets/3098809/15240821/7ad6cb28-18ec-11e6-81af-2a23246efe34.png)

**Comment by tractorcow** [comment]
You'll have to use the asset admin (old) for the time being. :) It has a publish button for assets.

![image](https://cloud.githubusercontent.com/assets/936064/15461712/37455686-2111-11e6-8a4b-48c0538ddb97.png)

I'm going to close this and re-open at https://github.com/silverstripe/silverstripe-asset-admin/issues/169 since this is an asset admin issue.
