### ISSUE TITLE
Deal with eventually consistent assets more gracefully

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5544]
## Acceptance criteria:
- After uploading images or resizing images in the CMS, the server will kick off events that upload to an eventually consistent backend such as S3.
- While the image is not available, a loading indicator will be shown
- Once the image is available, it will be displayed (e.g. with polling)
- Any critical meta-data necessary to insert the image into a WYSWYG editor is available immediately, for example width and height. Alternatively, the system can be build not to need this meta-data.

Accepted limitation:
- If the page containing an asset is published, the asset may not yet be available to all viewers of the page. For a time, the asset will 404 for selected visitors. This is because you can't test for global availability with S3. In the first iteration we'll assume that the lag is small enough not to cause issues.

---

Sometimes in multi-server configurations, assets are eventually consistent. Although session-stickiness can help mitigate this in some circumstances, it would be better to make the CMS deal with eventual consistency more gracefully.

The simplest way to do this is, wherever templates refer to an image that 404s, periodically attempt to refresh it. Starting with a 1 second delay, and doubling the length of the delay after each failure, would be a flexible solution.

There are 2 main places where this is an issue:
- Just after uploading an image
- Inserting a resampled into WYSIWYG

Assets usually appear within a few seconds, so having an auto-refresh option in the CMS is important. It's also not critical to solve this in every possible place that it may be an issue; the two examples above are the main ones.

To help test this, I've created https://github.com/sminnee/silverstripe-framework/tree/asset-ec-test-stub which provides this commit: https://github.com/sminnee/silverstripe-framework/commit/dfdf411aaf2afb5dd6cee835e6ddb87b6d9dac27

# Tasks:

 - Ensure Image_Backend fails over safely if image content isn't available
 - Ensure that thumbnails can be queried if exists (without causing it to be generated)
 - Ensure unready thumbnails are safely displayed in asset-admin thumbnails
 - Ensure unready thumbnails are safely displayed in asset-admin edit form
 - Ensure unready images are safely displayed in image shortcodes in the frontend
 - Error handling for image src = 404 re-polls in the future (`<img onerrro=something>`).
 
 ## PRs
 
  - [x] https://github.com/silverstripe/silverstripe-assets/pull/55
  - [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/570

**Comment by hafriedlander** [comment]
So we have a few ways to handle this on the network:

- Assume all 404s from /assets are temporary, set low cache (or no-cache) headers and retry in JS (ick, but lowest change)
- Send some other error code that caches & clients know is temporary, and retry in JS when we see that error code (not specific to /assets any more, better HTTP level compliance, but client still sees user-agent-specific error state in image until refresh succeeds)
- Send some placeholder with a "temporary success" note (either 200 + no-cache + x-try-again-soon header or some other 2xx code)
- Delay responding at all until the file becomes available (hard on PHP with pre-fork)

I like the third option most, but it's probably the most code of all of them.

**Comment by sminnee** [comment]
I should have clarified that I'm looking for a 3.x solution, where assets are directly pulled from the webserver without a PHP intermediary.

**Comment by hafriedlander** [comment]
You can use .htaccess to say "do this on file missing" so all those options except the fourth are pretty easy (and the fourth isn't impossible). There's probably also fancy things we can do if we assume nginx in front.

**Comment by tractorcow** [comment]
When uploading files into the system, given that "file availability" is normally achieved within a few seconds, it should be reasonable to incorporate this into the upload progress pipeline.

So that rather than having something like this:


- Click upload
- File upload progress appears, and ajax post initiates.
- When uploaded via ajax response, immediately show uploaded file
- If file isn't available, broken image appears, but next refresh is likely to show it


The progress logic incorporates the wait for availability:

- Click upload
- File upload progress appears, and ajax post initiates.
- When uploaded, the ajax handler which responded to this upload will wait for file availability with a timeout. We would need some kind of custom logic specific to AWS to hook into this availability check with custom logic (e.g. check all ec2 instances for this file). E.g. a hook in `onAfterLoad` in an extension on `Upload` should work.
- Once uploaded and file has become available, the ajax handler for this upload returns the thumbnail url. If a timeout has been reached (e.g. 10 seconds) it can return a specific notice for this timeout. Alternatively, it could decorate the File dataobject itself with a flag that indicates it's not available, and have that information visible in the UI via a tag / text.


Notice that all of this logic happens on the actual upload, rather than on the actual request to the underlying file.

**Comment by sminnee** [comment]
Another approach to the underlying problem would be to add some extension hooks that could trigger activity on post-filesystem-operations. A set-up involving eventual consistency problems could use these to add some code to pause PHP execution until after consistency was achieved (for example, by checking that the file appears on all relevant servers).

This would minimise the need to make major changes in SS3, and we could save broader solutions for SS4.

**Comment by hafriedlander** [comment]
According to http://stackoverflow.com/questions/9794696/how-do-i-choose-a-http-status-code-in-rest-api-for-not-ready-yet-try-again-lat, "503 status code + Retry-After header" is probably the most accurate response, which I agree with.

This assumes retry-on-download rather than delay-on-upload like suggested by @tractorcow.

Related: http://techblog.netflix.com/2014/01/s3mper-consistency-in-cloud.html

**Comment by hafriedlander** [comment]
Note that Damian's solution wouldn't work for S3, but would for SSP.

SSP is "soon consistent" - we know we will be consistent after the next successful run of csync. S3 there isn't a reliable way to detect when S3 has become consistent (because one server might have the file already and return a 200, but other servers don't yet).

**Comment by edlinklater** [comment]
I think @sminnee's idea of just adding extension hooks has merit - allows creation of solution-specific Extensions - e.g. one for current SSP, one for S3-based, etc - which could be pulled into projects as modules rather than having to be in core.

**Comment by sminnee** [comment]
Note: in the previous discussion "SSP" means "multiple filesystems synchronised with rsync/csync/etc"

**Comment by sminnee** [comment]
As well as `Upload::onAfterLoad`, `HtmlEditorField::processImage` might also be a good extension point for WYSIWYG-resampled images.

**Comment by dhensby** [comment]
How would one application server in a HA cluster know that an upload to another application server had happened and that we can wait a bit for consistency?

eg: User posts file to node-A, node-A accepts file upload and begins syncing across asset stores. User's next HTTP request to ask for the file comes from node-B, node-B makes request from inconsistent asset store and file is not there.

How does node-B know you just uploaded this file and we're waiting for consistency?

Framework is pretty dependent on immediate consistency; would it be possible to solve this on an infrastructure level where we only recognise an upload as complete once we have achieved consistency? This is what I think @tractorcow was suggesting...

**Comment by sminnee** [comment]
Placing this on the alpha4 milestone. This will be pretty critical in providing an S3-backed CMS that has a good experience.

**Comment by chillu** [comment]
Check this with https://github.com/madmatt/silverstripe-s3 once implemented
