### ISSUE TITLE
Allow 2 users of the same group to share a temp cache.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5550]
Right now, the default configuration is that the manifest cache is stored in a user-specific, php-version-specific folder.

It should also be possible to configure this to be a folder specific to a system group, with the files set as group-writeable rather than user-writeable. The system should probably detect whether a given user is a member of this group, and only use this location for such users. Alternatively, the configuration can also specify a whitelist of configuration.

Presumably this will need to be configured in `_ss_environment.php` since the yaml config relies on the cache being available.

**Comment by robbieaverill** [comment]
One problem is that in `TempPath.php` `getTempParentFolder()` it's using `sys_get_tmp_dir()` to get the base path to the cache storage location, which differs between CLI and web server. This would need to be rewritten in a way that is the same for both before this change would be useful, otherwise you're still getting two separate cache storage locations.

Environment: OSX with local Apache

**Comment by maxime-rainville** [comment]
Just had a look at my local sandbox and it looks like this is still a problem in SS4.

**Comment by sminnee** [comment]
This is a stale enhancement ticket imo; closing.

It could arguably be used to simply Linux user management (you don't need to run dev/build as www-data) but we've set up the status quo deployment chains for so long now I can't see much value in keeping this open
