### ISSUE TITLE
Create SoftDeletable extension

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5603]
This was the outcome of #5482.
- Create a SoftDeletable extension that adds an IsDeleted column, with a default filter of IsDeleted = 0.
- Update the delete command to set IsDeleted to 1 instead of actually deleting the record.
- Ensure that there is a data query param or other mechanism for asking for all records.

@axyr has put up their hand for this one.

**Comment by axyr** [comment]
"@axyr rather than a new includeDeleted() method it's probably better to use DataList::setDataQueryParam. See Versioned for an example."

Yes, that can be used behind the scenes. But dont you think : 

`Member::get()->includeDeleted()->byID(1);` or
`Member::get()->withDeleted();`

ofcource with/include Deleted can set the setDataQueryParam behind the scenes.

I was thinking of a deleted_at column with a timestamp instead of a boolean

**Comment by tractorcow** [comment]
This should be in a module, IMO, and not a part of core, given that there is one real universal approach here.

@axyr I suggest to use query parameters, as @sminnee suggested, as is the standard approach. See Versioned extension for a good example of how to do this.

The example you gave could be done another way, e.g. SoftDeletable::with_deleted('Member')->byId(), etc. This prevents having to create a new extension just for DataList. I am assuming you're not thinking of adding those methods directly on DataList itself, are you? :P

**Comment by tractorcow** [comment]
Also see https://github.com/silverstripe/silverstripe-cms/pull/1490 for the pull request where this feature would be used, on the page history section.

**Comment by lekoala** [comment]
I recently made a module for the same reasons (most of the time, it's not a good idea to delete a member, I'd rather keep the record somewhere in the database).

https://github.com/lekoala/silverstripe-softdelete

Maybe it can help you on this topic ? :-)

the only problem I'm facing with the fact it's a DataExtension is that it's not so easy to override the "delete" method, because some other module may expect the delete actually deletes the record.

**Comment by sminnee** [comment]
This module looks very much like what I had in mind, thanks! @axyr you might wnat to check it out

> the only problem I'm facing with the fact it's a DataExtension is that it's not so easy to override the "delete" method, because some other module may expect the delete actually deletes the record.

The simplest approach would be to tell users of the extension to put this method instead:
```php
function delete() {
  $this->getExtensionInstance('SoftDeletable')->deleteHandler();
}
```

**Comment by chillu** [comment]
Since there's a module, I'm going to close this. Given the increased versioned abilities in core and the new "archive" view, it's easy to "soft delete" through adding versioned
