### ISSUE TITLE
RFC: move admin into a new module

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5641]
## Acceptance criteria:
- The admin/ subfolder of framework is split into a new silverstripe/admin module
- It is a dependency of silverstripe/cms, silverstripe/asset-admin, silverstripe/campaign-admin, silverstripe/reports, and silverstripe/siteconfig.

---

Plans have been afoot to split out the admin section into its own module ever since it was packaged into the framework/admin folder along with its templates.

The first part of this RFC is pretty simple: move the contents framework/admin to a `silverstripe/admin` composer package.

The second part is less obvious, but I think makes sense: shift all the react boilerplate support from framework/javascript to the `framework/admin` module. The goal of SS4 is not to provide generic NPM/React boilerplate, and I don't think that code lumped into framework/javascript is of much help here.

**Comment by chillu** [comment]
Clarified with Sam that we'll avoid exposing newly written JS in `framework` (= usage outside of the CMS). Existing JS in `framework` can stay in place (particularly the form field JS in https://github.com/silverstripe/silverstripe-framework/tree/master/client/src/legacy). 

The ideal goal would be for `framework` not to have an NPM dependency, in order to avoid inflating the time spent on `npm install` throughout the different modules. This means we'll need to ensure that JS in `framework/client/src` is vanilla JS (no ES6 transpiling). This seems to be the case for all existing JS, apart from https://github.com/silverstripe/silverstripe-framework/blob/master/client/src/i18n.js which would require a rewrite from ES6 to vanilla JS.

There's a separate discussion about dropping support for form field JS outside of the CMS, which we'll need to tackle case by case. This is beyond the scope of this RFC. Some thoughts on a selection of fields:

 * `AssetUploadField`: Move JS and PHP to admin
 * `ConfirmedPasswordField`: Used in `Member->getCMSFields()`. Move JS to admin. Keep PHP in framework. Replace `$showOnClick` and `$showOnClickTitle` options with HTML5 attributes which aren't documented on the PHP field, but can be used in the admin JS implementation.
 * `DateField`: Move JS to admin. Keep PHP in framework. Deprecate `showcalendar` option in PHP, since it required JS. Uses entwine, which is overkill on most website frontends. Since the field is so popular, document "init jQuery date picker" sample code in markdown docs for DateField.
 * `GridField`: Move JS to admin. Keep PHP in framework.

**Comment by dhensby** [comment]
> AssetUploadField: Move JS and PHP to admin

I think we'll need some kind of `FileUploadField` that isn't terrible for framework... though that can always be added later / a module.

> GridField: Move JS to admin. Keep PHP in framework.

I don't see why we'd want to keep the PHP for GridField in framework when it's so clearly an admin feature as well as, surely, useless without any JS behind it?

---

This would be a good time to really focus the form fields on being vanilla form fields - some should have their own JS, which could be disabled in admin, to make them useful, but we can be quite agressive with what is and isn't sensible to have in a framework.

I'd possibly argue that we should just use HTML5 form field types, implement some serverside validation for them, and leave it at that. Modules could then be used to have fancier ones.

**Comment by flamerohr** [comment]
I like the idea of HTML5 vanilla form fields in framework and modules could then have fancier ones (such as admin)

**Comment by tractorcow** [comment]
Main PR https://github.com/silverstripe/silverstripe-framework/pull/6695
