### ISSUE TITLE
Convert Entwine/Chosen dropdowns to a Bootstrap React component

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5670]
## Acceptance criteria:

- Dropdowns in the CMS are updated to align with the CMS style
- Best widget (chosen or a new one) is decided on for use in 4.0 stable

## Notes

Convert Chosen dropdowns and Chosen Choices to a Bootstrap React component. If the conversion of Chosen to Bootstrap is not to be made then the styles of the dropdown needs to changed

## Related

 * [Use react-select for react-based dropdowns (SingleSelectField and MultiSelectField)](https://github.com/silverstripe/silverstripe-admin/issues/52)

**Comment by chillu** [comment]
Bootstrap dropdowns are not a like-for-like replacement for ChosenJS, e.g. no inline search and no multi-select abilities - they only provide styling. There's a [Dropdown](http://v4-alpha.getbootstrap.com/components/dropdowns/) Bootstrap JavaScript component, but that's not based on a form control, but rather a mini-menu UI control - so not applicable here.

Rather than spending the energy converting ChosenJS components to react-select for legacy Entwine UIs, I suggest focusing on new libraries with new UIs (react-select in React-based UIs). They already look 99% consistent between Entwine and React, and once we have react-select in React-based UIs they'll behave consistent as well (inline search for dropdowns). 

The main downside here is that we'll include to large libraries in our JS bundles, but that's an acceptable tradeoff for team velocity at the moment.

I've done an overview of the different options in https://github.com/silverstripe/silverstripe-admin/issues/52#issuecomment-299744297

**Comment by chillu** [comment]
From Paul on Slack:

> That issue is now irrelevant with the new react dropdowns. Although there will still be select dropdowns which still use chosen which are not in react areas so this issue is to capture those as well. Chosen selects don’t use Bootstrap styling and spacing
