### ISSUE TITLE
Convert all in page messages to Bootstrap conventions

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5674]
Use the Variables style sheet to modify the styles if needed.
If designs have not been created for the colours of the varying messages then use CMS existing colours and swap out the variables.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/643
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2263
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8377
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/101

**Comment by robbieaverill** [comment]
I've just had a look at this. It's going to be tricky to do it in a backwards compatible way, because having `message` class as well as `alert alert-success` overrides the Bootstrap colours and renders a grey alert.

I've added a casting helper to switch SilverStripe message types to Bootstrap ones and this works, but it would also affect frontend users and probably break frontends that rely on `good`, `bad` etc as message types.

We could add a new method e.g. `$AlertType` and run that in parallel instead?

**Comment by robbieaverill** [comment]
All merged =)
