### ISSUE TITLE
[4.0] DBText always converts newlines to line breaks

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#5925]
Related: #1942

I'm playing with converting a module of mine to be 4.0 compatible - it's a markdown parser.

Long and short is that I have a data model:

```php
class MarkdownText extends DBHTMLText
{
    // ...
}
```

Inherited casting is `['Value' => 'Text']`. It seems the most appropriate to continue to use (this is the same as my 3.x version, only the framework has had some changes made affecting the hierarchy e.g. aeccb8b).

`DBText` inherits from `DBString`:

```php
public function forTemplate() {
    return nl2br(parent::forTemplate());
}
```

So my value is always saved into the database with `nl2br` run over it:

**Input:** `my\nexample\nstring\here`
**Outut:** `my<br />example<br />string<br />here`

Would you be opposed to a getter/setter or an inherited config property for whether to do this? My alternative for now is to extend `DBText` just so I can override `forTemplate` to prevent it using `nl2br`, and define `private static $casting = ['Value => 'DBPlainText']` for example in my custom FormField implementation so it skips the `DBText` inheritance.

I find it interesting that the commit introducing this change (4a15845) is old and exists in the 3.x code already - was there a change made to how value casting is made?

Anyway, it makes sense for an HTML field to do this I suppose, but not a plain text field (non-HTML). In my example I'm using `DBHTMLText`, but `DBText` (its parent) behaves the same since the behaviour originates in `DBString`.

Feel free to close if you don't feel this is a "bug" :)

Thanks
R

**Comment by tractorcow** [comment]
I think the way you've approached this via a DBField subclass is the correct way to do it. Also, forTemplate() is only for outputting to templates; If this value is making its way into the database, then there is some other way that the DB is sanitising your field value.

See DBField::writeToManipulation() for the entry point from the DBField value into an actual database write. Maybe you'll need to override prepValueForDB() ?

What mechanism are you using for editing the markdown? A TextareaField? I have a feeling that the newline conversion might be occurring during the editing and/or serialising for the editor.

Check out ValueEntities() method; this is specifically designed so that Text fields can customise themselves for the body of any `<textarea>` component they are being edited within.

**Comment by robbieaverill** [comment]
I'll take a look around @tractorcow - thanks for the tips.

**Comment by tractorcow** [comment]
Let me know if you want to take this offline... bug me on skype sometime. :D

**Comment by diegopego86** [comment]
Hey @tractorcow I'm running into this issue as well, did you find a work around it?

**Comment by tractorcow** [comment]
@diegopego86 please open a new issue with a description of your problem.
