### ISSUE TITLE
[VIEW] Notice: Undefined Offset SSViewer:1066 (edge case)

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-framework#5931]
Steps to reproduce:
1. Use `$this->renderWith("ThisTemplateDoesntExist")` within a class that extends `\Page_Controller`

Will occur when a template cannot be found in the theme directory with `renderWith()`

```
$template = $this->chosenTemplates[$key];
```

to

```
if (!($template = (isset($this->chosenTemplates[$key])) ? $this->chosenTemplates[$key] : FALSE)) {
    throw new SomeRelevantException();
}
```

**Comment by maxime-rainville** [comment]
I would try to validate if this issue is still present in SS4, but I don't think there's enough details here for me to go on.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If you can still reproduce this issue in SS4, could leave some replications steps and I'll reopen.
