### ISSUE TITLE
Outputting multi-line text fields in templates.

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-framework#5978]
I think it's about time this be implemented as a feature in the framework core. Apparently there's no native/intuitive method for users to automatically output/formatted `TextareaField` content on the front-end. Why is that?

For example: http://stackoverflow.com/questions/4917596/is-it-possible-to-run-a-function-on-a-silverstripe-template-variable-to-format-o/14517067#14517067

And solutions like this are needed (this is mine):

```php
class TextFormatterExtension extends Extension {
	/**
	 * Chose 'HTMLOut' instead of 'HTML' because that's too generic, could end up overridden in future versions, and
	 * 'NL2BR' because it also needs to convert HTML entities unlike nl2br() on its own.
	 *
	 * @return string
	 */
	public function HTMLOut() {
		return nl2br(Convert::raw2xml($this->owner->value));
	}
}
```

It's so simple, I don't see why this can't be done. Let me know if you agree :smile::+1:

**Comment by kinglozzer** [comment]
We already call `nl2br()` in [`DBString::forTemplate()`](https://github.com/silverstripe/silverstripe-framework/blob/8dd644d25d4e01b6853922164440f8ac9c824f22/ORM/FieldType/DBString.php#L103-L108) (formerly `StringField::forTemplate()`), and `SSViewer.default_cast` is `Text`, so this _should_ happen automatically.

The fact that it doesn’t is because we don’t enforce `default_cast` in 3.x (see https://github.com/silverstripe/silverstripe-framework/pull/5653). Could you test on master and see if it handles this correctly?

**Comment by patricknelson** [comment]
I'm sorry @kinglozzer I'm a dunce :hankey: I realized that as I was vacillating between text vs. HTML for a field, I ultimately decided upon text, setup the `TextareaField` in `->getCMSFields()` but absentmindedly left the DB field type itself as `HTMLText` which will obviously will have a `->forTemplate()` that doesn't need to convert  newlines. Your response made me look backwards at the code to confirm exactly what my type was here (I was assuming `Text`, which I don't often use) and ... d'oh.

Place :hand: on :grimacing:
