### ISSUE TITLE
Making a method used in template private leads to inconsistent messaging

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-framework#6151]
Affects latest 3.4, unsure about other versions.

If you specify:
```php
private function Form() {
    return new Form($this, __FUNCTION__, new FieldList(), new FieldList());
}
```

Then call `$Form` in your template, you get "[User Error] Uncaught Exception: Object->__call(): the method 'form' does not exist on 'Flowchart'".

My assumption is we're using reflection somewhere but not checking the visibility property properly before attempting to call the method. Even just updating the error message to say the following would be better: "the method 'form' does not exist (or is protected/private) on the 'Flowchart' class".

Will try and PR for this when I get some spare time :)

**Comment by robbieaverill** [comment]
Semantically speaking private methods of a controller should not be accessible in a template, because they're private and as such belong only to that _specific instance_ of the controller.

**Comment by madmatt** [comment]
Sorry I probably wasn't clear. I agree with your point that private methods shouldn't be usable in templates. What I'm getting at is that the error message is unclear. If there is a private method with the same name as a variable in a template it says 'method doesn't exist'. What it should say is 'method does not exist or is protected/private scope'.

I haven't looked deeper, but I have a feeling ->hasMethod might not be taking into account private/protected scoped methods or something like that. Either that or SSViewer is doing something funky.

**Comment by madmatt** [comment]
edit: Looked over the code, it's not hasMethod() not instead is likely the class manifest builder (which does use reflection).

**Comment by kinglozzer** [comment]
Just had a quick look at this, I think the best place to fix it is probably [in `ViewableData`](https://github.com/silverstripe/silverstripe-framework/blob/3.4/view/ViewableData.php#L445-L449). I’m not sure of the best approach, though - using `ReflectionMethod` to check visibility may be difficult, as the method may not always exist on `$this` (due to the `__call()` magic we have).

**Comment by dhensby** [comment]
My understanding is that this is a standard PHP error for attempting to access methods/properties that are marked private...

**Comment by kinglozzer** [comment]
@dhensby It is the standard PHP error message, but what @madmatt is saying is that it’s not a very helpful message in the context of templates. I’m not sure if we should:

- Leave this alone. I’m sure devs with knowledge of method visibility will be able to work the cause out, and those without that knowledge will likely mark every method as `public` anyway.
- Change the error message to a more descriptive one
- Silently ignore `private` methods when doing lookups, so `$Form` in the example above wouldn’t output anything at all, as if the method doesn’t exist

The last two involve extra work to detect method visibility, and there may be performance implications of checking method visibility for every lookup we do, so I’m kinda leaning towards the status-quo.

**Comment by dhensby** [comment]
I'd leave it as is because (I hope) googling that error would result in a pretty quick conclusion that you're trying to access a private method on an object.

What *might* be helpful is a debug mode that would echo out something like "Coudln't find `$Form` on Controller/Model/whatever, check it's defined or is `public`"? But this is a fair amount of work

**Comment by robbieaverill** [comment]
I agree with @kinglozzer - you'd be introducing a performance hit (probably) by using reflection to determine if the method *does* exist but is private, and doing so to cater to developers who might not understand the concept of visibility. Another point (again, semantics) is that perhaps in terms of "visibility" the framework shouldn't be exposing methods existence that are private anyway, because they're private.

As @dhensby said, Googling the error - particularly with "user error" in the name will return an array of SilverStripe posts. Perhaps something might be added to the documentation to clarify that private/protected methods cannot be used from templates instead of changing the code's behaviour?

**Comment by madmatt** [comment]
I made a pull request to demonstrate all I was thinking of when I made this issue, see #6157.

I don't think we need anything crazier than this, just a simple error message modification is all I'm after here.

I'll close this issue and we can move discussion to the pull request instead. I'll link back to the comments here :)
