### ISSUE TITLE
 Stub out GraphQL story cards

### ISSUE THREAD

**Issue by marcello-silverstripe** [silverstripe/silverstripe-framework#6268]
AC:
- Ready for (remaining) implementation to be sized by open sourcerers

**Comment by chillu** [comment]
Closing this even in favour of more focused research cards: https://github.com/silverstripe/silverstripe-graphql/issues/11 and https://github.com/silverstripe/silverstripe-graphql/issues/10. Turns out to be more investigation work than the three points assigned here, between Will and myself we've spent that amount of time already just identifying *what* to research.
