### ISSUE TITLE
Add Director::isCMS() function or similar.

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#6310]
SIlverstripe needs something like this for a wide variety of use cases.
If what I have below is fine, I'll just PR something, otherwise I'm open to suggestions.

```
$controller = Controller::has_curr() ? Controller::curr() : null;
return ($controller instanceof LeftAndMain ||
		$controller instanceof TaskRunner ||
		$controller instanceof Security ||
		$controller instanceof DevelopmentAdmin ||
		$controller instanceof DevBuildController ||
		$controller instanceof DatabaseAdmin)
```

**Comment by dhensby** [comment]
I would think the only one that actually identifies if you're in the CMS is `$controller instanceof LeftAndMain` the others aren't actually in the CMS

Rather than adding `isCMS` we should find a way to decouple our code nicely.

What are the kind of problems you're trying to solve?

**Comment by tractorcow** [comment]
I've done something similar in fluent;

https://github.com/tractorcow/silverstripe-fluent/blob/master/code/Fluent.php#L412

The problem I wished to solve was to disable certain filters within the CMS.

**Comment by tractorcow** [comment]
I would argue that such code should be in the admin module, not in Director. I.e. admin is aware of itself, rather than making the core aware of admin.

**Comment by SilbinaryWolf** [comment]
Maybe something like LeftAndMain::in_cms() or CMSMenu::in_cms() itself? Feels like the most logical locations,

Also its a feature that's been needed since 2011 apparently:
https://www.silverstripe.org/community/forums/general-questions/show/18197

**Comment by sminnee** [comment]
What is the use-case for this? Security is sometimes "in the CMS" or not, depending on what you're doing.

This seems like one of those "common sense" features that seems clear until you try and define it precisely.

Does "is CMS" mean "not the website"? If it's the latter than would something like `if(!($controller instanceof ContentController))` be better?

**Comment by SilbinaryWolf** [comment]
The above idea won't cover custom frontend Controllers that don't extend ContentController.
I guess if I had to define exactly what "isCMS" I'd say if your URL path beings with the following, then you're in the CMS as logging in was required:
- /admin/
- /dev/

**Use Cases:**
- CDN Module (rewrite File/Image asset links on frontend only)
- Multisites Module (required in places, such as setting theme per site logic)

I've hit this plenty of times for other things, but I can't recall any right now.

**Comment by sminnee** [comment]
> The above idea won't cover custom frontend Controllers that don't extend ContentController.

The long list of classes that you *have* labelled as being part of the CMS, some of which aren't really part of the CMS (DatabaseAdmin), suggests to me that what you're really trying to describe by "CMS" is "not the website". So I'd probably go for `ContentController::isWebsite()` over `LeftAndMin::isCMS()`.

Agreed, occasionally you'll create a controller for your website from another class so you'd want to add a way of adding more base classes to the `isWebsite()` test. Probably a bit of config yaml.

>Use Cases: CDN Module (rewrite File/Image asset links on frontend only)

Let's unpack the CDN example...

Why is it that the CMS shouldn't rewrite to a CDN link? Is it because there's a risk that the image hasn't been uploaded to the CDN yet? If the page is immediately published are we okay with that being broken? Perhaps a consistent function that provides a CDN link only after the upload has been successful would be better?

What happens in the case of the preview section of the CMS? Should the links be rewritten there or not?

The problem with having, say, `File::Link()` behave differently depending on whether or not it's in the CMS is that the behaviour gets less predictable and more difficult to debug.

My general point is that "behave differently if it's the website rather than the CMS" is usually takes you down a road of messy coupling, and if there's a better way of solving the problem that would be good.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
