### ISSUE TITLE
Issue with Email Function

### ISSUE THREAD

**Issue by Allunby** [silverstripe/silverstripe-framework#6386]
Hi guys, I'm still experiencing this issue. I apologise I didn't know how to reopen my old issue thread, so posting a new one. If you want me to move this somewhere else, let me know.

OK. I've got a new SO thread regarding this issue. It details what I've tried.

http://stackoverflow.com/questions/40855009/silverstripe-issue-with-email-function

As an update to this I'd like to point out:

- Plain text emails are sending fine with both SS Mail Function, and php mail() function.
- HTML emails send fine with the PHP mail() function.
- I've tried using the send grid module that FinBoWa suggested in the comments. HTML sends fine.
- Problem appears to happen when I send HTML emails with $email->send()
- I don't have root access to the server this is sitting on. We have a shared hosting service and if you need to see any logs etc, I have to contact the support team.

If you need any further information about this, and what I've tried. Let me know.

**Comment by dhensby** [comment]
the original ticket is #5842

If emails send fine through a third-party mail delivery service, perhaps it's best to stick with them?

Can you replicate your problem locally or on other servers?

**Comment by Allunby** [comment]
Hmm, I'd prefer it if I could use the SS Email function to be honest. I want to be able to populate email templates. Also, it's probably something we should investigate, in case it's an issue with the framework.

I'm not able to send emails on my local server, however I have tried on other servers provided by our hosting service and the issue persists.

**Comment by jonom** [comment]
This looks like a server problem, not a SilverStripe problem. I'd guess the encoded message is getting messed up after PHP passes the email off. Maybe some additional line breaks are getting added which could explain the = signs that are getting rendered in the output when the client tries to decode the message. Here's a little more on that:

> If messages are not received, try using a LF (\n) only. Some Unix mail transfer agents (most notably » qmail) replace LF by CRLF automatically (which leads to doubling CR if CRLF is used). This should be a last resort, as it does not comply with » RFC 2822.
http://php.net/manual/en/function.mail.php

I'm guessing mail() is working when SS Email is not because vanilla mail() wouldn't encode the message, so it wouldn't matter if some extra line breaks were added. This could be a problem for some email clients though, if your lines are longer than 70 chars.

You can use a third party ESP with SilverStripe, you just need an appropriate Mailer class to hand it off. Here's one for PostMark: https://github.com/jonom/silverstripe-postmark-mailer

**Comment by Allunby** [comment]
Thanks for the responses gents. I'm passing all this information so far on to our hosting provider and see what they make of it.

**Comment by Allunby** [comment]
OK finally heard back from my hosting provider. After a lot of back and forth, testing and sending screenshots, they conceded that it was an issue with their set up. It was a problem with how their server was handling the CR/LF line endings (good spot, @jonom!). They have implemented a solution that strips CR characters. Thanks for your help with this folks, this was becoming incredibly frustrating. Much appreciated.

**Comment by dhensby** [comment]
Glad they got it sorted and sorry it took so long.
