### ISSUE TITLE
Pagination Summary is buggy

### ISSUE THREAD

**Issue by carpentiers** [silverstripe/silverstripe-framework#6412]
Hi. I'd like to point out there's a serious bug with the pagination. I followed what's said in Silverstripe's website tutorial and I remarked that if I change the PaginationSummary's value, I sometimes get a number of pages different from what I assigned and sometimes bizarre behaviours, too.
I will give you two examples. To put you in context, in my tests, I have a total of 6 pages. The only thing that will change is the summary of those pages.

1st example with PaginationSummary(3):
When on the 1st page, I get pages 1, 2, 3, ..., 6.
On the 2nd page, I get pages 1, 2, 3, ..., 6.
On the 3rd page, pages 1, 2, 3, 4, ..., 6. (You can notice a difference in the number of pages, it's not a summary of 3 pages, but 4.)
On the 4th page, pages 1, ..., 3, 4, 5, 6. (Same behaviour.)
On the 5th page, pages 1, ..., 4, 5, 6. (Back to normal.)
On the 6th page, pages 1, ..., 4, 5, 6.
In summary, we see an inconsistent number of pages shown which can affect the layout of the page, but still isn't that bad as the pagination still makes sense which isn't the case in the next example.

2nd example with PaginationSummary(4):
On the 1st page, I get pages 1, 2, 3, 4, 5, 6. (Quite long for what I asked for.)
On the 2nd page, pages 1, 2, 3, 4, 6. (Surprise! No ellipsis, but page 5 is missing, too!)
On the 3rd page, pages 1, 2, 3, 4, 5, 6. 
On the 4th page, pages 1, 2, 3, 4, 5, 6. 
On the 5th page, pages 1, 3, 4, 5, 6. (No ellipsis and page 2 is missing.)
On the 6th page, pages 1, 2, 3, 4, 5, 6.

The loop and the PaginationSummary function are obviously failing somewhere. It seems like PaginationSummary reaches it's end at some point, but doesn't return the value false, so the condition can't get into the ELSE which returns the ellipsis.What do we get then? No ellipsis and a missing page. That seems to occur only when the ellipsis is supposed to be there to replace only 1 single missing page as if the function confuses that page for the first or the last page. The number of pages presented by the pagination summary is inconsistent, too.

**Comment by dhensby** [comment]
The first example seems fine to me. Always show the first and last page and then 3 pages around the current page (one either side of and including the current page).

The second one is clearly doing something wrong for 2nd and 4th instances but all others are as I'd expect.

The number passed to the summary will be how many pages to show (not including the first and last pages) before truncating.

For 6 pages showing a summary with length 4, there are only 4 pages between 1 and 6 (pages 2, 3, 4, 5) so you'd expect all of them to always show.

The bug is not the lack of ellipsis, but the missing number.

Would you be prepared to patch this? Also, please confirm which version of SS you're using.

**Comment by PingMetal** [comment]
Thank you for your answer!

If the function works as you said, I still see a problem with the first example in instances 2 and 5.
For example, let's take the second instance. If you have a pagination summary of length 3, you would expect this result: page 1 (the first page, not counted), pages 2, 3, 4 (the ones considered as summary, including the current one), then an ellipsis... (skipping page 5) and finally page 6. That's unfortunately not the case here. I get 1, 2, 3, ..., 6. It looks erratic to me. What do you think?

Also, just to be sure I'm getting the function's supposed behaviour, when a person is on the first page the page gets included in the pagination summary length as the current page always gets included (despite it being the first or the last one), right?

My version is 3.5.0.

**Comment by PingMetal** [comment]
Giving a look at the source code shows me pagination doesn't work that way.

Passed down length should be an even number. When the current page is not close to the first or last one, the current page doesn't count in the length, the length is divided by 2 and is added before and after the current page to give a visually balanced pagination. I don't know how the function behaves when the current page is the first or last one, or the half of the length can't be evenly added to both sides of the current page, because the previous one is the first page or close to it. I will check it up more.

**Comment by PingMetal** [comment]
I just made a fix and now the page that isn't included in the pagination returns a null value making it possible to detect as skipped and show an ellipsis instead.

I forked PaginatedList.php and pulled a request.

**Comment by dhensby** [comment]
OK - thanks for looking into this. I've merged the fix into 3.4 which should then be merged up into 3.5 and master (4.0) eventually.
