### ISSUE TITLE
Switch to micmania1's config implementation

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6477]
## Acceptance criteria

 * Config uses silverstripe/config module
 * Hard-coded configs can be easily built as a wrapper around an array
 * Config performance is faster

Ingo to talk to Michael about this.

PRS:

 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6641
 - [x] https://github.com/silverstripe/silverstripe-config/pull/4
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1739
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/390

**Comment by chillu** [comment]
@micmania1 FYI, Sam has assigned this to 4.0.0-alpha5 at the moment, which is planned for around a month from today. Are there any documented blockers or TODOs? Existing discussion: https://groups.google.com/forum/#!searchin/silverstripe-dev/config%7Csort:relevance/silverstripe-dev/q5khashNiuY/0Q7zkKwwAwAJ

**Comment by micmania1** [comment]
@chillu The new implementation relies on PSR-6 cache interface which I believe is still up for discussion?

**Comment by tractorcow** [comment]
I'm going to keep a list of todos based on my review (as I go along):

# Caching

We can probably formalise this when we substitute the current cache system.

# Reproduce lookup options (e.g. inheritance, first_set)

We could probably move the lookup behaviour to a level above the core config (which can be pure key-value pairs). E.g. Some config lookup helper that applies class-hierarchy and applied extensions on top of the config.
 
That way these extra functions aren't a part of the config itself, they are just extra tools the framework uses to lookup config.
 
# Support nested config collections
 
I suggest flipping the class construction around to something similar to what @sminnee 
 proposed in the above discussion.
 
 ```
 new CachedConfig(
    new CascadedConfig([
      new YamlConfig(...),
      new PrivateStatticConfig(...),
    ]),
    new PSR6CacheHandler(...)
  );
 ```
 
This would make ConfigCollections responsible for invoking ->transform() on their config sources as-needed.


# Cacheable user-modified config

Just brainstorming some ideas to increase performance where user-modified code provides updated config.

I see these as a great substitute for having to invoke Config::inst()->set(). I imagine a `UserModifiedConfig` store which can be provided a list of callbacks which are conditionally invoked when the cache is regenerated. Alternatively, the non-cached ConfigCollection could just store these on ->set() and invoke the callback on ->get().

E.g. instead of

```php
$extraFields = $this->buildFields();
Config::inst()->update(SiteTree::class, 'db', $extraFields);
```

The cacheable version of this would be

```
Config::inst()->update(SiteTree::class, 'db', function() {
	return $this->buildFields();
});
```

The callback would then be invoked if either the cache is expired, or if currently flushing.

# Config merging outside of YML

This implementation appears to only merge config between YML files; If I have a config array defined in both yml and my class, values will be overwritten, not merged. The same issue applies when I wish to merge config with `Config::inst()->update`. Do we need to split `Config::inst()->merge(` and `Config::inst()->set(`?

Without this, for instance, it would be impossible to add extra 'allowed_actions` to a class, only to overwrite with new actions.

**Comment by tractorcow** [comment]
Please see https://github.com/silverstripe/silverstripe-framework/issues/6611

**Comment by tractorcow** [comment]
WIP as at:
 - https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/micmania-config
 - https://github.com/open-sausages/silverstripe-config/tree/pulls/config
 
This vs current master will be benchmarked:
 - Time to build cache (cold)
 - Time to boot from cached config (warm)
 - Time to query SiteTree::config()->get('db')
 - Time to query SiteTree::config()->get('db', Config::EXCLUDE_EXTRA_SOURCES)

**Comment by tractorcow** [comment]
Updated my test suite at https://gist.github.com/tractorcow/0b93d520a98125a0db018d8e54ea6ead

**Comment by tractorcow** [comment]
Results of tests (100x iterations of each)

#1 Build config with cold cache (flush=all)

rewrite: 39.7 seconds
master: 20.4 seconds

#2 Build config from cache (not flushed)

rewrite: 5.3 seconds
master: 5.0 seconds

#3 Query SiteTree::config()->get('db') 10000 times (uninherited, w/ extensions)

rewrite: 1.652s
mater: 0.7s

#4 Query SiteTree::config()->get('db') 10000 times (uninherited, no extensions)

rewrite: 0.53s
mater: 0.53s

#5 Modify SiteTree.db and re-equery (uninherited, w/ extensions)

rewrite: 0.57s
master: 0.81s

# 6 Modify SiteTree.db and re-query (uninherited, no extensions)

rewrite: 0.56s
master: 0.57s

**Comment by tractorcow** [comment]
So new config did better in test 5, but much worse in test 3. I think there's something wrong with my caching for middleware-applied values (that can be fixed).

**Comment by tractorcow** [comment]
ok, applying a non-persistant cache on top of CachedConfigCollection seems to have improved the performance a bit. :)

**Comment by tractorcow** [comment]
Actually, that extra cached bumped the performance to faster than the master config.

**Comment by tractorcow** [comment]
Repeating test 2 reveals that there is quite a bit of variance between ranges. I might increase the repetitions and re-do it.

**Comment by tractorcow** [comment]
Bump up to 1000 for the below tests:

1 Build config with cold cache 1000 times (flush=all)

rewrite: 
master: 3m18.600s

2 Build config from cache 1000 times (not flushed)

rewrite: 
master:

**Comment by tractorcow** [comment]
Conclusion: Generally faster in day to day usage, slightly slower to load from cache, but a lot slower to build the cache on the first hit.

**Comment by sminnee** [comment]
@tractorcow I think that performance situation is good enough to merge, and we can look at further optimisations as we see fit.
