### ISSUE TITLE
[SECURITY] html p tag being displayed 

### ISSUE THREAD

**Issue by hoKRa1** [silverstripe/silverstripe-framework#6536]
As you can see, the p tag is being displayed. Should be an easy fix.
![screenshot from 2017-01-19 11-16-06](https://cloud.githubusercontent.com/assets/13618634/22085383/bb0853da-de38-11e6-8fa8-6086253c50a7.png)

**Comment by jaylou** [comment]
I'm working on this now.

**Comment by kinglozzer** [comment]
This can be solved by casting the HTML content (in `Security::lostpassword()`) to an `HTMLFragment`:

```php
'Content' => DBField::create_field('HTMLFragment', '<p>' . _t(... //etc
```

**Comment by phptek** [comment]
@kinglozzer This might fix this _specific_ instance of the issue, but as you can see (in e.g. #6537), there are several places thoroughout the cms/framework where the seemingly "same" issue occurs. Do you think all instances of this issue be approached using the same fix, or is there a root cause at a higher level (I haven't had time to dig, but I've been helping those who have).

**Comment by dhensby** [comment]
is this 4.x or 3.x?

**Comment by dhensby** [comment]
If you're sending HTML to the templates then you have to cast it as `HTMLText` in some way.

**Comment by dhensby** [comment]
The best solution is have the `<p>` tags in the template and the content sent as plain text.

**Comment by phptek** [comment]
This was an issue in 4 (dev-master) also. The markup comes from the YML language files themselves and obviously worked in v3. Unless someone is going to repace all markup in language files and modify calling logic everywhere, I'd suggest there's something awry at a higher level.

**Comment by kinglozzer** [comment]
There isn’t a one-size-fits-all fix here, unfortunately. Stuff that goes through the template engine needs to be cast to `HTMLFragment` (or `HTMLText` in 3.x), and stuff that is returned to React for it to render will need some other solution (maybe https://github.com/silverstripe/silverstripe-framework/issues/6537#issuecomment-274036548).

We’ll likely have to fix these one-by-one as they come up. Regressions from 3.x may have been caused by casting API changes (https://docs.silverstripe.org/en/4/changelogs/4.0.0/#explicit-text-casting-is-now-enforced-on-all-template-variables).

Anyway, the bug described in this ticket should be pretty easy to solve. @hoKRa1, do you fancy submitting a PR with [this change](https://github.com/silverstripe/silverstripe-framework/issues/6536#issuecomment-273720145)?

**Comment by dhensby** [comment]
@phptek the template is behaving as expected here. This does need to be fixed one-by-one.

PHP should not be rendering HTML.

@kinglozzer even casting as `HTMLFragment` is dangerous because the content inside the `<p>` needs to be HTML encoded in that case.

If we don't have HTML in our strings, then that's the best and safest way to pass things to the template

**Comment by maxime-rainville** [comment]
This is not a problem in SS4.

Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

If someone is encountering this problem in SS4, please leave some replication steps and we can reopen.
