### ISSUE TITLE
RFC: DataObject's that are from the Stage table should proceed to get has_many/many_many from the same table. (Same for _versions / _Live)

### ISSUE THREAD

**Issue by SilbinaryWolf** [silverstripe/silverstripe-framework#6680]
## Problem

Is there any way to get a DataObject from "Stage" only *and* it will have a hint that will make it get its has_many/many_many components from the correct table?

Im getting a "Stage" DataObject and switching back to Live mode after that. This then causes the template renderer to attempt to use *_Live components in the template.

The use case is when you're using the below modules so frontend users can create content:
- https://github.com/nyeholt/silverstripe-frontend-objects
- https://github.com/SilbinaryWolf/silverstripe-multirecordfield

## Recommended Solution (by @sminnee)

 * Add a boolean parameter, `$cascade` to `DataQuery::setQueryParam` that if set to true will apply the query params of a DataObject to any of that DataObject's relation queries.
 * Use this parameter in Versioned
 * Use this parameter in the SS4 versions of Subsites, Translatable, and Fluent

**Comment by sminnee** [comment]
When the parent query is generated, query parameters are set. However, these query parameters don't get cascaded into the relation queries that are subsequently called. I'd argue that this is a bug, even though I wouldn't tackle it until SS4 due to the amount of refactoring needed.

It would be semantically cleaner if the query parameters of a given DataList were passed through to each DataObject in some way, and then those query parameters were attached to the subsequent relation queries made from those data objects.

The `DataModel` concept would have been a place to hold this state, but it's a little still-born. In paricular, the query parameters could have been held within the data model, and then the data model passed from DataList to DataObject and the relation queries of a DataObject executed against its DataModel property rather than global `DataList::get()` methods.

**Comment by kinglozzer** [comment]
We already apply query the parameters to each `DataObject` created by `DataList`, using `DataObject::setSourceQueryParams()`. Is it just a case of copying the parameters through to the relational methods? Or is it unsafe to assume that we can just blindly copy all query parameters across?

**Comment by sminnee** [comment]
I'd say that should be safe, but it's a major release change, and we'd want to note it in the docs about query params so developers are aware.

Query params should be thought of as defining my view on the world, rather than fiddling the details of a specific query.

I'm not sure if they're used much outside of versioned and subsides; does

**Comment by sminnee** [comment]
OK so having a look at how setQueryParam is used, it seems as though there are query parameters that are single-query only 

 * RelationList::Foreign.Filter
 * RelationList::Foreign.ID
 * DataObject::Component.ExtraFields
 * ManyManyThroughQueryManipulator::Foreign.JoinTableSQL
 * ManyManyThroughQueryManipulator::Foreign.ID

Whereas other query parameters are more data-model-wide and would naturally be cascaded:

 * Versioned::Versioned.mode
 * Versioned::Versioned.date
 * Versioned::Versioned.stage
 * SiteTreeSubsites::Subsite.filter
 * Translatable::Translatable.LocaleFilterEnabled
 * FluentExtension::Fluent.Locale
 * FluentExtension::Fluent.IsFrontend

Based on this my recommendation would be that we:

 * Add a boolean parameter, `$cascade` to `DataQuery::setQueryParam` that if set to true will apply the query params of a DataObject to any of that DataObject's relation queries.
 * Use this parameter in Versioned
 * Use this parameter in the SS4 versions of Subsites, Translatable, and Fluent

**Comment by sminnee** [comment]
@silverstripe/core-team I've updated the original post with this solution. Does it makes sense to people?

**Comment by sminnee** [comment]
Actually looking deeper it seems as though this is implemented already...

**Comment by sminnee** [comment]
Hi @SilbinaryWolf I've just validated that this behaviour already exists with the following test: https://gist.github.com/b032d2ae250b2e387c79e828164db616

I'm assuming that you wouldn't have raised this unless you had run into bugs with this; can you elaborate on the bug that you're seeing?

**Comment by tractorcow** [comment]
This was implemented with https://github.com/silverstripe/silverstripe-framework/pull/5095

Check out `getInheritableQueryParams` method in DataObject; This ensures that child relations inherit the necessary query parameters in order to "stick" to the same stage / subsite etc.

Much better than waiting for a new major release huh @SilbinaryWolf :D

**Comment by sminnee** [comment]
Note that it's SS4-only, which may be why SilbinaryWolf ran into the issue

**Comment by tractorcow** [comment]
Also look at Versioned::updateInheritableQueryParams. It has extra logic in there that, for instance, ensures that sub-queries for specific version records are mapped to archive queries at the modified date of that version.

**Comment by SilbinaryWolf** [comment]
Yup, ran into this on a 3.2 project and didn't notice any of this functionality on the later 3.x versions.

**Comment by tractorcow** [comment]
I apologise but it's only going to work on 4.0 only... I hope that doesn't hold you up too much.
