### ISSUE TITLE
ManyManyList::appendExtraFieldsToQuery() breaks sort orders that rely on _SortColumn0

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#6730]
Boy was this fun to track down 🙄😅. Discovered this with the blog module - you’re unable to use `$many_many_extraFields` with it (e.g. I wanted sortable “Related news” on pages).

Simplified example that doesn’t rely on blog below. Tested on 3.x, but a glance at 4.x suggests the behaviour around this hasn’t changed.

```php
class Page extends SiteTree
{
    private static $many_many = [
        'TestPages' => 'TestPage'
    ];

    private static $many_many_extraFields = [
        'TestPages' => [
            'Foo' => 'Varchar' // Can be anything, doesn't matter
        ]
    ];
}

class Page_Controller extends ContentController
{
    public function init()
    {
        parent::init();

        foreach ($this->TestPages() as $page) {
            die('winrar');
        }
    }
}

class TestPage extends Page
{
    // Any clause that contains a space or parenthesis
    private static $default_sort = '"Title" IS NOT NULL DESC';
}
```

## What happens

- The query is set up, the `$default_sort` clause is added and uses `_SortColumn0` as an alias if the clause contains spaces or parentheses ([see here](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/model/queries/SQLSelect.php#L332-L342))
- An extra `SELECT` statement is added (e.g. `SELECT "Title" IS NOT NULL DESC AS _SortColumn0`)
- `ManyManyList::appendExtraFieldsToQuery()` calls `DataQuery::selectFromTable()`, which then wipes the list of fields being selected - meaning the `_SortColumn0` select statement is gone
- Errors happen:

> `Couldn't run query: SELECT [...] Unknown column '_SortColumn0' in 'order clause'`

## Fixing it

Perhaps make `ManyManyList::appendExtraFieldsToQuery()` instead call a new method `DataQuery::addSelectFromTable()`, rather than altering the behaviour of `DataQuery::selectFromTable()`. The naming of the `appendExtraFieldsToQuery()` method suggests that’s what it should be doing, rather than wiping existing selects out and starting again

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/6731

**Comment by camelscript** [comment]
I have something similar. There is 2 objects 
```
private static $db = array(
    'Date' => 'Date',
);

private static $has_one = array(
    'Location' => 'LocationPage',
);
```
and 
```
class LocationPage extends Page {

private static $db = [
  'Heading' => 'HTMLVarchar(250)',
  'SubHeading' => 'Varchar(250)'
];
```
If i do `return Schedule::get()->sort(['Location.Title' => 'ASC']);`
and later loop in template over sorted list it throws error:
[User Error] Uncaught SS_DatabaseException: Couldn't run query: SELECT DISTINCT "Schedule"."ClassName", "Schedule"."LastEdited", "Schedule"."Created", "Schedule"."Date", "Schedule"."LocationID", "Schedule"."ID", CASE WHEN "Schedule"."ClassName" IS NOT NULL THEN "Schedule"."ClassName" ELSE 'Schedule' END AS "RecordClassName", "LocationPage"."Title" AS "_SortColumn0" FROM "Schedule" LEFT JOIN "LocationPage" ON "LocationPage"."ID" = "Schedule"."LocationID" INNER JOIN "Page" ON "LocationPage"."ID" = "Page"."ID" INNER JOIN "SiteTree" ON "LocationPage"."ID" = "SiteTree"."ID" ORDER BY "_SortColumn0" ASC Unknown column 'LocationPage.Title' in 'field list'

I believe it is because of `"LocationPage"."Title" AS "_SortColumn0" ` since it is not called "Title" anymore

**Comment by dhensby** [comment]
@camelscript the problem there is that it's assuming the title is on the `LocationPage` table but it's on `SiteTree` and so the query is wrong.

@kinglozzer does your recent PR fix this?

If it doesn't then we'll need to investigate. @camelscript please confirm the version of silverstripe you're using

**Comment by camelscript** [comment]
@dhensby Yes that's what I noticed also, but taught that SS can resolve it to SiteTree. 
Framework: 3.6.0 CMS: 3.6.0

**Comment by kinglozzer** [comment]
No my PR won’t have fixed this @dhensby

**Comment by dhensby** [comment]
@camelscript can you open a new issue for this, please?

**Comment by camelscript** [comment]
New issue created #7029
