### ISSUE TITLE
Update Member.PasswordEncryption on password update

### ISSUE THREAD

**Issue by leomeloxp** [silverstripe/silverstripe-framework#6770]
After doing some work to implement a custom `PassswordEncryptor ` I noticed that for any user in the database once their *PasswordEncryption* property has been set, it is never updated.

This, imo, poses a little bit of a security concern as if I have an encryption method that gets compromise during the website's lifecycle and I decide to change the security setting to use a different encryption method it will only be applied to new users...

As seen in [`Member.php` lines 939-953](https://github.com/silverstripe/silverstripe-framework/blob/3.5.3/security/Member.php#L939-L953) this could possibly be changed very easily by just removing the *inline if* check and always use the Security set encryptor instead of the Database one for password changes, ie a new password is being encrypted and saved to the database with no bearings to the old one.

I may be able to provide this change as a PR in the next couple of days, but thought I'd bring the issue up first to see what others have to say (and potentially highlight any drawbacks from my proposed change).

Cheers.

**Comment by dhensby** [comment]
I agree with your sentiment but I don't think we should discard the current `PasswordEncryption` property because we rely on that to determine if the settings should change. see: https://github.com/silverstripe/silverstripe-framework/blob/3/security/MemberAuthenticator.php#L156-L160

There's also no guarantee that the current default is more secure than the current setting - we shouldn't just upgrade everyone on that assumption.

We do need a PR to MemberAuthenticator to use the config system instead of directly accessing the private static...

**Comment by sminnee** [comment]
Definitely don't discard PasswordEncryption, but yes, using the current default encryptor on update would be good.

**Comment by kinglozzer** [comment]
Resolved in https://github.com/silverstripe/silverstripe-framework/pull/7635
