### ISSUE TITLE
Lack of Config::inst()->update() confuses people

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6803]
I've seen a lot of people on silverstripe-users trip over the changes around config mutation.

I think that we should add a shim for Config::inst()->update() that

 * throws a warning, explaining both the new syntax and advising that people avoid config mutation in favour of yaml config
 * executes Config::modify()->update()

I think this will improve dev experience for upgrades

**Comment by tractorcow** [comment]
The risk here is that `Config` class is framework only. The actual `inst()` method returns a ConfigCollection, which belongs to config module. At this moment, config module has NO knowledge of any framework classes, so it would be troublesome for it to invoke `Config::modify()` from within the config module (adds new coupling).

Would it be acceptable for us to show the error (point 1) but make it a fatal error rather than have this invoke Config::modify() ?

**Comment by sminnee** [comment]
Yeah maybe a more helpful error message with instructions for updating would be okay.

**Comment by robbieaverill** [comment]
>Would it be acceptable for us to show the error (point 1) but make it a fatal error rather than have this invoke Config::modify() ?

That provides an obvious upgrade path to follow, which would be great.

**Comment by robbieaverill** [comment]
PRs opened above to remove its use then add a user warning when using it

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-config/issues/17
