### ISSUE TITLE
DataObject::write bug ( 3.1.19)

### ISSUE THREAD

**Issue by smarcet** [silverstripe/silverstripe-framework#6848]
hello there 
on framework/model/DataObject.php
class
line 1217
DB::query("INSERT INTO \"{$baseTable}\" (\"Created\") VALUES (" . DB::getConn()->now() . ")");

its using mysql NOW() function to set the Created field
but on next lines
is using function SS_Datetime::now()->Rfc2822() that user web server local time

that is an inconsistency IHMO , should use  SS_Datetime::now()->Rfc2822()  on line 1217 too

bc if db server time zone differs from webserver time zone, u will end up having some dataobject with one time zone sometimes and another time zone another time on field Created

please advice

**Comment by smarcet** [comment]
more over, this bug seems only manifesting when u write a data object that belongs to a hierarchy of dataobject

**Comment by tractorcow** [comment]
We should probably use SS_Datetime::now()->Rfc2822() consistently. However, 3.1 is long unsupported. We'll only be able to fix this in 3.4 at the earliest.

**Comment by smarcet** [comment]
Ok I see I will overcome this situation overriding now function and use a custom mysqldatabase c lass specialization to have a consistent timezone conversion regards

**Comment by patricknelson** [comment]
@smarcet An another alternative solution in the interim would be to ensure your DB and web servers are properly synchronized and using the same timezone. Is that possible?

Also yeah I think if you're setting dates, you should be consistent and (preferably) using more objective formats. I personally never see a need to make them "human readable" (because to me a database is for storing data) and just utilize UNIX time stamps for storing and transmitting time information wherever possible. If it needs to be presented to a human, I then mutate it as I see fit and, of course, take into account context (at which point I perform the necessary time zone mutations).

Hell I'll be crazy and suggest this be the moment for all out anarchy :dagger: 🔥  and use UNIX time stamps here instead. Not only are UNIX time stamps objective (based on GMT) but they're very easy to transform in PHP, sortable and can be stored as Varchar/Text if you're worried about `int` overflow... I will wait patiently for the inflammatory comments of objection to roll in 😄 As I'm sure there are some pretty good non-human reasons why we shouldn't be using UNIX time stamps.

**Comment by dhensby** [comment]
this is fixed in newer versions of 3.x and @patricknelson has waited long enough for inflammatory comments - I think we can close this now :)
