### ISSUE TITLE
What happened to DataObject::db()?

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-framework#6863]
It's there in `3.5.3` and `3.6.0-beta1`, but not `4.0.0-alpha6` or `4.0.0-alpha7` (I didn't check other alphas). It'd be understandable if there was an `@deprectated` tag on it in 3.x, but there isn't...

**Comment by tractorcow** [comment]
Most dataobject schema code has been moved to the new DataObjectSchema class.

`* `DataObject::db` removed and replaced with `DataObjectSchema::fieldSpec` and `DataObjectSchema::fieldSpecs``.

As a practice, we do sometimes remove API in 4.x but don't add deprecated notices to 3.x. You will need to verify with the upgrading guide, which admittedly has some outdated references that need updating.

**Comment by phptek** [comment]
OK, good to know, thanks. Can I suggest an `@deprecated` tag be added to 3.6.0-beta / stable (and to any others you know of that have undergone a similar change)? Sort of important IMO to ease any upgrade woes. Sort of important also, given the additional longevity of 3.x.

**Comment by dhensby** [comment]
I'm not sure if it was done, but happy to accept a PR for this deprecation

**Comment by tractorcow** [comment]
Normally we only add the deprecated notice if we can immediately provide an alternative; Since DataObjectSchema is 4.0 only, we can't actually deprecate it in 3.x (Unless, we modify our convention).

**Comment by dhensby** [comment]
ah, of course. breaking changes / removing methods that aren't explicitly deprecated is allowed in a major version bump

**Comment by phptek** [comment]
Really? That means maintainers can cheat by not adding deprecated flags, and remove said logic subsequently. Not saying the SS crew would do that, but it's akin to police arresting you and after protesting as to your having done nothing wrong, police saying: Yeah, that law isn't in the statute books yet, we forgot.

**Comment by phptek** [comment]
Here's an idea, possibly for the upgrader: Whenever this happens, push the name of the removed method to a text file called "deprecated.txt" somewhere in the relevant package. Then on dev/build run `grep-r` (and whatever the Win equiv is) over "mysite" or "app" for calls to each method, and throw an exception or user_error() when one is encountered.

**Comment by dhensby** [comment]
We never have made guarantee to maintain APIs across major versions unless they are deprecated...

Our approach is that anything goes in a major release (BC breakage, APIs removed/added, etc).

as @tractorcow points out, deprecations usually require a non-deprecated working API to use in its place (otherwise the deprecation notices are useless/annoying because you can't actually stop using them). What deprecation lets you do is plan ahead for when they do get removed, but you can't do that if the new API isn't available.

It may be interesting to have the upgrader pick up on old APIs you're using that are now gone, but really PHP tells you when you try to use an API that's gone ;) - if you're finding an API has gone and there's no note in the upgrade guide to fix it, then we should fix our upgrade guide.

**Comment by phptek** [comment]
For sure, for the upgrader I was more thinking that the text file had a mapping, pointing devs to the equivalent functionality, perhaps as a link to an upgrade guide or just a useful exception message (better than PHP's "method not found or is not public") which is something the framework itself does a pretty good job of these days ala "did you forget a has_one on the other side?" etc.
