### ISSUE TITLE
sitetree batch actions: select all/none

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-framework#6994]
It would be tree-mendous if the sitetree batch actions included "select all" and "select none" options. Right now I'm looking at a site with a few hundred pages that need to be individually ticked... also the "select all" feature should honour any filtering. Sorry about the pun.

**Comment by tractorcow** [comment]
I concur on this. It would be a nice feature, but please keep in mind that feature requests aren't generally raised on github issues, unless someone is willing to sponsor and implement this. If you feel like putting yourself forward @mikeyc7m that would be great. :)

**Comment by chillu** [comment]
Please keep improvements like this to uservoice.silverstripe.com :) "select all" is particularly difficult since we lazy load the tree - so "select all" might need to execute dozens of XHR calls to actually get a full representation of items on the client. For this reason, I don't see it being implemented anytime soon. In general, I think those batch operations are better suited for a GridField list view (where they're also missing at the moment). Closing
