### ISSUE TITLE
"Using environment variables" does not write config to ".env"

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7047]
![image](https://user-images.githubusercontent.com/936064/27409625-88ab29b8-5736-11e7-89f6-910b06535f9c.png)

At the moment checking this will load config from an existing `.env` file, but will not write config to a new one, should it not exist.

It should be trivial to fix this and DatabaseAdapterRegistry to build an `.env` writer that just writes to root dir.

PR at https://github.com/silverstripe/silverstripe-framework/pull/7332

**Comment by dhensby** [comment]
Should the installer write to a `.env` in these circumstances? Did it used to write to a `_ss_environment.php`?

I feel like we shouldn't be doing this...

**Comment by tractorcow** [comment]
I think we all have different understandings of what this means... I understand "read from env" but @sminnee reads it as "write to env".

The bug is "the behaviour is not clear", but the enhancement is "make it write to .env if it doesn't already have these settings". Even if we don't implement the enhancement we need to fix the UX issue.

**Comment by sminnee** [comment]
OK I believe it's pretty clear that the installer should be writing the .env file.

By "install SilverStripe" I mean "set the environment up as close as practical to how an experienced SilverStripe developer would set their environment up".

And as I'm sure you'll agree, in SS3 this means writing database credentials to an _ss_environment.php file, and in SS4, writing to a .env file (updating the apache config to include env vars there isn't really practical).

I guess from the above comments that this wasn't the previous behaviour. But I can't see any argument for this not being the default behaviour.

**Comment by dhensby** [comment]
My understanding was that all the settings used to be written to `mysite/_config.php` and it didn't set up an env file if you asked to set up from one.

It just used that env file to populate the installer instead of manually entered details.

Now I'm not against changing how the installer works, but if the aim is to "set the environment up as close as practical to how an experienced SilverStripe developer would set their environment up", then I don't think this feature should be opt in it should be the only way of doing it...

I caveat this all with the fact I rarely ever touch the installer when setting up a site so I may misremember how it works and apologies if that's the case.
