### ISSUE TITLE
Namespaced classnames in URLs

### ISSUE THREAD

**Issue by pitchandtone** [silverstripe/silverstripe-framework#7069]
I have two modules that "require" putting the full namespace into a URL because they follow a route that uses $ClassName as a parameter.

GridFieldExtensions uses it in their GridFieldAddNewMultiClass
DataObject Preview uses it in their Director routes:  'show/$ClassName/$ID/$OtherClassName/$OtherID' => 'show'

While GridFieldExtensions encodes the classname so that the backslashes become %5C, the form handler converts them back to /s in the form action, which means the doesn't actually submit.

While it'd be nice to have use Classname everywhere, these two modules seem to indicate that we should expect namespaced classnames to be able to be URL and correctly encoded by forms.

I have yet to track down exacty what causes the unencoding, but I'd be interested to know if:
a) Someone knows what it is
b) If someone has a better idea

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-admin/blob/master/code/ModelAdmin.php#L364

The best we can do is either sanitise / de-sanitise, or use an alias, or otherwise move to GET / POST argument for classname.

Best to raise this issue over at GridFieldExtensions module, since we probably won't have a global solution in core.

**Comment by tractorcow** [comment]
Oh look, someone came up with a fix at https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/182
