### ISSUE TITLE
4.0 PRESENTATION: position of add and delete buttons in ModelAdmin

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#7123]
It appears to me that the Create / Save button should be bottom right (logical data-entry flow is from top-left to bottom-right) and the Delete / Remove button should be bottom-left  (not right next to save) as this out of standard / normal flow... 

My apologies if this has been done for some good reason, but it appears to make more sense to me as above.

**Comment by dhensby** [comment]
I can defer this to someone with "UX" in their title, but this isn't actually correct from a usability nor accessibility point of view.

Users read right-to-left in lines starting again from the far left for each line. The line containing buttons should be the same (put them on the left).

Also, for users who need to use magnifiers because of visual impairments, the want the actions to sit under the labels of a form so it is easier to scan down the labels and then see the actions without having to go on a hunt for them.

**Comment by sunnysideup** [comment]
Ok - fair points.

I found a couple of interesting notes that helped me understand it better:

https://ux.stackexchange.com/questions/8569/submit-buttons-on-the-left-or-the-right

http://www.measuringux.com/SubmitCancel/index.htm

https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150
