### ISSUE TITLE
HTML4Value is still the default

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7310]
Should we update this to HTML5 by default.

We could merge https://github.com/silverstripe/silverstripe-html5 into core and deprecate HTML4Value instead.

**Comment by dhensby** [comment]
I think we need to find a supported HTML5 parser :/

**Comment by dhensby** [comment]
Quick google:

- https://github.com/Masterminds/html5-php (PHP 5.3+, actively maintained, reasonable contributor size, v2)
- https://github.com/ivopetkov/html5-dom-document-php (PHP 7.0+, actively maintained, small contributor size, v0.5)

**Comment by sminnee** [comment]
This simpler approach might be worth considering. It's a bit hacky but doesn't require an extra lib, and I'm also not sure about the performance differences of the PHP-based DOM parser.

https://github.com/nette/tester/commit/e60cf2d0718f6daf88426bb012e03a7c939cd2ac

**Comment by chillu** [comment]
+1 for the regex-based approach - this is something we run the most important site content through (`SiteTree.Content`). Which is why I think a straightforward regex holds less surprises than an entirely new DOM parser, at least for 4.x. From the test on Sam's link, it looks like you can still query those tags - it just silences the error message noise.

Note that `HTMLValue->getDocument()` returns a `DOMDocument`, but the Masterminds library uses that for its value representation as well - so it wouldn't be an API change AFAICT.

**Comment by robbieaverill** [comment]
For the HTML5 module upgrade I've made a PR to replace the parser with the Masterminds library, it was plug and play - see silverstripe/silverstripe-html5#18

**Comment by chillu** [comment]
Oh right, in that case at least it's not a lot of work :) Happy to go with Robbie's suggestion. Do we have any impression for the performance impact of adding such a library? Given it's popularity, and the lack of people complaining about it on the issue tracker, my assumption is that it's acceptable for the typical document sizes we're dealing with.

**Comment by GuySartorelli** [comment]
HTML5 is the default in CMS 5. Closing.
