### ISSUE TITLE
Navigating away from a search filtered GridField triggers "dirty" warning

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7327]
## Steps to reproduce:

* Go to Security
* Search for a member using any of the search columns
* Click on the member to edit it
* See "are you sure you want to leave" message

**Comment by unclecheese** [comment]
Not sure why this was closed. The issue persists for me. Can anyone confirm otherwise?

**Comment by maxime-rainville** [comment]
@lukereative fixed this with this PR https://github.com/silverstripe/silverstripe-framework/pull/8315

**Comment by unclecheese** [comment]
Confirmed working in Firefox and Safari, but not in Chrome. Can you have another look, @lukereative ?

**Comment by lukereative** [comment]
@unclecheese and I have done some investigation as to why this happens in Chrome:

Chrome is showing the warning because changing and submitting the pagination number is causing the edit form data to be detected as changed due to `detectChanges` being triggered at different times depending on the browser (specific function `admin/thirdparty/jquery-changetracker/lib/jquery.changetracker.js:127`)

Chrome triggers `detectChanges` on pressing enter in the page number input directly after editing the page number in the input causing the edit form to have changes detected and the `changed` class added **but** if we change the page number, focus out of the page number input field then go back into the field then press enter the `changed` class is not added to the edit form and thus no warning on navigation.

Firefox does not trigger `detectChanges` on pressing enter in the pagination and therefore the `changed` class is never added and thus the warning is never shown.

**Comment by bergice** [comment]
Merged.
