### ISSUE TITLE
Performance recommendation: DataObjectSchema caching

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7384]
Parent issue https://github.com/silverstripe/silverstripe-admin/issues/199

Many methods on DataObjectSchema require a significant amount of bootstrapping to populate from the config and underlying class model; It should be possible to apply a simple cache on top of this which will ensure that built caches are persisted across multiple requests.

These properties could be cached:

 - compositeFields
 - databaseFields
 - databaseIndexes
 - defaultDatabaseIndexes
 - tableNames
 
In addition we could move additional ClassInfo methods into DataObjectSchema which rely on schema:
 - ClassInfo::dataClassesFor
 
These methods are not well defined and could probably just be deprecated / inlined

 - ClassInfo::getValidSubClasses (deprecate / move to siteconfig)
 
 
Using a similar model to what we use for config, we could write the cache on __destruct / register_shutdown_function, and read from cache on DataObjectSchema::__construct.

**Comment by chillu** [comment]
Removing this from the milestone since it's the least "cost/benefit ratio" of all the suggestions (effort/medium and impact/medium).

**Comment by tractorcow** [comment]
I'm not sure how much of this work is necessary; We have probably over-estimated the impact. Most of these fields are recalculated each request, but from cached config. It may be more complex than we actually get in value from this.

@chillu I suggest we just close this and focus on feature development / bugfixes.

**Comment by sb-relaxt-at** [comment]
We have done some profiling in order to improve performance in the backend. Although the calls are cached on a lower level there is is an enormous amount of calls to these methods (10-20k) that sum up to several milliseconds of execution time even for simple methods. Our tests show that in-memory caching of these methods can improve performance by 10-20%. Especially the rendering of the treeview is about 20% faster (going down from about 180ms to 150ms). But even the frontend can benefit. We haven't done any testing on other website instances but we can gladly share implementation and detailed testing results.

**Comment by chillu** [comment]
Hey Stephan, that sounds very interesting - keen to see implementation and testing results :)
