### ISSUE TITLE
RFC Cache inherited permissions

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#7442]
Applies to assets + cms modules.

Inherited permissions are calculated and cached on a per-request basis, with all cached results stored in a protected variable which is rebuilt on each request.

It would be more prudent to cache this and persist across requests, flushing when models are modified.

# Acceptance criteria:

- On a cache-hit, no DB queries are required
- File / Page modification flushes the cache
- Member, Group or Permission modification flushes the cache
- The same cache is shared between members
- If new member permissions are checked, they're added to the existing shared cache
- The cache supports multi-server setups without creating inconsistencies
- Loading a 1000+ page tree (with three levels of nesting) with CMS_ACCESS_CMSMAIN permissions loads demonstrably faster than before

# Suggested implementation

 - InheritedPermissions takes a CacheInterface dependency, which it uses to cache and restore permissions. Each key would be cached by class and ID ~~, as well as `SSViewer.global_key config` arg.~~ and MemberID.

# Pull Requests

## Merge first
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7673

## Merge next
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7674
- [x] https://github.com/silverstripe/silverstripe-assets/pull/102
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2045

**Comment by tractorcow** [comment]
cc @chillu for review

**Comment by chillu** [comment]
Agreed, but too late for 4.0 stable. In particular since this stuff tends to have high impact side effects and regressions. Removing milestone.

**Comment by tractorcow** [comment]
Affect of this issue is minified slightly by https://github.com/silverstripe/silverstripe-assets/pull/83. Shall we merge this smaller change instead?

**Comment by tractorcow** [comment]
The real challenge here will be cache-invalidation; When we modify a page, is it possible to flush the cache for only itself and it's children?

**Comment by patricknelson** [comment]
Another concern on cache busting is something I noted in https://github.com/silverstripe/silverstripe-cms/issues/1977 - custom implementations of permission methods (e.g. `->canCreate(...)`) which rely on unknown external factors. Also, when it comes to caching, file system is fast, database is faster and memory is (by far) the fastest. I'm more concerned about constant repeated hits to a particular method than I am hits to the DB (unless it's hits to variations of the method, in which case the DB has to be avoided since every query will be unique). At that point, caching should probably happen at multiple levels:

- **Low level:** Very granular keys to ensure busted at parent/child level on modification. Propagate cache-busting up to parents when child is modified (if needed).
    - **Why:** On the level itself, this is already understood (above), notwithstanding the details I've added on children/propagation.
- **High level:** A single cached data structure retaining all calculated permissions thus far (so that is loaded once into memory).
    - **Why:** Due to granularity of the above, going to fetch a cached value from `[insert caching system here]` for each specific permission will likely cause about as much overhead as calculation of the original value itself anyway.

The high level (monolithic?) would be useful for me as well given I have a clustered system of multiple servers and SilverStripe's default cache mechanism is via file system (which the servers do not sure), meaning I'd have to use a database or some other TCP/IP-based cache anyway.

**Comment by patricknelson** [comment]
Actually, re-analyzing the stack, I suppose the "custom implementations" issue pointed out first above may not be as much of a problem, since the caching happens _inside_ of the method and not _prior_ to calling the method (so caching would be self-consistent and encapsulated). i.e. Calls to `parent::canCreate($member, ...)` would return the same result anyway, just faster, even if my custom implementation depends on other factors. At that point, caching is up to me.

**Comment by patricknelson** [comment]
:thinking: Actually.... both is happening, never mind. 

(Bear with me, like I said, still wrapping my head around it)

**Comment by patricknelson** [comment]
Ran out of time looking at this, but diving even further, it's not actually propagating permission checks on nested objects by utilizing the `->can*()` methods (from what I can tell); instead this only gets invoked after a call to a `->can*()` method. So I guess the issue still stands (but maybe for a different issue/RFC) on how `InheritedPermissions` checks (and also caches) permissions when a `SiteTree` object (which really this is what it's for) has an overridden implementation of one of those `->can(...)` methods.

As a case in point: I originally was going to use SilverStripe's built-in permission model, but realized that while it was capable of granular permissions (e.g. via `Permission::checkMember($member, 'CUST_PERM')`) and capable of inheriting permissions (e.g. this), it is not capable of inheriting granular permissions, e.g. does `$member` have permission to access `CUST_PERM` in the context of this particular `SiteTree` instance?

**Comment by chillu** [comment]
I've added a few ACs:

> Member, Group or Permission modification flushes the cache
> The same cache is shared between members
> If new member permissions are checked, they're added to the existing shared cache
> The cache supports multi-server setups without creating inconsistencies
> Loading a 1000+ page tree (with three levels of nesting) with CMS_ACCESS_CMSMAIN permissions loads demonstrably faster than before

Regarding disk vs. memory caching, the [DefaultCacheFactory](https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/Core/Cache/DefaultCacheFactory.php) already uses a memory cache if possible (APC, PHP files which are accelerated via Zend Opcache, and only then falling back to standard filesystem). @patricknelson If you needed a cross-server cache to avoid redoing that computation on multiple servers, that should be pluggable.

**Comment by chillu** [comment]
@unclecheese and @tractorcow to work through performance value of this card, moving into blocked for now

**Comment by tractorcow** [comment]
All core changes merged other than CMS and assets module. Almost there!
