### ISSUE TITLE
Potential regression with SSViewer::dontRewriteHashlinks()

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#7447]
I've just updated my `framework` to the latest `4.0.x-dev` on my sandbox host, and I've noticed that in code where I'm making use of `SSViewer::dontRewriteHashlinks()`, hash links are still being rewritten.  For example:

```php
public function getTemplate()
{
    return SSViewer::create([static::class])->dontRewriteHashlinks();
}
```

Prior to updating `framework`, rendering this object using `getTemplate()` would result in HTML with regular hash links. However, it is now ignoring the `dontRewriteHashlinks()` call, and the resulting HTML has rewritten hash links. Is this a possible regression in the last update to `SSViewer`?

**Comment by tractorcow** [comment]
The way it works is a little different to how it once worked; This method used to affect the global state, but now it only affects the specific template you are rendering.

Can you please share a working proof of concept that I can test locally?

**Comment by colintucker** [comment]
@tractorcow sure thing, [here you go](https://github.com/colintucker/hashlink-test). Clone and make a `.env` for it. On build, a `HashLink\Test\TestPage` will be created as a root page that renders an object with a hashlink.  Check the code of `HashLink\Test\TestObject` to see what it's doing.

**Comment by tractorcow** [comment]
I'll need to install php7... I'll get back to you.

**Comment by tractorcow** [comment]
I see the problem; Unfortunately, it's not easy to fix.

When the string is originally rendered, (in forTemplate()) the hash-link is NOT rewritten.

However after this has been included in the parent page, the parent page does not have rewrite hashstring disabled, and it'll rewrite this link anyway.

You may need to turn it off on the TestPage, not on the TestObject.

This works:

```
<?php

namespace HashLink\Test;

use PageController;

class TestPageController extends PageController
{
    public function getViewer($action)
    {
        return parent::getViewer($action)->dontRewriteHashlinks();
    }
}

```

**Comment by colintucker** [comment]
@tractorcow disabling it per page is indeed a workaround, but my apps consist of a graph of individual component objects, each one responsible for it's own rendering.  Some will require hashlinks rewritten, and some not.  So ideally we still need to be able to modify this behaviour on an individual basis (i.e. per `SSViewer` instance), which was the former functionality until these changes.

Would @chillu care to weigh in with his thoughts?

**Comment by tractorcow** [comment]
Well, we could use a new option in DBHTMLText to flag whether hash links are re-written or not; When a nested text is included in a parent template (e.g. a page including an include), it could use this option to prevent re-writing of links we'd explicitly not re-written.

This is the same problem, and solution, that we had for shortcodes; Previously shortcodes were re-written by parent containers. The fix was a `HTMLFragment` injector registration which created DBHTMLText with shortcodes disabled, and these are used as the default fragment holder.

**Comment by tractorcow** [comment]
I've had a look at this, and it doesn't seem possible for an inner template to disable hash rewrites in an outer template.

You will need to set the variable before rendering pages where you need to disable hashlink rewrites.


```php
<?php


namespace HashLink\Test;

use PageController;
use SilverStripe\View\SSViewer;

class TestPageController extends PageController
{
    protected function init() {
        parent::init();
        SSViewer::setRewriteHashLinksDefault(false);
    }
}

```

The issue we were running into with setting this variable in getTemplate() is that this is inside the rewrite loop, making it too late to set this variable. It is backed up, and restored after every render, so temporary modifications to this inside the loop are both overwritten, and reset at the end of the loop.

The long term fix is to not have rewriting at all, or just rewrite them explicitly rather than after the fact.

**Comment by tractorcow** [comment]
By the way, you can turn them on for individual objects inside a parent, but you can't do the reverse. For your project you'll need to do this on a case by case basis after turning it off for the entire page.

**Comment by mikeyc7m** [comment]
this makes me sad.

is there any way to output the included template without rerendering by the parent? seems pretty redundant for the parent to redo it. i can understand parsing it for collecting requirements, but why rerender?

i used to use a data-href attribute as a workaround, but it now chews that attribute as well. perhaps the regex could be fussier?
