### ISSUE TITLE
[I18N] BUG i18nTextCollector should support SomeClass::class syntax

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7647]
Currently the following would cause an error in the text collector:

```php
return _t(SomeClass::class . '.Title', 'Some title');
```

As a result, all modules need to use FCQN in strings when referencing translations in other files.

We should fix the parser to support `::class` syntax.

For reference, `__CLASS__` currently works.

## Pull requests

- [x] Support for `self::class`: #7648 
- [x] Support for `Some::class`: https://github.com/silverstripe/silverstripe-framework/pull/10577

**Comment by unclecheese** [comment]
The text collector works on static analysis, so this would be a big change. Even just getting `__CLASS__` to parse was a significant amount of work as I remember.

For strings that cannot be resolved statically, you should use `i18nEntityProvider`.

Relevant: https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/i18n/TextCollection/i18nTextCollector.php#L619

**Comment by unclecheese** [comment]
Just having a quick look -- it appears as if the intention is to skip entities that cannot be statically analysed. https://github.com/silverstripe/silverstripe-framework/blob/4.0/src/i18n/TextCollection/i18nTextCollector.php#L619

What was the error you were getting?

**Comment by robbieaverill** [comment]
I've added a PR to enable `self::class` at #7648.

As @unclecheese noted, due to the fact that this is using static code analysis, it's not realistic to allow `parent::class` (without reflection) or `static::class` at this stage.

I've got a WIP to enable `SomeObject::class` support, which can be done with the following assumptions:

* SomeObject has been imported via a `use` statement, or;
* SomeObject exists in the same namespace (global or otherwise) as the current class

I think with the two assumptions above that the first one is safe, because the class has a `use` for the class, so it's not that important if it exists. The second assumption is "safe" in that it's how PHP would treat the class too.

I'll chip away at this for a few days - I facepalmed pretty hard when I looked at this code.

**Comment by robbieaverill** [comment]
Yeah @unclecheese - there is some code that's using `::class` at the moment (it's already been noted that it's an issue, although not actioned yet) - see `SiteConfigLeftAndMain` for an example which has a set of `LeftAndMain::class` calls in it.

**Comment by unclecheese** [comment]
Nice work on this, @robbieaverill .

**Comment by tractorcow** [comment]
Instead of implementing this ourselves we should use the nikic/php-parser that's now a part of core.

In addition, I'd not be against splitting text collector into it's own module.

**Comment by robbieaverill** [comment]
>In addition, I'd not be against splitting text collector into it's own module.

That seems like a good idea to me, particularly because it's not required for the average developer, only module maintainers

**Comment by robbieaverill** [comment]
It sounds like @NightJar is keen to get involved with the remaining work on this too =)

**Comment by lekoala** [comment]
any update on this? SiteConfig uses SiteTree::class syntax which is not supported

**Comment by robbieaverill** [comment]
I don’t think it prevents text collection, but it certainly fills up your console with plenty of errors. Siteconfig and other modules are still incorrectly written and we would appreciate any pull requests to fix them up.

I got self::class going but SomeClass::class involves factoring in namespaces and is a bit trickier without using a php parser in this code. I got sidetracked and forgot about this :-D

**Comment by NightJar** [comment]
Not that I'm aware of sorry. I desired to get amongst it, but never found the time.

**Comment by lekoala** [comment]
I have thought a little about this, and maybe it's not quite necessary to support this syntax in _t. The current behaviour force the TextCollector to look at all modules to determine the "master" string. This adds a lot of complexity.
A simpler approach would be to have a clear distinction between "local" translation (inside the module) and "external" translation (use a translation from another module)

The whole thing could be then really simple:

_t('Entity.KEY', 'Default translation');
_g('Entity.KEY');  // here I introduce a _g helper which is for "global translation" 

Also, I believe we could skip the entity entirely and just do

_t('KEY', 'Default translation') ; // in that scenario, Entity would be the filename without the extension which would enforce consistent naming without any cost or __CLASS__ or static::class or whatever

This approach remove a lot of complexity : no need to "collect" or "handle" external translation. No need to provide a default translation when using an external translation (the current setting forces us to provide a translation otherwise we have a warning). Text collecting also become a lot easier because each module can be collected on its own.

I'm just saying that because I'm building my own TextCollector to overcome these specific issues, and it might be worth considering adding that to the core.

**Comment by robbieaverill** [comment]
I'm having a look at this now, and will continue on Friday. I started by using nikic/php-parser as an AST parser, which handles FQCN strings and `SomeClass::class` namespace resolution nicely, but since it works at parse time it still won't handle constants like `__CLASS__`. We can track the current class name and replace `__CLASS__` and `self::class` with it, but that still won't work for `parent::class` and `static::class` (even though they're edge case). I'm going to have a look into using phpstan instead, or [a combination](https://github.com/phpstan/phpstan-php-parser) of the two. Will update when I have some findings =)

**Comment by robbieaverill** [comment]
I've got an MVP module for collecting i18n entities from PHP classes using an AST parser: https://github.com/robbieaverill/silverstripe-textcollector. This is still a parse time approach, so won't support `parent::class`, `static::class`, or variables in keys/values, but now supports `SomeClass::class` easily. I haven't put much work into how to fold it into framework other than [a quick patch](https://gist.github.com/robbieaverill/b2fcb86b53ed6d9450a1fd0b33adad60) to plug it in.

**Comment by GuySartorelli** [comment]
This will be in 4.13 (if we release a 4.13)
