### ISSUE TITLE
Performance: ClassInfo::class_name() calls in DataObjectSchema

### ISSUE THREAD

**Issue by JayDevlin** [silverstripe/silverstripe-framework#7669]
While testing ss4 with xdebug, I‘ve noticed that there are a lot of calls (1600+) to `ClassInfo::class_name()` from `DataObjectSchema`. The purpose of this is to normalise the class name. That‘s fine but under “optimal” circumstances it is doing nothing except wasting quite a lot of CPU time (≈5%).

Test setup: a request to 'home' with default installation (framework, cms, simple theme)

ClassInfo::class_name()
![classinfo-class_name](https://user-images.githubusercontent.com/770383/33488924-94c5025e-d6b2-11e7-8f37-7900cfc51b9b.png)

"Proof of concept" patch: https://github.com/silverstripe/silverstripe-framework/compare/4.0...JayDevlin:performance-dataobjectschema

DataObjectSchema→getClassName()
![dataobjectset-getclassname](https://user-images.githubusercontent.com/770383/33488944-a6b48bba-d6b2-11e7-8176-e52454efe137.png)

Three tests are failing:
- DataListTest::testDataClassCaseInsensitive() //  tests normalisation
- DataObjectSchemaTest::testBaseDataClass() //  tests normalisation
- DataObject::testHasOwnTable() // “ReflectionException” is not thrown

https://travis-ci.org/JayDevlin/silverstripe-framework/builds/310036082

There might be circumstances where this normalisation is required, I guess, but is it really necessary for each request, for all classes and on any system?

Thoughts?

**Comment by kinglozzer** [comment]
We do need to normalise them, but I think there are a few cases where we could normalise them with `strtolower()` instead which should be faster.

**Comment by JayDevlin** [comment]
`ClassInfo::class_name()` does `strtolower()` the class name for using it as a cache key, but then it returns the correct notation.

When is `eg: ClassInfo::class_name('dataobJEct'); //returns 'DataObject'` needed?

**Comment by kinglozzer** [comment]
Yep, we could skip looking up the correct notation entirely is what I mean - that’s the expensive part as it triggers reflection (and possibly autoloading).

There are a few places currently, e.g. `$className === DataObject::class`, `cacheTableNames()`, `cacheDatabaseFields()` etc use the correct notation as keys. I don’t spot any that are impossible to patch to lowercase, though

**Comment by JayDevlin** [comment]
Ok, more questions:

What is the purpose of `strtolower` classes in `DataObjectSchema` when every class is in correct notation? What is the use case, why is it needed?

And what is the purpose of
```
$this->expectException(ReflectionException::class); // <- test failure
// Failed asserting that exception of type "ReflectionException" is thrown.
```
in `DataObjectTest::testHasOwnTable()`? Do we need this there?

The next assertion
```
$this->assertFalse($schema->classHasTable("ThisIsntADataObject"));
```
works fine without  `ClassInfo::class_name() ` in `DataObjectSchema`.

**Comment by kinglozzer** [comment]
@tractorcow is probably better positioned to answer these, but...

>What is the purpose of strtolower classes in DataObjectSchema when every class is in correct notation? What is the use case, why is it needed?

I’m pretty sure the purpose of normalising them is because we can’t guarantee that the class is always _passed_ with the correct notation to `DataObjectSchema`. We can guarantee that for core, but not for third party modules/project code.

Not sure I understand your 2nd question. `$this->assertFalse($schema->classHasTable("ThisIsntADataObject"));` isn’t supposed to work, it’s supposed to throw an exception because a class named `ThisIsntADataObject` doesn’t exist. That’s what `$this->expectException()` is telling PHPUnit - to expect an exception

**Comment by JayDevlin** [comment]
1) Ok. It's a little strange but well... it's php after all.

2) What I meant is that the test is correct by asserting that `ThisIsntADataObject` doesn't exist. It doesn't throw an exception because I didn't provide any reflection in my PoC. I will think about that.

**Comment by chillu** [comment]
> I’m pretty sure the purpose of normalising them is because we can’t guarantee that the class is always passed with the correct notation to DataObjectSchema

I think as long as we can clearly throw exceptions on non-existent classes, that'd be an acceptable change for a 5% overall performance improvement. It's a bit hard to say what effects this has for high usage `DataObject` APIs. Most of them use `self::class`, there's only secondary APIs like `DataObject->getRemoteJoinField()`. And stuff like `ClassInfo::dataClassesFor()`. It sounds like a change we could make in 4.x?

**Comment by dhensby** [comment]
This originates from issue #3938 and fix #3949

The reason we normalise the classnames is because we need to:

1. Treat classnames we receive as case-insensitive to mimic PHP behaviour - some devs expect to be able to use any case to reference classes because PHP.
2. This "fix" was implemented in 3.x and so we had to ensure the changes were backwards compatible, this meant that caches that were previously storing values based on the "normalised" class value remained that way, we couldn't just make all caches (or anything else) suddenly rely on lowercase names.

It would have been good to make everything rely on lowercased classnames in the 4.x release, but we didn't keep tabs on that and so it hasn't happened.

I don't see that we have much scope in the 4.x line to stop normalising class names in this way...

**Comment by JayDevlin** [comment]
This is not really pretty but radically cache everything in `DataObjectSchema` would gain even more.

DataObjectSchema
![dataobjectschema](https://user-images.githubusercontent.com/770383/33565244-e738119a-d91c-11e7-845b-5af920d94e12.png)

"Proof of Concept" patch:
https://github.com/silverstripe/silverstripe-framework/compare/4.0...JayDevlin:performance-dataobjectschema-2

CachedDataObjectSchema
![cacheddataobjectschema](https://user-images.githubusercontent.com/770383/33565267-f4fce1c0-d91c-11e7-9a84-119c4cf3b1af.png)

Except one behat test, all tests pass:
https://travis-ci.org/JayDevlin/silverstripe-framework/builds/311392430

**Comment by dhensby** [comment]
The caching patch seems much more reasonable (though the approach could be better - I get it's just a PoC).

Do we have any data on memory usage increases?

A lot of our "performance" improvement patches do just push CPU usage into memory usage, so whilst we might be improving performance in speed we are regressing performance in memory.

**Comment by JayDevlin** [comment]
Not really sure if this is correct but I got these results:

DataObjectSchema:
memory_get_usage($real_usage = false): 6191656 bytes
memory_get_usage($real_usage = true): 2097152 bytes
memory_get_peak_usage($real_usage = false): 6200024 bytes
memory_get_peak_usage($real_usage = true): 2097152 bytes

CachedDataObjectSchema:
memory_get_usage($real_usage = false): 6242704 bytes
memory_get_usage($real_usage = true): 2097152 bytes
memory_get_peak_usage($real_usage = false): 6250912 bytes
memory_get_peak_usage($real_usage = true): 2097152 bytes

**Comment by JayDevlin** [comment]
> $ ab -n 1000 -c 5

DataObjectSchema:
Time taken for tests:   25.961 seconds
Requests per second:    38.52 [#/sec] (mean)
Time per request:       25.961 [ms] (mean, across all concurrent requests)

CachedDataObjectSchema:
Time taken for tests:   24.147 seconds
Requests per second:    41.41 [#/sec] (mean)
Time per request:       24.147 [ms] (mean, across all concurrent requests)

**Comment by kinglozzer** [comment]
R.e. caching, I’d suggest adopting the approach outlined in https://github.com/silverstripe/silverstripe-framework/issues/7384 so it’s persisted between requests 👍

**Comment by JayDevlin** [comment]
I'll look into this. It will take some time for me to come up with something presentable.

**Comment by tractorcow** [comment]
> We do need to normalise them, but I think there are a few cases where we could normalise them with strtolower() instead which should be faster.

I dislike strtolower in general because it messes up case-sensitive class names, such as injected service references. It's a massive performance cost to act in a case-insensitive fashion such as we have been trying to maintain.

**Comment by tractorcow** [comment]
> What is the purpose of strtolower classes in DataObjectSchema when every class is in correct notation? What is the use case, why is it needed?

I assume you mean in `ClassInfo`. It's because user-code in 3.x (that we are trying to support in 4.x) had a lot of cases where we would try to get db fields for classes such as `sitetree` vs `SiteTree`.

If we don't do this, we end up with lots of duplicate caches which only differ based on case.

We could probably be a bit less strict and refactor out into a strtolower($class), but only on cache keys, and only as long as those case-incorrect keys were never returned from a method (returned values should be case-correct only).

It just requires someone to go through, update all class_name() call, and refactor out where possible.

For instance, DataObjectSchema::$databaseFields could possibly be lowercase keys, but not DataObjectSchema::$tableNames, since the key is returned from DataObjectSchema::tableClass() via array_search.

**Comment by JayDevlin** [comment]
> I assume you mean in ClassInfo.

The goal was/is to try to reduce calls from `DataObjectSchema` to `ClassInfo` by skipping normalisation by `ClassInfo` and just `strtolower` in `DataObjectSchema` instead. I asked the reason about `strtolower` because I write my class names in correct notation and expect most users do too (so normalisation is not needed or desired). `strtolower` is a good tradeoff because its footprint is negligible. Though, @dhensby mentioned that caches need to be normalised and backwards compatible, so I've not thought about that further and simply cached everything instead.

Normalisation is not an issue. ClassInfo::class_name() is not an issue. A thousend calls to `ClassInfo` is not a real problem either. But a thousend times normalising correct notations of class names and eating performance for nothing is an issue.

**Comment by tractorcow** [comment]
> because I write my class names in correct spelling and expect most users do too (so normalisation is not needed or desired).

We decided a while back to support case-insensitive class names in user code to match PHP behaviour. Still, I agree we are far too rigorous with our approach. :)

For instance, maybe the tableNames array could be split into two mapping tables, so that each could have lowercase names for search lookup? (spend memory to get performance).
