### ISSUE TITLE
Themed asset inclusion using ResourceLoader breaks manual template rendering

### ISSUE THREAD

**Issue by dhensby** [silverstripe/silverstripe-framework#7729]
## Affected Version

4.x

## Description

With the new themed resources one now includes themed CSS, images and javascript using template helpers such as `<% themedCSS("css/main.css") %>`; this would have been `<link rel="stylesheet" href="$ThemeDir/css/main.css">` in SS 3.

When executing a template like so: `SSViewer::execute_template('Template');` the themed resources are not included. This is because `execute_template` disables the inclusion of requirements (which is helpful as we don't want requirements from the main request thread included in our one-off template rendering) but then means the `themedCSS` (or other themed resources that are brought in) are ignored.

I'd expect that the themed resource to be included in the rendered template.

## Steps to Reproduce

- Create a template with the themed resource included (eg: `<% themedCSS('cssfile.css') %>`)
- Render template using `SSViewer::execute_template()`
- Notice themed resource is not included

**Comment by tractorcow** [comment]
I'm not 100% sure I agree with the conclusion, although I'll admit this is a problem. `<% require %>` calls in templates aren't instructions to include that specific requirement in that actual template, just in the final page call. That is why you can have a `Widget.ss` that adds a `<% require %>` which actually sends that requirement up into the page header, potentially several templates higher up the chain.

`<% themedCSS("css/main.css") %>` works the same way in 3.x, this is not a new change.

The problem I agree with is the fact that these resources aren't being emitted anywhere. This is due to the nature of Requirements_Backend being bound to a static member on Requirements object. That's a lot harder to solve.

Wouldn't a simpler fix for the time being be to allow `execute_template` to conditionally include requirements for the time being? A larger refactor of requirements persistence could be done later. This would probably be something similar in scope to the de-staticifying to Session object.

**Comment by tractorcow** [comment]
Ok, I've slightly modified my feeling on this. I've documented that over at https://github.com/silverstripe/silverstripe-framework/pull/7730#issuecomment-355871510 with some recommendations. :)

**Comment by tractorcow** [comment]
Fixed with #7730
