### ISSUE TITLE
RFC: DataList::toRawArray() - Fast querying of data for things that need a low response time

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#7753]
**Problem I'm aiming to solve:**
When you want to get data from a large amount of records and have rapid response time (ie. for an autocomplete field), the current paradigm I have generally seen is a direct `DB::query()`.

I think we can get the benefits of the ORM and keep things fast if we just add a function to DataList which returns raw data.

**How it might look in code (using 3.6.X)**
DataList::toRawArray()
```
public function toArray() {
	$query = $this->dataQuery->query();
	$rows = $query->execute();
	$results = array();

	foreach($rows as $row) {
		$results[] = $row;
	}

	return $results;
}
```

DataList::toArray() (for comparison)
```
public function toArray() {
	$query = $this->dataQuery->query();
	$rows = $query->execute();
	$results = array();

	foreach($rows as $row) {
		$results[] = $this->createDataObject($row);
	}

	return $results;
}
```

**Comment by chillu** [comment]
Hmmm, it weakens the `DataList` API, particularly since we'll have `toNestedArray()` (uses `DataObject->toMap()`) and `toRawArray()` (straight up database results). I think mixing those abstraction levels isn't helpful, if you want to bypass the ORM on that level than don't work on a `DataList` level, and go down to `DataQuery` instead. Given that we already have `DataQuery->firstRow()` and `DataQuery->lastRow()`, maybe we could add `DataQuery->allRows()`. I think this is mostly about discovering how to use this lowlevel API, maybe you can have a crack at documenting this better?

**Comment by silbinarywolf** [comment]
I have no problems with making this happen at the `DataQuery` level and adding documentation around this.

Then I can still do my filtering on a DataList and call `DataList->dataQuery()->allRows()` to retrieve raw data if I need that speed boost.

Assumptions are that the following needs to happen for a PR to get in:
- Add DataQuery->allRows() function to SS4
- Add unit test for allRows() to SS4
- Update documentation with example of accessing raw SQL data and why you might want this functionality.
- Seperate PR after merged in, backport to SS 3.X (if time permits)

Let me know if this is correct. I'll be keeping on an eye on this but I won't have time to action it for a couple of months I'd say.

**Comment by maxime-rainville** [comment]
I'm not sure about this one. I'm thinking people who have a specific need for this are probably better off doing a `DB::query()` instead.

**Comment by chillu** [comment]
OK two core committers tending against this change, and no further traction. I'm going to close this.
