### ISSUE TITLE
Prepare for GDPR compliance

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-framework#7791]
On 25 May 2018, the [EU General Data Protection Regulation (GDPR)](https://www.eugdpr.org/) will come into enforcement. SilverStripe should decide to what extent it should change the core code to accommodate this change, to what extent it can provide advice about best practices, and to what extent it is left up to the individual site owners.

In addition, best practices can be established for what data is stored by default, what is done with that data, and how it is stored, processed, and disclosed.

At minimum a blogpost or docs update that addressed potential areas to look at or config settings to tweak would be a great bout of confidence for the community.

**Comment by DorsetDigital** [comment]
As a starting point, it's probably worth considering what the core system actually stores that falls under the regulation.   From what I can see, the following are the only issues:

Member table: Name, Email, etc.
LoginAttempt table:  IP, Email

As I understand it, the critical things we need for GDPR are statements about the use of the data, and means to expire it, etc.

For the second of the two, the simplest way to deal with it would be to take it out of the equation altogether.  If it were possible to disable the loginattempt logging with a configuration option, that solves the issue.   If the loginattempt data is needed, then some mechanism to expire/purge it periodically (maybe an add-on) would help.

**Comment by dhensby** [comment]
a good place to start: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr

**Comment by chillu** [comment]
I agree that GDPR compliance itself is critical (we've started reviewing our own systems like SilverStripe Platform and silverstripe.com/org back in November). But in the context of our open source software, my understaning is that the software itself is neither a "Data Processor" nor a "Data Controller". It really depends on what you build with it. I agree that some documentation about potential privacy impacts emerging from our software would be nice. But unless somebody thinks we need to change our APIs or system behaviour, it's not `impact/critical`. I'll raise a GDPR blog post with our marketing team! :)

**Comment by chillu** [comment]
Regarding `LoginAttempt`, there's been [recent changes](https://github.com/silverstripe/silverstripe-framework/commit/f1dd3d6f03eb1d94c29c495994a1da9176a758d9#diff-41b85a1c8dd9a73784e8b33811f10130) to only store the email hash rather than email address itself. For existing users with matching email addresses on the attempt, we're still [associating](https://github.com/silverstripe/silverstripe-framework/blob/d876e36424918909b65c0c53d4d682d50aadcf7b/src/Security/MemberAuthenticator/MemberAuthenticator.php#L165) IPs to members though, so are effectively storing personally identifable information. 

You can turn off login recording via `Security.login_recording: false`. But in its default behaviour, it means that any website might need a privacy statement for CMS users, even if you're not collecting data from visitors or providing other login-based services. Maybe "business applications" like the CMS are exempt from GDPR, if the CMS user is employed by the "data controller" organisation?

**Comment by dhensby** [comment]
Also `login_recording` is implicitly on when `lock_out_after_incorrect_logins` is set

**Comment by chillu** [comment]
@dhensby Do you want to have a crack at summarising what personally identifiable data SilverStripe CMS stores by default, e.g. as part of https://docs.silverstripe.org/en/4/developer_guides/security/secure_coding/, or as another "privacy" page in that section?

**Comment by christopherdarling** [comment]
Given that most people use Google Anaytics or similar one thing that you may want to include is that the `LostPasswordHandler` by default redirects to a URL that contains the users email address which is PII and will end up in Analytics software https://github.com/silverstripe/silverstripe-framework/blob/af2c3886b90bcb2c2964633c9dcc33c91d960140/src/Security/MemberAuthenticator/LostPasswordHandler.php#L264-L273

**Comment by kinglozzer** [comment]
Excellent point @christopherdarling. Ultimately that’s going to depend on how people implement their analytics snippets, but I suspect that many people put it directly in `Page.ss` meaning `Security` URLs will include tracking code.

Perhaps we should move the email to the session, rather than the URL?

**Comment by christopherdarling** [comment]
Yeah, I think that's most likely the case. It's certainly how most of my sites have been implemented at least.

Moving to session sounds a good suggestion

**Comment by dhensby** [comment]
What do we need the email for at all in this context? To say we sent an email to: [insert email]? We can just remove that feature completely, it's not really needed

**Comment by christopherdarling** [comment]
@dhensby  I'd agree with that, it wouldn't bother me if it were removed.

**Comment by chillu** [comment]
Created ticket for email issue: https://github.com/silverstripe/silverstripe-framework/issues/8080

**Comment by chillu** [comment]
> Given that most people use Google Anaytics or similar one thing that you may want to include is that the LostPasswordHandler by default redirects to a URL that contains the users email address which is PII and will end up in Analytics software

Just following up on this, that's been resolved for a while through https://github.com/silverstripe/silverstripe-framework/commit/560fe9820a51eb3001dafdc1e34806434392a3e3#diff-a01f0c31fe0157e58576a47bffd12adc.

I can't see any specific action left on this ticket, closing.
