### ISSUE TITLE
Support get_by_id without $callerClass

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#7888]
I always get a bit annoyed when I have to write `MyClass::get_by_id(MyClass::class, $id)` because it seems like such a redundancy to write that second MyClass. 

I know how I can make it support `MyClass::get_by_id($id)` while maintaining full backwards compatibility, but before doing that and submitting a PR I thought I'd first hear whether people would be against it.

**Comment by dhensby** [comment]
I think the general view is that we'd like to do away with `DataObject::get_by_id()` and replace it with `MyObject::get()->byID()` - the reason `get_by_id` has hung about is because it's got a cache backing it and no one has got round to caches to back `DataList`.

So... taking into account nothing has happened to properly deprecate `get_by_id`, I'd definitely consider a PR for adding the `MyObject::get_by_id()` syntax if it was BC safe

**Comment by JorisDebonnet** [comment]
Being handled and discussed in PR #7894.
