### ISSUE TITLE
Improve public webroot upgrade path

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7920]
# Overview

The [upgrade instructions](https://docs.silverstripe.org/en/4/changelogs/4.1.0/) around the public webroot require too much knowledge from users.

# Acceptance Criteria

 * Only kicks in when `public` subfolder is created by the user
 * `assets` are moved automatically to `public/assets`. The user gets an info message that this likely needs to be manually migrated in other hosting environments
 * If I have a `.htaccess` file in the base path that's different from the `3.x` defaults, I get a warning and instructions on how to migrate (link to contents of new file)
 * If I have an `index.php` in the base path, I get a warning and instructions on how to migrate (link to contents of new file)
 * Auto-run `composer vendor-expose`
 * Show an info message suggesting an "expose" configuration for `composer.json` for common public folders in `themes` (`js`, `javascript`, `dist`, `css`, `styles`, etc). Point out that any hardcoded paths will break, and link to detailed theme docs that work with the public subfolder
 * The current [upgrade instructions](https://docs.silverstripe.org/en/4/changelogs/4.1.0/) are updated to reflect this automatic task, but also spell out what happens behind the scenes
 * The upgrade instructions are moved from 4.1.0 to 4.0.0, with a note that this section only applies to >=4.1.0 upgrades. Most devs will read the 4.0.0 guide, and likely miss the 4.1.0 link at the top. This shouldn't become a pattern for all upgrades, but this one is important.
 * The upgrade instructions make it clear that hosting config changes are required to deploy this (and points out that it works out of the box on SSP and CWP)
 * The `.htaccess` file only contains relevant rules when placed in the `public/` subfolder, removing unnecessary noise like `RewriteRule ^vendor(/|$) - [F,L,NC]`

# Notes

 * Explicitly removing unnecessary rules from `.htaccess` when moving to `public/` subfolder is preferrable to introducing the complexity of conditional `public-files` via the vendor plugin
 * Once the `.htaccess` file has been modified and moved into the `public/` subfolder, it becomes unsafe to opt out of using `public/` later, since that file will be missing rules. This is acceptable, but ideally we can warn users about it if there's any automatic process moving `public/.htaccess` to `.htaccess`
 * ~~Track under ORB-162~~

# Pull Request
* [ ] https://github.com/silverstripe/silverstripe-upgrader/pull/78

**Comment by Juanitou** [comment]
> If I have an index.php in the base path, I get a warning and instructions on how to migrate (link to contents of new file)

This has already bitten me, as following the instructions and just moving the `index.php` from a 4.0 install breaks the autoload logic. More details in the [Slack thread](https://silverstripe-users.slack.com/messages/C36U3BDHN/convo/C36U3BDHN-1521697874.000165/?thread_ts=1521697874.000165) (thanks to bummzack for the workaround).

**Comment by chillu** [comment]
@Juanitou Good point, I've added that to the upgrading docs:

> If upgrading from 4.0, replace the file the [index.php](https://github.com/silverstripe/recipe-core/blob/1.1/public/index.php) from `recipe-core` in order to fix autoloading paths

Should be on doc.ss.org in an hour or so

**Comment by tractorcow** [comment]
Making a note that we'll probably roll this into the upgrader.

**Comment by tractorcow** [comment]
See https://app.zenhub.com/workspace/o/silverstripe/silverstripe-upgrader/issues/65

**Comment by maxime-rainville** [comment]
# What will happen
1. If you don't have a `public` folder we create one for you.
1. If you have an assets folder, it gets move to your public folder.
1. If there's a `.htaccess` file and it is identical to the standard SS3 one or the SS4 one:
  * We delete it and replace it with the root recipe core one.
  * We create a .htaccess file in public matching the one in recipe-core.
  * Alternatively, if it's not identical, we move it to public with a warning
1. Delete the `index.php` from the root (if present), and copy the recipe core `index.php` to public.
1. Run a `composer vendor-expose` (Yeah for Max’s new `ComposerExec`)
1. Warn about VHOST and hardcoded paths needing update.

Last step will either write the change if you have set the --write flag or display which files would have been move to where and `diff` for file that would have been changed.

# Prerequisite
I’m thinking we should make having having `recipe-core:^1.1` installed a prerequisite to do all of this. For one thing, we need the silverstripe vendor plugin installed to do the the `vendor-expose`. If I need to copy stuff from recip-core, it will make the process easier. Otherwise, I’ll need to get it from github, or copy the file content in the upgrader codebase, which would make the process nightmarish when we push out a SS4.2, SS4.3, etc.

# What kicks off this crazy process
I’m not sure about this criteria:
> Only kicks in when public subfolder is created by the user

I think it would make sense to minimise the number of conscious decision the developer has to make. If you are already thinking of upgrading to the new `app` structure why would you feel upgrading to the new public structure is a bridge too far?

The options I can think off the top of my head:
* Create separate command from `reorganise` dedicated to this task.
* Add an optional opt-in flag on the reorganise command.
* Add an optional opt-out flag on the reorganise command and do the public migration by default.
* Auto trigger the behavior on the `reorganise` command, but only if you have installed `recipe-core:^1.1`. This could be combine with the opt-out flag
* The original trigger behavior of requiring the user to manually create a public folder

# Nice to have
* What about we do a 3 way-merge for the `.htaccess` file and the `index.php` file. https://github.com/bircher/php-merge

**Comment by chillu** [comment]
> I’m thinking we should make having having recipe-core:^1.1 installed a prerequisite to do all of this. 

I assume you're adding this through the "composer.json rewrite task" you've just gotten into peer review? If that's the case, I'm fine with it.

> Only kicks in when public subfolder is created by the user

Yeah, that was written before I decided that we should tie all those commands together into a wrapper command. Happy with a dedicated task.

> What about we do a 3 way-merge for the .htaccess file and the index.php file. 

I think for now, just replace the .htaccess file, show before/after file in output, and allow devs to adjust.

**Comment by maxime-rainville** [comment]
Cool. I'll go with a separate command ... it does have things in common with reorganize as it moves files around, but the two can be done independently from one another and it does have intricacies that differ from reorganise.

I shall christen this one ... `webroot`.
