### ISSUE TITLE
RFC: Default config folder should be "config"

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#7954]
Following on from #7946, a lot of people have mentioned that putting an underscore in the config folder name is kind of redundant.

Although for back-compat we'd want to keep allowing _config, we should also allow "config" and we should use that value in our documentation and project/module skeletons.

## Identifying SilverStripe modules

The historic reason that _config was used was as a marker to detect whether a folder represented a SilverStripe module. "config" is much less unique and so that can't be used as a marker - we'd need something else.

In principle, it should be possible to use some composer.json metadata (type = silverstripe-module || silverstripe-vendormodule) to do this. I can't recall how much code is already in place to support this or whether this will have a performance impact.

Notably, this won't work for modules that aren't based on composer packages. For example if we retained the use of `app/src` and `app/config` then we'd need to be able to mark "app" as a SilverStripe module. We'd likely need a new mechanism for doing this.

**UPDATE:** Upon further thought this latter comment makes me think that this RFC might be more trouble than it's worth. We're going to make virtual modules materially harder to support, and that seems like a lot to give up for the sake of an underscore.

## _config.php

I don't know that we should move this file - it's a hangover from SilverStripe 2 and we should probably deprecated it more fully. But this change does mean that you'll have `_config.php` and `config/something.yml` as your config locations.

Alternatively we could allow `config/bootstrap.php` or something as the php-loaded config location.

**Comment by sminnee** [comment]
> Backward compatibility probably isn't a reason to keep it.

In 4.x, we have to keep looking for config files in `_config/` even if we deprecate it.

**Comment by drdrak3** [comment]
For me, it depends on where the config folder is. If it remains mixed in with folders that **might** be modules/sub-modules, then an application may have a **config** submodule, which would be difficult to differentiate. I like the underscore as it separates configuration/yaml files from PHP code.

**Comment by sminnee** [comment]
Good point, although I'd note that modules will typically be in vendor/

**Comment by sminnee** [comment]
@patricknelson you should probably see my latest updates in the description in which I talk myself out of this idea.

**Comment by patricknelson** [comment]
Maybe part of the problem is the allowance of modules in the root in the first place? This is a pretty broad discussion (since it also covers #7946 and probably others) but that suggests a more Laravel-esque approach of each root folder having a special meaning. Personally, I'm vacillating between `app/config/` and `config/` for this very reason. I've _always_ thought modules belonged under `vendor/` with front-end files being copied/farmed out to a _separate_ `public/` folder, so there are a lot of fundamental differences between my preferred way (basically Laravel) and The SilverStripe Way ™️ .

**Comment by patricknelson** [comment]
Updated above with:
> (or some other separate folder not maintained by composer that you could commit directly to, such as modules/)

**Comment by patricknelson** [comment]
Right. I'm forward thinking, in the sense that maybe SS 5.x should no longer allow modules in the root. Even that is pretty aggressive, since I still personally like having a place to put private modules that I build myself without having to go through all the extra effort of making it `composer`-ified.

**Comment by sminnee** [comment]
> still personally like having a place to put private modules that I build myself without having to go through all the extra effort of making it composer-ified.

Could you elaborate on how you manage those modules? This use-case seems material to the discussion so it'd be good to get more data.

**Comment by patricknelson** [comment]
Right now it's pretty obvious. I just do it the SilverStripe way and put them into the root. And, as implied by the "`composer`-ified" statement, the result is that it's just that -- a folder in the root that also _does not_ contain a corresponding separate repository, `package.json` file, `packagist` entry and so on. Because it's private and quick and easier to update that way (but not shared among multiple sites). At that point, then you still have to drop in the extra effort.

So, there's a grey area when you want to build out module-like functionality, but not yet at the stage where it's properly separated and managed like a true module. That is, a single site, private module.

**Comment by sminnee** [comment]
At okay so you're not just checking the code into your project repository and using the module on a single project?

**Comment by patricknelson** [comment]
Your question doesn't compute. There's a fairly slim, but real grey area where you can either utilize an existing module (i.e. direct download, extract, _modify_ and then use) or build your own where you commit the code directly. In a single project. Does that help, @sminnee ?

**Comment by robbieaverill** [comment]
I don't like the idea of changing this convention for SS4, but since we've already changed mysite to app for 4.2 we could probably get away with it if it's backwards compatible.

Totally makes sense to me to do this for SS5 though.

**Comment by GuySartorelli** [comment]
I like both the idea of changing `_config/` to `config/` and `_config.php` to `config/bootstrap.php` or something similar (note that in CMS 6 we will be checking the "type" in composer.json to determine if a module is indeed a module, in addition to falling back on the specifically-named `_config` file and dir) - though I do note there is very little real-world benefit to doing so. If someone wants to raise a pull request for this work I'll happily review it, but the CMS Squad is extremely unlikely to prioritise this work.

**Comment by sminnee** [comment]
the ticket has been open since 2018, feel free to close it.
