### ISSUE TITLE
removeFieldFromTab returns wrong value

### ISSUE THREAD

**Issue by worikgh** [silverstripe/silverstripe-framework#7986]
## Affected Version

$ ../composer.phar info --direct
mpdf/mpdf                  v7.0.3             A PHP class to generate PDF files from HTML with Unicode/UTF-8 and CJK support
phpunit/phpunit            5.7.27             The PHP Unit Testing framework.
silverstripe-themes/simple dev-master c2fdd14 The SilverStripe simple theme (default SilverStripe 3 theme)
silverstripe/recipe-cms    1.0.3              SilverStripe recipe for fully featured page and asset content editing
silverstripe/recipe-plugin 1.1.0              Helper plugin to install SilverStripe recipes

## Description

```      
  if(!$fields->removeFieldFromTab('Root.Main', 'Number')){
            throw new Exception("Could not remove 'Number'");
        }
```
`removeFieldFromTab`  evaluates to false if it succeeds.  It removes the fireld yet the exception is thrown.

It is documented as returning `$this`

**Comment by maxime-rainville** [comment]
Hi @worikgh.

I'm having a bit of difficulty replicating the issue you are facing. Can you provide a bigger code sample with more context?

**Comment by worikgh** [comment]
```
        if(!$fields->removeFieldFromTab('Root.Main', 'Thumbnail')){
            error_log(__CLASS__.":".__FUNCTION__.":".__LINE__. " BUG in SS");
        }            
```
`Thumbnail` is in a `has_one`.  If I do not remove it (after `parent::getCMSFields()`) there is a field added to add a thumbnail.  Naturally the thumbnail is derived and is not uploaded so I remove the field.

That code above always removes the field and always writes to the error _log.

If that is not enough help I will either send you the whole file (not so great) or whip up a small example (much better).

**Comment by maxime-rainville** [comment]
Either the whole file or a small example would awesome.

**Comment by worikgh** [comment]
https://gist.github.com/worikgh/b77d3288e3e2f7547de6b2b9903d347e

Run as admin,  Load up the 'Tests' admin

Click on 'Add Test'

inspect error log.

Is this clear?

cheers
W

**Comment by kinglozzer** [comment]
The method just returns `null`, regardless of outcome:

https://github.com/silverstripe/silverstripe-framework/blob/1c8576cee789cf8ec09f60cba3a362072d6d976b/src/Forms/FieldList.php#L183-L196

> It is documented as returning `$this`

Could you point to where that’s documented? As those docs are clearly wrong

We could probably make it return a boolean for error/success, but I don’t think we can change public APIs until 5.x

**Comment by kinglozzer** [comment]
Never mind, I’ve found it: http://api.silverstripe.org/4/SilverStripe/Forms/FieldList.html#method_removeFieldFromTab

The API docs are generated from the `4` branch, which is currently not released which is why you’re seeing the wrong docs... we have the same problem with our developer docs 😞not sure what the solution is 😕

**Comment by tractorcow** [comment]
The issue here is that, while there are some discrepancies between specific minor version releases, you will need to check the php / in-code documentation for specific return types. The docs reflect the latest version API. If you upgrade to 4.1.0 you'll see that FieldList::removeFieldFromTab() return type is `$this`.

If you are on older minor releases you won't get the updated API I'm afraid, and we have no plans to maintain separate documentation branches for separate minor versions as we once did.
