### ISSUE TITLE
Executing a dev/task should print a "Task completed, time taken %s" after completion.

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-framework#7992]
## The problem

On an internal poll, it was found that developers preferred the use of the web interface for running dev/tasks, however various third party modules or old code doesn't actually echo a message when a dev/task has completed properly. 

In the CLI this is not much of an issue as there won't be a PHP timeout and you'll know when the execution is complete and you'll be able to type in a new command.

In web however, a PHP timeout could occur and you'll be stuck with zero indication on whether the task completed properly or not. I also already understand that ideally a dev/task shouldn't be failing / timing out at all but in practice this generally ends up being a problem.

## The solution

Add a message after running the `BuildTask::run()` that says something like "Task completed. Time taken: %s". (We could measure how long it took as a sort of bonus feature of adding this in)

**Comment by robbieaverill** [comment]
I'd be keen on this idea, but not (to make it any worse) until we have a better CLI system to be honest. Related: https://github.com/silverstripe/silverstripe-framework/issues/5542

That being said, the way build tasks output is messy already, so adding something like this wouldn't make much of a difference in my opinion.

What do others think?

**Comment by torleif** [comment]
We use an extension of the build task which has some extra functionality. We get around the time out issue by having a task which will splits the task into bit sized chunks.

it's handy because if you're running on cli it will behave like normal, but in the browser the user will see a nice window like this:

![image](https://user-images.githubusercontent.com/67215/39277120-5ba8187a-4940-11e8-82d0-da1be8336806.png)

Our approach is much more user friendly (and looks a lot better 😃). if a task is manual, it's better to have the browser as a first class citizen. Some environments are not geared up for cli, and it's easier for non technical users to run them. 

I'd love to see SilverStripe with a `BuildTask` extension which would poll the completion status as opposed to simply timing out.

**Comment by maxime-rainville** [comment]
@torleif Is this something you guys did yourself or are you using a third party package to accomplish this?

**Comment by robbieaverill** [comment]
I think we should move this to an idea on the RFC for a Symfony based console instead, it's unlikely to be done in the 4.x release line without that being implemented first
