### ISSUE TITLE
difflib uses each() which is deprecated in php 7.2

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-framework#8053]
## Affected Version

SilverStripe 4.1 on php 7.2

## Description

I tried comparing two versions in the History tab in Dev-mode. I got a 500 error because php outputs a Deprecation warning. 

## Steps to Reproduce

Run SilverStripe 4.x on a machine with php 7.2, run in dev mode, and try comparing two history versions.

It is caused by `/thirdparty/difflib` which uses the deprecated `each` function. I guess it should be updated, replaced or patched. I can patch it just for this issue, if that is a good enough solution? 

## Pull Requests
- [ ] (4.x) https://github.com/silverstripe/silverstripe-framework/pull/8111
 - [ ] https://github.com/silverstripe/silverstripe-behat-extension/pull/178 (required to get below passing)
- [ ] (3.x) https://github.com/silverstripe/silverstripe-framework/pull/8120

**Comment by maxime-rainville** [comment]
Just had a quick look. This file appears to be only used directly by `SilverStripe\View\Parsers\Diff` via a require_once statement.

It's been copied over from a project called _PhpWiki_ which was hosted on SourceForge. It appears to have been abandoned since 2015.

The way we are using right now is dodgy. I think we should switch to an alternative. If we can't find one, we should rewrite the logic and fold it back into our own codebase properly.

We can quickly rewrite the existing file so it works with PHP7.2, but I think it would be better to take this opportunity to redo it properly.

We'll have the same problem in core/Diff.php in SS3 framework who is also using this old class. So if we want SS3 to work on PHP7.2, we'll need to fix it there as well.
