### ISSUE TITLE
Setting a path (e.g. TEMP_PATH) in the .env file outputs into the public folder

### ISSUE THREAD

**Issue by Zazama** [silverstripe/silverstripe-framework#8099]
## Affected Version

4.1.1

## Description

When setting TEMP_PATH to e.g. "silverstripe-cache" in the .env file, the cache folder is created inside the public folder instead of the base path.
`TEMP_PATH="silverstripe-cache"`

Expected:
`/path/to/silverstripe/silverstripe-cache`
Output:
`/path/to/silverstripe/public/silverstripe-cache`

Is this the expected output? If yes, is there another way to set the cache folder to the root path instead of using a rather "hacky" ../silverstripe-cache? Because defining it in the _config.php throws an error that it's already defined.

## Steps to Reproduce

- Use public folder structure.
- Set e.g. TEMP_PATH in .env file

### PR
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/10138

**Comment by maxime-rainville** [comment]
There's a bit of insightful comment in `constants.php` that says `TEMP_PATH` expect an absolute path. However, it's not documented anywhere else and even that comment is not attached directly to the constant. I think it's unreasonable to expect developers to trawl through our source code to figure out how to use a constant.

* I would suggest we add an entry for `TEMP_PATH` to our [Environment management doc](https://docs.silverstripe.org/en/4/getting_started/environment_management/#core-environment-variables).
* If a non-absolute path is provided, we probably should try to assume that it's relative to BASE_PATH or throw an Exception.

On a related note, there's probably a few more constants in there that could use an entry in the _Environment management_ doc. I'm not sure that I would actively encourage developers to override all of those however.

https://github.com/silverstripe/silverstripe-framework/blob/a0d0564369177b6158ca76e9c421c36c7845d51d/src/includes/constants.php#L14-L29

**Comment by maxime-rainville** [comment]
Actually, we've deprecated a bunch of those constants. So some of them should be removed from the doc:
* FRAMEWORK_DIR
* FRAMEWORK_PATH
* THIRDPARTY_DIR
* THIRDPARTY_PATH
* THEMES_DIR
* THEMES_PATH

https://docs.silverstripe.org/en/4/changelogs/4.0.0/#module-paths

**Comment by Zazama** [comment]
I've actually seen the comment which states that the path must be absolute, yet it created the TEMP_PATH folder inside the public folder, so at first I thought that relative paths work, too.
While I still think that relative paths should work with TEMP_PATH (and other constants, because you can't execute php in the .env file anymore), I found a solution working for my original problem by re-setting the environment variable in the _config.php file of my project.

```php
use SilverStripe\Core\Environment;

Environment::setEnv('TEMP_PATH', BASE_PATH . '/silverstripe-cache');
```

It now creates the folder in `/path/to/silverstripe/silverstripe-cache` instead of `/path/to/silverstripe/public/silverstripe-cache`

**Comment by maxime-rainville** [comment]
Not sure what the initial rational for making `TEMP_PATH` absolute was. It might just have been that it was originally introduce when we were using `_ss_environment.php` which could be located any where on the file system. So making it relative might have introduce confusion.

If no one can think of a good reason to disallow relative `TEMP_PATH`, we probably should allow them.

**Comment by tractorcow** [comment]
It's created in public because the current working directory is set at the index.php location, which is public.

The rational for this being absolute is that TEMP_PATH shouldn't be a part of your website's folder structure.

**Comment by tractorcow** [comment]
The bug is that if you use a relative path the site should error and force you to set an absolute path. :)

**Comment by Zazama** [comment]
Okay, then let me tackle this issue from another point. Our company is hosting on a managed server where SilverStripe has issues with the temp directory of the system, so we always just created a "silverstripe-cache" folder inside the root path of the SilverStripe installation. As of upgrading/using SilverStripe 4, this wasn't sufficient anymore, because SilverStripe only used the created "silverstripe-cache" folder on every second site access and the other times showing the website in an old and always the same old state, which is probably a bug itself. Now, the only solution I was able to gather is to set the TEMP_PATH, making all problems with the cache directory disappear and now even that solution seems to be wrong, because the variable:

> shouldn't be a part of your website's folder structure

In reality though, there doesn't seem to be an alternative variable or solution to use, at least I wasn't able to find one.

Therefore, I agree that the bug is

> that if you use a relative path the site should error and force you to set an absolute path. :)

but I still think there should be a way to set a cache folder inside the base path without worrying about path changes etc.

**Comment by sb-relaxt-at** [comment]
Correct me if I'm wrong, but the .env variable TEMP_PATH is never read so the constant is set in constants.php based on some heuristic (see TempFolder). From my understanding it is not possible to directly set the constant TEMP_PATH without modifying index.php.

**Comment by sb-relaxt-at** [comment]
Any news/comments on this? Should it be possible to set the TEMP_PATH via a .env file? If so, this does not work properly, otherwise I would vote for adding this possibility.

**Comment by maxime-rainville** [comment]
@sb-relaxt-at It's still on our radar, but honestly it's a low priority. From the discussion, I think the general sentiment on the team is that we should disallow relative paths.

If this is a high priority for you, you can do a PR and we'll review it.

**Comment by sb-relaxt-at** [comment]
@phptek Exactly, that is the inconsistent behaviour I have mentioned.

@maxime-rainville This issue is not/no longer about allowing a relative path for TEMP_PATH. It is about whether or not it should be possible to (consistently) specify a constant in the .env file. In especially, if it should be possible to set the TEMP_PATH in the .env file. From my point of view this should be possible, as the .env file seems to be the appropriate place to specify global configs like TEMP_PATH.

**Comment by tieupmedia** [comment]
Hello together,
are there any news for this topic?

I've a major problem with the two cache folders on a shared host (Strato Webspace). The files, stored in /var/tmp/silverstripe-cache-php7.2.25-XXX (although TEMP_PATH in the .env file is set) are in a public space, where other customers may have access, too. And furthermore it reaches a disc quota limit, which breaks the whole SilverStripe frontend and backend.

**Comment by robbieaverill** [comment]
@tieupmedia the second part you mentioned about reaching your disk quota isn't something we can solve - suggest you look at using a cache service like Redis, or something similar

**Comment by tieupmedia** [comment]
@robbieaverill The main disc quota for the hosting package isn't exceeded. There is another one, cause the folder /var/tmp resides outside the customer path and that shouldn't be used at all. Thats why I configured TEMP_PATH to a folder inside the customer root.

**Comment by sb-relaxt-at** [comment]
I do agree, it is quite annoying to have two different temp directories, as setting the TEMP_PATH in the .env file does not influence code that directly accesses the TEMP_PATH constant.

**Comment by tieupmedia** [comment]
@sb-relaxt-at But just defining the TEMP_PATH as PHP constant inside the index.php doesn't resolve this problem, or am I wrong?

**Comment by kinglozzer** [comment]
Hmm, this is a bit confusing. There a bunch of issues at play here:

- Defining `TEMP_PATH` in `.env` doesn’t affect the value of the `TEMP_PATH` PHP constant. As far as I can tell, it was never supposed to, however it partly does because:
- Injector service definitions in YAML that use ``'`TEMP_PATH`'`` will first attempt to use an _environment variable_ with that name, but fall back to looking for a _PHP constant_ with that name. This results in some code using the environment variable, and some using the PHP constant which holds a different value
- The current working directory is wherever index.php is (typically public/), which results in those Injector services putting files in the public directory
- You can’t influence this in PHP code, because `constants.php` is called by composer’s autoloader as soon as `vendor/autoload.php` is required. You can hack in something before the require statement in `index.php`, but that doesn’t work for CLI
- `CoreKernel` calls `TempFolder::getTempFolder()` instead of using the `TEMP_PATH` constant

In my opinion we _should_ support a relative path for this, because it’s not always possible to know the absolute path ahead of time. E.g. with atomic deploys, you want a separate `silverstripe-cache` directory for each deployment and will want to pre-warm the site.

I can only see one way to resolve this nicely, and that is:

1) Read the `TEMP_PATH` environment variable (if set) in `constants.php`
2) If the path is relative, correct it to be relative to the site root instead of the public directory
3) Replace `TempFolder::getTempFolder()` with `TEMP_PATH` in `CoreKernel`
4) Either remove the `TEMP_PATH` environment variable, or update it with the corrected relative path

4 is necessary because otherwise the manifests will use the corrected relative path, but Injector services (like caches) won’t because Injector prioritises environment variables over PHP constants.
