### ISSUE TITLE
Warning: The `type` attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by aNickzz** [silverstripe/silverstripe-framework#8221]
## Affected Version

SilverStripe 4.1.2, though I expect this affects all versions

## Description

`Requirements_Backend` renders javascript `<script>` tags with a redundant `type="application/javascript"` attribute. These are not required in HTML5 as `application/javascript` is the default type for `<script>`.

Warnings shown on [Nu Html Checker](http://validator.w3.org/nu/) using a bookmarklet from [codepen](https://codepen.io/stevef/pen/LasCJ): 
![image](https://user-images.githubusercontent.com/15243523/41884058-c0bf236e-7930-11e8-90ea-0f68269f017e.png)

## Steps to Reproduce

1. Install a new instance of Silverstripe
2. Check html output

## Discussion

This can be fixed in either https://github.com/silverstripe/silverstripe-framework/blob/a33a08091dd7031443f989859701acac74c34730/src/View/Requirements_Backend.php#L807 or https://github.com/silverstripe/silverstripe-framework/blob/a33a08091dd7031443f989859701acac74c34730/src/View/HTML.php#L56
I suppose this should be behind a config in case HTML4 support is required (I don't know how often that happens), but I would expect it to omit the type attribute by default.

**Comment by robbieaverill** [comment]
SilverStripe 4 doesn't fully support HTML5 yet, but we do have a HTML5 module that adds extra support for it: https://github.com/silverstripe/silverstripe-html5

**Comment by aNickzz** [comment]
Is HTML5 in the pipes somewhere?
I don't see it on the [roadmap](https://www.silverstripe.org/software/roadmap/) or in any recently updated [open issues](https://github.com/silverstripe/silverstripe-framework/issues?utf8=✓&q=is%3Aopen+updated%3A>%3D2018-01-01+html5)

**Comment by dhensby** [comment]
Something being uncessacary doesn't make it a bug for being there. This provides BC compat for people running HTML4  XHTML1 sites. I don't see that this warrants an open issue.

I don't think we have an official position on whether we are or are not supporting HTML <5 in our templating engine, but at the moment we are implicitly and we most likely wouldn't be removing this in SS 4

**Comment by lerni** [comment]
@dhensby I can understand closing this but it'll come up again, since linters like https://sonarwhal.com/ ect. bug people about it and HTML 5.2 says you should omit it or even urges authors to omit the attribute. I think it would make sense to remove it in 5.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type
https://www.w3.org/TR/html52/semantics-scripting.html#element-attrdef-script-type

**Comment by dhensby** [comment]
I've closed it because I feel this issue is such low impact and the benefit to taking it out (keeping linters happy) isn't worth the harm for sites that aren't explicitly HTML5.

If we can get agreement and someone's prepared to put the work into it for SS 5, then sure, but we can't use the issue tracker as a place for tickets to remain open that no one plans on addressing
