### ISSUE TITLE
RFC: Better handling of new APIs in minor releases

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8257]
SilverStripe 4 was released 8 months ago, and we plan to support it for 4 years. We are still relatively early in its adoption cycle for the upgrading of new sites. Given what we see with the upgrade cycle, relying on frequent major releases to provide new software are likely to leave most of the SilverStripe community behind.

If a feature can be done in a minor release, it is going to be much more rapidly adopted by the SilverStripe community. This is a vehicle for us to have a more continuous delivery of features into production websites. So, in my view, there's a huge incentive to do as much as a we can in a non-breaking way.

To support this, this RFC suggests a few principles to work by.

## Mark new APIs as @internal by default

Producing a new API is risky. Will it meet all the cases it needs or require breaking changes to best suit the use case? In a major release, we can have a lengthy alpha cycle where these kinds of issues are ironed out. Does this mean that we need to slow down minor releases, or to leave risky APIs until major releases?

The status quo approach is neither necessary nor ideal. Even if you have a long alpha phase, most people won't step in and really start using an API until it's in a stable release. And it's not necessary, because we can tell the developer community "this API is still experimental" and make subsequent changes to it more safely. In docblock, this would be something like:

`@internal This new API is experimental and may change in a future minor release`.

By marking an API as '@internal` we are effectively giving an alpha release of _just that feature_. 

People can choose to make use of the API, recognising that it may change in a future API release, or play it safe. If we're able to use silverstripe-upgrader to identify/fix affected code, this can still be a reasonably safe proposition.

## Rather than breaking APIs, favour the introduction of new APIs

Sometimes we will want to break APIs that have existed for a long time. Surely that needs to wait until a major release? Not so fast...

In many cases an API change could be redesigned to instead introduce a _new_ API. This might be something that developers can choose to use (e.g. replacing DataList::column() with DataList::columnValues() and DataLis::columnUniqueValues(), as has been recently discussed). Or it might be applied system wide via a config option that is off by default.

Another good way to approach this is to provide an alternative mini-package for just 1 part of the recipe. For example, upgrading the pages area to React could be provided in a `silverstripe/react-pages` module that replaces CMSMain. You can install it when you're ready to live with the limitations / changes of that module. This also means that the react-pages can be released prior to it being feature-complete.

By making the API option we are effectively doing a major release of just 1 feature, rather than the whole framework at once.

People can invest the migration cost for those features that they get value from, or choose to ignore it for now. It's akin to feature-flagging.

## This might slow us down, isn't that bad?

It might be easier to just go and break APIs, release major releases, and not have to jump through the hoops that this RFC suggests. However, the code of the project is only as useful as the production sites it is deployed to. If we release our code in a way that doesn't break things, then it can be deployed to production sites much more easily.

SilverStripe sites tend to say on the same minor version for a while. A lot of sites will _never_ get off the major version they were originally built-for. Much as I wish it weren't so, there are still SS2.4 sites in the wild! So, although I don't have any data, I believe that pushing more features into minor releases will speed up adoption of those features by _years_. And even those changes that need to be optionally enabled, the users who benefit from them will be able to do so with much less effort than a full-major-upgrade would require.

Surely that's with a bit of care with how we code them?

**Comment by chillu** [comment]
Long overdue discussion, and very timely, thanks for raising this Sam! I think this is the right balance between the principles of meaningful "continuous improvement" (on production sites), and clear comms around stability. 

Two minor concerns:
 * We need stronger internal practices about "graduating" APIs, to avoid them accidentally staying marked as internal for years (while they gain widespread use). This would also extend to updating developer documentation.
 * Most developers won't get any IDE warnings on using stuff tagged with `@internal`. See this sample output from PHPStorm.

![image](https://user-images.githubusercontent.com/111025/42609758-460486d2-85e2-11e8-9d92-37377b4cefc9.png)

Maybe I'm doing this wrong? Looks like this [should work](https://github.com/Elgg/Elgg/issues/7714).
Anyway, devs without a full-blown IDE are now more likely to accidentally use unstable APIs.
Also, at the moment, `@internal` is filtered out from API docs (see [DBDate](http://api.silverstripe.org/4/SilverStripe/ORM/FieldType/DBDate.html) which is missing the `getInternalFormatter()`method), but we can likely fix that.

On balance, I'd say it would be far more impactful for devs to wait *years* for new APIs, not only based on our release cycle, but also on the major release upgrade cycle on their client's projects, which is quite often outside of their control (as opposed to minor release upgrades).

**Comment by sminnee** [comment]
> We need stronger internal practices about "graduating" APIs, to avoid them accidentally staying marked as internal for years (while they gain widespread use). This would also extend to updating developer documentation.

Agreed. We'd probably want a way of clearly delineating experimental APIs from other uses of the @internal keyword (if there are any). That way you could run a script listing the APIs that are still internal. As a general rule you'd probably want to stabilise the API by the _next_ minor release.

> Also, at the moment, @internal is filtered out from API docs (see DBDate which is missing the getInternalFormatter()method), but we can likely fix that.

I wonder if we could tweak our API docs templates to show them instead as experimental APIs?

**Comment by dhensby** [comment]
### Marking new APIs as `@internal`

Whilst I support the idea of more explicitly denoting what we consider to be our "public API" I do worry that an approach like this will just lead to an abuse of `@internal` and breaking changes for people.

I'd like to lay out why I think we adopted semver and what we hope to achieve with it: SemVer helps to communicate an expectation and set out a kind of "contract" with our users around what kind of changes they can expect in each release as well as the potential risk of breakages and regressions upgrading from one version to another. Patch releases are "safe", minor releases are "safe but with element of risk", major releases are "unsafe"; safety here measures how likely you'll hit a regression or BC breakage when upgrading.

If we aren't careful we can easily undermine this "contract" with our users by adding APIs that are outside of it's scope. Especially if the presumption here is that we are providing features *early* to people, we'd practically be encouraging people to use them but just giving ourselves free reign to completely break the behaviour of these features from 1 release to another.

### Rather than breaking APIs, favour the introduction of new APIs

I agree that we shouldn't be breaking APIs, but (as is clear from recent conversations) I don't agree that we should classify changing "buggy" behaviour as a breaking change. Unfortunately there are some quirks with our ORM (all queries are distinct by default) and other idiosyncrasies that mean it's quite easy for these unintended "features" to stick around. There can also be features that were *intentionally* written a certain way because of a misunderstanding or some other error. If it's determined that this behaviour is wrong (illogical, counter-intuitive, unexpected)

By replacing methods like `DataList::column()` with `DataList::columnUnique()` we risk creating an overly verbose API just so we can avoid the need to change existing bugs.

Now, where we identify the need for a new feature to replace an old one, I'm all for adding new APIs and deprecating existing ones; I just want to avoid this becoming an excuse to not fix problems.

I like the mini-package idea as a way of opting in to new features and getting "early access" without having to use an entirely unstable code-base. We should think about what long term maintenance and termination of those packages looks like, though.

**Comment by dhensby** [comment]
Also, isn't one of the fundamental premises of this suggestion that lots of sites have ongoing feature development over time (and thus the need for potentially new features) but they resits major version upgrades?

My experience is that this is quite rare; it's not often a site will have ongoing feature development and suddenly a feature that we would add with a package would suddenly become necessary. It's more likely that a new project will commence development and the latest version will be used then, relevant features in that version will be taken advantage of and that's about it.

So maybe this is going to solve an adoption problem that doesn't really exist. As you note, many 2.4 sites are still like and it's not like they've been updated or upgraded in any hurry, but lots of *new* sites have been built on 4 and very few on 2... So if we release a v5 soon, yes not many existing sites will upgrade but many new ones will be built on it

**Comment by chillu** [comment]
It feels like the discussion has stalled here. We've made some public statements around this as part of https://www.silverstripe.org/blog/update-on-silverstripe-5-x/

> Regardless of where this discussion leads, we’re committed to our existing Long Term Support (LTS) plan for the 4.x release line. We’ll have at least two years of ‘limited support’ after 5.x is released (and well after this release date is announced) allowing everyone ample time to coordinate upgrades. In the meantime, this doesn’t mean that new features and APIs need to wait.

> While we stand by our commitment to semantic versioning, the core team is discussing better ways at getting new APIs into the hands of early adopters. This could potentially involve new opt-in module releases (rather than new core recipe versions) or marking some APIs as internal in stable releases to strike a balance between providing a stable editing environment for authors, while allowing devs to plan ahead.

> For core CMS UI changes, we’ll be looking into creating parallel implementations (similar to the gradual introduction of a React-based asset section SilverStripe 4.x) which both devs and authors can choose to use before the changes become the main implementation. This is going to be an important factor for the upcoming React/GraphQL-based GridField.

@sminnee What do you think is the next step here? This seems like more of an agreement on the spirit of API design, than specific changes we can implement. It's always going to be case-by-case: The `@internal` use case might be too little visibility for some APIs we want people to try out, parallel APIs might hurt us in the long run due to naming confusions. 

We could add a step to the release process to check with `@internal` APIs we should "graduate" as part of minor releases, but it feels like that process is already complex enough. There's no other good way to set periodical reminders on these things, right?

**Comment by sminnee** [comment]
Yeah my instinct would be to close this issue. It was an interesting discussion but not definitively conclusive and I don't think that keeping this issue open is particularly helpful.
