### ISSUE TITLE
RFC: Deprecate Object access in 3.7

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8478]
In 3.7 we've renamed Object to SS_Object, and Object is only used if PHP 7.1 or lower is installed. This let us run SS3 on PHP 7.2. 🎉 

However, if you're currently running a site on PHP 7.1 and you're looking to upgrade to PHP 7.2, it can be hard to know if it will break.

It would be helpful if any reference to the Object class triggered a deprecation warning. This would let 3.7 users better understand whether or not their sites were going to break when they upgrade to PHP 7.2.

From memory, access to the Object class is by far the most likely change that would cause problems with this upgrade.

Ordinarily a deprecation would happen in a minor release, but given that PHP 7.1 EOLs in a year, 3.7 is supported for another 10 months after that, and we don't want a 3.8, this might be worthwhile.

**Comment by robbieaverill** [comment]
I wonder if we can provide an upgrade path to SS4 with the methods people use on Object other than simply extending Object, that'd provide for a much safer deprecation

**Comment by maxime-rainville** [comment]
The upgrader right now as a way of saying "replace this class/method with this other one". But it doesn't quite have the ability of saying "instead of extending this class, use this trait".

I just had a look, and we don't currently warn about `SS_Object` ... so if you upgrade from SS3.6, you'll get a warning about Object, but if you upgrade from 3.7 the upgrader will fall on its face. This will fix it https://github.com/silverstripe/silverstripe-framework/pull/8561

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
