### ISSUE TITLE
Safer default password minimum length and complexity

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#8522]
~~We don't have any restrictions on passwords at the moment~~: https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/PasswordValidator.php#L44

*UPDATE*: We have password restrictions through recipe-core auto-generated for `app/_config.php`, but they're 8 rather than the recommended 10 chars.

This is a typical case of convention over configuration: We shouldn't rely on developers doing the right thing and hunting down how to configure this properly. If you search for "password" on doc.ss.org, you'll get a link to https://docs.silverstripe.org/en/4/developer_guides/security/secure_coding/ on the third page, which describes how to do this. The "authentication" and "security" pages on doc.ss.org don't mention it. 

Ideally we can implement this for new installations via some installer defaults, and then encourage devs to double check their settings in a 4.x minor release. This should also detail what happens to existing users that don't fulfill these requirements yet, and how devs could force them to update their passwords.

Happy to take guidance on the lowest common denominator length and complexity. 

/cc @Firesphere 

# PRs
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/8587
 - [x] https://github.com/silverstripe/recipe-core/pull/39

**Comment by Firesphere** [comment]
My first thought would be to not enable any configuration by default on a `dev` environment. As you probably know and do yourself, a dev-password is usually "admin" or "password" or something alike. I would think a Live environment injector configuration with sane defaults (16 characters as shortest possible password) would be a good start, with explicit documentation, preferably as part of the initial `app` installation process, so it's obviously inside a developers view instead of something obscure inside the framework, where we have made some decision about what is good without giving a clear view of where it happened.

Although a `live` only default password restriction in theory leaves UAT sites still unprotected by a proper password validation default, I do not see a big problem there because UAT sites are usually protected by an IP permit list, thus limiting it's dangers.

For the thought of implementation, I would suggest the password length, if insufficient, on current sites, would show a message, same as the `install.php` file does, on production sites. More intrusive than just a toast message, but not intrusive enough to stop the user from doing it's job.

Complexity should not be considered an issue, but entropy should. Pure length (as per my presentations over the last few weeks) have much more impact than complexity. The famous XKCD comic is the best example of how and why complexity is not an issue anymore for computers. This is a remnant of the 90's, where it used to be a problem for computers, because calculating different variations of letters was an expensive operation.

I'd say, 16 characters minimum, and I don't care what these characters are. `aaaaaaaaaaaaaaaa` is more secure than `Passw0rd!`

**Comment by robbieaverill** [comment]
I think a 16 character minimum is too extreme for us to provide as a default. I haven't seen a mainstream website like Facebook or Google even requiring a password to be that long!

**Comment by Firesphere** [comment]
> I think a 16 character minimum is too extreme for us to provide as a default. I haven't seen a mainstream website like Facebook or Google even requiring a password to be that long!

I agree, it's just my personal opinion, of which I'm very aware is a pretty extreme one :D

**Comment by ScopeyNZ** [comment]
I agree with putting in sensible defaults that isn't going to end with forcing developers to immediately change it whenever they create a new SilverStripe project.

Personally I think 8 characters minimum with no specific restriction on character types is enough. Really all we can do is educate people about password re-use - something that is more susceptible with a _long_ password requirement.

Additionally, entropy is reasonably well covered by using salted passwords with a high number of iterations. People who manage to obtain a copy of a SilverStripe Member database will have a hard time with individually salted bcrypt hashed passwords.

**Comment by Firesphere** [comment]
> Personally I think 8 characters minimum with no specific restriction on character types is enough. Really all we can do is educate people about password re-use - something that is more susceptible with a long password requirement.

No, we shouldn't educate people on not re-using passwords, we should educate people on using a password manager, _then_ add password re-use (HaveIBeenPwned for example)

> Additionally, entropy is reasonably well covered by using salted passwords with a high number of iterations. People who manage to obtain a copy of a SilverStripe Member database will have a hard time with individually salted bcrypt hashed passwords.

With the downside of the salts being stored right next to the hashed password, so the salt is a given there.

**Comment by ScopeyNZ** [comment]
Yes but that's not the point of a salt. It's common place to store the salt right next to the password, you need it when revalidating.

The point of a salt is to make sure that anyone trying to brute-force passwords through use of a rainbow table has to regenerate the rainbow table for each user (for each salt).

**Comment by chillu** [comment]
This is not the battle of best security standards and customer education, it's setting a least common denominator as the project default. Middle ground between not laughably simple (e.g. one character minimum), and not surprising to most developers deploying their sites with a default configuration (e.g. 16 characters minimum). The real solution here is MFA, which we're handling separately already (stay tuned). I think the OWASP is a pretty good common denominator? https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Password_Length

**Comment by Firesphere** [comment]
From NZISM:

- a minimum password length of ten characters, consisting of at least three of the following character sets:
  - lowercase characters (a-z); 
  - uppercase characters (A-Z);
  - digits (0-9); and
  - punctuation and special characters.

I believe those are fair defaults to go with?
(Somewhere in section 16.2)

**Comment by chillu** [comment]
Just dug through this a bit more, turns out we *do* set those defaults, just in a very convoluted way (recipe-core providing an `app/_config.php`): https://github.com/silverstripe/recipe-core/blob/4/app/_config.php#L8

It does default to 8 chars, which is no longer best practice. I don't see this as semver breakage to move to 10 chars, since it only applies to new users and changed passwords. Marking as 4.4 for now.

**Comment by dnsl48** [comment]
The framework defaults have been added in https://github.com/silverstripe/silverstripe-framework/pull/8587
Here's the PR for removing it from the recipe-core: https://github.com/silverstripe/recipe-core/pull/38

**Comment by dnsl48** [comment]
https://github.com/silverstripe/recipe-core/pull/39

**Comment by dnsl48** [comment]
merged
