### ISSUE TITLE
GridFieldConfig_RelationEditor doesn't work with `$searchable_fields`

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-framework#8574]
## Affected Version

Vanilla SilverStripe 4.3

## Description

The `GridFieldAddExistingAutocompleter` falls on its face when working with DataObject that define a `private static $searchable_fields`.

Basically, the Ajax request to fetch the list of DataObject fails with a 500 error when you start typing the auto complete field.

```
ERROR [Emergency]: Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class DataListFilter.SilverStripe\ORM\Filters\PartialMatch does not exist in /home/maxime/Projects/ss4x/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:17
```

This may or may not be related to the new react search field.

## Steps to Reproduce

1. Implement this GIST in your SilverStripe SilverStripe project https://gist.github.com/maxime-rainville/9f544d1858b761db323c209933fd038c
1. Create a Sub Dummy.
1. Create a Dummy.
1. Try to link your Dummy to your SubDummy.
1. You'll get a 500 Internal server error

If you remove `$searchable_fields` from SubDummy and flush, everything works fine.

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/9991
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10211

**Comment by maxime-rainville** [comment]
Confirm the bug in 4.0, 4.1 and 4.2. So it's not related to the react search ... for a change.

My got feeling at this stage is that GridField Search context is bleeding into the search context for `GridFieldAddExistingAutocompleter`.

The problem is probably with `GridFieldAddExistingAutocompleter::scaffoldSearchFields()`.

**Comment by colintucker** [comment]
Just wanted to add my two cents and mention that this issue is still present in 4.7.3.  @maxime-rainville is spot on, it's related to the `scaffoldSearchFields()` method in `GridFieldAddExistingAutocompleter`.  It occurs when the `$searchable_fields` config for the model object refers to a filter using the full class name.

This code will generate the error:

```php
private static $searchable_fields = [
        'Title' => [
            'title' => 'Title (partial)',
            'filter' => PartialMatchFilter::class,
        ]
    ];
}
```

...while this won't:

```php
private static $searchable_fields = [
        'Title' => [
            'title' => 'Title (partial)',
            'filter' => 'PartialMatchFilter'
        ]
    ];
}
```

Now, `createSearchFilter()` in `DataList` is expecting the filter to be one of the types defined by the `coresearchfilters` config, i.e. `DataListFilter.PartialMatch`. `GridFieldAddExistingAutocompleter::scaffoldSearchFields()` is taking the filter spec and trimming off "Filter" from the end:

```php
$filter = preg_replace('/Filter$/', '', $spec['filter']);
```

This works fine for the `PartialMatchFilter` string, and will generate `Title:PartialMatch` for the above example. However, when we use the full class name in the spec, we end up with `Title:SilverStripe\ORM\Filters\PartialMatch`, which is obviously going to fail. 

The workaround is to the short class name string in the filter spec, but that's probably not best in the long run. Ideally, we should be detecting whether the spec refers to a subclass of `SearchFilter` and handling appropriately.

**Comment by lekoala** [comment]
@colintucker just got the issue as well. I'm defining a specific instance if $spec['filter'] as it is allowed in 

https://github.com/silverstripe/silverstripe-framework/blob/ff409d5e3127994ea1ef94b2f0644fed96ee2e10/src/ORM/DataObject.php#L3921

but that doesn't work and you get an error because there is a preg_replace being applied on an object. Getting the filter name won't work either because you can map an arbitrary string to the filter (in my case, I have a "SoftDelete" filter being mapped to a "SoftDeleteSearchFilter"... trimming Filter is therefore naive at best.

So the class needs to be updated to:
- Detect objects
- Find matching filter based on DataListFilter definitions

**Comment by lekoala** [comment]
I've tried to find a way to get a list of all DataListFilters, but the injector only seems to support getting specific filters

this works 

Injector::inst()->getServiceSpec("DataListFilter.EndsWith");

this doesn't

Injector::inst()->getServiceSpec("DataListFilter");

therefore, finding the right alias might be tricky!

**Comment by lekoala** [comment]
So I've made a pull request. It's not perfect, but it's better than what is currently in place :) at least it's not crashing.

**Comment by maxime-rainville** [comment]
Everything should be working now.
