### ISSUE TITLE
RFC: Introduce a "sudo mode"

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-framework#8595]
## Description

Currently a user needs to enter their password to validate a change in password. This is an example where extra authentication is required for an action in the CMS.

It's fair to say that we expect more of these as we move forward. Actions like adding MFA and possibly updating user roles might be considered an action that requires extra trust.

A possible UX friendly solution to this is to introduce a "sudo mode" like GitHub has: https://help.github.com/articles/sudo-mode/ . Actions deemed to need extra trust require you to enter a password so you enter "sudo mode". You are in this "sudo mode" state for an hour or so, refreshed when you perform any action that requires this mode.

Hopefully we can add this in a nice consumable way that would make it easy for CMS module authors to consume if they add actions which require a heightened level of trust. Eg. QueuedJobs might want extra authentication before allowing queueing some potentially destructive jobs?

/cc @clarkepaul

**Comment by sminnee** [comment]
Yeah I like this idea. I would probably couple its introduction as a new API to the implementation of some specific features that use it, e.g. managing permissions.

These seem like a good idea but I'm not sure where they'd sit in the priority queue.

The other thing I would consider if we're enriching the scope of authentication is the soft-identification of a user. For example, when I click a link in an email back to the site, it would be in principle feasible for the website to know that I'm probably Sam. We shouldn't expose private data, but you might for example use it to present more sensible defaults or populate the "Hi, Sam" text. A persistent cookie could also be used to populate this.

Amazon does this and it's one of Jared Spool's recommendations around "Security UX"

The result would be that identity check would be two parts:
 * Who is the current user?
 * How confident are we that this is the current user? (weak, normal, sudo)

You might also consider things such such as:
 * If a user is using remember me, should this be a different confidence level?

**Comment by chillu** [comment]
I've mentioned in the architecture catchup that would be good to have an event hook model where additional modules can overrule the logic similiar to `canView` (tri-state: yes, no, abstain). I've referenced [Recaptcha v3 actions](https://developers.google.com/recaptcha/docs/v3#actions) as one potential risk engine to hook into there. It turns out that Recaptcha only provides a JS API, not an actual API endpoint. That doesn't invalidate this thought (there are other risk engines), but it emphasises that we should build any UI behaviour with this level of extensibility in mind as well.

**Comment by brynwhyman** [comment]
In regards to our current authentication work, here are the areas I could think of a sudo mode being required:
- `/admin/security/EditForm/`
- `/admin/settings/`, ideally further refined to the 'Access' tab

Someone else had mentioned that requiring sudo-mode before accessing the edit form would mitigate any requirement for new read-only views.

We'd also want to think about error handling. I.e if the password fails, log the user out and redirect to `/security/login`

**Comment by robbieaverill** [comment]
I'm starting to look at this now. I think @sminnee's suggestions sounds good, and would feed nicely into future flexibility for personalisation, but I don't think (personally) they need to be requirements for the initial scope of this feature development.

At a high level, I'm thinking of building a middleware layer that will look at request paths to identify whether "sudo mode" should be enforced, and rely on a session based service layer to control whether sudo mode has been entered within X minutes. I'll built extensibility into this to potentially allow for third party module plugins as @chillu has suggested, but I don't want to drastically change the permission model - for this reason I think a pluggable middleware is a good approach instead.

We need this for the MFA module's MVP, which needs to work on SilverStripe 3.x and 4.0+, so will build this feature into a separate module which can potentially be ported into framework in a new minor release.

Here's a Laravel equivalent which appears to do what I'm suggesting here, I'm looking a bit at it now: https://github.com/csun-metalab/laravel-sudo

**Comment by robbieaverill** [comment]
We've taken a slight pivot on this for the MFA work and decided to implement the checking for sudo mode permission directly inline in the CMS's MFA form field. The backend component will be added to a module that will contain a variety of features that will eventually be made into core PRs (e.g. sudo mode, account reset UI flows, inviting a user to set up their account etc) which will be supported alongside MFA until the features are part of core, where that module will be deprecated.

**Comment by robbieaverill** [comment]
Here's the status of the implementation we've done so far:

* React HOC to enable sudo mode for components, a backend controller to `check` and `activate` it, and a service class to do the same: https://github.com/silverstripe/silverstripe-security-extensions/pull/1
* MFA example of implementing it in the backend: https://github.com/silverstripe/silverstripe-mfa/pull/156

The "silverstripe-security-extensions" module is a polyfill that we've created to add new features for MFA that should be in core modules, but is supported on SilverStripe 3.7 (soon) and SilverStripe 4.x. Ultimately these features will be directed at core, then this module will be deprecated.

**Comment by robbieaverill** [comment]
I've raised an issue to merge the security-extensions module into core, which would include the start of sudo mode. See https://github.com/silverstripe/silverstripe-framework/issues/9203.

**Comment by chillu** [comment]
@brynwhyman I think we need to prioritise this, it's too much of an XSS vector in admin/security right now (even with CSRF protection in place). After a quick review, I think these tasks are outstanding:

- Decide whether we want to protect the whole `admin/security` and `admin/myprofile` sections, or only the submissions within them
- Determine other administrative UIs we want to protect with this
- Design a UX based on the existing sudo mode React component we've got in place for MFA (either full screen overlay or blocking form submissions). This will need @clarkepaul input.
- Optional: Remove "current password" prompt in "my profile" form (since that'll be taken care of by sudo mode)
- Add `silverstripe/security-extensions` as a requirement to `silverstripe/recipe-core`. This is going to be contentious. My rationale for this is the same as for the [mimevalidator discussion](https://github.com/silverstripe/silverstripe-framework/issues/8782): It's the only way we can secure large sections of Silverstripe customers, and put us in a position where XSS aren't as impactful on supported releases.
- Ensure `silverstripe/security-extensions` can function without MFA (since we can't add MFA to the installer without further work, see [issue](https://github.com/silverstripe/silverstripe-installer/issues/280))

Props to Guy and Robbie for getting the module so close already, it's appears that its mostly missing some UI bits!

/cc @silverstripe/core-team I'm suggesting adding a `recipe-core` dependency above. Note that since `silverstripe/security-extensions` is a dependency of `silverstripe/mfa`, it's already a supported module.

**Comment by brynwhyman** [comment]
I'm all for prioritising this. I think the features in silverstripe/security-extensions would be great enhancements to the CMS. 

It's worth noting that the module was created as a holding place with the original intention to port the features to silverstripe/cms, framework, or some place else. There features are quite distinct from each other and probably don't make a whole lot of sense as a bundle in their own module, unless we plan to add other 'security' features to it.

**Comment by GuySartorelli** [comment]
This was introduced as a part of the security-extensions module, and as of CMS 5 will be part of core.
Closing this issue.
