### ISSUE TITLE
Validation message wrong language with UserForms

### ISSUE THREAD

**Issue by jrson83** [silverstripe/silverstripe-framework#8669]
This may be SilverStripe related:

https://github.com/silverstripe/silverstripe-userforms/issues/839

SilverStripe 4.2.2 & UserForms 5.3

SilverStripe language is set to German. If I set e.g. Textfield to "required" the validation message is displayed in English.

'Fieldname' is required.

On SilverStripe 3.6 with UserForms 3.1 the message was:

'Fieldname' ist ein Pflichtfeld.

Update*:
If I look at the validation language files it actually makes no sense, cause the German validation message looks like:

required:"Dieses Feld ist ein Pflichtfeld."

The Englisch message should be:

required: "This field is required."

But the output is totally different. It seems that SilverStripe is overwriting the required field message with text from silverstripe/admin/client/lang files, cause the output in all the files is for de & en:

"Admin.VALIDATOR_MESSAGE_REQUIRED": "{name} is required.",

I'm not sure if it's this file, cause i tried to change the text to German, made a dev/build and flush=all but it is still English.

One note, it seems the problem is only the required message. If I try with an E-Mail formfield and insert an invalid e-mail, it displays the German text.

**Comment by robbieaverill** [comment]
Hey @jrson83. It seems like this is caused by a conflict in the i18n keys between the admin module and userforms. This was bound to occur at some point, since we don't have namespacing in them like we do for the PHP translation keys.

In this case I think it's best to resolve this by updating the userforms translation keys to something like `UserFormsAdmin` or something like that, rather than changing the admin module. Let's move this to https://github.com/silverstripe/silverstripe-userforms/issues/839
