### ISSUE TITLE
URL NOT PCI compliance

### ISSUE THREAD

**Issue by sparkcom** [silverstripe/silverstripe-framework#8899]
## Affected Version
Silverstripe 3.6 to 4.3 

## Description
If you visit a SS website, for example,  https://somedomain.com/about-us
and again  https://somedomain.com/about-us.old . It will not show page not found 404, it will just show  https://somedomain.com/about-us

Metric security pci scan says: 
By appending various suffixes (ie: .old, .bak, ~, etc...) to the names of
various files on the remote host, it seems possible to retrieve their
contents, which may result in disclosure of sensitive information. See
also :
http://projects.webappsec.org/w/page/13246953/Predictable%20Resource%20Location

If fact,  if you add .old, .copy,  or .anyting, it will show the page without the dot and the last part.

**Comment by sparkcom** [comment]
OK, I tried 
https://www.silverstripe.org/software/hosting.copy and it's the same as 
https://www.silverstripe.org/software/hosting

**Comment by kinglozzer** [comment]
SilverStripe’s routing strips off file extensions, yes (see https://github.com/silverstripe/silverstripe-framework/issues/5385), but I can’t see how that’s related to either the link you’ve included or PCI compliance. Serving the same content for `/my-page` and `/my-page.json` isn’t a security vulnerability, there’s no way to use that to expose sensitive files or perform file/directory enumeration.

If you feel that there is a security vulnerability here, please contact security@silverstripe.org rather than posting it on the public issue tracker. Thanks! 😄

**Comment by sonet** [comment]
From the search engine perspective there is the content duplication and/or race conditions. The server/cms shouldn't be responding with a 200 status code to all the possible url variations serving the exact same content.

**Comment by sparkcom** [comment]
@sonet that's right. Duplicated content is a concern to that.  probably the extensions should only be stripped off if it's php/html
