### ISSUE TITLE
Infinite loop in tests if temp database creation fails

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#8902]
If the temporary database creation fails for some reason, test executing locks up in an infinite loop. The root cause is this code, which is necessary for some edge-cases. I've come across this when a test table has a >64 character name.

```diff
diff --git a/src/ORM/Connect/TempDatabase.php b/src/ORM/Connect/TempDatabase.php
index a47c50078..e8f88e2b3 100644
--- a/src/ORM/Connect/TempDatabase.php
+++ b/src/ORM/Connect/TempDatabase.php
@@ -290,14 +290,14 @@ class TempDatabase
             return;
         }
 
-        try {
-            $this->rebuildTables($extraDataObjects);
-        } catch (DatabaseException $ex) {
-            // In case of error during build force a hard reset
-            // e.g. pgsql doesn't allow schema updates inside transactions
-            $this->kill();
-            $this->build();
+        //try {
             $this->rebuildTables($extraDataObjects);
-        }
+        // } catch (DatabaseException $ex) {
+        //     // In case of error during build force a hard reset
+        //     // e.g. pgsql doesn't allow schema updates inside transactions
+        //     $this->kill();
+        //     $this->build();
+        //     $this->rebuildTables($extraDataObjects);
+        // }
     }
 }
```

There's a couple of approaches that could be taken here.

 * Remove this try / catch, see what fails in the build matrix, and re-apply it to trigger only on that specific error
 * Change the code to kill/build only once.

Marking as a low-impact bug because it doesn't affect actual sites, only testing, and only occurs in edge-cases.

**Comment by chillu** [comment]
This was introduced by @tractorcow and @maxime-rainville - any ideas?
https://github.com/silverstripe/silverstripe-framework/commit/a116b5dad805ed8deec6e86aec2618b89c8e0ca4#diff-e079cc41387745f8bcb2528b07222c99L250
https://github.com/silverstripe/silverstripe-framework/commit/6da72d686f02f98dd8857ff236a85ee35174770d#diff-e079cc41387745f8bcb2528b07222c99

I'm going to increase the impact of this to `high`, since it will happen to most developers who use namespaces, and try to write the simplest of unit tests. As a core developer, this just took me nearly an hour to track down, because the infinite loop just runs out of memory before you get a stack trace, so I didn't even know where to set breakpoints and diagnose the issue. Given that "write unit test with a model" is pretty damn common, this can be a massive time sink.

**Comment by chillu** [comment]
Argh, just hit this again. https://github.com/silverstripe/silverstripe-framework/pull/9456 is the minimum viable fix, since I didn't get any feedback on my query above.
