### ISSUE TITLE
DOCS: Clarify the process for creating 'tweak releases'

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#9056]
Some releases are not as simple as tagging the head of a release branch. In the case where an RC has come back with a clean audit, the release is simply a recapitulation of that tag with only updates to dependencies, and security fixes on top of it.

Without patch release branches, this is a bit complicated and counterintuitive. It involves subverting cow's branching process and forcing it to use the tag you're augmenting.

Document:
- [ ] How to change the cow branches
- [ ] How to use `release:plan`
- [ ] How create the changelog
- [ ] Post-release merge ups

**PRs**

- [ ] #9392

**Comment by robbieaverill** [comment]
In the past we have audited stable releases, made follow ups as necessary and tagged a new patch release including any unreleased patch changes since then. I agree that going forward we need to remove the unaudited patch changes regardless, not sure if this should be a “block merges on this branch until further notice” CI check, patch branch support in cow, or “we have reviewed the extra commits internally” situation though

**Comment by Cheddam** [comment]
Implementation note: The documentation I produced to resolve this issue is based on the new `release:checkout-tagged-base` command, so less 'workarounds' were needed. I covered 'post-release merge ups' by describing that any extra commits should be reflected in the release branch ASAP, and that simply merging the tag back into the branch would **not** be a good approach. `release:plan` and `release:changelog` usage remains the same for tweak releases (in core, at least).
