### ISSUE TITLE
RFC: Recommend silverstripe/recipe-testing for test

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#9067]
We've [recently come across an issue](https://github.com/silverstripe/silverstripe-framework/pull/9065) that would be most cleanly solved by changing require-dev dependencies of any module/project that runs on PHP 7.4.

Ideally, we could add this to silverstripe/recipe-testing. However, this module is not widely adotped: https://packagist.org/packages/silverstripe/recipe-testing/dependents

My RFC is essentially that we promote the use of recipe-testing a little more heavily:

 * Add it to the require-dev of supported modules
 * Add it to the require-dev of default projects

Thoughts?

**Comment by chillu** [comment]
So we're talking about adding the deps in https://github.com/silverstripe/recipe-testing/blob/1/composer.json, right? Apart from the current predicament about `mock-objects`, this would allow us to add other test utilities en masse. But then again, we'd still need to add configuration and code to use those test utilities to each module (e.g. running some new static analyser via `travis.yml`), so will need to send a PR to every module either way.

> Add it to the require-dev of supported modules

90% of our modules don't require behat, so it feels weird including it everywhere? Since `require-dev` only applies to the root, this only really affects CI runs and module contributors. But it feels hacky.

> Add it to the require-dev of default projects

So this means you'll get more deps with the default project, slowing down composer install times, and adding noise. Not everyone will want to test with Behat or use php_codesniffer, I'd even argue that's the minority of projects. I'd rather just remove `require-dev: phpunit/phpunit` from the installer project and document that in our "how to test" docs as a first step.
