### ISSUE TITLE
TreeMultiSelectField search results

### ISSUE THREAD

**Issue by AljosaB** [silverstripe/silverstripe-framework#9078]
## Affected Version
SS 4.4.1

## Steps to Reproduce

- open any page
- click settings tab
- under "Who can view this page?" select "Only these groups (choose from list)"
- try searching for a group

## Description

When searching using TreeMultiSelectField I'm first getting filtered results that are being replaced with all items a second later. That happens because there are actually 2 requests being made where first one is retrieving filtered set and second one is replacing it with unfiltered one. (shown on picture below)

![image](https://user-images.githubusercontent.com/1818329/59682633-e905a180-91d6-11e9-9546-ee702a5ff971.png)

**Comment by unclecheese** [comment]
Related https://github.com/JedWatson/react-select/issues/2256

**Comment by adrhumphreys** [comment]
We ran into this issue/one similar enough we found that by adding `onSelectResetsInput={false}` to the <Select field would fix the issue on our side.

The issue was happening on vanilla silverstripe. When you start typing in a word as soon as you paused typing the text would be deleted as `componentWillReceiveProps` was triggered on the Select component which would then check the prop `onSelectResetsInput` and if it was true would clear the typed text

**Comment by unclecheese** [comment]
Temporary PR that will us through the crunch until we upgrade `react-select`. https://github.com/silverstripe/silverstripe-admin/pull/940

**Comment by robbieaverill** [comment]
Updated impact since this makes the field almost unusable if you have more than 5-6 items in it, probably entirely unusable with 1000 items in it

**Comment by unclecheese** [comment]
That's weird. I thought I selected `impact/high`. Thanks.

Yes, the higher the impact, the greater the justification for a hack fix like this. ;-)

**Comment by robbieaverill** [comment]
Temporarily (lol) fixed in 4.4.x, will be available in SilverStripe 4.4.4 - the next release
