### ISSUE TITLE
GridFieldFilterHeader doesn't add search parameters to URL

### ISSUE THREAD

**Issue by wilr** [silverstripe/silverstripe-framework#9080]
## Affected Version

SilverStripe 4.3+

## Description

When using the GridFieldFilterHeader submitting the search doesn't update the History URL so actions such as 'Back' don't work, can't send / save a link to a search.

Raising this as an issue before I submit a fix for it - was this intentional that it wasn't stateless by updating / use GET URL parameters? I looked for a discussion but I couldn't see one.

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/943
- [ ] https://github.com/silverstripe/silverstripe-framework/pull/9199

**Comment by chillu** [comment]
Yeah I've always tried to do this when implementing CMS features, but it seems to it's forgotten by default now. Persistent URLs to views are important, thanks for flagging that. So definitely not intentional. Just consider how this works with multiple GridFields on the same view. @unclecheese has done some work on this recently?

**Comment by sminnee** [comment]
FYI I've suggested building on #9190 to push grid field state into the URL via the history API, and have it be managed by GridField itself rather than selected components. This may assist with this.

**Comment by GuySartorelli** [comment]
This functionality was added in 4.12
