### ISSUE TITLE
New GridFieldFilterHeader UX

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-framework#9118]
<img width="1219" alt="Screenshot 2019-07-09 at 12 07 34" src="https://user-images.githubusercontent.com/1655548/60883649-a3228300-a242-11e9-9fe6-8db744d5c1da.png">

1. There’s no way to change which field the main search input filters on - it seems to default to the first searchable field. That’s a safe enough default, but ideally you’d be able to configure this to filter against multiple fields (e.g. in my case, it could match against _any_ field)
2. The placeholder text says “Search \<dataobject plural_name\>”, but gives no indication of which field you’re actually filtering on. It implies that it may match against any field/data
3. It’s not obvious that more search options are available. I think it just needs to stand out more, maybe make it a button in a different colour and add “More filters” text or something?

**Comment by ScopeyNZ** [comment]
/cc @silverstripeux

I'd say 1 is probably a bug, or at least a feature regression (which I think counts as a bug).

The other two are UX concerns.

Do you agree? Maybe we should split the first problem into a separate issue and triage as a bug?

**Comment by clarkepaul** [comment]
1. I'm not aware if the functionality was different compared with the older search but @maxime-rainville should do.
2. Yup fair comment, we could change the placeholder text to be the single column it searches from if it is only the single column. e.g. _Search from First name_
3. This is a hard one because the search field has so much going on and at small sizes or on smaller panels there isn't the space for all of the actions to have labels, so we tried to keep the same UI for all situations. Even if the user is using a desktop we don't actually know how much space the search has to show the full label. We battled with this problem when we designed it, in SS3 it did have "More filters" or something similar which took a lot of space from the search field. Perhaps replace the arrow with "Filters..." ?

**Comment by kinglozzer** [comment]
> I'm not aware if the functionality was different compared with the older search but @maxime-rainville should do.

Not 100% sure as I haven’t checked, but I think the older functionality only had separate inputs for each field... so I guess it didn’t need the ability to choose a “primary” column? 

> Yup fair comment, we could change the placeholder text to be the single column it searches from if it is only the single column. e.g. _Search from First name_

I think that’d help. The ideal solution would be for it to search all text-based columns with an OR, then the popup form searches individual columns with an AND... but that’s _a lot_ more work than changing some placeholder text 😉 

> This is a hard one because the search field has so much going on and at small sizes or on smaller panels there isn't the space for all of the actions to have labels, so we tried to keep the same UI for all situations. Even if the user is using a desktop we don't actually know how much space the search has to show the full label. We battled with this problem when we designed it, in SS3 it did have "More filters" or something similar which took a lot of space from the search field. Perhaps replace the arrow with "Filters..." ?

I think making it a button would help - it both makes it stand out more, and offers a hint at what it does. I came back to this today because I had to explain this to a client on the phone, who struggled to find the arrow even while I was talking them through it!

Here it is just with some text added...
<img width="372" alt="Screenshot 2019-08-01 at 16 48 19" src="https://user-images.githubusercontent.com/1655548/62308175-ddb3c000-b47c-11e9-9dd7-138b57c78c55.png">
<img width="1074" alt="Screenshot 2019-08-01 at 16 48 31" src="https://user-images.githubusercontent.com/1655548/62308182-e0161a00-b47c-11e9-9001-da12bf22ca24.png">

Or my personal preference (remember it is hidden completely until you click the search icon 😅)
<img width="373" alt="Screenshot 2019-08-01 at 16 50 03" src="https://user-images.githubusercontent.com/1655548/62308189-e3110a80-b47c-11e9-9ee6-434eab74b531.png">
<img width="1078" alt="Screenshot 2019-08-01 at 16 50 11" src="https://user-images.githubusercontent.com/1655548/62308194-e5736480-b47c-11e9-98cd-8c60d549599e.png">

**Comment by maxime-rainville** [comment]
The pre ss4.3 search didn't have a combined search field. All the filters were tied to a specific field.

But I agree we need to provide a better way of defining the fields that should be included in the main search. In a perfect world, you would be able to use [silverstripe-fulltextsearch](https://github.com/silverstripe/silverstripe-fulltextsearch) in GridFields so we can provide the same level of search in the backend as we do in the front end.

**Comment by clarkepaul** [comment]
@kinglozzer Just be mindful of how it looks when populated with filters... looks a little broken actually :(
![image](https://user-images.githubusercontent.com/555033/62329543-53b23880-b50a-11e9-81ed-9b851b1afdcb.png)
<img width="298" alt="Pasted_Image_2_08_19__9_45_AM" src="https://user-images.githubusercontent.com/555033/62329553-60369100-b50a-11e9-9b7b-09f3a301f82c.png">

**Comment by stevie-mayhew** [comment]
Can we instead of having this in the header search, split out the search component to its own item and use this filter header as something which lives inside the gridfield, like it used to? 

I think we're confusing contexts here, and also causing way too many interactions by having it hidden away like this.

We could put the filter back in somehow like this:
![Screen Shot 2019-08-02 at 10 18 36 AM](https://user-images.githubusercontent.com/1953220/62331097-f53b8900-b50e-11e9-8d27-8a6bc7ef1b0e.png)

Filters applied could be added to the results something like this:
![Screen Shot 2019-08-02 at 10 22 44 AM](https://user-images.githubusercontent.com/1953220/62331272-9591ad80-b50f-11e9-9b46-5513fd869d85.png)

Search as a dedicated component:
![Screen Shot 2019-08-02 at 10 26 33 AM](https://user-images.githubusercontent.com/1953220/62331435-0d5fd800-b510-11e9-85b1-9563e109b77f.png)

**Comment by clarkepaul** [comment]
I like the ideas but in reality, I don't think we'd get the time to redo this with so many changes all at once. We do have plans to update the grid field to react at some stage so potentially could be incorporated in that work?

The goal with the search work was to create a single experience (reduce variations) for all search's but it just doesn't work as well for grid fields with the current UI. 

My preference is when the search icon is in the table header (as it used to be) rather than the actions toolbar. I like the idea of bringing out the tags. Not sure about separating search and filters as you can get in some weird states between the two them, I remember experimenting with this a while back and wasn't satisfied with the experience.

**Comment by kinglozzer** [comment]
@clarkepaul Would you (or anyone else @silverstripe-ux) object to one of my suggestions for making the “Filters” button more visible as something of a stop-gap? That’s my main concern at the moment - clients keep reporting to me that the search doesn’t work when they’re just not spotting the little arrow

**Comment by clarkepaul** [comment]
Yup I'd be happy with just the text 
- move the little drop to the right side of the _Filter_ label
- _Filter_ label can be hidden on mobile and just show the dropdown arrow

The reason I'd prefer to hold back on the dropdown looking like a button is that I think it would get confused with an actual "Search" button—it looks like the primary action when I don't think it should. Buttons also take up more space horizontally and space is precious. We also need to make space for the [enter] help text which is pictured in the very first screenshot.

**Comment by jonom** [comment]
I made a feature request post in the forum for [macOS Finder style filters](https://forum.silverstripe.org/t/powerful-modeladmin-filters-to-make-silverstripe-an-awesome-crud-package/2301). I'd love to see something like that so that users can:

* Apply more than one filter per field
* Define the **type** of filter, not just the value (restricted to filters that make sense for the data type of the chosen field)
* Use AND / OR to build complex filters

Example use cases:

* Find Members edited between 2018-02-01 and 2018-04-02
* Find Members whose email starts with "j" and ends with "gmail.com"
* Find Members whose first name is "Joe" or "John"
* Find Members where all of the above are true

**Comment by jonom** [comment]
And if you could bookmark/save these search parameters some how then all the better 😄

**Comment by lozcalver** [comment]
This has been resolved in other issues/PRs - default behaviour is now to search across multiple fields, and the extra fields dropdown now has a "Search options" label which makes it more visible
