### ISSUE TITLE
react-select needs upgrade

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#9188]
We're currently running `1.3` on `silverstripe/admin: >= 1.4`. This release has a bug: https://github.com/silverstripe/silverstripe-framework/issues/9078.

The `>= 2.0` releases of `react-select` solve the issue, but the APIs are pretty different. Biggest change is that they've moved to an injectable `Components` prop instead of using renderers (e.g. `menuRenderer`). https://react-select.com/components#replacing-components.

**Comment by maxime-rainville** [comment]
This issue is blocking us from removing the [`componentWillReceiveProps`](https://github.com/silverstripe/silverstripe-admin/pull/1196) method statement on `TreeDropdownField` component.

Had a quick go at upgrading to react-select 2. Looks like it has a lot of UX consideration because v2 changes how styles are handled.

If we're going to do this, it's going to require some input from @silverstripeux. This could be a good opportunity to add the `TreeDropdownField` to the pattern lib.

I'm thinking maybe we scrap the component all together and restart from scratch.

**Comment by GuySartorelli** [comment]
Got updated in CMS 5
