### ISSUE TITLE
[3.7] Travis builds are broken with PHP 7.4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#9208]
## Affected Version

3.7.x

## Description

The Travis builds are broken due to a list of deprecations that have been introduced recently into PHP 7.4. We have a bit of patching to do to fix them up, but shouldn't be much work.

## Steps to Reproduce

https://travis-ci.org/silverstripe/silverstripe-framework/jobs/577129681

**Comment by NightJar** [comment]
calling `error_reporting((E_ALL | E_STRICT) & ~E_DEPRECATED);` in `mysite/_config.php` is a nifty work around for people viewing this issue in relation to working on a project.
PHP level deprecated notices should not be displayed when Silverstripe CMS is in `live` mode (assuming this is your only problem).

https://github.com/silverstripe/silverstripe-framework/blob/9ae617932efa05963d9f884225e47e6469dbfbf7/core/Core.php#L137-L139

**Comment by chillu** [comment]
For reference, the error is:

> ERROR [Deprecated]: Array and string offset access syntax with curly braces is deprecated

And we're using ths syntax in (at least) `Email.php`: https://github.com/silverstripe/silverstripe-framework/blob/3/email/Email.php#L771

@brynwhyman I'm going to mark this as `impact: high` since 7.4 is stable now, and this has the potential to drain a lot of developer brainpower to hunt down and work around. I guess this is part of a wider "ensure PHP 7.4 support" card which has already been flagged through https://github.com/silverstripe/silverstripe-framework/issues/9116.

**Comment by robbieaverill** [comment]
FYI the 4.x patch for the example error is https://github.com/silverstripe/silverstripe-framework/commit/d1c927ff2372a422ca8d5145aee6ba5192355f80

**Comment by robbieaverill** [comment]
Fixed now: https://travis-ci.org/github/silverstripe/silverstripe-framework/builds/669700308

Thanks @kinglozzer
