### ISSUE TITLE
FULLTEXT indexes force the table type to MyISAM

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-framework#9242]
SilverStripe when building a table that contains a FULLTEXT index for a MySQL database forces the table type to be MyISAM: https://github.com/silverstripe/silverstripe-framework/blob/8a06682e3148ec8bc0037ca9b92cbe7432c33100/src/ORM/Connect/MySQLSchemaManager.php#L44-L46

This appears to be a legacy holdover from when InnoDB didn't support FULLTEXT indexes, but since MySQL 5.6 you can [use a FULLTEXT within an InnoDB table](https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html), and according to the [server requirements page](https://docs.silverstripe.org/en/4/getting_started/server_requirements/) for 4.x we support no less than MySQL 5.6.

The mix of InnoDB and MyISAM tables can make the process of performing a `mysqldump` on the database trickier. As MyISAM doesn't support transactions you're forced to lock tables during the dump which will prevent writes, whereas with InnoDB you can use `--single-transaction` to take the dump from the point of the transaction without locking or preventing writes.

**Comment by chillu** [comment]
When changing this default, we should also ensure that existing tables are smoothly transitioned over to InnoDB (assuming that's possible).

Context for SS Ltd platforms: This makes it harder to take snapshots (which rely on `mysqldump` under the hood), and impacts platform users in having longer snapshot creation times, as well as impacting database writes during snapshot creation (potentially with data loss if those requests time out)

**Comment by chillu** [comment]
Looked a bit further into this, in short I want to change this either in a 4.x minor release for existing databases to auto-convert from MyISAM to InnoDB on dev/build. If it's considered a major change, an opt-in change, or something on a recipe level, it won't benefit the platform use case Indy laid out, and it's less attractive for us to invest time into.

From what I can tell, there's three ways you can define a FULLTEXT index:

 * Defining `'type' => 'fulltext'` in `DataObject::$db` column definitions
 * Adding the [FulltextSearchable](https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/Search/FulltextSearchable.php) extension to a class. This is described in our [search docs](https://docs.silverstripe.org/en/4/developer_guides/search/fulltextsearch/)
 * Implementing [DBIndexable](https://github.com/silverstripe/silverstripe-framework/blob/4/src/ORM/FieldType/DBIndexable.php) on a custom `DBField` subclass and returning `TYPE_FULLTEXT` in `getIndexType`

By default, any of this *only* causes a MyISAM table when the settings are in place before the table is created (happens in `MySQLSchemaManager->createTable()`). That code has been there since the dawn of time though, so I'd expect a good chunk of projects who have opted into FULLTEXT with one of the three methods above to have MyISAM tables.

I've looked through our [kitchen sink repo](https://github.com/silverstripe/cwp-recipe-kitchen-sink) as the most comprehensive set of supported modules.  Searched for `TYPE_FULLTEXT`, `"fulltext` and `'fulltext`, as well as `FulltextSearchable`. I can't find any supported module which either explicitly creates a FULLTEXT index, or sets a MyISAM engine. In our platforms, the majority of search uses are handled through Solr, making it less likely that projects *also* rely on MySQL's own search. Although there are valid use cases, for example better search in ModelAdmin or the CMS Pages section.

Testing this with MySQL 5.6, I can't see any behaviour changes on simple searches when using MyISAM vs. InnoDB. My test setup was pretty simple, just adding this to a default controller, and called `FulltextSearchable::enable();` in `_config.php`

```
class PageController extends ContentController
{
   public function SearchForm()
        {
            $form = new Form($this, "SearchForm",
                new FieldList(
                    new TextField('q')
                ),
                new FieldList(
                    new FormAction('doSearch')
                )
            );
            $form->setFormMethod('GET');
            $form->disableSecurityToken();

            return $form;
        }

        public function doSearch($data, $form)
        {
            $results = SiteTree::get()->filter('SearchFields:Fulltext', $data['q']);

            return $this->customise([
                'Results' => $results
            ])->renderWith('Page_results');
        }
}
```

Reading through the [MySQL recommendations for converting MyISAM to InnoDB](https://dev.mysql.com/doc/refman/5.6/en/converting-tables-to-innodb.html), we're already doing the basics right through dev/build (calling `ALTER TABLE engine=InnoDB`). They don't have specific instructions to recreate indexes, so presumably this happens behind the scenes. They do note that InnoDB requires more storage, which might be an issue if the database storage is close to max.
