### ISSUE TITLE
Date format adding plus 1 year if you use DBDate.

### ISSUE THREAD

**Issue by robby-nzta** [silverstripe/silverstripe-framework#9297]
## Affected Version
In silverstripe 4.4.4

## Description
Expected display wrong year - showing 2026 not 2025.
In CMS and database field, the data is stored '2025-12-31'. 
Afer applying format - $endDate.format('MMM Y'), it shows that 2026 instead 2025.

workaround for me,  $EndDate.Year showing correct year data. 

It could be from template or php.

Thanks.

**Comment by kinglozzer** [comment]
@robby-nzta I think you should be using `yyyy` for the year instead of `Y`, as per the examples here: http://userguide.icu-project.org/formatparse/datetime#TOC-Date-Time-Format-Syntax. Could you test that?

**Comment by patricknelson** [comment]
Thanks @kinglozzer, this fix works. Interestingly, this affects both the old `Zend_Date` (SS 3.x) and `IntlDateFormatter` classes.

I just wrote up a quick script to compare the outputs of date formats for both `MMM d, yyyy` (correct) and `MMM d, YYYY` (incorrect) and even though a vast majority of the time it seemed to work (hence the reason why the bug would creep up), it turns out that it impacts January 1, 2, 3 for some years (offsets `-1 year`) and December 29, 30 and 31 for some years (offsets `+1 year`). I ran a test between January 1, 2010 and January 1 2020.

Here's the really weird part: For  `Zend_Date`, the years that the Jan/December `+/- 1 year` offsets would appear to occur on were seemingly random at first (maybe had something to do with leap years?) but with `IntlDateFormatter` it would always occur on every single December 29th, 30th and 31st (and includes the 28th only on leap years) and thus would only ever offset `+1 year`.

**SilverStripe 4.x (`IntlDateFormatter`)**

```php
<?php
// Initialize framework.
require_once(__DIR__ . "/../../app/framework.php");

use SilverStripe\ORM\FieldType\DBDate;

// Config
$startDate = '2010-01-01';
$numDays = 11 * 365 + 30;
$testFormats = [
    'MMM d, yyyy',
    'MMM d, YYYY',
];

// Loop
set_time_limit(0);
$stamp = strtotime($startDate);
for($i = 0; $i < $numDays; $i++) {
    $input = date('Y-m-d', strtotime("+$i days", $stamp));

    $lastValue = $lastFormat = '';
    foreach($testFormats as $format) {
        $dateField = new DBDate('Date');
        $dateField->setValue($input);
        $dateField->setValue($input);
        $value = $dateField->Format($format);

        if ($lastValue === '') {
            $lastValue = $value;
            $lastFormat = $format;
        }
        if ($value !== $lastValue) {
            dump(str_repeat('#', 100));
            dump('input: ' . $input);
            dump("$format: $value");
            dump("$lastFormat: $lastValue");
        }

        $lastValue = $value;
        $lastFormat = $format;
    }
}

dump(str_repeat('#', 100));
dump("FIRST DATE TESTED: $startDate");
dump("LAST DATE TESTED: $input");
```

**SilverStripe 3.x (using `Zend_Date`)**
```php
<?php
// Initialize framework.
require_once(__DIR__ . "/../ebayinc/framework.php");


// Config
$startDate = '2010-01-01';
$numDays = 11 * 365 + 30;
$testFormats = [
	'MMM d, yyyy',
	'MMM d, YYYY',
];

// Loop
set_time_limit(0);
$stamp = strtotime($startDate);
for($i = 0; $i < $numDays; $i++) {
	$input = date('Y-m-d', strtotime("+$i days", $stamp));

	$lastValue = $lastFormat = '';
	foreach($testFormats as $format) {
		$dateField = new DateField('Date');
		$dateField->setConfig('dateformat', $format);
		$dateField->setValue($input);
		$value = $dateField->Value();

		if ($lastValue === '') {
			$lastValue = $value;
			$lastFormat = $format;
		}
		if ($value !== $lastValue) {
			dump(str_repeat('#', 100));
			dump('input: ' . $input);
			dump("$format: $value");
			dump("$lastFormat: $lastValue");
		}

		$lastValue = $value;
		$lastFormat = $format;
	}
}

dump(str_repeat('#', 100));
dump("FIRST DATE TESTED: $startDate");
dump("LAST DATE TESTED: $input");
```

**Comment by mikenz** [comment]
Related: https://www.youtube.com/watch?v=D3jxx8Yyw1c
"Why It's Already 2020"

**Comment by patricknelson** [comment]
Yeah, I just saw that too! That’s when I realized it may have actually been an artifact of ISO 8601 date formatting, which is precisely what the `YYYY format is (capitals) and explains the weird year offsets. Now I feel like a big dummy 😆

**Comment by patricknelson** [comment]
I will say, however, that it is interesting that the output for `Zend_Date` and `IntlDateFormatter` **are still different** despite the fact that they both claim to `ISO 8601` compliant.

**Comment by Cheddam** [comment]
Sounds like a resolution has been found! @robby-nzta, I'm going to close this issue - if you feel there's still an issue in framework to be addressed please let me know.
