### ISSUE TITLE
forceSSL does not fire

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9308]
## Affected Version

SS 4.4.4

## Description

I have the following in my _config.php:

```php
if (Director::isLive() || Environment::getEnv('SS_IS_TEST_SITE')) {
    die('test');
    Director::forceSSL();
}
```
when I run the site, I get:
'test'  
because SS_IS_TEST_SITE = true ... good, it works ;-).  However, when I remove the `die` statement, it does not force (redirect to) SSL. SSL does work, but I manually have to change the requested URL to `https://`

NB: the site is NOT in live mode, it is in test or dev mode, but I still want it to be secure. When I change it to LIVE mode (Director::isLive() == true), it does work.

**Comment by Cheddam** [comment]
@sunnysideup I've done a quick dig on this, and it appears to be caused by `CanonicalURLMiddleware` (which handles the HTTPS redirect) being disabled outside of Live mode by default. You can resolve this by updating your code to the following:

```php
if (Director::isLive() || Environment::getEnv('SS_IS_TEST_SITE')) {
    CanonicalURLMiddleware::singleton()->setEnabledEnvs(true); // Enables on all environment types
    Director::forceSSL();
}
```

I've raised a PR at #9333 to improve the documentation for the next developer who tries to apply this behaviour.

**Comment by sunnysideup** [comment]
THANK YOU!
