### ISSUE TITLE
Move the Forms folder content to silverstripe-admin's Forms folder

### ISSUE THREAD

**Issue by alessandromarotta** [silverstripe/silverstripe-framework#9539]
More I look at the Forms folder inside silverstripe-framework and more I wonder why it isn't in the silverstripe-admin module instead.

What is the sense of the presence of the classes that define the formfields in the silverstripe-framework package? wouldn't it be more logical that they were in the silverstripe-admin module?

I just tried moving the contents of the "_silverstripe/framework/src/Forms_" folder to the "_silverstripe/admin/code/Forms_" folder and everything works as before.

Could this be a good idea to get an even smaller silverstripe-framework package?

**Comment by michalkleiner** [comment]
@alessandromarotta do you always need the admin interface to be able to use form fields, e.g. in a custom form on your public front-end? No.

**Comment by alessandromarotta** [comment]
The best thing should be to move the form fields in an external module, required by Silverstripe-Admin and Silverstripe-CMS modules.

I think that there are really few developers that are using silverstripe formfields in the front end.

**Comment by ScopeyNZ** [comment]
I'm pretty sure this request falls well into the "too much effort for very little gain" bucket.

**Comment by kinglozzer** [comment]
> I'm pretty sure this request falls well into the "too much effort for very little gain" bucket.

Agreed, it sounds simple but in reality it isn’t as forms tie into other things in framework, e.g. request handling, security (with login forms), database formfield scaffolding (we’d probably need to somehow provide hooks for this instead of hardcoding classes from another module). I think we’d need to see a significant benefit to doing this before we could consider it

Thanks for the suggestion anyway @alessandromarotta 😃
