### ISSUE TITLE
DBDate Format Function Doesn't Work For 1-3rd January 2021

### ISSUE THREAD

**Issue by Jonathan-Fortune** [silverstripe/silverstripe-framework#9847]
## Affected Version

At least from Silverstripe 3.1.7 to 4.7

## Description

DBDate::Format(...) doesn't show correct year for dates between 1st Jan 2021 and 3rd Jan 2021.
I have tried other dates but these strangely seem to be the only ones affected.

## Steps to Reproduce

The code below:
```
$date = new DBDate();
echo $date->setValue('2021-01-02')->Format('{o} LLL Y');
```
echoes "2nd Jan 2020" rather than "2nd Jan 2021".

All Format() calls containing the year seem to have a similar output for these dates ranges.

This has been tested on everything from 3.1.7 and 4.7 on completely different server environments with the same results.

**Comment by kinglozzer** [comment]
For SilverStripe 4, you need to use a lowercase `y` instead of an uppercase `Y`: the uppercase version is the year in which the week begins. See https://unicode-org.github.io/icu/userguide/format_parse/datetime/#date-field-symbol-table.

I’d expect SS3 to work, as `Format()` in SS3 uses the formats described here https://www.php.net/manual/en/datetime.format.php, but we aren’t supporting SS3 any more anyway

**Comment by Jonathan-Fortune** [comment]
Ah! Thank you very much Loz.
