### ISSUE TITLE
can't set attributes to fields in elemental

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-framework#9885]
## Affected Version

4.7 + Elemental 

## Description

The attributes do not seem to be applied to any Elemental Block fields.  This is a real shame because it makes the Elemental Block not as pretty as it could be.

## Steps to Reproduce

Add the following fields to a page:
```php
        $fields->addFieldsToTab(
            'Root.Links',
            [
                OptionsetField::create('LinkType', 'Link Type', $this->owner->dbObject('LinkType')->enumValues())
                    ->setAttribute('onclick', 'console.log(1)'),
                TextField::create('ExternalLink', 'External Link')
                     ->setAttribute('placeholder', 'test')
            ]
        );
```

Attributes work fine.

Add them to an Elemental Block and it does not work.

Having `onchange` available is awesome because you can added conditionals - etc...

**Comment by michalkleiner** [comment]
Should the issue be better raised with https://github.com/silverstripe/silverstripe-elemental/ module?

**Comment by sunnysideup** [comment]
> Should the issue be better raised with https://github.com/silverstripe/silverstripe-elemental/ module?

Sure, my guess is that is a GraphQL conversion issue, rather than an Elemental specific issue.

**Comment by kinglozzer** [comment]
Thanks for reporting @sunnysideup, I’m going to close this as we’re tracking it in a couple of places already:

- https://github.com/silverstripe/silverstripe-elemental/issues/738
- https://github.com/silverstripe/silverstripe-framework/issues/9124

I found a possible workaround until it’s fixed by calling `setSchemaData()` directly, from memory it was something like this:
`$field->setSchemaData(['attributes' => ['placeholder', 'test']])`

**Comment by micschk** [comment]
Temporary workaround (eg for placeholder attribute):
`$field->setSchemaData(['attributes' => ['placeholder' => 'My placeholder value']]);`
